<?php $this->headTitle($this->translate('Task detail')) ?>
<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>
<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.js')
    ->prependFile($this->basePath() . '/js/admin/task/task-detail.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-tpls-0.11.2.min.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload','ui.bootstrap']);")
    ->prependScript("TASK_ID = {$this->id};")
    ->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js')
?>

<?php
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
		var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
		var EXITS_CONFIRM_TEXT = '" . $this->translate('This client was existed') . "';
		var EXITS_CONFIRM_OPTION_TEXT = '" . $this->translate('This option was existed, please chose other') . "';
		var CANNOT_DELETE_TEXT =  '" . $this->translate('This file can not delete, it is using by iterms') . "';
    ");
?>
<style>
.note-editor {
    height: 150px;
}

    .label_check label{
        margin-right: 0.3em;
    }
</style>
<div class="row">
<div class="col-lg-12">
	<div class="ibox" ng-controller="TaskDetailController" id="TaskDetailController">
		<div class="ibox-content">
			<?php include "detail/info.phtml"; ?>
			<?php include "detail/miniform.phtml"; ?>
			<div class="hr-line-dashed"></div>
            <?php include "detail/files.phtml";?>   
			<div class="hr-line-dashed"></div>			
			<div class="row m-t-sm">
				<div class="col-lg-12">
				<div class="panel blank-panel">
					<div class="panel-heading">
						<div class="panel-options">
							<ul class="nav nav-tabs">
								<li class="active"><a href="#tasks" data-toggle="tab"><span class="label label-warning">{{ project.tasksNum }}</span> <?php echo $this->translate("Task Allocation"); ?></a></li>
								
								<li class=""><a href="#message" data-toggle="tab"><span class="label label-warning">{{ project.activitiesNum }}</span> Messages & Activities</a></li>
								
							</ul>
						</div>
					</div>
					<div class="panel-body">
						<div class="tab-content">	
							<?php include "detail/order_information.phtml"; ?>
							<?php include "detail/activities.phtml"; ?>
						</div>
					</div>	
				</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
<div ng-controller="ModalController" id="modalContainer">
	<?php include "detail/modal/translation_modal.phtml"; ?>
    <?php include "detail/modal/interpreting_modal.phtml" ?>
    <?php include "detail/modal/engineering_modal.phtml" ?>
    <?php include "detail/modal/desktop_publishing_modal.phtml" ?>
   
</div>
<script>
    $(document).ready(function(){
        $('.dtbox').DateTimePicker();

        // trigger datetime picker when click to calendar icon
        // TODO: this is not working
        $('i.fa.fa-calendar').on('click', function(e){
            console.log('clicked');
            e.preventDefault();

            $(this).parents('.input-group').find('input[readonly]').click();
        });
    });
</script>