<?php $this->headTitle($this->translate('Unpaid Tasks')) ?>
<!-- Scripts -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/css/plugins/datapicker/datepicker3.css')
	 //->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css')
    //->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    //->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
    //->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<?php
$this->headScript ()
	//->prependFile($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.js')
	->prependFile($this->basePath() . '/js/admin/common/angular/service/project.js')
	->prependFile($this->basePath() . '/js/admin/task/freelancer-unpaid-task.js')
	//->prependFile($this->basePath() . '/js/admin/common/angular/ItemListController.js')
    //->prependFile($this->basePath() . '/js/admin/common/angular/service/project.js')
    //->prependFile($this->basePath() . '/js/admin/common/angular/CurrentUser.js')
    //->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    //->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', []);")
    ->prependScript("FREELANCER_ID = {$this->freelancer_id};")
    //->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    //->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-tpls-0.11.2.min.js')
    //->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-0.11.2.min.js')
    //->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    //->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    //->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    //->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    //->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    //->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js')
->prependFile($this->basePath() . '/js/plugins/datapicker/bootstrap-datepicker.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js');

$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
    ");
?>
					
<div class="row" ng-controller="FreelancerUnpaidTask" ng-init="init()">
	<div class="col-lg-12">
		<div class="wrapper wrapper-content animated fadeInUp">
			<div class="ibox">
				<div class="ibox-title">
					<h5>Unpaid Tasks</h5>
				</div>

				<div class="ibox-content">
				
					<div class="row m-b-sm m-t-sm">
                                <div class="col-md-10">
                                    <div class="input-group">
                                    	<input type="text" placeholder="Search" class="input-sm form-control" ng-model="filter.bsearch">
                                    	<span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary" ng-click='search()'> Search</button> 
                                      </span>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                	<a data-toggle="collapse" href="#adv_search" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Advance Search</a>
                                </div>
                    </div>
							
					<div class="row">
						<div class="col-lg-12">
							<div id="adv_search" class="panel-collapse collapse faq-answer">
                                        <form method="" class="form-horizontal">
                                            <div class="row">
                                                <div class="col-lg-4">
                                                    <div class="form-group">
                                                        <label class="col-sm-3 control-label"> Task ID</label>
                                                        <div class="col-sm-9"><input type="text" class="form-control" ng-model="filter.taskId"></div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-4">
                                                    <div class="form-group">
                                                        <label class="col-sm-3 control-label">Reference</label>
                                                        <div class="col-sm-9"><input type="text" class="form-control" ng-model="filter.reference"></div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-4">
                                                    <div class="form-group" id="data_4">
                                                        <label class="col-sm-3 control-label">Month</label>
                                                        <div class="col-sm-9">
                                                            <div class="input-group date">
                                                                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                                <input type="text" class="form-control" value="" ng-model="filter.dueMonth">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="text-right tooltip-demo">
                                                <a class="btn btn-sm btn-primary" ng-click="advancedSearch()"><i class="fa fa-search"></i> Search</a>
                                                <a class="btn btn-white btn-sm" type="reset"  ng-click="reset()"><i class="fa fa-times"></i> Reset</a>
                                            </div>
                                        </form>
                                    </div>
						</div>
					</div>
					<div class="hr-line-dashed"></div>
					 <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Task ID</th>
                                        <th>Task Reference</th>
                                        <th>Status</th>
                                        <th>Completed Date</th>
                                        <th>Amount</th>
                                    </tr>
                                    </thead>
                                    <tbody>
	                                    <tr ng-repeat="task in tasks">
	                                        <td>{{ task.project.project_no }}-{{ task.id }}</td>
	                                        <td>{{ task.project.reference }}</td>
	                                        <td>{{task.status.name }}</td>
	                                        <td>{{formatDate(task.dueDate.date) | date:'yyyy.MMM.dd'}}</td>
	                                        <td>{{task.project.currency | uppercase}} {{task.total_freelancer}}</td>
	                                    </tr>
                                    
                                    </tbody>
                                </table>
                            </div>
					<div class="btn-group text-right">
						<button type="button" class="btn btn-white" ng-class="pages.previous?'':'disabled'" ng-click="onBtnPreviousClicked()"><i class="fa fa-chevron-left"></i></button>
						<button ng-repeat="page in pages.pagesInRange" class="btn btn-white" ng-class="page==pages.current?'active':''" ng-click="onBtnGoto(page-1)">{{page}}</button>
						<button type="button" class="btn btn-white"	ng-class="pages.next?'':'disabled'" ng-click="onBtnNextClicked()"><i class="fa fa-chevron-right"></i></button>						

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
 <script>


 function simpleLoad(btn, state) {
     if (state) {
         btn.children().addClass('fa-spin');
         btn.contents().last().replaceWith(" Loading");
     } else {
         setTimeout(function () {
             btn.children().removeClass('fa-spin');
             btn.contents().last().replaceWith(" Refresh");
         }, 2000);
     }
 }
 $(document).ready(function(){

     $('#data_1 .input-group.date').datepicker({
         todayBtn: "linked",
         keyboardNavigation: false,
         forceParse: false,
         calendarWeeks: true,
         autoclose: true
     });

     $('#data_2 .input-group.date').datepicker({
         startView: 1,
         todayBtn: "linked",
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true
     });

     $('#data_3 .input-group.date').datepicker({
         startView: 2,
         todayBtn: "linked",
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true
     });

     $('#data_4 .input-group.date').datepicker({
         minViewMode: 1,
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true,
         todayHighlight: true
     });

     $('#data_5 .input-daterange').datepicker({
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true
     });

     $('#loading-example-btn').click(function () {
         btn = $(this);
         simpleLoad(btn, true)

         // Ajax example
//         $.ajax().always(function () {
//             simpleLoad($(this), false)
//         });

         simpleLoad(btn, false)
     });
 });
</script>
