<?php $this->headTitle($this->translate('My Tasks')) ?>
<!-- Scripts -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/datetimepicker/DateTimePicker.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/footable/footable.core.css')
?>

<?php
$this->headScript ()
	->prependFile($this->basePath() . '/v2/js/plugins/datetimepicker/DateTimePicker.js')
	->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
	->prependFile($this->basePath() . '/v2/js/admin/task/freelancer-task-view.js')
    ->prependScript("angularApp = angular.module('project', []);")
    ->prependScript("FREELANCER_ID = {$this->freelancer_id};")
    ->prependFile($this->basePath() . '/v2/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/footable/footable.all.min.js');

$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
        var ACCEPT_TASK_FAIL = '" . $this->translate('You have other going task so you can not accept this task') . "';
    	var TASKNUM = '" . $this->taskNum . "';
    ");
?>

    <script>
        $(document).ready(function() {

            $('.footable').footable();

        });

    </script>

<div class="row animate fadeInUp">

    <div class="ibox" ng-controller="FreelancerTaskView" ng-init="init()">
        <div class="ibox-content m-b-sm ">
            <div class="row">

                <form method="" class="form-horizontal">
                    <div class="col-lg-12">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="col-sm-3 control-label"><?php echo $this->translate('Task ID','Freelancer'); ?></label>
                                <div class="col-sm-9"><input type="text" class="form-control" ng-model="filter.taskId"></div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label"><?php echo $this->translate('Reference','Freelancer'); ?></label>
                                <div class="col-sm-8"><input type="text" class="form-control" ng-model="filter.reference"></div>
                            </div>
                        </div>
	                    <div class="text-right">
	                        <a href="#" class="btn btn-sm btn-primary" ng-click="advancedSearch()"><i class="fa fa-search"></i> <?php echo $this->translate('Search','Freelancer'); ?></a>
	                        <a href="#" class="btn btn-white btn-sm" type="reset" ng-click="reset()"><i class="fa fa-times"></i> <?php echo $this->translate('Reset','Freelancer'); ?></a>
	                    </div>
                    </div>
                </form>

            </div>

        </div>        
        <div class="ibox-content">

            <div class="project-list">

                <table class="footable table table-hover toggle-arrow-tiny">
                    <thead>
                    <tr>

                        <th data-hide="phone,tablet"><?php echo $this->translate('Status','Freelancer'); ?></th>
                        <th><?php echo $this->translate('Task ID','Freelancer'); ?></th>
                        <th data-hide="phone,tablet"><?php echo $this->translate('Task Info','Freelancer'); ?></th>
                        <th class="text-right"><?php echo $this->translate('Task Price','Freelancer'); ?></th>
                    </tr>
                    </thead>                                
                    <tbody>
                        <tr ng-repeat="task in tasks">
                            <td class="project-status">
                                <span class="label label-{{ task.status.decorator }}" style="font-size: 12px;">{{task.status.name }}</span>
                            </td>
                            <td class="project-title">
                                <strong style="font-size: 16px;">{{ task.task_number }}</strong>
                            </td>
                            <td class="project-title tooltip-demo">
                                <span><code style="font-size: 14px;">{{ task.project.sourceLanguage.name }} <i class="fa fa-arrow-right"></i>
                                    <span ng-repeat="lang in project.targetLanguages">
                                        {{ task.language.name }}
                                    </span>
                                    </code>
                                </span>
                                <br />
                                <span style="font-size: 14px;">{{ task.project.reference }}</span>
                            </td>
                            <td class="project-actions text-right">
                                <span class="text-navy" style="font-size: 15px;"><strong>$350.22</strong></span>&nbsp;
                                <a href="" ng-if="task.status.id == 6" ng-click="Accept(task.id)" class="btn btn-info btn-sm"><i class="fa fa-check-square-o"></i> <?php echo $this->translate('Accept','Freelancer'); ?></a> <a href="" class="btn btn-white btn-sm" ng-click="View(task.id)"><i class="fa fa-folder"></i> <?php echo $this->translate('View','Freelancer'); ?></a></a>
                            </td>
                        </tr>
                        </tr>
                    </tbody>
                </table>

				<div class="btn-group text-right">
					<button type="button" class="btn btn-white" ng-class="pages.previous?'':'disabled'" ng-click="onBtnPreviousClicked()"><i class="fa fa-chevron-left"></i></button>
					<button ng-repeat="page in pages.pagesInRange" class="btn btn-white" ng-class="page==pages.current?'active':''" ng-click="onBtnGoto(page-1)">{{page}}</button>
					<button type="button" class="btn btn-white"	ng-class="pages.next?'':'disabled'" ng-click="onBtnNextClicked()"><i class="fa fa-chevron-right"></i></button>
				</div>
            </div>

        </div>
    </div>

</div>


 <script>
 $(document).ready(function(){
	 $('#taskNumber').html(TASKNUM);

     $('#loading-example-btn').click(function () {
         btn = $(this);
         simpleLoad(btn, true)

         // Ajax example
//         $.ajax().always(function () {
//             simpleLoad($(this), false)
//         });

         simpleLoad(btn, false)
     });
 });

 function simpleLoad(btn, state) {
     if (state) {
         btn.children().addClass('fa-spin');
         btn.contents().last().replaceWith(" Loading");
     } else {
         setTimeout(function () {
             btn.children().removeClass('fa-spin');
             btn.contents().last().replaceWith(" Refresh");
         }, 2000);
     }
 }
    $(document).ready(function(){
        $('.dtbox').DateTimePicker();

        // trigger datetime picker when click to calendar icon
        // TODO: this is not working
        $('i.fa.fa-calendar').on('click', function(e){
            console.log('clicked');
            e.preventDefault();

            $(this).parents('.input-group').find('input[readonly]').click();
        });
    });
</script>
