<div class="row">
<div class="col-lg-12">
<div class="wrapper wrapper-content fadeInUp">
<div class="ibox">
<div class="ibox-content">
<div class="row">
    <div class="col-lg-12">
        <div class="m-b-md">
            <a data-toggle="collapse" href="#edit_project" class="btn btn-danger btn-xs pull-right"><i class="fa fa-edit"></i> Edit Project</a>
            <h2><span class="text-info">88888888-01</span> Task Reference xxds;dkasdkasdka</h2>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-lg-5">
        <dl class="dl-horizontal" style="margin-bottom: 0px;">
            <dt>Status:</dt> <dd><span class="label label-primary">Ongoing</span> </dd> <!--  <span class="label label-danger">Ordered</span> <span class="label label-primary">Ongoing</span>  <span class="label label-success">Reviewing</span> <span class="label label-default">Completed</span> <span class="label label-white">Rejected</span> -->
            <br>
            <dt>Client Contact:</dt> <dd><a href="#" class="text-navy"> Smith, Alex</a></dd>
            <dt>Client Company:</dt> <dd>Zender Company</dd>
            <br>
            <dt>Start Date:</dt> <dd>15 October 2014 - 11:04 AM</dd>
            <dt>Due Date:</dt> <dd>15 October 2014 - 11:04 AM</dd>
            <br>
            <dt>Source Language:</dt> <dd><code>English</code></dd>
            <br>
        </dl>
    </div>
    <div class="col-lg-7">
        <dl class="dl-horizontal" style="margin-bottom: 0px;">
            <dt>Priority:</dt> <dd><span class="label label-primary">Normal</span> </dd> <!-- <span class="label label-danger">High</span> -->
            <br>
            <dt>Sales:</dt> <dd>Jiang, Kevin</dd>
            <dt>Project Manager:</dt> <dd>Yang, Michael</dd>
            <br>
            <dt>Field:</dt> <dd>Accounting</dd>
            <dt>Type:</dt>
            <dd>
                <div class="tooltip-demo">
                    <code data-toggle="tooltip" data-placement="top" title="" data-original-title="Translation with Translation Memory">TM</code>
                </div>
            </dd>
            <br>
            <dt>Target Languages:</dt> <dd><code>Chinese</code></dd>
        </dl>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div id="edit_project" class="panel-collapse collapse faq-answer">
            <form method="" class="form-horizontal">
                <div class="row form-horizontal">

                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Reference *</label>
                            <div class="col-sm-9">
                                <input id="" name="" value="Project reference" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="form-group" id="ordered_date">
                            <label class="col-sm-3 control-label">Start Date *</label>
                            <div class="col-sm-9">
                                <div class="input-append date form_datetime" >
                                    <input class="form-control" type="text" value="" readonly>
                                    <span class="add-on"><i class="icon-remove"></i></span>
                                    <span class="add-on"><i class="icon-th"></i></span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Field *</label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" id="" name="" value="" aria-required="true">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Sales </label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" id="country" name="country" value="" aria-required="true">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Priority *</label>
                            <div class="col-sm-9">
                                <div data-toggle="buttons">
                                    <label class="btn btn-outline btn-primary btn-sm">
                                        <input type="radio" name="gender" value="male"> Normal
                                    </label>
                                    &nbsp;
                                    <label class="btn btn-outline btn-danger btn-sm">
                                        <input type="radio" name="gender" value="female"> High
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" id="due_date">
                            <label class="col-sm-3 control-label">Due Date *</label>
                            <div class="col-sm-9">
                                <div class="input-append date form_datetime" >
                                    <input class="form-control" type="text" value="" readonly>
                                    <span class="add-on"><i class="icon-remove"></i></span>
                                    <span class="add-on"><i class="icon-th"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">Client *</label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" id="" name="" value="" aria-required="true">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label">PM *</label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" id="" name="" value="" aria-required="true">
                                    <option>option 1</option>
                                    <option>option 2</option>
                                    <option>option 3</option>
                                    <option>option 4</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-right tooltip-demo">
                    <a href="#" class="btn btn-sm btn-primary"><i class="fa fa-save"></i> Update</a>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="hr-line-dashed"></div>
<div class="row">
    <div class="col-lg-5">
        <dl class="dl-horizontal">
            <dt>Project Files:</dt>
            <dd>
                <ul class="list-unstyled project-files tooltip-demo">
                    <li><a href="" data-toggle="tooltip" data-placement="left" title="" data-original-title="46.13 K | 2014-07-21 10:04:59"><i class="fa fa-file"></i> Project_document.docx</a> <a href=""><i class="fa fa-trash"></i></a></li>
                    <li><a href="" data-toggle="tooltip" data-placement="left" title="" data-original-title="46.13 K | 2014-07-21 10:04:59"><i class="fa fa-file"></i> Contract_20_11_2014.docx</a> <a href=""><i class="fa fa-trash"></i></a></li>
                </ul>
                <div class="text-center m-t-md">
                    <a href="#" class="btn btn-xs btn-primary"><i class="fa fa-cloud-upload"></i> Upload Source files</a>
                </div>
            </dd>
        </dl>
    </div>
    <div class="col-lg-7">
        <dl class="dl-horizontal">
            <dt>Final Files:</dt>
            <dd>
                <ul class="list-unstyled project-files tooltip-demo">
                    <li><a href="" data-toggle="tooltip" data-placement="left" title="" data-original-title="46.13 K | 2014-07-21 10:04:59"><i class="fa fa-file"></i> Project_document.docx</a> <a href=""><i class="fa fa-trash"></i></a></li>
                    <li><a href="" data-toggle="tooltip" data-placement="left" title="" data-original-title="46.13 K | 2014-07-21 10:04:59"><i class="fa fa-file"></i> Contract_20_11_2014.docx</a> <a href=""><i class="fa fa-trash"></i></a></li>
                </ul>
                <div class="text-center m-t-md">
                    <a href="#" class="btn btn-xs btn-primary"><i class="fa fa-cloud-upload"></i> Upload Final files</a>
                </div>
            </dd>
        </dl>
    </div>
</div>
<div class="hr-line-dashed"></div>

<div class="row m-t-sm">
<div class="col-lg-12">
<div class="panel blank-panel">
<div class="panel-heading">
    <div class="panel-options">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#tasks" data-toggle="tab"> Task Allocation</a></li>
            <li class=""><a href="#message" data-toggle="tab"><span class="label label-warning">6</span> Messages & Activities</a></li>
        </ul>
    </div>
</div>

<div class="panel-body">

<div class="tab-content">
<div class="tab-pane active" id="tasks">
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Iterms - <span class="text-info">Translation (No TM)</span></th>
            <th>Unit </th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>uploaded file name 1 / or Task Name</td>
            <td>Source Word</td>
            <td>CNY 0.12</td>
            <td>2000</td>
            <td>CNY 240.00</td>
            <td>
                <a data-toggle="modal" href="#modal-translation-noTM"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>uploaded file name 2 / or Task Name</td>
            <td>Source Word</td>
            <td>CNY 0.12</td>
            <td>1000</td>
            <td>CNY 120.00</td>
            <td>
                <a data-toggle="modal" href="#modal-translation-noTM"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
            </td>
        </tr>

        </tbody>
    </table>
</div>
<div class="text-center">
    <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-translation-noTM">Add Iterm</a>
</div>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Iterms - <span class="text-info">Translation (Use TM)</span></th>
            <th>Unit </th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>2</td>
            <td>Translation with TM</td>
            <td>Source Word</td>
            <td>CNY 0.12</td>
            <td>1000</td>
            <td>CNY 120.00</td>
            <td>
                <a data-toggle="modal" href="#modal-translation-TM"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;

                <a data-toggle="collapse" href="#use_tm"><i class="fa fa-eye"></i></a>
            </td>
        </tr>
        <tr>
            <td colspan="7">
                <div id="use_tm" class="panel-collapse collapse">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>TM Template</th>
                                <th>Rate (%)</th>
                                <th>Unit Price</th>
                                <th>Quantity (Word)</th>
                                <th>Quantity</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Repetitions</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>100</td>
                                <td>CNY 1.20</td>
                            </tr>
                            <tr>
                                <td>100%</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>200</td>
                                <td>CNY 2.40</td>
                            </tr>
                            <tr>
                                <td>95%-99%</td>
                                <td>10%</td>
                                <td>CNY 0.012</td>
                                <td>200</td>
                                <td>CNY 2.40</td>
                            </tr>
                            <tr>
                                <td>85%-94%</td>
                                <td>50%</td>
                                <td>CNY 0.06</td>
                                <td>300</td>
                                <td>CNY 18.00</td>
                            </tr>
                            <tr>
                                <td>75%-84%</td>
                                <td>50%</td>
                                <td>CNY 0.06</td>
                                <td>200</td>
                                <td>CNY 12.00</td>
                            </tr>
                            <tr>
                                <td>50%-74%</td>
                                <td>100%</td>
                                <td>CNY 0.12</td>
                                <td>1000</td>
                                <td>CNY 120.00</td>
                            </tr>
                            <tr>
                                <td>No Match</td>
                                <td>100%</td>
                                <td>CNY 0.12</td>
                                <td>1000</td>
                                <td>CNY 120.00</td>
                            </tr>
                            <tr>
                                <td colspan="4" align="right"><strong>Total</strong></td>
                                <td class="text-info">CNY xxxx.xx</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </td>
        </tr>

        </tbody>
    </table>
</div>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Iterms - <span class="text-info">DTP <i class="fa fa-apple"></i></span></th>
            <th>Unit </th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>uploaded file name 1 / or Task Name</td>
            <td>Page</td>
            <td>CNY 10.00</td>
            <td>10</td>
            <td>CNY 100.00</td>
            <td>
                <a data-toggle="modal" href="#modal-dtp-mac"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>uploaded file name 2 / or Task Name</td>
            <td>Hour</td>
            <td>CNY 50.00</td>
            <td>2</td>
            <td>CNY 100.00</td>
            <td>
                <a data-toggle="modal" href="#modal-dtp-mac"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
            </td>
        </tr>

        </tbody>
    </table>
</div>
<div class="text-center">
    <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-dtp-mac">Add Iterm</a>
</div>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Iterms - <span class="text-info">DTP <i class="fa fa-windows"></i></span></th>
            <th>Unit </th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>uploaded file name 1 / or Task Name</td>
            <td>Page</td>
            <td>CNY 10.00</td>
            <td>10</td>
            <td>CNY 100.00</td>
            <td>
                <a data-toggle="modal" href="#modal-dtp-pc"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>uploaded file name 2 / or Task Name</td>
            <td>Hour</td>
            <td>CNY 50.00</td>
            <td>5</td>
            <td>CNY 250.00</td>
            <td>
                <a data-toggle="modal" href="#modal-dtp-pc"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
            </td>
        </tr>

        </tbody>
    </table>
</div>
<div class="text-center">
    <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-dtp-pc">Add Iterm</a>
</div>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Iterms - <span class="text-info"> ENG</span></th>
            <th>Unit </th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>uploaded file name 1 / or Task Name</td>
            <td>Graphic</td>
            <td>CNY 10.00</td>
            <td>10</td>
            <td>CNY 100.00</td>
            <td>
                <a data-toggle="modal" href="#modal-eng"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>uploaded file name 2 / or Task Name</td>
            <td>Hour</td>
            <td>CNY 50.00</td>
            <td>2</td>
            <td>CNY 100.00</td>
            <td>
                <a data-toggle="modal" href="#modal-eng"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
            </td>
        </tr>

        </tbody>
    </table>
</div>
<div class="text-center">
    <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-eng">Add Iterm</a>
</div>

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>Iterms</th>
            <th>Unit </th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>Interpreter 1</td>
            <td>Day</td>
            <td>CNY 5000.00</td>
            <td>1</td>
            <td>CNY 5000.00</td>
            <td>
                <a data-toggle="modal" href="#modal-interpreting"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
            </td>
        </tr>
        <tr>
            <td>2</td>
            <td>Interpreter 2</td>
            <td>Half Day</td>
            <td>CNY 4000.00</td>
            <td>1</td>
            <td>CNY 4000.00</td>
            <td>
                <a data-toggle="modal" href="#modal-interpreting"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
                <a href="#"><i class="fa fa-trash-o text-danger"></i></a>
            </td>
        </tr>

        </tbody>
    </table>
</div>
<div class="text-center">
    <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-interpreting">Add Iterm</a>
</div>

<div class="hr-line-dashed"></div>

<form class="form-horizontal">
    <div class="form-group">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-md-4">
                    <select class="form-control" name="account">
                        <option>Select Client Resource</option>
                        <option>Translator 1</option>
                        <option>Translator 2</option>
                        <option>Translator 3</option>
                        <option>...</option>
                    </select>
                </div>

                <div class="col-md-2"><button class="btn btn-primary" type="submit">Assign Task</button></div> <!-- this button never disabled -->
                <div class="col-md-3" align="center"><a href="" disabled class="btn btn-success" type="submit">Send to Specialism Pool</a></div>
                <div class="col-md-3" ><a href="" class="btn btn-info" type="submit">Send to Client's Resource Pool</a></div>
                <!-- if the task has been send to any pool, then the button need to be disabled then the task status should be pooling-->
            </div>
        </div>
    </div>
</form>

</div>
<div class="tab-pane" id="message">
    <div class="feed-activity-list">
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Yang, Michael</strong> create quote. <br>
                <div class="well">
                    Project log or Description, if no log or description, then dont show div class=well
                </div>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 15:36</small>
                <strong>Smith, Alex</strong> accept the quote. <br>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong><a href="#" class="text-navy">freelancer_name1</a></strong> pick up task <a href="#" class="text-navy">#8888888-01</a>. <br>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong><a href="#" class="text-navy">freelancer_name2</a></strong> pick up task <a href="#" class="text-navy">#8888888-02</a>. <br>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong><a href="#" class="text-navy">freelancer_name2</a></strong> post message. <br>
                <div class="well">
                    Project log or Description, if no log or description, then dont show div class=well
                </div>
            </div>
        </div>

        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Yang, Michael</strong> create task <a href="#" class="text-navy">#8888888-03</a>. <br>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Smith, Alex</strong> post message. <br>
                <div class="well">
                    requirements
                </div>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Yang, Michael</strong> post message. <br>
                <div class="well">
                    answer
                </div>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Yang, Michael</strong> post message. <br>
                <div class="well">
                    answer
                </div>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Smith, Alex</strong> request re-do the project, project rejected. <br>
            </div>
        </div>
        <div class="feed-element">
            <div class="media-body ">
                <small class="pull-right">2014-Aug-20, 14:36</small>
                <strong>Smith, Alex</strong> accept the delivery, project closed. <br>
            </div>
        </div>
    </div>
    <br>
    <div class="form-group">
        <div class="summernote">

        </div>
    </div>
    <div class="hr-line-dashed"></div>
    <div class="form-group" align="right">
        <div class="col-sm-12">
            <button class="btn btn-primary" type="submit">Send</button>
        </div>
    </div>
</div>

</div>

</div>

</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>