

<div class="panel panel-primary">

                                            <div class="panel-body">
                                                <h4><i class="fa fa-coffee"></i>&nbsp; Translation</h4>
                                                <div class="hr-line-dashed"></div>

                                                <div class="table-responsive">
                                                    <table class="table table-striped table-bordered">
                                                        <thead>
                                                            <tr>
                                                                <th>#</th>
																<th><?php echo $this->translate('Source Language') ?></th>
																<th><?php echo $this->translate('Target Language') ?></th>
																<th><?php echo $this->translate('Translation Pric') ?></th>
																<th><?php echo $this->translate('Action') ?></th>
                                                            </tr>
                                                            </thead>
                                                            <tbody>
                                                            <tr ng-repeat="tp in translationPrices">
																<td>{{$index + 1}}</td>
																<td>{{tp.sourceLanguage.name}}</td>
																<td>{{tp.targetLanguage.name}}</td>
																<td>{{tp.price | number:2 }}</td>
																<td>
																	<a href="#" ng-click="editTranslationPrice($index, tp.id)" onclick="return false;">
																		<i class="fa fa-edit"></i>
																	</a>
																	<a href="#" ng-click="deleteTranslationPrice($index, tp.id)" onclick="return false;">
																		<i class="fa fa-trash-o text-danger"></i>
																	</a>
																</td>
															</tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="hr-line-dashed"></div>
                                                <div class="text-center">
                                                    <a data-toggle="modal" class="btn btn-outline btn-primary" ng-click="addTranslationPrice()"  onclick="return false;" href="#">Add Language pairs and prices</a>
                                                </div>
                                            </div>
                                        </div>

										<div class="panel panel-info">
                                            <div class="panel-body">
                                                <h4><i class="fa fa-desktop"></i>&nbsp; <?php echo $this->translate('Desktop Publishing') ?></h4>
                                                <div class="hr-line-dashed"></div>
                                                <div class="table-responsive">
                                                    <table class="table table-striped">
                                                        <thead>
                                                            <tr>
                                                                <th>#</th>
																<th><?php echo $this->translate('Languages') ?></th>
																<th>DTP <?php echo $this->translate('software') ?></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Page') ?> <i class="fa fa-apple"></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Page') ?> <i class="fa fa-windows"></i></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Hour') ?> <i class="fa fa-apple"></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Hour') ?> <i class="fa fa-windows"></i></th>
																<th>Action</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr ng-repeat="desktopPrice in desktopPrices">
																<td>{{$index + 1}}</td>
																<td>{{desktopPrice.language.name}}</td>
																<td>{{desktopPrice.software.name}}</td>
																<td>{{desktopPrice.priceMac | number:2 }}</td>
																<td>{{desktopPrice.pricePc | number:2 }}</td>
																<td>{{desktopPrice.priceHourMac | number:2 }}</td>
																<td>{{desktopPrice.priceHourPc | number:2 }}</td>
																<td>
																	<a data-toggle="modal" href="#modal-dtp" ng-click="editDesktopPrice($index)" onclick="return false;"><i class="fa fa-edit"></i></a>
																	<a href="#" ng-click="deleteDesktopPrice($index, desktopPrice.id)" onClick="return false;"><i class="fa fa-trash-o text-danger"></i></a>
																</td>
															</tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="text-center">
                                                    <a data-toggle="modal" class="btn btn-outline btn-info" ng-click="addDesktopPrice()" onclick="return false;" href="#"><?php echo $this->translate('Add DTP prices') ?></a>
                                                </div>
                                            </div>
                                        </div>
										<div class="panel panel-success">
                                            <div class="panel-body">
                                                <h4><i class="fa fa-comments-o"></i>&nbsp; <?php echo $this->translate('Interpreting') ?></h4>
                                                <div class="hr-line-dashed"></div>

                                                <div class="table-responsive">
                                                    <table class="table table-striped">
                                                        <thead>
                                                            <tr>
                                                                <th>#</th>
                                                                <th>Source Language </th>
                                                                <th>Target Language </th>
                                                                <th>Interpreting Service</th>
                                                                <th>Price/Day</th>
                                                                <th>Price/half-Day</th>
                                                                <th>Action</th>
                                                            </tr>
                                                            </thead>
                                                            <tbody>
                                                            <tr ng-repeat="interpretingPrice in interpretingPrices">
																<td>{{$index + 1}}</td>
																<td>{{interpretingPrice.sourceLanguage.name}}</td>
																<td>{{interpretingPrice.targetLanguage.name}}</td>
																<td>{{interpretingPrice.service.name}}</td>
																<td>{{interpretingPrice.priceDay | number:2 }}</td>
																<td>{{interpretingPrice.priceHalfDay | number:2 }}</td>
																<td>
																	<a data-toggle="modal" href="#" ng-click="editInterpretingPrice($index)" onclick="return false;"><i class="fa fa-edit"></i></a>
																	<a href="#" ng-click="deleteEngineeringPrice($index, interpretingPrice.id)" onclick="return false;"><i class="fa fa-trash-o text-danger"></i></a>
																</td>
															</tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="text-center">
                                                    <a data-toggle="modal" class="btn btn-outline btn-success" ng-click="addInterpretingPrice()" onclick="return false;" href="#"><?php echo $this->translate('Add Interpreting prices') ?></a>
                                                </div>
                                            </div>
                                        </div>
