<div class="panel panel-primary">
                                            <div class="panel-body">
                                                <h4><i class="fa fa-coffee"></i>&nbsp; Translation</h4>
                                                <div class="hr-line-dashed"></div>
                                                <div class="table-responsive">
                                                    <table class="table table-bordered table-striped">
                                                        <thead>
                                                          <tr>
                                                            <th>TM</th>
                                                            <th><?php echo $this->translate('Repetitions') ?></th>
                                                            <th>100%</th>
                                                            <th>95% - 99%</th>
                                                            <th>85% - 94%</th>
                                                            <th>75% - 84%</th>
                                                            <th>50% - 74%</th>
                                                            <th><?php echo $this->translate('No Match') ?></th>
                                                          </tr>
                                                        </thead>
                                                        <tbody>
															<tr>
																<td>TM Rate</td>
																<td>
																	<input id="repetition" name="repetition" type="number" ng-model="userInfo.tmRatios.repetitions" class="form-control required" value="{{userInfo.tmRatios.repetitions}}">
																</td>
																<td>
																	<input id="tm_100" name="tm_100" type="number" ng-model="userInfo.tmRatios.yibai" class="form-control required" value="{{userInfo.tmRatios.yibai}}">
																</td>
																<td>
																	<input id="tm_95-99" name="tm_95-99" type="number" ng-model="userInfo.tmRatios.jiuwu" class="form-control required" value="{{userInfo.tmRatios.jiuwu}}">
																</td>
																<td>
																	<input id="tm_85-94" name="tm_85-94" type="number" ng-model="userInfo.tmRatios.bawu" class="form-control required" value="{{userInfo.tmRatios.bawu}}">
																</td>
																<td>
																	<input id="tm_75-84" name="tm_75-84" type="number" ng-model="userInfo.tmRatios.qiwu" class="form-control required" value="{{userInfo.tmRatios.qiwu}}">
																</td>
																<td>
																	<input id="tm_50-74" name="tm_50-74" type="number" ng-model="userInfo.tmRatios.wushi" class="form-control required" value="{{userInfo.tmRatios.wushi}}">
																</td>
																<td>
																	<input id="tm_no_match" name="tm_no_match" type="number" ng-model="userInfo.tmRatios.nomatch" class="form-control required" value="{{userInfo.tmRatios.nomatch}}">
																</td>
															</tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="table-responsive">
                                                    <table class="table table-striped table-bordered">
                                                        <thead>
                                                            <tr>
                                                                <th>#</th>
																<th><?php echo $this->translate('Source Language') ?></th>
																<th><?php echo $this->translate('Target Language') ?></th>
																<th><?php echo $this->translate('Translation Pric') ?></th>
																<th><?php echo $this->translate('Action') ?></th>
                                                            </tr>
                                                            </thead>
                                                            <tbody>
                                                            <tr ng-repeat="tp in translationPrices">
																<td>{{$index + 1}}</td>
																<td>{{tp.sourceLanguage.name}}</td>
																<td>{{tp.targetLanguage.name}}</td>
																<td>{{tp.price}}</td>
																<td>
																	<a href="#" ng-click="editTranslationPrice($index, tp.id)" onclick="return false;">
																		<i class="fa fa-edit"></i>
																	</a>
																	<a href="#" ng-click="deleteTranslationPrice($index, tp.id)" onclick="return false;">
																		<i class="fa fa-trash-o text-danger"></i>
																	</a>
																</td>
															</tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="hr-line-dashed"></div>
                                                <div class="text-center">
                                                    <a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-translation">Add Language pairs and prices</a>
                                                </div>
                                            </div>
                                        </div>
										
										<div class="panel panel-info">
                                            <div class="panel-body">
                                                <h4><i class="fa fa-desktop"></i>&nbsp; <?php echo $this->translate('Desktop Publishing') ?></h4>
                                                <div class="hr-line-dashed"></div>
                                                <div class="table-responsive">
                                                    <table class="table table-striped">
                                                        <thead>
                                                            <tr>
                                                                <th>#</th>
																<th><?php echo $this->translate('Languages') ?></th>
																<th>DTP <?php echo $this->translate('software') ?></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Page') ?> <i class="fa fa-apple"></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Page') ?> <i class="fa fa-windows"></i></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Hour') ?> <i class="fa fa-apple"></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Hour') ?> <i class="fa fa-windows"></i></th>
																<th>Action</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr ng-repeat="desktopPrice in desktopPrices">
																<td>{{$index + 1}}</td>
																<td>{{desktopPrice.language.name}}</td>
																<td>{{desktopPrice.software.name}}</td>
																<td>{{desktopPrice.priceMac}}</td>
																<td>{{desktopPrice.pricePc}}</td>
																<td>{{desktopPrice.priceHourMac}}</td>
																<td>{{desktopPrice.priceHourPc}}</td>
																<td>
																	<a data-toggle="modal" href="#modal-dtp" ng-click="editDesktopPrice($index)" onclick="return false;"><i class="fa fa-edit"></i></a>
																	<a href="#" ng-click="deleteDesktopPrice($index, desktopPrice.id)" onClick="return false;"><i class="fa fa-trash-o text-danger"></i></a>
																</td>
															</tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="text-center">
                                                    <a data-toggle="modal" class="btn btn-outline btn-info" href="#modal-dtp"><?php echo $this->translate('Add DTP prices') ?></a>
                                                </div>
                                            </div>
                                        </div>
										<div class="panel panel-success">
                                            <div class="panel-body">
                                                <h4><i class="fa fa-comments-o"></i>&nbsp; <?php echo $this->translate('Interpreting') ?></h4>
                                                <div class="hr-line-dashed"></div>
                                                <div class="table-responsive">
                                                    <table class="table table-striped">
                                                        <thead>
                                                            <tr>
                                                                <th>#</th>
                                                                <th>Source Language </th>
                                                                <th>Target Language </th>
                                                                <th>Interpreting Service</th>
                                                                <th>Price/Day</th>
                                                                <th>Price/half-Day</th>
                                                                <th>Action</th>
                                                            </tr>
                                                            </thead>
                                                            <tbody>
                                                            <tr ng-repeat="interpretingPrice in interpretingPrices">
																<td>{{$index + 1}}</td>
																<td>{{interpretingPrice.sourceLanguage.name}}</td>
																<td>{{interpretingPrice.targetLanguage.name}}</td>
																<td>{{interpretingPrice.service.name}}</td>
																<td>{{interpretingPrice.priceDay}}</td>
																<td>{{interpretingPrice.priceHalfDay}}</td>
																<td>
																	<a data-toggle="modal" href="#modal-eng" ng-click="editEngineeringPrice($index)" onclick="return false;"><i class="fa fa-edit"></i></a>
																	<a href="#" ng-click="deleteEngineeringPrice($index, interpretingPrice.id)" onclick="return false;"><i class="fa fa-trash-o text-danger"></i></a>
																</td>
															</tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="text-center">
                                                    <a data-toggle="modal" class="btn btn-outline btn-success" href="#modal-interpreting"><?php echo $this->translate('Add Interpreting prices') ?></a>
                                                </div>
                                            </div>
                                        </div>