<div class=" setup-content" id="step-1">
	<div class="col-md-12">
		<div class="ibox-title">
			<h5>
				<i class="fa fa-files-o"></i> Source Files / Text
			</h5>
		</div>
		<div class="ibox-content">
			<div class="row">
				<div class="col-lg-12">

					<div class="panel blank-panel">
						<div class="panel-heading">
							<div class="panel-options">
								<ul class="nav nav-tabs">
									<li class="active"><a href="#tab-1" data-toggle="tab">Upload
											Files</a></li>
									<li class=""><a href="#tab-2" data-toggle="tab">Paste Text</a>
									</li>
								</ul>
							</div>
						</div>
						<div class="panel-body">
							<div class="tab-content">
								<div class="tab-pane active" id="tab-1">
									<div class="panel panel-default">
										<div class="panel-body" ng-controller="AppController"
											nv-file-drop="" uploader="uploader">

											<div class="col-md-12">
												<h4>
													We accept the following files, under <span
														class="text-danger">50MB</span> size:
												</h4>
												<p>Allowed file types are "txt, zip, rar, gif, jpeg, jpg,
													png, doc, docx, ppt, pptx, pdf, chm, xls, xlsx, txt, zip,
													rar".</p>
												<p>
													<span class="text-danger">If files are bigger then 50MB,
														pleasae put the download link into the "Project
														Information" at bottom.</span>
												</p>
												<br>
												<div class="col-md-4" id="files">
													<span class="btn btn-primary btn fileinput-button"> <i
														class="fa fa-cloud-upload"></i> <span>Select files</span>
														<input id="fileupload" type="file" name="files[]"
														nv-file-select="" uploader="uploader" multiple>
													</span>
												</div>
												<!--  
												<div class="col-md-8">
													<p></p>
													<div class="progress progress-bar-default">
														<div style="width: 43%" aria-valuemax="100"
															aria-valuemin="0" aria-valuenow="43" role="progressbar"
															class="progress-bar">
															<span class="sr-only">43% Complete (success)</span>
														</div>
													</div>
												</div>
												-->
												<br> <br> <br>
												<table class="table table-striped table-bordered">
													<thead>
														<tr>
															<th>#</th>
															<th>File Name</th>
															<th>File Size</th>
															<th>Time Stamp</th>
															<th></th>
														</tr>
													</thead>
													<tbody>
														<tr ng-repeat="item in uploader.queue">
															<td>{{$index + 1}}</td>
															<td><a href="#" ng-hide="item.isUploading">{{
																	item.file.name }}</a>
																<div class="progress" style="margin-bottom: 0"
																	ng-show="item.isUploading">
																	<div class="progress-bar" role="progressbar"
																		ng-style="{ 'width': uploader.progress + '%' }"
																		style="width: 0%;">{{ item.file.name }}</div>
																</div></td>
															<td>{{ item.file.size/1024/1024|number:2 }} Mb</td>
															<td>{{ getTime(item) }}</td>
															<td class="text-center child-is-link"><i
																ng-click="removeItem(item)"
																class="fa fa-trash-o text-danger"></i></td>
														</tr>
													</tbody>
												</table>
											</div>

										</div>
									</div>
								</div>

								<div class="tab-pane" id="tab-2">
									<textarea class="form-control" rows="8"
										ng-model="project.sourcetext"></textarea>
								</div>
							</div>
						</div>
					</div>




				</div>
			</div>
		</div>
		<div class="text-center">
			<button id="activate-step-2" type="button"
				class="btn btn-primary btn-lg" ng-click="initStep2()">Next</button>
			<!-- next button show after at least one file is uploaded -->
		</div>
	</div>
</div>
