<div class="panel panel-default">
    <div class="panel-heading" style="padding-bottom: 10px;">
        Translation - <span class="text-info"><strong>Business</strong></span>
    </div>
    <div class="panel-body">
        <div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Iterms - <span class="text-info">Translation (No TM)</span></th>
						<th>File</span></th>
                        <th>Unit </th>
                        <th>Unit Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tbody>
                    <tr ng-repeat="item in itermnotmsnews[language.id]">
                        <td>{{ $index + 1 }}</td>
						<td>{{ item.name }}</td>
                        <td>{{ item.file.name }}</td>
                        <td><?php echo $this->translate("Source word") ?></td>
                        <td>{{ item.rate }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.total }}</td>
                        <td>
                        <span ng-click="editTranslationNoTMPrice($index, item.id, language.id)">
                            <i class="fa fa-edit"></i>
                        </span> &nbsp;&nbsp;
                            <span ng-click="deleteTranslationNoTMPrice($index, item.id, language.id)"><i class="fa fa-trash-o text-danger"></i></span>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="text-center">
                <a class="btn btn-outline btn-primary"
                   ng-click="addTranslationNoTMPrice(language.id)">Add Iterm</a>
            </div>
            <div class="hr-line-dashed"></div>
        </div>
        <div>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Iterms - <span class="text-info">Translation (Use TM)</span></th>
                        <th>Unit </th>
                        <th>Unit Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>1</td>
                        <td>{{ itemtms[language.id][0].name }}</td>
                        <td>Source Word</td>
                        <td>{{ itemtms[language.id][0].rate }}</td>
                        <td>{{ itemtms[language.id][0].sourcerepetitions + itemtms[language.id][0].sourceyibai + itemtms[language.id][0].sourcejiuwu + itemtms[language.id][0].sourcebawu + itemtms[language.id][0].sourceqiwu + itemtms[language.id][0].sourcewushi}}</td>
                        <td>{{ itemtms[language.id][0].total }}</td>
                        <td>
							
                            <a data-toggle="modal" ng-click="editTranslationTM(1, item.id, language.id)"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;

                            <a data-toggle="collapse" href="#use_tm_{{language.id}}"><i class="fa fa-eye"></i></a>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="7">
                            <div id="use_tm_{{language.id}}" class="panel-collapse collapse">
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <thead>
                                        <tr>
                                            <th>TM Template</th>
                                            <th>Rate (%)</th>
                                            <th>Unit Price</th>
                                            <th>Quantity (Word)</th>
                                            <th>Quantity</th>
                                        </tr>
                                        </thead>
                                        <tbody>
										<tr>
											<td>Repetitions</td>
											<td>{{ itemtms[language.id][0].raterepetitions }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].raterepetitions / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourcerepetitions }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].raterepetitions / 100) * itemtms[language.id][0].sourcerepetitions | number:2 }}</td>
										</tr>
										<tr>
											<td>100%</td>
											<td>{{ itemtms[language.id][0].rateyibai }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].rateyibai / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourceyibai }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].rateyibai / 100) * itemtms[language.id][0].sourceyibai | number:2 }}</td>
										</tr>
										<tr>
											<td>95%-99%</td>
											<td>{{ itemtms[language.id][0].ratejiuwu }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratejiuwu / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourcejiuwu }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratejiuwu / 100) * itemtms[language.id][0].sourcejiuwu | number:2 }}</td>
										</tr>
										<tr>
											<td>85%-94%</td>
											<td>{{ itemtms[language.id][0].ratebawu }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratebawu / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourcebawu }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratebawu / 100) * itemtms[language.id][0].sourcebawu | number:2 }}</td>
										</tr>
										<tr>
											<td>75%-84%</td>
											<td>{{ itemtms[language.id][0].rateqiwu }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].rateqiwu / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourceqiwu }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].rateqiwu / 100) * itemtms[language.id][0].sourceqiwu | number:2 }}</td>
										</tr>
										<tr>
											<td>50%-74%</td>
											<td>{{ itemtms[language.id][0].ratewushi }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratewushi / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourcewushi }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratewushi / 100) * itemtms[language.id][0].sourcewushi | number:2 }}</td>
										</tr>
										<tr>
											<td>No Match</td>
											<td>{{ itemtms[language.id][0].ratenomatch }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratenomatch / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourcenomatch }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratenomatch / 100) * itemtms[language.id][0].sourcenomatch | number:2 }}</td>
										</tr>
										<tr>
											<td colspan="4" align="right"><strong>Total</strong></td>
											<td class="text-info">{{ itemtms[language.id][0].total }}</td>
										</tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>