<div class="panel panel-primary">
	<div class="panel-heading">
		<i class="fa fa-info-circle"> <strong><?php echo $this->translate('Basic Information') ?></strong></i>
	</div>
	<div class="panel-body">
			
		<div class="row">
			<div class="col-lg-6">
				<div class="form-group">
					<label><i class="fa fa-plug"></i>&nbsp; <?php echo $this->translate('Status') ?></label>
					<div data-toggle="buttons">
						<label class="btn btn-outline btn-primary {{active_class(userInfo.isActive, '1')}}" ng-click="setActive('1')">
							<input type="radio" name="active" > <?php echo $this->translate('Active') ?>
						</label>
						&nbsp;
						<label class="btn btn-outline btn-primary {{active_class(userInfo.isActive, '0')}}" ng-click="setActive('0')">
							<input type="radio" name="deactive"  > <?php echo $this->translate('De-Active') ?>
						</label>
					</div>				
				</div>
				<div class="hr-line-dashed"></div>	
				<div class="form-group">
					<label><?php echo $this->translate('Email') ?> *</label> <input id="email" name="email" ng-disabled="pagetype=='edit'" ng-model="userInfo.email" type="text" class="form-control" value="{{userInfo.email}}">
				</div>
				<div ng-show="pagetype == 'new'" class="hr-line-dashed"></div>
				<div ng-show="pagetype == 'new'" class="form-group">
					<label><?php echo $this->translate('Password') ?> *</label> 
					<input id="password" name="password" type="password" ng-model="userInfo.password" class="form-control required">
				</div>
				<div class="hr-line-dashed"></div>
				<div class="form-group">
					<label><?php echo $this->translate('First name') ?> *</label> 
					<input id="firstname" name="firstname" type="text" ng-model="userInfo.firstName" class="form-control required" value="{{userInfo.firstName}}">
				</div>
				<div class="hr-line-dashed"></div>
				<div class="form-group">
					<label><?php echo $this->translate('Gender') ?> *</label>
					<div data-toggle="buttons">
						<label class="btn btn-outline btn-primary btn-sm {{active_class(userInfo.gender, '0')}}"  ng-click="setGender('0')" > 
							<input type="radio" name="gender" > <?php echo $this->translate('Male') ?>
						</label> &nbsp; <label
							class="btn btn-outline btn-primary btn-sm {{active_class(userInfo.gender, '1')}}"  ng-click="setGender('1')"> 
							<input type="radio" name="gender"> <?php echo $this->translate('Female') ?>
						</label>
					</div>
				</div>
				<div class="hr-line-dashed"></div>
				<div class="form-group">
					<label><?php echo $this->translate('City') ?> *</label> 
					<input id="city" name="city" type="text" ng-model="userInfo.city" class="form-control required" value="{{userInfo.city}}">
				</div>
			</div>
			<div class="col-lg-6">
				<div class="form-group">
					<label><i class="fa fa-legal"></i>&nbsp; <?php echo $this->translate('Client Type') ?></label>
					<div data-toggle="buttons">
						<label class="btn btn-outline btn-primary {{active_class(userInfo.profileUpdated, '1')}}" ng-click="setProfileUploaded('1')">
							<input type="radio" name="contracted" > <?php echo $this->translate('Contracted') ?>
						</label>
						&nbsp;
						<label class="btn btn-outline btn-primary {{active_class(userInfo.profileUpdated, '0')}}" ng-click="setProfileUploaded('0')">
							<input type="radio" name="uncontracted"> <?php echo $this->translate('Un-Contracted') ?>
						</label>
					</div>
				</div>
				<div class="hr-line-dashed"></div>
				<div class="form-group">
					<label><?php echo $this->translate('Username') ?> *</label> 
					<input id="userName" name="userName" type="text" ng-model="employer.username" class="form-control required" value="{{employer.username}}">
				</div>
				<div ng-show="pagetype=='new'" class="hr-line-dashed"></div>
				<div ng-show="pagetype=='new'" class="form-group">
					<label><?php echo $this->translate('Confirm Password') ?> *</label> 
					<input id="password" name="confirmpwd" type="password" class="form-control required">
				</div>
				<div class="hr-line-dashed"></div>
				<div class="form-group">
					<label><?php echo $this->translate('Last name') ?> *</label> 
					<input id="surname" name="surname" type="text" ng-model="userInfo.lastName" class="form-control required" value="{{userInfo.lastName}}">
				</div>
				<div class="hr-line-dashed"></div>
				<div class="form-group">
					<label><?php echo $this->translate('Phone') ?> *</label> 
					<input id="phone" name="phone" type="phone" ng-model="userInfo.phone" class="form-control required" value="{{userInfo.phone}}">
				</div>
				<div class="hr-line-dashed"></div>
				<div class="form-group">
					<label><?php echo $this->translate('Country') ?> *</label> 
					<select class="form-control required" id="country" name="country" ng-model="userInfo.country" ng-options="country.name for country in countries">						
					</select>
				</div>
			</div>
		</div>
	</div>
</div>