<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">

                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Amelia Smith</strong>
                             </span> <span class="text-muted text-xs block">Administrator <b class="caret"></b></span> </span> </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="contacts.html">Reset Password</a></li>
                        <li><a href="mailbox.html">Mailbox</a></li>
                        <li class="divider"></li>
                        <li><a href="login.html">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    PT
                </div>

            </li>
            <li> <!-- different roles have different dashboard, a little bit different, can do at last -->
                <a href="<?php echo $this->url('admin',array("lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span></a>
            </li>

            <li>
                <a href="#"><i class="fa fa-book"></i> <span class="nav-lable">Finance</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="financial_report.html">Profit Report</a></li>  <!-- admin, sales director and operation manager can see all clients info, but sales manager can only see his own clients -->
                    <li><a href="transaction.html">Transactions</a></li>  <!-- admin, sales director and operation manager can see all clients info, but sales manager can only see his own clients -->
                    <li><a href="client-unpaid.html">Unpaid Projects</a></li>  <!-- admin, sales director and operation manager can see all clients info, but sales manager can only see his own clients -->
                    <li><a href="freelancer-unpaid.html">Unpaid Tasks</a></li>  <!-- admin, operation manager can see, and PM can see, but sales and sales director can not see -->
                    <li><a href="bankinfo.html">PaperTask Bank Info</a></li> <!-- all can see -->
                </ul>
            </li>

            <li> <!-- admin, operation manager, sales manager can see -->
                <a href="#"><i class="fa fa-group"></i> <span class="nav-lable">Staffs</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="<?php echo $this->url('admin', array('controller' => 'staff', 'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>">
                            Staff List</a></li>
                </ul>
            </li>

            <li> <!-- only admin can see the mail system -->
                <a href="#"><i class="fa fa-envelope"></i> <span class="nav-lable">Mail</span></a>
            </li>

            <li>
                <a href="<?php echo $this->url('admin', array('controller' => 'papertask', 'action' => 'profile',"lang"=>$this->translate('lang','Application'))) ?>">
                    <i class="fa fa-gear"></i> <span class="nav-lable">Settings</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'staff',
                        'action' => 'edit-profile',"lang"=>$this->translate('lang','Application'))) ?>">My Profile</a></li>
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'resetpassword', 'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>">Reset Password</a></li>
                    </ul>
            </li>
        </ul>

    </div>
</nav>
