<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">

                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Amelia Smith</strong>
                             </span> <span class="text-muted text-xs block">Administrator <b class="caret"></b></span> </span> </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'employer',
                    'action' => 'profile',"lang"=>$this->translate('lang','Application'))) ?>">Profile</a></li>
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'resetpassword',
                    'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>">Reset Password</a></li>
                     
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->url('user', array('controller' => 'logout',
                    'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>/logout">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    PT
                </div>

            </li>
            <li> <!-- different roles have different dashboard, a little bit different, can do at last -->
                <a href="<?php echo $this->url('admin',array('controller' => 'dashboard',
                    'action' => 'client-dashboard',"lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span></a>
            </li>

            

            <li>

                <a href="<?php echo $this->url('admin', array('controller' => 'project',
                    'action' => 'client-quotes',"lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-files-o"></i> <span class="nav-label">Quotes</span></a>
            </li>
<?php
$children = $this->viewModel()->getCurrent()->getChildren();
$child = $children[0];
?>
            <li> <!-- admin, sales director, operation manager can see full info, sales manager and pm can only see clients belong to them -->
                <a href="<?php echo $this->url('admin', array('controller' => 'project',
                    'action' => 'client-projects',"lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-archive"></i> <span class="nav-label">Projects</span> <span class="fa arrow"></span> <span class="label label-warning"><?php echo $child->numberproject?></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'project',
'action' => 'client-projects',"lang"=>$this->translate('lang','Application'))) ?>">All Projects</a></li>
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'project',
'action' => 'client-ongoing-projects',"lang"=>$this->translate('lang','Application'))) ?>">Ongoing Projects</a></li>
						<li><a href="<?php echo $this->url('admin', array('controller' => 'project',
'action' => 'client-review-projects',"lang"=>$this->translate('lang','Application'))) ?>">Reviewing Projects</a></li>
						<li><a href="<?php echo $this->url('admin', array('controller' => 'project',
'action' => 'client-completed-projects',"lang"=>$this->translate('lang','Application'))) ?>">Completed Projects</a></li>
						<!-- 
                        <li><a href="transaction.html">Ongoing Projects</a></li>
                        <li><a href="client-unpaid.html">Review <span class="label label-warning">16</span></a></li>
                        <li><a href="freelancer-unpaid.html">Completed Projects</a></li>
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'project',
'action' => 'order-translation',"lang"=>$this->translate('lang','Application'))) ?>">Create Project</a></li> -->
                    </ul>
            </li>

            <li>
                <a href="#"><i class="fa fa-book"></i> <span class="nav-lable">Finance</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                   <!-- <li><a href="transaction.html">Transactions</a></li> -->  <!-- admin, sales director and operation manager can see all clients info, but sales manager can only see his own clients -->
                   <!-- <li><a href="client-unpaid.html">Unpaid Projects</a></li> --> <!-- admin, sales director and operation manager can see all clients info, but sales manager can only see his own clients -->
                	<li><a href="<?php echo $this->url('admin', array('controller' => 'finance',
'action' => 'transaction',"lang"=>$this->translate('lang','Application'))) ?>">Transactions</a></li>
                	<li><a href="<?php echo $this->url('admin', array('controller' => 'finance',
'action' => 'client-unpaid',"lang"=>$this->translate('lang','Application'))) ?>">Unpaid Projects</a></li>
                    <!-- <li><a href="<?php echo $this->url('admin', array('controller' => 'finance',
'action' => 'freelancer-unpaid',"lang"=>$this->translate('lang','Application'))) ?>">Unpaid Tasks</a></li>-->
                </ul>
            </li>


			<!-- only admin can see the mail system -->
			<!-- 
            <li> 
                <a href="#"><i class="fa fa-envelope"></i> <span class="nav-lable">Mail</span></a>
            </li>
			 -->
            <li>
                <a href="<?php echo $this->url('admin', array('controller' => 'papertask', 'action' => 'profile',"lang"=>$this->translate('lang','Application'))) ?>">
                    <i class="fa fa-gear"></i> <span class="nav-lable">Settings</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'employer',
                                'action' => 'profile',"lang"=>$this->translate('lang','Application'))) ?>">Account Information</a></li>
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'resetpassword', 'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>">Reset Password</a></li>
                    </ul>
            </li>

        </ul>

    </div>
</nav>
