<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">

                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Amelia Smith</strong>
                             </span> <span class="text-muted text-xs block">Administrator <b class="caret"></b></span> </span> </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="contacts.html">Reset Password</a></li>
                        <li><a href="mailbox.html">Mailbox</a></li>
                        <li class="divider"></li>
                        <li><a href="login.html">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    PT
                </div>

            </li>
            <li> <!-- different roles have different dashboard, a little bit different, can do at last -->
                <a href="<?php echo $this->url('admin',array("lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span></a>
            </li>

            <li>
                <a href="<?php echo $this->url('admin', array('controller' => 'project',
                    'action' => 'quote',"lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-files-o"></i> <span class="nav-label">Quotes</span></a>
            </li>

            <li> <!-- admin, sales director, operation manager can see full info, sales manager and pm can only see clients belong to them -->
                <a href="<?php echo $this->url('admin', array('controller' => 'project',
                    'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-archive"></i> <span class="nav-label">Projects</span> <span class="fa arrow"></span> <span class="label label-warning">16</span></a>
                    <ul class="nav nav-second-level collapse">
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'project',
'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>">All Projects</a></li>
                        <li><a href="transaction.html">Ongoing Projects</a></li>
                        <li><a href="client-unpaid.html">Review <span class="label label-warning">16</span></a></li>
                        <li><a href="freelancer-unpaid.html">Completed Projects</a></li>

                    </ul>
            </li>

            <li>
                <a href="#"><i class="fa fa-book"></i> <span class="nav-lable">Finance</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                   <!-- <li><a href="transaction.html">Transactions</a></li> -->  <!-- admin, sales director and operation manager can see all clients info, but sales manager can only see his own clients -->
                   <!-- <li><a href="client-unpaid.html">Unpaid Projects</a></li> --> <!-- admin, sales director and operation manager can see all clients info, but sales manager can only see his own clients -->
                	<li><a href="<?php echo $this->url('admin', array('controller' => 'finance',
'action' => 'transaction',"lang"=>$this->translate('lang','Application'))) ?>">Transactions</a></li>
                	<li><a href="<?php echo $this->url('admin', array('controller' => 'finance',
'action' => 'client-unpaid',"lang"=>$this->translate('lang','Application'))) ?>">Unpaid Projects</a></li>
                </ul>
            </li>


            <li> <!-- only admin can see the mail system -->
                <a href="#"><i class="fa fa-envelope"></i> <span class="nav-lable">Mail</span></a>
            </li>

            <li>
                <a href="<?php echo $this->url('admin', array('controller' => 'papertask', 'action' => 'profile',"lang"=>$this->translate('lang','Application'))) ?>">
                    <i class="fa fa-gear"></i> <span class="nav-lable">Settings</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'employer',
                                'action' => 'profile',"lang"=>$this->translate('lang','Application'))) ?>">Account Information</a></li>
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'resetpassword', 'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>">Reset Password</a></li>
                    </ul>
            </li>

        </ul>

    </div>
</nav>
