<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">

                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Amelia Smith</strong>
                             </span> <span class="text-muted text-xs block">Administrator <b class="caret"></b></span> </span> </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="profile.html">Profile</a></li>
                        <li><a href="contacts.html">Reset Password</a></li>
                        <li><a href="mailbox.html">Mailbox</a></li>
                        <li class="divider"></li>
                        <li><a href="login.html">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    PT
                </div>

            </li>
            <li>
                <a href="<?php echo $this->url('admin',array("lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span></a>
            </li>

            <li>
                <a href="<?php echo $this->url('admin', array('controller' => 'task',
                    'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-tasks"></i> <span class="nav-label">Task Pool</span></a>
            </li>

            <li>
                <a href="<?php echo $this->url('admin', array('controller' => 'project',
                    'action' => 'quote',"lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-file-text-o"></i> <span class="nav-label">My Tests</span></a>
            </li>
            <li>
                <a href="<?php echo $this->url('admin', array('controller' => 'project',
                    'action' => 'quote',"lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-files-o"></i> <span class="nav-label">My Tasks</span> <span class="label label-warning">1</span></a>
            </li>

            <li>
                <a href="#"><i class="fa fa-book"></i> <span class="nav-lable">Finance</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="transaction.html">Transactions</a></li>
                    <li><a href="client-unpaid.html">Unpaid Tasks</a></li>
                    <li><a href="<?php echo $this->url('admin', ['controller'=>'freelancer', 'action'=>'edit-payment-info']) ?>">Edit Payment Info</a></li>
                </ul>
            </li>


            <li> <!-- only admin can see the mail system -->
                <a href="#"><i class="fa fa-envelope"></i> <span class="nav-lable">Mail</span></a>
            </li>

            <li>
                <a href="<?php echo $this->url('admin', array('controller' => 'papertask', 'action' => 'profile',"lang"=>$this->translate('lang','Application'))) ?>">
                    <i class="fa fa-gear"></i> <span class="nav-lable">Settings</span><span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level collapse">
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'freelancer',
                        'action' => 'detail',"lang"=>$this->translate('lang','Application'))) ?>">My Profile</a></li>
                        <li><a href="<?php echo $this->url('admin', array('controller' => 'resetpassword', 'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>">Reset Password</a></li>
                    </ul>
            </li>

        </ul>

    </div>
</nav>
