        <nav class="navbar navbar-static-top" role="navigation">
            <div class="navbar-header">
                <button aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" class="navbar-toggle collapsed" type="button">
                    <i class="fa fa-reorder"></i>
                </button>
                <a href="#" class="navbar-brand">PaperTask</a>
            </div>
            <div class="navbar-collapse collapse" id="navbar">         
                <ul class="nav navbar-nav">
                    <li>
                        <a href="<?php echo $this->url('admin',array("lang"=>$this->translate('lang','Application'))) ?>"><i class="fa fa-th-large"></i> <span class="nav-label"><?php echo $this->translate('Dashboard', 'Application'); ?></span></a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url('admin', array('controller' => 'task', 'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>"><span class="nav-label"><?php echo $this->translate('Tasks', 'Application'); ?></span></a>
                    </li>

                    <li class="dropdown ">
                        <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('Projects', 'Application'); ?> <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'project',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('Project List', 'Application'); ?></a></li>
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'project', 'action' => 'quote',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('Quote List', 'Application'); ?></a></li>
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'project', 'action' => 'new',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('New Project', 'Application'); ?></a></li>
                        </ul>
                    </li>

                    <li class="dropdown ">
                        <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('Freelancers', 'Application'); ?> <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'freelancer', 'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('Freelancer List', 'Application'); ?></a></li>
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'freelancer', 'action' => 'new',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('New Freelancer', 'Application'); ?></a></li>
                        </ul>
                    </li>

                    <li class="dropdown ">
                        <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('Clients', 'Application'); ?> <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'employer', 'action' => 'list',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('Client List', 'Application'); ?></a></li>
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'employer', 'action' => 'new',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('New Client', 'Application'); ?></a></li>
                        </ul>
                    </li>

                    <li class="dropdown ">
                        <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> <?php echo $this->translate('Finance', 'Application'); ?> <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'finance', 'action' => 'transaction',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('Transactions', 'Application'); ?></a></li>
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'finance', 'action' => 'client-unpaid',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('Unpaid Projects', 'Application'); ?></a></li>
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'finance', 'action' => 'freelancer-unpaid',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('Unpaid Tasks', 'Application'); ?></a></li>
                        </ul>
                    </li>

                </ul>

                <ul class="nav navbar-top-links navbar-right">
                    <li class="dropdown ">
                        <a aria-expanded="false" role="button" href="#" class="dropdown-toggle" data-toggle="dropdown"> <?php echo $this->userData()['name'] ?> <span class="label label-info"><?php echo $this->userData()['role_name'] ?></span> <span class="caret"></span></a>
                        <ul role="menu" class="dropdown-menu">
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'staff', 'action' => 'edit-profile',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('Profile', 'Application'); ?></a></li>
                            <li><a href="<?php echo $this->url('admin', array('controller' => 'resetpassword', 'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>"><?php echo $this->translate('Reset Password', 'Application'); ?></a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url('user', array('controller' => 'logout', 'action' => 'index',"lang"=>$this->translate('lang','Application'))) ?>/logout"><i class="fa fa-sign-out"></i> <?php echo $this->translate('Logout', 'Application'); ?></a>
                            </li>
                        </ul>
                    </li>
                </ul>

            </div>
        </nav>
		<script>
				$('li.dropdown').hover(function () {
		$(this).toggleClass('open').siblings().removeClass('open');
	});
		</script>
