<?php $this->headTitle($this->translate('Edit Profile')) ?>
<?php
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css');
$this->headScript()
    ->prependFile($this->basePath() . '/js/admin/staff/edit-profile.js')
    ->prependFile($this->basePath() . '/js/common.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-file-upload/angular-file-upload.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload']);")
    ->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js');
?>
<Script>
    var USER_ID = '<?php echo $user['id']; ?>';
	var LANG_CODE = '<?php echo $this->lang_code; ?>';
</Script>
<div ng-controller="editProfileController" class="ibox float-e-margins" id="editProfile" ng-init="init()">
    <div class="ibox-title">
        <h4><i class="fa fa-edit"></i> <?php echo $this->translate('Edit Profile') ?></h4>
    </div>

    <div class="ibox-content">
        <form name="editProfileForm" method="">
            <?php if($this->isAdmin): ?>
            <div class="row">
                <div class="col-lg-2">
                    <h4><i class="fa fa-plug"></i>&nbsp; <?php echo $this->translate('Status'); ?></h4>
                </div>
                <div class="col-lg-8">
                    <div data-toggle="buttons">
                        <label class="btn btn-outline btn-primary {{active_class(userInfo.isActive, '1')}} " ng-click="setActive('1')">
                            <input type="radio" name="active" > <?php echo $this->translate('Active'); ?>
                        </label>
                        &nbsp;
                        <label class="btn btn-outline btn-primary {{active_class(userInfo.isActive, '0')}} " ng-click="setActive('0')">
                            <input type="radio" name="deactive" value=""> <?php echo $this->translate('De-Active'); ?>
                        </label>
                    </div>
                </div>

            </div>
            <div class="hr-line-dashed"></div>
            <?php endif ?>
            <div class="panel panel-primary">
                <div class="panel-body">
                    <h4><i class="fa fa-info-circle"></i> <?php echo $this->translate('Basic Information') ?></h4>
                    <div class="hr-line-dashed"></div>

                    <?php include __DIR__ . "/profile/basic-info.phtml" ?>
                </div>
            </div>

            <?php if($this->isAdmin): ?>
            <div class="panel panel-primary staff-type">
                <div class="panel-body">

                    <?php include __DIR__ . "/staff-type.phtml" ?>
                </div>
            </div>
            <?php endif; ?>

            <?php if($user['group']['id']*1 == 3): ?>
            <div class="panel panel-primary staff-type">
                <div class="panel-body">

                    <?php include __DIR__ . "/profile/bank-info.phtml" ?>
                </div>
            </div>
            <?php endif; ?>

            <div class="panel panel-primary">
                <div class="panel-body">

                    <?php include __DIR__ . "/profile/resume.phtml" ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4 col-sm-offset-4">
                    <button class="btn btn-primary btn-block" type="submit">
                        <?php echo $this->translate('Save') ?></button>
                </div>
            </div>

        </form>
    </div>
</div>
