<?php $this->headTitle($this->translate('Staffs')) ?>
<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/admin/staff/index.js')
    ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js')
    ->prependScript("angularApp = angular.module('project', []);")
?>
<?php
$this->inlineScript()
    ->prependScript("
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
    ");
?>
<div class="ibox" id="staffController" ng-controller="listStaffController" ng-init="init()">
<div class="ibox-title">
    <h5><?php echo $this->translate('Staff') ?></h5>

    <div class="ibox-tools">
        <a data-toggle="collapse" href="#search_staff" class="btn btn-primary btn-xs"><i class="fa fa-search"></i>
            <?php echo $this->translate('Search') ?></a>
    </div>
</div>

<div class="ibox-content">
    <div class="row">
        <div class="col-lg-12">
            <div id="search_staff" class="panel-collapse collapse faq-answer">
                <form name="searchForm" action="" class="form-horizontal">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Name</label>
                                <div class="col-sm-9"><input type="text" class="form-control" ng-model="searchParams.name"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Alias</label>
                                <div class="col-sm-9"><input type="text" class="form-control" ng-model="searchParams.alias"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"></label>
                                <div class="col-sm-10">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" value="0" id="unactive" ng-click="setSearchParamInactive()"> &nbsp;&nbsp;&nbsp;<strong>Include unactive account </strong>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">ID</label>
                                <div class="col-sm-9"><input type="text" class="form-control" ng-model="searchParams.idStaff"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Type</label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="" ng-model="searchParams.type">
                                        <!--<option></option>
                                        <option value="1">Admin</option>
                                        <option value="2">General Manager</option>
                                        <option></option>
                                        <option value="3">Sales Director</option>
                                        <option value="4">Sales</option>
                                        <option></option>
                                        <option value="5">Operation Manager</option>
                                        <option value="6">Project Manager</option>
                                        <option></option>
                                        <option value="7">Financial Manager</option>
                                        <option></option>
                                        <option value="8">In-house Translator</option>
                                        <option value="9">In-house DTP</option>
                                        <option value="10">In-house Engineering</option>-->
                                        <option ng-repeat="role in roles" ng-value="role.id">{{role.type}}</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Email</label>
                                <div class="col-sm-9"><input type="text" class="form-control" ng-model="searchParams.email"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Country</label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="" ng-model="searchParams.country" >
                                        <option ng-repeat="country in countries" ng-value="country.id">{{country.name}}</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="text-right tooltip-demo">
                        <a href="#" class="btn btn-sm btn-primary" ng-click="advancedSearch()"><i class="fa fa-search"></i> Search</a>
                        <a href="#" class="btn btn-white btn-sm" type="reset" ng-click="resetSearch()"><i class="fa fa-times"></i> Reset</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="project-list">
        <table class="table table-hover">
            <tbody>
            <tr ng-hide="list.length">
                <td class="text-danger"><h3><?php echo $this->translate('No result.') ?></h3></td>
            </tr>
            <tr ng-repeat="user in list">
                <td class="project-status" width="1%">
                    <span class="label {{user.isActive ? 'label-primary' : 'label-default'}}">
                        {{user.isActive ? '<?php echo $this->translate('Active') ?>' : '<?php echo $this->translate('Unactive') ?>'}}
                    </span>
                </td>
                <td class="project-title">
                    <strong><i class="fa fa-user"></i> {{user.lastName}}, {{user.firstName}}</strong>
                    <br/>
                    <small><?php echo $this->translate('Created') ?> {{ user.createdTime }}</small>
                </td>
                <td class="project-title">
                    <strong><i class="fa fa-envelope"></i> {{user.email}}</strong>
                    <br/>
                    <small>{{user.country.name}}</small>
                </td>
                <td class="project-title">
                    <strong><i class="fa fa-smile-o"></i> {{user.staff.type.type}}</strong> <!-- here put alias -->
                    <br>
                    <small><i class="fa fa-tag"></i> {{user.alias}}</small>
                </td>
                <td class="project-completion">
                    <strong><i class="fa fa-mobile"></i> {{user.cellphone}}</strong>
                    <br />
                    <small> Tasks done: 88</small>
                </td>
                <td class="project-actions">
                    <a href="<?php echo $this->url('admin', ['controller'=>'staff', 'action'=>'view']) ?>?id={{user.id}}"
                       class="btn btn-white btn-sm">
                        <i class="fa fa-folder"></i> <?php echo $this->translate('View') ?></a>
                    <a href="<?php echo $this->url('admin', ['controller'=>'staff', 'action'=>'edit-profile']) ?>?id={{user.id}}"
                       class="btn btn-white btn-sm">
                        <i class="fa fa-pencil"></i> <?php echo $this->translate('Edit') ?></a>
                    <a ng-click="deleteStaff(user.id)" href="#" class="btn btn-danger btn-sm">
                        <i class="fa fa-trash"></i> <?php echo $this->translate('Delete') ?></a>
                    <!-- TODO: only admin has right to show the delete button -->
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div ng-hide="!list.length" class="pager btn-group text-right">
        <button type="button" data-page="{{pages.current - 1}}"
                class="btn btn-white"><i class="fa fa-chevron-left"></i></button>
        <button ng-repeat="n in rangeCustom" data-page="{{n+1}}"
                class="btn btn-white{{(n+1==pages.current) ? ' active' : ''}}">{{n + 1}}</button>
        <buttondata-page="{{pages.current + 1}}"  type="button"
            class="btn btn-white"><i class="fa fa-chevron-right"></i></button>
    </div>
</div>
</div>