<?php $this->headTitle($this->translate('Staff Profile')) ?>
<?php
$this->headScript()
    ->prependFile($this->basePath() . '/js/admin/staff/view.js')
    ->prependFile($this->basePath() . '/js/common.js')
    ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js')
					
    ->prependScript("angularApp = angular.module('project', []);")
    ->prependFile ( $this->basePath () . '/js/plugins/validate/jquery.validate.min.js' )
	->prependFile ( $this->basePath () . '/js/plugins/pace/pace.min.js' )
	->prependFile ( $this->basePath () . '/js/inspinia.js' );
$this->inlineScript()
    ->prependScript("
        var USER_ID = '" . $this->user['id'] . "';
        var STAFF_ID = '" . $staff . "';
    ");
?>
<div ng-controller="viewStaffController" class="row animated fadeInRight" ng-init="init()">
<div class="col-md-4">
    <div class="ibox">
        <div class="ibox-title">
            <h5><?php echo $this->user['lastName'] ?>, <?php echo $this->user['firstName'] ?></h5>

            <div class="ibox-tools">
                <?php if ($this->user['isActive']): ?>
                    <span class="label label-primary"><?php echo $this->translate('Active') ?></span>
                <?php else: ?>
                    <span class="label label-default"><?php echo $this->translate('Unactive') ?></span>
                <?php endif; ?>
            </div>
        </div>

        <div class="ibox-content profile-content">
            <p><i class="fa fa-envelope"></i> &nbsp; <?php echo $this->user['email'] ?>
                &nbsp;
                <?php if (!$this->user['gender']): ?>
                    <i class="fa fa-male"></i>
                <?php else: ?>
                    <i class="fa fa-female"></i>
                <?php endif; ?>
            </p>

            <p><i class="fa fa-tag"></i> &nbsp; <?php echo $this->user['alias'] ?></p>
            <!-- Freelancer Alias generate by system automaticly -->
            <p><i class="fa fa-phone"></i> &nbsp; <?php echo $user['phone']; ?></p>
            <p><i class="fa fa-mobile"></i> &nbsp; </p>

            <p><i class="fa fa-map-marker"></i> &nbsp; <?php echo $user['city'] ?>,
                {{user.user.country.name}}</p>

            <p>
                <?php
                    foreach ( $cvfiles as $k => $v ) {                        
                        ?>
                        <i class="fa fa-file-text"></i><a href="" class="text-info"> &nbsp; <?php echo $v['name'];?></a>
                        <?php
                    } 
                ?>                
            </p>

            <form role="form" class="form-inline">
                <div class="form-group">
                    <input ng-model="password" type="password"
                           placeholder="<?php echo $this->translate('Reset password') ?>"
                           class="form-control required" required>
                </div>
                <button ng-click="resetPassword()" class="btn btn-danger" type="submit">
                    <?php echo $this->translate('Reset') ?></button>
                <p ng-show="passwordChanged==1" class="text-success">
                    <?php echo $this->translate('Password changed.') ?></p>
            </form>
            <div class="hr-line-dashed"></div>
            <h4><?php echo $this->translate('Staff Type') ?></h4>

            <div class="row file-manager">
                <ul class="tag-list" style="padding: 0">
                    <li><a href="">{{staff.type.type}}</a></li>
                </ul>
            </div>

            <div class="hr-line-dashed"></div>
            <h4><?php echo $this->translate('Payment information') ?></h4>

            <p><strong><?php echo $this->translate('Paypal') ?></strong>: <?php echo $bankInfo['paypal'];?></p>

            <p><strong><?php echo $this->translate('Alipay') ?></strong>: <?php echo $bankInfo['alipay']; ?></p>

            <p><strong><?php echo $this->translate('Bank Info') ?></strong>: </p>
            <address class="well">
                <strong><?php echo $bankInfo['account']; ?></strong><br>
                <?php echo $bankInfo['address'];?><br>
                <?php echo $bankInfo['city']; ?>, <?php echo $bankInfo['country'];?> <br>
                <strong>Beneficiary Name</strong>: <?php echo $bankInfo['name'];?><br>
                <strong>Account No./IBAN</strong>: <?php echo $bankInfo['accountNo'];?><br>
                <strong>Swift Code</strong>: <?php echo $bankInfo['swift'];?><br>
                <strong>ABA Routing Number</strong>: <?php echo $bankInfo['routingNumber']; ?>
            </address>

            <a href="<?php echo $this->url('admin', ['controller'=>'staff', 'action'=>'edit-profile']) ?>?id=<?php echo $user['id'];?>"
               class="btn btn-primary btn-block"><i class="fa fa-paste"></i> Edit</a>
        </div>
    </div>
</div>
<div class="col-md-8">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h3><i class="fa fa-file-text-o"></i> <?php echo $this->translate('Resume') ?></h3>
        </div>
        <div class="ibox-content">
            <h4><?php echo $this->translate('Working Experiences') ?></h4>
            <p><?php echo $resume['workingExperiences'];?></p>
            <div class="hr-line-dashed"></div>
            <h4><?php echo $this->translate('Education') ?></h4>
            <p><?php echo $resume['education'];?></p>
        </div>
    </div>
</div>
</div>