<h1>Languages/Skills/Prices</h1>
<fieldset>

    <div class="panel panel-info">
        <div class="panel-body">
            <h4><i class="fa fa-desktop"></i>&nbsp; Currency *</h4>
            <br />
            <div data-toggle="buttons">
				<label class="btn btn-outline btn-primary {{userInfo.currency == 'cny' ? 'active' : ''}}"
					   ng-click="userInfo.currency = 'cny'">
					<input class= "required" type="radio" name="currency" value="CNY" /><i class="fa fa-cny"> CNY</i>
				</label>
				&nbsp;
				<label class="btn btn-outline btn-primary {{userInfo.currency == 'usd' ? 'active' : ''}}"
					   ng-click="userInfo.currency = 'usd'">
					<input class= "required" type="radio" name="currency" value="USD" /><i class="fa fa-usd"> USD</i>
				</label>
			</div>
		</div>
    </div>
    <div class="panel panel-primary" ng-show="translation == 1">
        <div class="panel-body">
            <h2><i class="fa fa-coffee"></i>&nbsp; Translation</h2>
            <div class="hr-line-dashed"></div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>Specialisms * &nbsp; </label>
                        <select ng-class="{ required : translation == 1}" class="form-control multiselect" multiple="multiple"
                                ng-model="freelancer.TranslationSpecialisms"
                                ng-options="t.name for t in specialisms"
                                name="userTranslationSpecialisms" id="userTranslationSpecialisms">
                        </select>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>CAT Tools * &nbsp; </label>
                        <select ng-class="{ required : translation == 1}" class="form-control multiselect" multiple="multiple"
                                ng-model="freelancer.TranslationCatTools"
                                ng-options="t.name for t in catTools"
                                name="userTranslationCatTools" id="userTranslationCatTools">
                        </select>
                    </div>
                </div>
            </div>
            
                                                <div class="table-responsive">
                                                    <table class="table table-striped table-bordered">
                                                        <thead>
                                                            <tr>
                                                                <th>#</th>
																<th><?php echo $this->translate('Source Language') ?></th>
																<th><?php echo $this->translate('Target Language') ?></th>
																<th><?php echo $this->translate('Translation Pric') ?></th>
																<th><?php echo $this->translate('Action') ?></th>
                                                            </tr>
                                                            </thead>
                                                            <tbody>
                                                            <tr ng-repeat="tp in translationPricesP">
																<td>{{$index + 1}}</td>
																<td>{{tp.sourceLanguage.name}}</td>
																<td>{{tp.targetLanguage.name}}</td>
																<td>{{tp.price | number:2 }}</td>
																<td>
																	<a href="#" ng-click="editTranslationPrice($index, tp.id)" onclick="return false;">
																		<i class="fa fa-edit"></i>
																	</a>
																	<a href="#" ng-click="deleteTranslationPrice($index, tp.id)" onclick="return false;">
																		<i class="fa fa-trash-o text-danger"></i>
																	</a>
																</td>
															</tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="hr-line-dashed"></div>
                                                <div class="text-center">
                                                    <a data-toggle="modal" class="btn btn-outline btn-primary" ng-click="addTranslationPrice()"  onclick="return false;" href="#">Add Language pairs and prices</a>
                                                </div>
        </div>
    </div>

    <div class="panel panel-info" ng-show="desktop_publish == 1">
        <div class="panel-body">
            <h2><i class="fa fa-desktop"></i>&nbsp; Desktop Publishing</h2>
            <div class="hr-line-dashed"></div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>Operating System * &nbsp; </label>
                        <select ng-class="{ required : desktop_publish == 1}" class="form-control multiselect" multiple="multiple"
                                ng-model="freelancer.DesktopOperatingSystems"
                                ng-options="t.name for t in operatingSystems"
                                name="userDesktopOperatingSystems" id="userDesktopOperatingSystems">
                        </select>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>CAT Tools * &nbsp; </label>
                        <select ng-class="{ required : desktop_publish == 1}" class="form-control multiselect" multiple="multiple"
                                ng-model="freelancer.DesktopCatTools"
                                ng-options="t.name for t in catTools"
                                name="userDesktopCatTools" id="userDesktopCatTools">
                        </select>
                    </div>
                </div>
            </div>
            <div class="hr-line-dashed"></div>
                                                <div class="table-responsive">
                                                    <table class="table table-striped">
                                                        <thead>
                                                            <tr>
                                                                <th>#</th>
																<th><?php echo $this->translate('Languages') ?></th>
																<th>DTP <?php echo $this->translate('software') ?></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Page') ?> <i class="fa fa-apple"></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Page') ?> <i class="fa fa-windows"></i></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Hour') ?> <i class="fa fa-apple"></th>
																<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Hour') ?> <i class="fa fa-windows"></i></th>
																<th>Action</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr ng-repeat="desktopPrice in desktopPricesP">
																<td>{{$index + 1}}</td>
																<td>{{desktopPrice.language.name}}</td>
																<td>{{desktopPrice.software.name}}</td>
																<td>{{desktopPrice.priceMac | number:2 }}</td>
																<td>{{desktopPrice.pricePc | number:2 }}</td>
																<td>{{desktopPrice.priceHourMac | number:2 }}</td>
																<td>{{desktopPrice.priceHourPc | number:2 }}</td>
																<td>
																	<a data-toggle="modal" href="#modal-dtp" ng-click="editDesktopPrice($index)" onclick="return false;"><i class="fa fa-edit"></i></a>
																	<a href="#" ng-click="deleteDesktopPrice($index, desktopPrice.id)" onClick="return false;"><i class="fa fa-trash-o text-danger"></i></a>
																</td>
															</tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="text-center">
                                                    <a data-toggle="modal" class="btn btn-outline btn-info"  ng-click="addDesktopPrice()" onclick="return false;" href="#"><?php echo $this->translate('Add DTP prices') ?></a>
                                                </div>
        </div>
    </div>

    <div class="panel panel-success" ng-show="interpreting == 1">
        <div class="panel-body">
            <h2><i class="fa fa-comments-o"></i>&nbsp; Interpreting</h2>
            <div class="hr-line-dashed"></div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Specialisms * &nbsp; </label>
                        <select ng-class="{ required : interpreting == 1}" class="form-control multiselect" multiple="multiple"
                                ng-model="freelancer.InterpretingSpecialisms"
                                ng-options="t.name for t in specialisms"
                                name="userInterpretingSpecialisms" id="userInterpretingSpecialisms">
                        </select>
                    </div>
                </div>
            </div>
             <div class="table-responsive">
                                                    <table class="table table-striped">
                                                        <thead>
                                                            <tr>
                                                                <th>#</th>
                                                                <th>Source Language </th>
                                                                <th>Target Language </th>
                                                                <th>Interpreting Service</th>
                                                                <th>Price/Day</th>
                                                                <th>Price/half-Day</th>
                                                                <th>Action</th>
                                                            </tr>
                                                            </thead>
                                                            <tbody>
                                                            <tr ng-repeat="interpretingPrice in interpretingPricesP">
																<td>{{$index + 1}}</td>
																<td>{{interpretingPrice.sourceLanguage.name}}</td>
																<td>{{interpretingPrice.targetLanguage.name}}</td>
																<td>{{interpretingPrice.service.name}}</td>
																<td>{{interpretingPrice.priceDay | number:2 }}</td>
																<td>{{interpretingPrice.priceHalfDay | number:2 }}</td>
																<td>
																	<a data-toggle="modal" href="#" ng-click="editInterpretingPrice($index)" onclick="return false;"><i class="fa fa-edit"></i></a>
																	<a href="#" ng-click="deleteEngineeringPrice($index, interpretingPrice.id)" onclick="return false;"><i class="fa fa-trash-o text-danger"></i></a>
																</td>
															</tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                <div class="text-center">
                                                    <a data-toggle="modal" class="btn btn-outline btn-success" ng-click="addInterpretingPrice()" onclick="return false;" href="#"><?php echo $this->translate('Add Interpreting prices') ?></a>
                                                </div>
        </div>
    </div>
</fieldset>