<div class="ibox" ng-controller="AppController" nv-file-drop="" uploader="uploader">
    <div class="ibox-title">
        <h5><i class="fa fa-files-o"></i> Project Files / Source Text</h5>
        <div class="ibox-tools" id="files">
            <input type="file" nv-file-select="" uploader="uploader" multiple="multiple" />
        </div>
    </div>
    <div class="ibox-content">
        <div class="row">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>#</th>
                    <th>File Name</th>
                    <th>File Size</th>
                    <th>Time Stamp</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="item in uploader.queue">
                    <td>{{$index + 1}}</td>
                    <td><a href="#" ng-hide="item.isUploading">{{ item.file.name }}</a>
                        <div class="progress" style="margin-bottom: 0" ng-show="item.isUploading">
                            <div class="progress-bar" role="progressbar"
                                 ng-style="{ 'width': uploader.progress + '%' }" style="width: 0%;">{{ item.file.name }}</div>
                        </div>
                    </td>
                    <td class="text-right">{{ item.file.size/1024|number:2 }} Kb</td>
                    <td>{{ DateFormatter.format(item.file.lastModified) }}</td>
                    <td class="text-center child-is-link">
                        <i ng-click="removeItem(item)" class="fa fa-trash-o text-danger"></i>
                    </td>
                </tr>
                </tbody>
            </table>
            <div class="hr-line-dashed"></div>
                <div class="col-lg-12">
                    <textarea class="form-control" ng-model="project.sourcetext" rows="3"></textarea>
                </div>
        </div>
    </div>
</div>