<?php $this->headTitle($this->translate('Dashboard')) ?>
<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/footable/footable.core.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/v2/js/employer/client-dashboard.js')
	
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/footable/footable.all.min.js')
	->prependScript("angularApp = angular.module('project', []);")
?>

    <script>
        $(document).ready(function() {

            $('.footable').footable();

        });

    </script>

<?php
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>
<div class="row animate fadeInUp" ng-controller="DashboardProjectController">

	<div class="col-lg-12">
        <div class="col-md-6">
        <a href="<?php echo $this->url('admin', array('controller' => 'project', 'action' => 'order-translation',"lang"=>$this->translate('lang','Application'))) ?>">
            <div class="ibox-content product-box m-b-sm border-bottom text-navy">
                <div class="text-center p-lg">
                    <h1><i class="fa fa-archive"></i> <strong><?php echo $this->translate('Order a Translation','Employer'); ?></strong></h1>
                </div>
            </div>
        </a>
        </div>

        <div class="col-md-6">
        <a href="<?php echo $this->url('admin', array('controller' => 'project', 'action' => 'need-quote',"lang"=>$this->translate('lang','Application'))) ?>">
            <div class="ibox-content product-box m-b-sm border-bottom text-navy">
                <div class="text-center p-lg">
                    <h1><i class="fa fa-file-pdf-o"></i> <strong><?php echo $this->translate('I Need a Quote','Employer'); ?></strong></h1>
                </div>
            </div>
        </a>
        </div>


        <div class="ibox">
            <div class="ibox-content">

                <div class="project-list">

                    <table class="footable table table-hover toggle-arrow-tiny">
                        <thead>
                        <tr>
                            <th data-toggle="true" data-hide="phone,tablet"><?php echo $this->translate('Status','Employer'); ?></th>
                            <th data-toggle="true"><?php echo $this->translate('Project ID','Employer'); ?></th>
                            <th data-toggle="true" data-hide="phone,tablet"><?php echo $this->translate('Project Reference','Employer'); ?></th>
                            <th data-hide="phone,tablet"><?php echo $this->translate('Project Date','Employer'); ?></th>
                            <th data-toggle="true" class="text-right"><?php echo $this->translate('Price','Employer'); ?></th>
                        </tr>
                        </thead>                                
                        <tbody>
                           <tr ng-repeat="project in allprojects">
                                <td class="project-status">
									
                                    <span class="label label-danger" style="font-size: 12px;" ng-if="project.status == 0">{{ ProjectStatus.get(project.status).name }}</span>
									<span class="label label-danger" style="font-size: 12px;" ng-if="project.status == 1">{{ ProjectStatus.get(project.status).name }}</span>
									<span class="label label-warning" style="font-size: 12px;" ng-if="project.status == 2">{{ ProjectStatus.get(project.status).name }}</span>
									<span class="label label-success" style="font-size: 12px;" ng-if="project.status == 3">{{ ProjectStatus.get(project.status).name }}</span>
									<span class="label label-info" style="font-size: 12px;" ng-if="project.status == 4">{{ ProjectStatus.get(project.status).name }}</span>
                                </td>
                                <td class="project-title">
                                    <span style="font-size: 16px;">{{ project.project_no }}</span>
                                </td>
                                <td class="project-title">
                                    <span><code style="font-size: 14px;">{{ project.sourceLanguage.name }} <i class="fa fa-arrow-right"></i>
                                        <span ng-repeat="lang in project.targetLanguages">
                                            {{ lang.name}}   
                                        </span>
                                        </code>
                                    </span>
                                    <br />
                                    <span style="font-size: 14px;">{{ project.reference }}</span>
                                    

                                </td>
                                <td class="project-title">
                                    <small style="font-size: 12px;">{{ DateFormatter.short(project.startDate) }}</small>
                                </td>
                                <td class="project-actions text-right">
                                    <span class="text-warning" style="font-size: 15px;"><strong>{{ project.currency}} {{ project.total_tmp}}</strong></span>&nbsp;
										
                                    <a href="#" class="btn btn-info btn-sm" ng-show="project.status == 0"><i class="fa fa-check"></i> <?php echo $this->translate('Accept','Employer'); ?> </a>

									<a href="#" class="btn btn-white btn-sm" ng-click="goToDetail(project)"><i class="fa fa-folder"></i> <?php echo $this->translate('View','Employer'); ?> </a>
                                </td>
                            </tr>
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    

      
	</div>
</div>