<?php $this->headTitle($this->translate('Dashboard')) ?>
<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/v2/js/plugins/footable/footable.core.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/v2/js/admin/dashboard/client-dashboard.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/footable/footable.all.min.js')
?>

    <script>
        $(document).ready(function() {

            $('.footable').footable();

        });

    </script>

<?php
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>
<div class="row animate fadeInUp" ng-controller="DashboardProjectController">

	<div class="col-lg-12">
        <div class="col-md-6">
        <a href="<?php echo $this->url('admin', array('controller' => 'project', 'action' => 'order-translation',"lang"=>$this->translate('lang','Application'))) ?>">
            <div class="ibox-content product-box m-b-sm border-bottom text-navy">
                <div class="text-center p-lg">
                    <h1><i class="fa fa-archive"></i> <strong><?php echo $this->translate('Order a Translation','Employer'); ?></strong></h1>
                </div>
            </div>
        </a>
        </div>

        <div class="col-md-6">
        <a href="<?php echo $this->url('admin', array('controller' => 'project', 'action' => 'need-quote',"lang"=>$this->translate('lang','Application'))) ?>">
            <div class="ibox-content product-box m-b-sm border-bottom text-navy">
                <div class="text-center p-lg">
                    <h1><i class="fa fa-file-pdf-o"></i> <strong><?php echo $this->translate('I Need a Quote','Employer'); ?></strong></h1>
                </div>
            </div>
        </a>
        </div>






        <div class="ibox">
            <div class="ibox-content">




                <div class="project-list">

                    <table class="footable table table-hover toggle-arrow-tiny">
                        <thead>
                        <tr>

                            <th data-hide="phone,tablet"><?php echo $this->translate('Status','Employer'); ?></th>
                            <th><?php echo $this->translate('Project ID','Employer'); ?></th>
                            <th data-hide="phone,tablet"><?php echo $this->translate('Project Info','Employer'); ?></th>
                            <th class="text-right"><?php echo $this->translate('Price','Employer'); ?></th>
                        </tr>
                        </thead>                                
                        <tbody>
                            <tr>
                                <td class="project-status">
                                    <span class="label label-danger" style="font-size: 12px;">Quote</span>
                                </td>
                                <td class="project-title text-navy">
                                    <a href="project_detail.html">201511124888</a>
                                    <br/>
                                    <small style="font-size: 12px;">2015.Nov.17 - 2015.Nov.23</small>
                                </td>
                                <td class="project-title">
                                    
                                    <span class="simple_tag" style="font-size: 8px;">English</span>
                                    <i class="fa fa-arrow-right"></i>
                                    <span class="simple_tag" style="font-size: 8px;">Chinese</span>
                                    <span class="simple_tag" style="font-size: 8px;">Jananese</span>
                                    
                                    <br/>
                                    <span>
                                    here put project deccription                                        
                                    </span>
                                </td>
                                <td class="project-actions text-right">
                                    <span class="text-warning" style="font-size: 15px;"><strong>USD 50.25</strong></span>&nbsp;
                                    <a href="#" class="btn btn-info btn-sm"><i class="fa fa-check"></i> Accept </a>
                                    <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> View </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="project-status">
                                    <span class="label label-warning" style="font-size: 12px;">Ordered</span>
                                </td>
                                <td class="project-title text-navy">
                                    <a href="project_detail.html">201511124888</a>
                                    <br/>
                                    <small style="font-size: 12px;">2015.Nov.17 - 2015.Nov.23</small>
                                </td>
                                <td class="project-title tooltip-demo">
                                    <span class="simple_tag" style="font-size: 8px;">English</span>
                                    <i class="fa fa-arrow-right"></i>
                                    <span class="simple_tag" style="font-size: 8px;">Chinese</span>
                                    <span class="simple_tag" style="font-size: 8px;">Jananese</span>
                                    <span class="simple_tag" style="font-size: 8px;">Korean</span>
                                    <span class="simple_tag" style="font-size: 8px;">Spanish</span>
                                    <span class="simple_tag" style="font-size: 8px;">Russian</span>
                                    <br/>
                                    <span>
                                    here put project deccription                                        
                                    </span>
                                </td>
                                <td class="project-actions text-right">
                                    <span class="text-navy" style="font-size: 15px;"><strong>USD 50.25</strong></span>&nbsp;
                                    <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> View </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="project-status">
                                    <span class="label label-success" style="font-size: 12px;">Ongoing</span>
                                </td>
                                <td class="project-title text-navy">
                                    <a href="project_detail.html">201511124888</a>
                                    <br/>
                                    <small style="font-size: 12px;">2015.Nov.17 - 2015.Nov.23</small>
                                </td>
                                <td class="project-title tooltip-demo">
                                    <span class="simple_tag" style="font-size: 8px;">English</span>
                                    <i class="fa fa-arrow-right"></i>
                                    <span class="simple_tag" style="font-size: 8px;">Chinese</span>
                                    <span class="simple_tag" style="font-size: 8px;">Jananese</span>
                                    <span class="simple_tag" style="font-size: 8px;">Korean</span>
                                    <span class="simple_tag" style="font-size: 8px;">Spanish</span>
                                    <span class="simple_tag" style="font-size: 8px;">Russian</span>
                                    <span class="simple_tag" style="font-size: 8px;">Chinese</span>
                                    <span class="simple_tag" style="font-size: 8px;">Jananese</span>
                                    <span class="simple_tag" style="font-size: 8px;">Korean</span>
                                    <span class="simple_tag" style="font-size: 8px;">Spanish</span>
                                    <span class="simple_tag" style="font-size: 8px;">Russian</span>
                                    <br/>
                                    <span>
                                    here put project deccription                                        
                                    </span>
                                </td>
                                <td class="project-actions text-right">
                                    <span class="text-navy" style="font-size: 15px;"><strong>USD 50.25</strong></span>&nbsp;
                                    <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> View </a>
                                </td>
                            </tr>
                            <tr>
                                <td class="project-status">
                                    <span class="label label-info" style="font-size: 12px;">Reviewing</span>
                                </td>
                                <td class="project-title text-navy">
                                    <a href="project_detail.html">201511124888</a>
                                    <br/>
                                    <small style="font-size: 12px;">2015.Nov.17 - 2015.Nov.23</small>
                                </td>
                                <td class="project-title tooltip-demo">
                                    <span class="simple_tag" style="font-size: 8px;">English</span>
                                    <i class="fa fa-arrow-right"></i>
                                    <span class="simple_tag" style="font-size: 8px;">Russian</span>
                                    <span class="simple_tag" style="font-size: 8px;">Chinese</span>
                                    <span class="simple_tag" style="font-size: 8px;">Jananese</span>
                                    <span class="simple_tag" style="font-size: 8px;">Korean</span>
                                    <span class="simple_tag" style="font-size: 8px;">Spanish</span>
                                    <span class="simple_tag" style="font-size: 8px;">Russian</span>
                                    <br/>
                                    <span>
                                    here put project deccription                                        
                                    </span>
                                </td>
                                <td class="project-actions text-right">
                                    <span class="text-navy" style="font-size: 15px;"><strong>USD 50.25</strong></span>&nbsp;
                                    <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> View </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    

      
	</div>
</div>