<?php $this->headTitle($this->translate('Dashboard')) ?>
<!-- Le styles -->
<?php $this->headLink()
    //->prependStylesheet($this->basePath() . '/v2/js/plugins/datetimepicker/DateTimePicker.css')
    //->prependStylesheet($this->basePath() . '/v2/css/plugins/summernote/summernote-bs3.css')
    //->prependStylesheet($this->basePath() . '/v2/css/plugins/summernote/summernote.css')
    //->prependStylesheet($this->basePath() . '/v2/css/plugins/multiselect/bootstrap-multiselect.css')
//    ->prependStylesheet($this->basePath() . '/v2/css/plugins/steps/jquery.steps.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    //->prependFile($this->basePath() . '/v2/js/plugins/datetimepicker/DateTimePicker.js')
    ->prependFile($this->basePath() . '/v2/js/admin/dashboard/client-dashboard.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/CurrentUser.js')
    //->prependFile($this->basePath() . '/v2/js/admin/angular-steps.js')
    //->prependFile($this->basePath() . '/v2/js/admin/bootstrap-modal.js')
    //->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload', 'ui.bootstrap']);")
    //->prependFile($this->basePath() . '/v2/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    //->prependFile($this->basePath() . '/v2/js/plugins/angular-bootstrap/ui-bootstrap-tpls-0.11.2.min.js')
    //->prependFile($this->basePath() . '/v2/js/plugins/angular-bootstrap/ui-bootstrap-0.11.2.min.js')
    //->prependFile($this->basePath() . '/v2/js/plugins/angular-summernote/angular-summernote.js')
    //->prependFile($this->basePath() . '/v2/js/plugins/summernote/summernote.min.js')
    //->prependFile($this->basePath() . '/v2/js/plugins/multiselect/bootstrap-multiselect.js')
    //->prependFile($this->basePath() . '/v2/js/plugins/validate/jquery.validate.min.js')
    //->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/bootbox/bootbox.min.js')
    //->prependFile($this->basePath() . '/v2/js/plugins/pace/pace.min.js')
    //->prependFile($this->basePath() . '/v2/js/inspinia.js')
?>

<?php
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>
<div class="row animate fadeInUp" ng-controller="DashboardProjectController">

<!--
                <div class="col-md-6">
                    <div class="ibox">
                        <div class="ibox-content product-box">

                        	<a href="<?php echo $this->url('admin', array('controller' => 'project', 'action' => 'order-translation',"lang"=>$this->translate('lang','Application'))) ?>">
	                            <div class="product-imitation" style="color: #676a6c">
	                                <i class="fa fa-archive fa-5x"></i>
	                                <h1 class="m-b-xs"><strong><?php echo $this->translate('Order a Translation','Admin'); ?></strong></h1>
	                                <div class="font-bold">
	                                	<?php echo $this->translate('Please provide translation information, the quote will be provided in the shortest time. ','Admin'); ?>
	                                </div>
	                            </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="ibox">
                        <div class="ibox-content product-box">

                        	<a href="<?php echo $this->url('admin', array('controller' => 'project', 'action' => 'need-quote',"lang"=>$this->translate('lang','Application'))) ?>">
	                            <div class="product-imitation" style="color: #676a6c">
	                                <i class="fa fa-archive fa-5x"></i>
	                                <h1 class="m-b-xs"><strong><?php echo $this->translate('I Need a Quote','Admin'); ?></strong></h1>
	                                <div class="font-bold">
	                                	<?php echo $this->translate('Please provide translation information, the quote will be provided in the shortest time. ','Admin'); ?>
	                                </div>
	                            </div>
                            </a>
                        </div>
                    </div>
                </div>
-->

	<div class="col-lg-12">

        <a href="<?php echo $this->url('admin', array('controller' => 'project', 'action' => 'order-translation',"lang"=>$this->translate('lang','Application'))) ?>">
            <div class="ibox-content product-box m-b-sm border-bottom text-navy">
                <div class="text-center p-lg">
                    <h1><i class="fa fa-plus"></i> <strong><?php echo $this->translate('Order a Translation','Admin'); ?></strong></h1>
                    <span><?php echo $this->translate('Please provide translation information, the quote will be provided in the shortest time. ','Admin'); ?></span>
                </div>
            </div>
        </a>

                    <div class="ibox">
                        <div class="ibox-content">

                            <div class="project-list">

                                <table class="table table-hover">
                                    <tbody>
                                    <tr>
                                        <td class="project-status">
                                            <span class="label label-danger">Quote</span>
                                        </td>
                                        <td class="project-title text-navy">
                                            <a href="project_detail.html">201511124888</a>
                                            <br/>
                                            <small style="font-size: 12px;">project deccription</small>
                                        </td>
                                        <td class="project-title tooltip-demo">
                                            <button class="btn btn-white btn-xs" data-toggle="tooltip" data-placement="top" title="Tooltip on left"> Tag</button>
                                            <button class="btn btn-white btn-xs"> Mag</button>
                                            <button class="btn btn-white btn-xs"> Rag</button>

                                            <br/>
                                            <small style="font-size: 12px;">project deccription</small>
                                        </td>
                                        <td class="project-people">
                                            <a href=""><img alt="image" class="img-circle" src="img/a3.jpg"></a>
                                            <a href=""><img alt="image" class="img-circle" src="img/a1.jpg"></a>
                                            <a href=""><img alt="image" class="img-circle" src="img/a2.jpg"></a>
                                            <a href=""><img alt="image" class="img-circle" src="img/a4.jpg"></a>
                                            <a href=""><img alt="image" class="img-circle" src="img/a5.jpg"></a>
                                        </td>
                                        <td class="project-actions">
                                            <a href="#" class="btn btn-white btn-sm"><i class="fa fa-check"></i> Accept </a>
                                            <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> View </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="project-status">
                                            <span class="label label-info">Ordered</span>
                                        </td>
                                        <td class="project-title text-navy">
                                            <a href="project_detail.html">201511124888</a>
                                            <br/>
                                            <small style="font-size: 12px;">project deccription</small>
                                        </td>
                                        <td class="project-completion">
                                            <button class="btn btn-white btn-xs"> Tag</button>
                                            <button class="btn btn-white btn-xs"> Mag</button>
                                            <button class="btn btn-white btn-xs"> Rag</button>

                                            <div class="progress progress-mini">
                                                <div style="width: 28%;" class="progress-bar"></div>
                                            </div>
                                        </td>
                                        <td class="project-people">
                                            <a href=""><img alt="image" class="img-circle" src="img/a7.jpg"></a>
                                            <a href=""><img alt="image" class="img-circle" src="img/a6.jpg"></a>
                                            <a href=""><img alt="image" class="img-circle" src="img/a3.jpg"></a>
                                        </td>
                                        <td class="project-actions">
                                            <a href="#" class="btn btn-white btn-sm"><i class="fa fa-folder"></i> View </a>
                                            <a href="#" class="btn btn-white btn-sm"><i class="fa fa-pencil"></i> Edit </a>
                                        </td>
                                    </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
        
            <div class="vote-item">
                <div class="row">
                    <a href="#">
                    <div class="col-md-11 text-navy">
                        <div class="vote-title" style="margin-left: 5px;">
                            201511124888
                        </div>
                        <div class="vote-info" style="margin-left: 5px;">
                            <span style="font-size: 12px;">test111</span>
                        </div>
                    </div>
                    </a>
                    <div class="col-md-1 ">
                        <div class="vote-icon">
                            <span class="label label-danger" style="font-size: 15px;">Quote</span>
                        </div>
                    </div>
                </div>
            </div>
        

        <br />

        <a href="#">
            <div class="vote-item">
                <div class="row">
                    <div class="col-md-11 text-navy">
                        <div class="vote-title" style="margin-left: 5px;">
                            201511124888
                        </div>
                        <div class="vote-info" style="margin-left: 5px;">
                            <i class="fa fa-comments-o"> Comments (32)</i> 
                            <i class="fa fa-clock-o"> 1 Hours ago</i> 
                            <i class="fa fa-user"> Andrew Williams</i> 
                        </div>
                    </div>
                    <div class="col-md-1 ">
                        <div class="vote-icon">
                            <span class="label label-info" style="font-size: 12px;">Ordered</span>
                        </div>
                    </div>
                </div>
            </div>
        </a>
        <a href="#">
            <div class="vote-item">
                <div class="row">
                    <div class="col-md-11 text-navy">
                        <div class="vote-title" style="margin-left: 5px;">
                            201511124888
                        </div>
                        <div class="vote-info" style="margin-left: 5px;">
                            <i class="fa fa-comments-o"> Comments (32)</i> 
                            <i class="fa fa-clock-o"> 1 Hours ago</i> 
                            <i class="fa fa-user"> Andrew Williams</i> 
                        </div>
                    </div>
                    <div class="col-md-1 ">
                        <div class="vote-icon">
                            <span class="label label-primary" style="font-size: 12px;">Ongoing</span>
                        </div>
                    </div>
                </div>
            </div>
        </a>
        <a href="#">
            <div class="vote-item">
                <div class="row">
                    <div class="col-md-11 text-navy">
                        <div class="vote-title" style="margin-left: 5px;">
                            201511124888
                        </div>
                        <div class="vote-info" style="margin-left: 5px;">
                            <i class="fa fa-comments-o"> Comments (32)</i> 
                            <i class="fa fa-clock-o"> 1 Hours ago</i> 
                            <i class="fa fa-user"> Andrew Williams</i> 
                        </div>
                    </div>
                    <div class="col-md-1 ">
                        <div class="vote-icon">
                            <span class="label label-success" style="font-size: 12px;">Reviewing</span>
                        </div>
                    </div>
                </div>
            </div>
        </a>
        <a href="#">
            <div class="vote-item">
                <div class="row">
                    <div class="col-md-11 text-navy">
                        <div class="vote-title" style="margin-left: 5px;">
                            201511124888
                        </div>
                        <div class="vote-info" style="margin-left: 5px;">
                            <i class="fa fa-comments-o"> Comments (32)</i> 
                            <i class="fa fa-clock-o"> 1 Hours ago</i> 
                            <i class="fa fa-user"> Andrew Williams</i> 
                        </div>
                    </div>
                    <div class="col-md-1 ">
                        <div class="vote-icon">
                            <span class="label label-warning" style="font-size: 12px;">Unpaid</span>
                        </div>
                    </div>
                </div>
            </div>
        </a>        
	</div>
</div>