<div class="setup-content" id="step-2">
	<div class="col-md-12">
	    <div class="ibox-title">
	        <h3><?php echo $this->translate('Select Translation Languages','Admin'); ?></h3>
	     </div>
		<div class="ibox-content">

			<div class="row">
				
				<div class="col-md-6">					
					<select id="sourceLanguage" required class="form-control required valid" name="sourceLanguage"
					aria-required="true"
					ng-options="language.name for language in sourceLanguages track by language.id"
					ng-model="project.sourceLanguage"
					required
					ng-change="changePServicePrice();removeLangFSML();clearTargetLanguages();">
					<option value="" ng-disabled="disable" ng-hide="true">Select Source Language</option>
				</select>

				</div>
				<div class="col-md-6">

					<select class="form-control required valid" name="targetLanguage"
					aria-required="true"
					ng-options="language.name for language in modifiedTarLangs track by language.id"
					ng-model="project.targetLanguage"
					required
					ng-change="add_targetLanguage();changePServicePrice();">
					<option value="" ng-hide="hidetargetLang" >Add Target Languages</option>
				</select>
				</div>
			</div>
		</div>
		<br />

        <div class="ibox-content">
            <div id="projectsList">
                <div class="project-list">

                    <table class="footable table table-hover toggle-arrow-tiny">
                        <thead>
                        <tr style="font-size: 16px;">
                        	<th data-hide="phone,tablet"></th>
                            <th ><?php echo $this->translate('Target Languages','Admin'); ?></th>
                            <th data-hide="phone,tablet"><?php echo $this->translate('Unit Price','Admin'); ?></th>
                            <th data-hide="phone,tablet"><?php echo $this->translate('Quality Level','Admin'); ?></th>
                            <th data-hide="phone,tablet"><?php echo $this->translate('Translate Graphics?','Admin'); ?></th>
                            <th class="text-right"></th>
                        </tr>
                        </thead>                                
                        <tbody>
                            <tr ng-repeat="item in project.targetLanguages">
                                <td class="project-status">
                                    <span class="label label-warning pull-left">{{$index + 1}}</span>
                                </td>
                                <td class="project-status">
                                    <span style="font-size: 14px;" class="label label-info">{{item.name}}</span>
                                </td>
                                <td class="project-title">
                                    <strong class="text-danger" style="font-size: 16px;">{{currency}} {{item.price | number:3}} / <?php echo $this->translate('Word','Admin'); ?></strong>
                                </td>
                                <td class="project-title tooltip-demo">
									<select required class="form-control valid" name="servicelevel"
										aria-required="false"
										ng-options="servicelevel.name for servicelevel in ProjectServiceLevel"
										ng-model="project.serviceLevel"							
										ng-change="changePServicePrice();">
										<option value="" ng-hide="true">Select Quality level</option>
									</select>
                                </td>
                                <td class="project-title tooltip-demo">
									<select class="form-control required valid " name="transGraph"
										aria-required="true"
										ng-options="transGraph.name for transGraph in transGraphs"
										ng-model="project.transGraph"
										ng-change="changeTransGraphs()">
									</select>
                                </td>

                                <td class="project-actions text-right child-is-link">
                                	<button ng-click="removeTargetLang(item)" class="btn btn-white btn-xs"> <i class="fa fa-trash-o text-danger"></i></button>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <div class="btn-group text-right">
                        <pagination total-items="pages.totalItemCount" ng-model="page" max-size="maxSize"
                                    class="pagination-sm" boundary-links="true" ng-change="pageChanged()"></pagination>
                    </div>
                </div>
            </div>
        </div>

        <br /><br />
		<div class="text-center">
			<button id="activate-step-1" type="button" class="btn btn-primary btn-lg"><?php echo $this->translate('Previous','Admin'); ?></button>
            <button id="activate-step-3"  type="button" ng-click="orderTranslation()" class="btn btn-primary btn-lg"><?php echo $this->translate('Order Translation','Admin'); ?></button>
		</div>
		<br /><br /><br />
	</div>
</div>

