<div class=" setup-content" id="step-2">
	<div class="col-md-12">
		<hr>
		<div class="row">
			<div class="col-md-6">
				<h4>Translate From *</h4>
				<select id="sourceLanguage" required class="form-control required valid" name="sourceLanguage"
					aria-required="true"
					ng-options="language.name for language in languages"
					ng-model="project.sourceLanguage"
					required
					ng-change="removeLangFSML();clearTargetLanguages();">
					<option value="" ng-disabled="disable" ng-hide="true">Select Source Language</option>
				</select>

			</div>
			<div class="col-md-6">
				<h4>Translate To *</h4>
				<select class="form-control required valid" name="targetLanguage"
					aria-required="true"
					ng-options="language.name for language in modifiedTarLangs"
					ng-model="project.targetLanguage"
					required
					ng-change="add_targetLanguage();changePServicePrice();">
					<option value="" ng-hide="true" >Add Target Languages</option>
				</select>
			</div>
		</div>
		<br>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>#</th>
					<th>Target Languages</th>
					<th>Rate</th>
					<th>Quality Level</th>
					<th>Translate Graphics</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="item in project.targetLanguages">
					<td>{{$index + 1}}</td>
					<td><span class="label label-primary">{{item.name}}</span></td>
					<td>{{currency}} {{item.price}} / word</td>
					<!-- here load the price of this client, if there is not private price for this client, then load papertask list price -->
					<td>
						<!-- here should put client default service level, get info from client profile page -->	
						<select required class="form-control valid" name="servicelevel"
							aria-required="false"
							ng-options="servicelevel.name for servicelevel in ProjectServiceLevel"
							ng-model="project.serviceLevel"							
							ng-change="changePServicePrice();">
							<option value="" ng-hide="true">Select Quality level</option>
						</select>
					</td>
					<td>
							<!-- default all "yes" -->
							<select class="form-control required valid " name="transGraph"
							aria-required="true"
							ng-options="transGraph.name for transGraph in transGraphs"
							ng-model="project.transGraph"
							ng-change="changeTransGraphs()">	
						</select>
					</td>

					<td class="text-center child-is-link"><i
						ng-click="removeTargetLang(item)"
						class="fa fa-trash-o text-danger"></i>
					</td>
				</tr>
				<!-- 
			<tr>
				<td>2</td>
				<td><span class="label label-primary">Chinese</span>
				</td>
				<td>CNY 0.12 / word</td>
				
				<td class="text-center"><a href="#"><i
						class="fa fa-trash-o text-danger"></i>
				</a></td>
			</tr> -->
			</tbody>
		</table>
		<div class="text-center">
			<button id="activate-step-1" type="button" class="btn btn-primary btn-lg">Previous</button>
            <button id="activate-step-3" ng-hide="isGraph" type="button" ng-click="orderTranslation()" class="btn btn-primary btn-lg">Order Translation</button>
			<button type="button"    ng-click="needaQuote()" class="btn btn-primary btn-lg">Order Translation</button>
		</div>
	</div>
</div>
