<div class="row setup-content" id="step-1">
	<div class="col-lg-12">
        <div class="tabs-container">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#tab-1" style="font-size: 18px;"><?php echo $this->translate('Upload file(s)','Admin'); ?></a></li>
                <!--
                <li class=""><a data-toggle="tab" href="#tab-2">Paste Text</a></li>
                -->
            </ul>
            <div class="tab-content">
                <div id="tab-1" class="tab-pane active">
					<div class="panel-body" ng-controller="AppController"
						nv-file-drop="" uploader="uploader">
						<div class="col-md-12">
							<div class="col-md-9">
								<h2>
									<?php echo $this->translate('We accept the following files, under','Admin'); ?> <span
										class="text-danger">50MB</span> <?php echo $this->translate('size:','Admin'); ?></a>
								</h2>
								<p style="font-size: 15px;"><?php echo $this->translate('Allowed file types are "txt, zip, rar, gif, jpeg, jpg, png, doc, docx, ppt, pptx, pdf, chm, xls, xlsx, txt, zip, rar".','Admin'); ?></p>
								<p>
									<!--
									<span class="text-danger"><?php echo $this->translate('If files are bigger then 50MB, pleasae put the download link into the "Project Information" at bottom.','Admin'); ?></span>
									-->
								</p>
							</div>
							<br />
							<div class="col-md-3 text-center" id="files">
								<span class="btn btn-primary btn-lg fileinput-button"> <i
									class="fa fa-cloud-upload"></i> <span><?php echo $this->translate('Select files','Admin'); ?></span>
									<input id="fileupload" type="file" name="files[]"
									nv-file-select="" uploader="uploader" multiple>
								</span>
							</div>
							<br /><br />
							<table class="table table-bordered">
								<!--
								<thead>
									<tr>
										<th width="10%">#</th>
										<th><?php echo $this->translate('File Name','Admin'); ?></th>
										<th width="20%"><?php echo $this->translate('File Size','Admin'); ?></th>
										
										<th><?php echo $this->translate('size:','Admin'); ?>Time Stamp</th>
										
										<th width="5%"></th>
									</tr>
								</thead>
								-->
								<tbody>
									<tr ng-repeat="item in uploader.queue" style="font-size: 18px;">
										<td width="5%">{{$index + 1}}</td>
										<td><a href="#" ng-hide="item.isUploading">{{
												item.file.name }}</a>
											<div class="progress" style="margin-bottom: 0"
												ng-show="item.isUploading">
												<div class="progress-bar" role="progressbar"
													ng-style="{ 'width': uploader.progress + '%' }"
													style="width: 0%;">{{ item.file.name }}</div>
											</div></td>
										<td>{{ item.file.size/1024/1024|number:2 }} Mb</td>
										<!--
										<td>{{ getTime(item) }}</td>
										-->
										<td width="5%" class="text-center child-is-link"><a href=""><i
											ng-click="removeItem(item)"
											class="fa fa-trash-o text-danger"></i></a></td>
									</tr>
								</tbody>
							</table>
						</div>

					</div>
                </div>
                <!--
                <div id="tab-2" class="tab-pane">
                    <div class="panel-body">
                        <textarea class="form-control" rows="8"
							ng-model="project.sourcetext"></textarea>
                    </div>
                </div>
                -->
            </div>
        </div>

        <br /><br />

		<div class="text-center">
			<button id="activate-step-2" type="button"
				class="btn btn-primary btn-lg" ng-click="initStep2()"><?php echo $this->translate('Next','Admin'); ?></button>
			<!-- next button show after at least one file is uploaded -->
		</div>
		<br /><br /><br />
	</div>
</div>
