<?php $this->headTitle($this->translate('Result','Landing')) ?>

<div class="features">
    <div class="container">
		 <br />
          <br />
          <br />
          <br />
		<div class="row feature-row-last">
              <div class="item col-md-6 col-md-offset-3 text-center">
                  <h1 class="icon">
                      <i class="fa fa-check-circle"></i>
                  </h1><!--//icon-->
                  <div class="content">
                      <?php echo $this->html_text?>

                  </div><!--//content-->
              </div><!--//item-->
			

          </div><!--//row-->
    </div>
</div>