<?php $this->headTitle($this->translate('GET IN TOUCH WITH PAPERTASK','Landing')); ?>

<?php
echo $this->headScript()
    ->prependFile($this->basePath() . '/js/landing/contact.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependScript("angularApp = angular.module('contact', []);")
    ->prependFile($this->basePath() . '/js/angular.min.js');
    
echo $this->inlineScript()
    ->prependScript("
        var LANG_CODE = '" . $this->lang_code . "';
        var EXITS_CONFIRM_TEXT = '" . $this->translate('This option was existed, please choose other') . "';
        "); 

?>

    <!-- ******CONTACT****** --> 
    <section id="contact" class="contact section has-pattern">
        <div class="container">
            <div class="row text-center">
                <br /><br />
                <h1 class="text-center"><?php echo $this->translate('GET IN TOUCH WITH PAPERTASK','Landing') ?></h1>
                <br />
                <div class="intro col-md-6 col-sm-12 col-xs-12 col-md-offset-3">
                    <h3 class="text-center">
                    <?php echo $this->translate('PLEASE CONTACT US TO GET MORE INFORMATION ABOUT OUR SERVICES','Landing') ?></h3>
                    <br />
                    <ul class="list-unstyled contact-details">
                        <li><i class="fa fa-envelope"></i><a href="mailto:contact@papertask.com">contact@papertask.com</a></li>
                    </ul>
                    <br />
                </div>
            </div><!--//row-->
            <div class="row text-center">
                <div class="contact-form row">                            
                    <form class="form">                
                        <div class="contact-form col-md-6 col-sm-12 col-xs-12">                            
                            <div class="form-group">
                                <label class="sr-only"><?php echo $this->translate('First Name','Landing') ?> *</label>
                                <input name="firstName" type="text" ng-model="form.firstName" class="form-control required" placeholder="<?php echo $this->translate('First Name','Landing') ?> *" required>
                            </div><!--//form-group-->
                        </div>
                        <div class="contact-form col-md-6 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label class="sr-only"><?php echo $this->translate('Last Name','Landing') ?> *</label>
                                <input name="lastName" type="text" ng-model="form.lastName" class="form-control required" required placeholder="<?php echo $this->translate('Last Name','Landing') ?> *">
                            </div><!--//form-group-->
                        </div>
                        <div class="contact-form col-md-6 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label class="sr-only"><?php echo $this->translate('Email Address','Landing') ?> *</label>
                                <input name="email" ng-model="form.email" type="email" class="form-control email required" required placeholder="<?php echo $this->translate('Email Address','Landing') ?> *">
                            </div><!--//form-group-->
                        </div>
                        <div class="contact-form col-md-6 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label class="sr-only"><?php echo $this->translate('Phone Number','Landing') ?></label>
                                <input name="phone" ng-model="form.phone" type="text" class="form-control" placeholder="<?php echo $this->translate('Phone Number','Landing') ?>">
                            </div><!--//form-group-->
                        </div>
                        <div class="contact-form col-md-6 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label class="sr-only"><?php echo $this->translate('Company','Landing') ?></label>
                                <input name="company" ng-model="form.company" type="text" class="form-control" placeholder="<?php echo $this->translate('Company','Landing') ?>">
                            </div><!--//form-group-->
                        </div>
                        <div class="contact-form col-md-6 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <label class="sr-only"><?php echo $this->translate('Job Title','Landing') ?></label>
                                <input name="jobTitle" ng-model="form.jobTitle" type="text" class="form-control" placeholder="<?php echo $this->translate('Job Title','Landing') ?>">
                            </div><!--//form-group-->
                        </div>
                        <div class="contact-form col-md-12 col-sm-12 col-xs-12">
                            <div class="form-group message">
                                <label class="sr-only" for="message"><?php echo $this->translate('Comments','Landing') ?></label>
                                <textarea name="comments" ng-model="form.comments" class="form-control" rows="6" placeholder="<?php echo $this->translate('Comments','Landing') ?>:"></textarea>
                            </div><!--//form-group-->
                        </div>
                        <button name="submit" ng-click="submitForm()" type="submit" class="btn btn-lg btn-theme"><?php echo $this->translate('Get In Touch','Landing') ?></button>
                        
                    </form><!--//form-->                 
                </div><!--//contact-form-->
            </div><!--//row-->
            <div class="text-center">
                 <ul class="social-icons list-inline">
                    <li><a href="#" ><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#" ><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#" ><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="#" ><i class="fa fa-google-plus"></i></a></li>                  
                </ul><!--//social-icons-->
            </div><!--//row-->
        </div><!--//container-->
    </section><!--//contact-->  

