<?php $this->headTitle($this->translate('Professional Cloud Translation and Localization Service By PaperTask','Landing')) ?>

<?php
echo $this->headScript()
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/landing/languages.js')
    ->prependScript("angularApp = angular.module('project', []);")
	->prependFile($this->basePath() . '/js/angular.min.js')
?>    
<?php
echo $this->inlineScript()
    ->prependScript("
    
	
	if(typeof(angular) != 'undefined' && typeof(angularApp) == 'undefined'){
        var angularApp = angularApp || angular.module('languages', []);
	  }
   
	 
    ");
echo $this->inlineScript()
    ->prependScript("
        var LANG_CODE = '" . $this->lang_code . "';
        var EXITS_CONFIRM_TEXT = '" . $this->translate('This option was existed, please choose other') . "';
        "); 	

?>
<!-- ******slider****** --> 
<div id="inSlider" class="carousel carousel-fade" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="container">
                <div class="carousel-caption">
                    <ul>
                        <li style="font-size: 22px;"><?php echo $this->translate('The new mode of translation services','Landing') ?></li>
                        <li style="font-size: 22px;"><?php echo $this->translate('High quality human translation','Landing') ?></li>
                        <li style="font-size: 22px;"><?php echo $this->translate('10,000+ professional translators worldwide','Landing') ?></i>
                        <li style="font-size: 22px;"><?php echo $this->translate('Support more than 30 languages','Landing') ?></i>
                        <li style="font-size: 22px;"><?php echo $this->translate('New smart quotation system, without human intervention','Landing') ?></i>
                        <li style="font-size: 22px;"><?php echo $this->translate('Guaranteed high quality and lowest price in the market','Landing') ?></i>
                    </ul>
                    <br />
                    <p class="text-center">
                        <a style="font-size: 20px;" class="btn btn-lg btn-primary" href="<?php echo $this->translate('lang','Application'); echo $this->basePath('/order/'); ?>" role="button"><?php echo $this->translate('Instant Quote / Order Translation','Landing') ?></a>
                    </p>
                </div>
                <div class="carousel-image wow zoomIn">
                    <img src="/v2/img/landing/home1.png" alt="home" width="500" height="315">/>
                </div>
            </div>
            <!-- Set background for slide in css -->
            <div class="header-back one"></div>

        </div>
    </div>
</div><!--//slider-->

<section id="ovewview" class="overview gray-section" style="margin-top: 0px;">
    <div class="container">
    <div class="row">
        <div class="col-lg-12 text-center">
            <div class="navy-line"></div>
            <h1><?php echo $this->translate('Globalization people-powered translation cloud platform','Landing') ?><br/> </h1>
            <!--
            <p style="font-size: 18px; color: #676a6c; font-weight:300;"><?php echo $this->translate('You can easily order files or text which need to be translated through our website. Our platform will instantly at your service. In the first task, experienced PaperTask project manager will assign it the job to the qualified translator(s) based on the field of your job, and add the translators to your resource group, so they will take over in a few minutes, and complete the translation. For your subsequent jobs, the platform will automatically assign it to the translators in your resource group.','Landing') ?></p>
            -->
        </div>
    </div>

    <br />
    <br />
    <div class="row">
        <div class="col-md-3 text-center wow fadeInLeft">
            <div>
                <i class="fa fa-check-circle-o features-icon" style="font-size: 80px;"></i>
                <h2><?php echo $this->translate('Language Quality Assurance','Landing') ?></h2>
                <p style="font-size: 18px; color: #676a6c; font-weight:300;"><?php echo $this->translate('While ensuring the translation speed, our process control and professional translators guarantee language quality','Landing') ?></p>
            </div>
        </div>
        <div class="col-md-3 text-center wow fadeInRight">
            <div>
                <i class="fa fa-line-chart features-icon" style="font-size: 80px;"></i>
                <h2><?php echo $this->translate('Reliable and Scalable','Landing') ?></h2>
                <p style="font-size: 18px; color: #676a6c; font-weight:300;"><?php echo $this->translate('PaperTask has more than 5000 professional native speakers located in 50+ countries helping clients globally','Landing') ?></p>
            </div>
        </div>
        <div class="col-md-3 text-center wow fadeInRight">
            <div>
                <i class="fa fa-cogs features-icon" style="font-size: 80px;"></i>
                <h2><?php echo $this->translate('Feature-rich Platform','Landing') ?></h2>
                <p style="font-size: 18px; color: #676a6c; font-weight:300;"><?php echo $this->translate('Through PaperTask Continuous Dynamic Translation, project setup, deadline calculations, translator assignments, document revisions, and job kick-offs are all automated','Landing') ?></p>
            </div>
        </div>
        <div class="col-md-3 text-center wow fadeInRight">
            <div>
                <i class="fa fa-smile-o features-icon" style="font-size: 80px;"></i>
                <h2><?php echo $this->translate('Competitive Value','Landing') ?></h2>
                <p style="font-size: 18px; color: #676a6c; font-weight:300;"><?php echo $this->translate('Guaranteed high quality and competitive price in the market, more than 100 companies worldwide are using PaperTask to be their online translation platform','Landing') ?></p>
            </div>
        </div>
    </div>
    <br />
    <br />
    </div>
</section>
<br />
<br />
<section id="pricing" class="pricing"  ng-app="languages" id="languagesController" ng-controller="languagesController">
    <div class="container">
        <div class="row m-b-lg" style="margin-bottom: 20px;">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1><?php echo $this->translate('PLEASE CHECK OUT THE LANGUAGES WE SUPPORT','Landing') ?></h1>
                <p style="font-size: 18px;"><?php echo $this->translate('WE\'RE HONEST ABOUT QUALITY, AND WE OFFER ALL MAJOR LANGUAGES FOR TRANSLATION','Landing') ?></p>

                <br><br><br>
                <form class="showPriceForm" name="showPriceForm" class="form-horizontal" role="form">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label text-navy" style="font-size: 16px; padding-top: 7px;"><?php echo $this->translate('Source Language','Landing') ?></label>
                                <div class="col-sm-8">
                                    <select ngChange="updateTargetLanguages()" ng-model="params.sourceLanguage"
                                            required name="sourceLanguage" class="form-control required">
                                        <option value=""><?php echo $this->translate('Please select','Landing') ?></option>
                                        <option ng-repeat="id in sourceLanguages" value="{{id}}"><?php echo $this->translate('{{languages[id] | i18n}}','Landing');?></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label text-navy" style="font-size: 16px; padding-top: 7px;"><?php echo $this->translate('Target Language','Landing') ?> </label>
                                <div class="col-sm-8">
                                    <select ng-model="params.targetLanguage" required name="targetLanguage"
                                            class="form-control required">
                                        <option value=""><?php echo $this->translate('Please select','Landing') ?></option>
                                        <option ng-repeat="id in targetLanguages" value="{{id}}"><?php echo $this->translate("{{languages[id] | i18n}}","Landing");?></option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label text-navy" style="font-size: 16px; padding-top: 7px;">
                                    <?php echo $this->translate('Word Count','Landing') ?></label>
                                <div class="col-sm-8">
                                    <input name="wordCount" ng-model="params.wordCount" type="number"
                                           class="form-control required" required>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-4 control-label text-navy" style="font-size: 16px; padding-top: 7px;">
                                    <?php echo $this->translate('Choose Currency','Landing') ?></label>
                                <div class="col-sm-8">
                                    <select ng-model="params.currency" name="currency" required class="form-control required">
                                        <option value="USD">USD</option>
                                        <option value="CNY">CNY</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <p />
                    <div align="center">
                        <br><br><br>
                        <button type="submit" style="font-size: 18px;" ng-click="showPrice()" class="btn btn-primary btn-lg"><?php echo $this->translate('Show Price','Landing') ?> </button>
                        <br><br>
                    </div>
                </form>


            </div>
        </div>


        <div id = "features" class="row section has-pattern hidden">
            <div class="col-lg-4 wow zoomIn">
                <ul class="pricing-plan list-unstyled">
                    <li class="pricing-title">
                        <?php echo $this->translate('Professional','Landing') ?>
                    </li>
                    <li class="pricing-desc" style="font-size: 16px; color: #676a6c;">
                        <?php echo $this->translate('Fast translation by native speakers','Landing') ?>
                    </li>
                    <li class="pricing-price" style="font-size: 20px;">
                        <span>{{params.currency}} {{price.professionalPrice | number:3}}</span> / <?php echo $this->translate('per word','Landing') ?>
                    </li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('Emails, Letters','Landing') ?></li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('Daily content, social media posts','Landing') ?></li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('User reviews, user generated content','Landing') ?></li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('Internal communication, customer support','Landing') ?></li>
                    <li class="pricing-price" style="font-size: 20px;">
                        <span>{{params.currency}} {{price.professionalPrice*params.wordCount | number:2}}</span>
                    </li>
                    <li>
                        <a class="btn btn-primary btn-xs" href="<?php echo $this->translate('lang','Application'); echo $this->basePath('landing/index/order'); ?>"><?php echo $this->translate('Order Now','Landing') ?></a>
                    </li>
                </ul>
            </div>

            <div class="col-lg-4 wow zoomIn">
                <ul class="pricing-plan list-unstyled selected">
                    <li class="pricing-title">
                        <?php echo $this->translate('Business','Landing') ?>
                    </li>
                    <li class="pricing-desc" style="font-size: 16px; color: #676a6c;">
                        <?php echo $this->translate('Professional quality translation plus proofreading','Landing') ?>
                    </li>
                    <li class="pricing-price" style="font-size: 20px;">
                        <span>{{params.currency}} {{price.businessPrice | number:3}}</span> / <?php echo $this->translate('per word','Landing') ?>
                    </li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('Application/introduction, website localization','Landing') ?></li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('Business presentations, reports, articles','Landing') ?></li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('Instructions, manuals, guidelines','Landing') ?></li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('Points translation, product description','Landing') ?></li>
                    <li class="pricing-price" style="font-size: 20px;">
                        <span>{{params.currency}} {{price.businessPrice*params.wordCount | number:2}}</span>
                    </li>
                    <li>
                        <a class="btn btn-primary btn-xs" href="<?php echo $this->translate('lang','Application'); echo $this->basePath('landing/index/order'); ?>"><?php echo $this->translate('Order Now','Landing') ?></a>
                    </li>
                </ul>
            </div>

            <div class="col-lg-4 wow zoomIn">
                <ul class="pricing-plan list-unstyled">
                    <li class="pricing-title">
                        <?php echo $this->translate('Premium','Landing') ?>
                    </li>
                    <li class="pricing-desc" style="font-size: 16px; color: #676a6c;">
                        <?php echo $this->translate('Professional plus extra proofreading','Landing') ?>
                    </li>
                    <li class="pricing-price" style="font-size: 20px;">
                        <span>{{params.currency}} {{price.premiumPrice | number:3}}</span> / <?php echo $this->translate('per word','Landing') ?>
                    </li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('Posters','Landing') ?></li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('Webpage, Webpage copy','Landing') ?></li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('News release','Landing') ?></li>
                    <li style="font-size: 15px; color: #676a6c;"><i class="fa fa-check"></i> <?php echo $this->translate('Promotional/marketing materials','Landing') ?></li>
                    <li class="pricing-price" style="font-size: 20px;">
                        <span>{{params.currency}} {{price.premiumPrice*params.wordCount | number:2}}</span>
                    </li>
                    <li>
                        <a class="btn btn-primary btn-xs" href="<?php echo $this->translate('lang','Application'); echo $this->basePath('landing/index/order'); ?>"><?php echo $this->translate('Order Now','Landing') ?></a>
                    </li>
                </ul>
            </div>
        </div>

    </div>

</section>

<section id="freelancer" class="gray-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1><?php echo $this->translate('WORK FREE','Landing') ?></h1>
                <p style="font-size: 18px;"><?php echo $this->translate('Work With PaperTask','Landing') ?></p>
            </div>
        </div>
        <br /><br />
        <div class="row">
            <div class="col-md-4 text-center wow fadeInLeft">
                <div>
                    <i class="fa fa-user features-icon"></i>
                    <h2><?php echo $this->translate('Register','Landing') ?></h2>
                    <p class="text-navy" style="font-size: 18px; color: #676a6c; font-weight:300;"><?php echo $this->translate('Sign up PaperTask, you may work with PaperTask together for translation jobs.','Landing') ?></p>
                </div>
            </div>
            <div class="col-md-4 text-center wow fadeInRight">
                <div>
                    <i class="fa fa-check features-icon"></i>
                    <h2><?php echo $this->translate('Qualify','Landing') ?></h2>
                    <p class="text-navy" style="font-size: 18px; color: #676a6c; font-weight:300;"><?php echo $this->translate('If you want to get a job here, you must pass our certification, after that, you can get the translation tasks.','Landing') ?></p>
                </div>
            </div>
            <div class="col-md-4 text-center wow fadeInRight">
                <div>
                    <i class="fa fa-globe features-icon"></i>
                    <h2><?php echo $this->translate('Work Free','Landing') ?></h2>
                    <p class="text-navy" style="font-size: 18px; color: #676a6c; font-weight:300;"><?php echo $this->translate('In success pass our testing, you can get the translation jobs and work with us, look forward to your joining!','Landing') ?></p>
                </div>
            </div>
        </div>
        <br /><br /><br />
        <div class="row">
            <div class="col-lg-12 text-center">
                <a href="<?php echo $this->url('user',array('lang'=>$this->translate('lang','Landing'))) ?>/register/freelancer/" class="btn btn-primary" style="font-size: 18px;"><i class="fa fa-envelope"></i> <?php echo $this->translate('Register As a Freelancer, Now!','Landing') ?></a>
                <p class="m-t-sm"></p>
            </div>
        </div>
        <br /><br />
    </div>

</section>

<section id="client" class="team">
    <div class="container">
        <div class="row m-b-lg">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1><?php echo $this->translate('Our Clients','Landing') ?></h1>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-sm-2 wow">
                <div class="team-member">
                    <img src="/v2/img/press/bbc.png" style="width: 120px;" alt="BBC">
                </div>
            </div>
            <div class="col-sm-2 wow">
                <div class="team-member">
                    <img src="/v2/img/press/imationlogo.jpg" style="width: 120px;" alt="IMATION">
                </div>
            </div>
            <div class="col-sm-2 wow">
                <div class="team-member">
                    <img src="/v2/img/press/novozymes.jpg" style="width: 130px;" alt="<?php echo $this->translate('NOVOZYMES','Landing') ?>">
                </div>
            </div>
            <div class="col-sm-2 wow">
                <div class="team-member">
                    <img src="/v2/img/press/Stibo-Systems-logo.png" style="width: 120px;" alt="<?php echo $this->translate('STIBO SYSTEMS','Landing') ?>">
                </div>
            </div>
            <div class="col-sm-2 wow">
                <div class="team-member">
                    <img src="/v2/img/press/nc.jpg" style="width: 120px;" alt="<?php echo $this->translate('NATIONAL CENTRE FOR THE PERFORMING ARTS','Landing') ?>">
                </div>
            </div>
            <div class="col-sm-2 wow">
                <div class="team-member">
                    <img src="/v2/img/press/zurich.jpg" style="width: 120px;" alt="<?php echo $this->translate('Zurich','Landing') ?>">
                </div>
            </div>
        </div>
    </div>
</section>

<section id="contact" class="gray-section contact">
    <div class="container">
        <div class="row m-b-lg">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1><?php echo $this->translate('GET IN TOUCH WITH PAPERTASK','Landing') ?></h1>
                <p style="font-size: 17px;"><?php echo $this->translate('PLEASE CONTACT US TO GET MORE INFORMATION ABOUT OUR SERVICES','Landing') ?></p>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12 text-center">
                <a href="mailto:contact@papertask.com" class="btn btn-primary" style="font-size: 18px;"><i class="fa fa-envelope"></i> contact@papertask.com</a>
                <p class="m-t-sm"></p>
            </div>
        </div>

        <!--
        <div class="row m-b-lg text-center">
            <div class="contact-form row">                            
                <form name="contactForm" class="form">                
                    <div class="contact-form col-md-6 col-sm-12 col-xs-12">                            
                        <div class="form-group">
                            <label class="sr-only"><?php echo $this->translate('First Name','Landing') ?> *</label>
                            <input name="firstName" type="text" ng-model="form.firstName" class="form-control required" placeholder="<?php echo $this->translate('First Name','Landing') ?> *" required>
                        </div>
                    </div>
                    <div class="contact-form col-md-6 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label class="sr-only"><?php echo $this->translate('Last Name','Landing') ?> *</label>
                            <input name="lastName" type="text" ng-model="form.lastName" class="form-control required" required placeholder="<?php echo $this->translate('Last Name','Landing') ?> *">
                        </div>
                    </div>
                    <div class="contact-form col-md-6 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label class="sr-only"><?php echo $this->translate('Email Address','Landing') ?> *</label>
                            <input name="email" ng-model="form.email" type="email" class="form-control email required" required placeholder="<?php echo $this->translate('Email Address','Landing') ?> *">
                        </div>
                    </div>
                    <div class="contact-form col-md-6 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label class="sr-only"><?php echo $this->translate('Phone Number','Landing') ?></label>
                            <input name="phone" ng-model="form.phone" type="text" class="form-control" placeholder="<?php echo $this->translate('Phone Number','Landing') ?>">
                        </div>
                    </div>
                    <div class="contact-form col-md-6 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label class="sr-only"><?php echo $this->translate('Company','Landing') ?></label>
                            <input name="company" ng-model="form.company" type="text" class="form-control" placeholder="<?php echo $this->translate('Company','Landing') ?>">
                        </div>
                    </div>
                    <div class="contact-form col-md-6 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label class="sr-only"><?php echo $this->translate('Job Title','Landing') ?></label>
                            <input name="jobTitle" ng-model="form.jobTitle" type="text" class="form-control" placeholder="<?php echo $this->translate('Job Title','Landing') ?>">
                        </div>
                    </div>
                    <div class="contact-form col-md-12 col-sm-12 col-xs-12">
                        <div class="form-group message">
                            <label class="sr-only" for="message"><?php echo $this->translate('Comments','Landing') ?></label>
                            <textarea name="comments" ng-model="form.comments" class="form-control" rows="6" placeholder="<?php echo $this->translate('Comments','Landing') ?>:"></textarea>
                        </div>
                    </div>
                    <button name="submit" ng-click="submitForm()" class="btn btn-lg btn-primary"><?php echo $this->translate('Get In Touch','Landing') ?></button>
                    
                </form>
            </div>
        </div>
        -->
        <br /><br /><br /><br />
        <div class="row m-b-lg text-center">

                <p><strong>&copy; 2015 <a href="<?php echo $this->url('home',array('lang'=>$this->translate('lang', 'Application'))) ?>">PaperTask.com</a> <?php echo $this->translate('All rights reserved.', 'Application'); ?></strong> &nbsp;&nbsp;&nbsp; <a href="<?php echo $this->url('terms',array('lang'=>$this->translate('lang', 'Application'))) ?>"><?php echo $this->translate('Terms of Use', 'Application'); ?></a>
                        &nbsp;&nbsp;&nbsp;
                        <a href="<?php echo $this->url('privacy',array('lang'=>$this->translate('lang', 'Application'))) ?>"><?php echo $this->translate('Privacy Policy', 'Application'); ?></a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <div class="btn-group dropup">
                        <button type="button" class="btn btn-sm btn-default"><?php
                        if ($this->translate('lang', 'Application')=="en-US"){
                            echo "ENGLISH";
                        }
                        if ($this->translate('lang', 'Application')=="zh-CN"){
                            echo "简体中文";
                        }
                        ?></button>
                        <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li ><a href="<?php echo $this->url($this->route,array("lang"=>"en-US")) ?>">ENGLISH</a></li>
                            <li selected="selected"><a href="<?php echo $this->url($this->route,array("lang"=>"zh-CN")) ?>">简体中文</a></li>
                        </ul>
                    </div>
                </p>


        </div>
    </div>
</section>

