<?php $this->headTitle($this->translate('Professional Cloud Translation and Localization Service By PaperTask','Landing')) ?>
    



    <!-- ******General****** --> 
    <section id="faq" class="faq section">
        <div class="container">
            <div class="row">
                <h2 class="title text-center"><?php echo $this->translate('Globalization people-powered translation cloud platform','Landing') ?></h2>
                <div class="faq-col col-md-12 col-sm-12 col-xs-12">

                        <p class="answer" style="font-size: 18px;">
                            <?php echo $this->translate('You can easily order files or text which need to be translated through our website. Our platform will instantly at your service. In the first task, experienced PaperTask project manager will assign it the job to the qualified translator(s) based on the field of your job, and add the translators to your resource group, so they will take over in a few minutes, and complete the translation. For your subsequent jobs, the platform will automatically assign it to the translators in your resource group.','Landing') ?>
                        </p>

                </div><!--//faq-col-->
            </div><!--//row-->
        </div><!--//container-->
    </section><!--//faq-->

    
    <!-- ******QUALITY****** --> 
    <section class="how section has-pattern">
        <div class="container">
            <div class="row">
                <div class="content col-md-8 col-sm-8 col-xs-12 text-center">
                    <h2 class="title"><?php echo $this->translate('Language Quality Assurance','Landing') ?></h2>
                    <p class="intro text-left" style="font-size: 25px;"><?php echo $this->translate('While Ensuring the Translation Speed, Our Language Quality Assurance benefits you by','Landing') ?>:</p>

                    <ul class="intro text-left" style="font-size: 20px;">
                        <li ><?php echo $this->translate('The new mode of translation services','Landing') ?></li>
                        <li><?php echo $this->translate('High quality human translation','Landing') ?></li>
                        <li><?php echo $this->translate('20,000+ professional translators worldwide','Landing') ?></i>
                        <li><?php echo $this->translate('Support more than 70 languages','Landing') ?></i>
                        <li><?php echo $this->translate('New smart quotation system, without human intervention','Landing') ?></i>
                        <li><?php echo $this->translate('Guaranteed high quality and lowest price in the market','Landing') ?></i>
                    </ul>

                </div><!--//content-->
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div align="center">
                        <img src="/assets/quality-control.png" alt="Quality" class="img-responsive">
                    <div align="center">
                </div><!--//video-->
            </div><!--//row-->
        </div><!--//container-->
    </section><!--//how-->

    
    <!-- ******Sourcing****** --> 
    <section id="story" class="story section has-pattern">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-5 col-xs-12">
                    <br>
                    <div align="center">
                        <img src="/assets/crowsourcing.png" alt="Reliable" class="img-responsive">
                        <br /><br />
                    </div>
                </div><!--//video-->

                <div class="content col-md-7 col-sm-7 col-xs-12 text-center">
                    <h2 class="title"><?php echo $this->translate('Reliable, consistent Quality in large Volume translation','Landing') ?></h2>
                    <p class="intro text-left" style="font-size: 25px;"><?php echo $this->translate('Quality Control for Large Scale Translation Project','Landing') ?></p>
                    <ul class="intro text-left" style="font-size: 20px;font-weight: 300;">
                        <li ><?php echo $this->translate('Rigorous and meticulous review, both technical and editorial, confirms complete accuracy, appropriateness, and consistency of all translations.','Landing') ?></li>
                        <li><?php echo $this->translate('PaperTask maintains access to current and specific industry-related terminology and lexicons.','Landing') ?></i>
                        <li><?php echo $this->translate('Memory technology is utilized by PaperTask platform, allowing the company to use previously translated material.','Landing') ?></li>
                    </ul>
                </div><!--//content-->
            </div><!--//row-->
        </div><!--//container-->
    </section><!--//story-->

    <!-- ******Project****** --> 
    <section class="how section has-pattern">
        <div class="container">
            <div class="row">
                <div class="content col-md-7 col-sm-7 col-xs-12 text-center">
                    <h2 class="title"><?php echo $this->translate('Feature-rich Localisation/Translation Management Platform','Landing') ?></h2>
                    <p class="intro text-left" style="font-size: 22px;"><?php echo $this->translate('While Ensuring the Translation Speed, Our Language Quality Assurance benefits you by','Landing') ?>:</p>

                    <ul class="intro text-left" style="font-size: 15px;">
                        <li ><?php echo $this->translate('Collaborative translation shortens the translation cycle, improving delivery times by 50% Or better!','Landing') ?></li>
                        <li><?php echo $this->translate('The delivery phase, as well as other factors like cost tracking and invoicing, are all largely automated in PaperTask.','Landing') ?></li>
                        <li><?php echo $this->translate('Continuous Dynamic Translation by PaperTask is one of the most advanced solution on the market today. Project setup, deadline calculations, translator assignments, document revisions, and job kick-offs are all automated.','Landing') ?></i>
                        <li><?php echo $this->translate('PaperTask helps clients manage their translators, keep track of their specialty domains, and keep records about performance.','Landing') ?></i>
                        <li><?php echo $this->translate('New smart quotation system, without human intervention','Landing') ?></i>
                        <li><?php echo $this->translate('Client invoices are generated automatically. Customers can always view projects payment status, spending reports, download invoices directly.','Landing') ?></i>
                    </ul>

                </div><!--//content-->
                <div class="col-md-5 col-sm-5 col-xs-12">
                    <br><br><br><br>
                    <div align="center">
                        <img src="/assets/platform.png" alt="PaperTask Platform" class="img-responsive">
                    </div>
                </div><!--//video-->
            </div><!--//row-->
        </div><!--//container-->
    </section><!--//how-->
    
    <!-- ******TESTIMONIALS****** --> 
    <section id="testimonials" class="testimonials section" style="padding: 50px 0;">
        <div class="container">

            <div class="press row text-center">
                <h2 class="title text-center"><?php echo $this->translate('Our Clients','Landing') ?></h2>
                <ul class="col-md-12 list-inline">
                    <li><img class="img-responsive" src="/assets/images/press/bbc.png" alt="BBC" style="width: 120px;" /></li>
                    <li><img class="img-responsive" src="/assets/images/press/imationlogo.jpg" alt="IMATION" style="width: 120px;" /></li>
                    <li><img class="img-responsive" src="/assets/images/press/novozymes.jpg" alt="<?php echo $this->translate('NOVOZYMES','Landing') ?>" style="width: 120px;" /></li>
                    <li><img class="img-responsive" src="/assets/images/press/Stibo-Systems-logo.png" alt="<?php echo $this->translate('STIBO SYSTEMS','Landing') ?>" style="width: 120px;" /></li>
                    <li><img class="img-responsive" src="/assets/images/press/nc.jpg" alt="<?php echo $this->translate('NATIONAL CENTRE FOR THE PERFORMING ARTS','Landing') ?>" style="width: 120px;" /></li>
                    <li class="last"><img class="img-responsive" src="/assets/images/press/zurich.jpg" alt="" style="width: 120px;" /></li>
                </ul>
            </div><!--//row-->
        </div><!--//container-->
    </section><!--//Testimonials-->

    <section id="contact" class="gray-section contact">
    <div class="container">
        <div class="row m-b-lg">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1><?php echo $this->translate('GET IN TOUCH WITH PAPERTASK','Landing') ?></h1>
                <p><?php echo $this->translate('PLEASE CONTACT US TO GET MORE INFORMATION ABOUT OUR SERVICES','Landing') ?></p>
            </div>
        </div>
        <div class="row m-b-lg">
            <div class="col-lg-3 col-lg-offset-3">
                <address>
                    <strong><span class="navy">Company name, Inc.</span></strong><br/>
                    795 Folsom Ave, Suite 600<br/>
                    San Francisco, CA 94107<br/>
                    <abbr title="Phone">P:</abbr> (123) 456-7890
                </address>
            </div>
            <div class="col-lg-4">
                <p class="text-color">
                    Consectetur adipisicing elit. Aut eaque, totam corporis laboriosam veritatis quis ad perspiciatis, totam corporis laboriosam veritatis, consectetur adipisicing elit quos non quis ad perspiciatis, totam corporis ea,
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <a href="mailto:test@email.com" class="btn btn-primary">Send us mail</a>
                <p class="m-t-sm">
                    Or follow us on social platform
                </p>
                <ul class="list-inline social-icon">
                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center m-t-lg m-b-lg">
                <p><strong>&copy; 2015 Company Name</strong><br/> consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p>
            </div>
        </div>
    </div>
</section>

