<?php $this->headTitle($this->translate('Professional Cloud Translation and Localization Service By PaperTask')) ?>
<div class="banner">
    <div class="container">
        <br><br>
        <div class="row">
            <div class="feature-item col-md-7 text-left">
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;
                    <?php echo $this->translate('The new mode of translation services','Landing') ?></i>
                <br><br>
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;
                    <?php echo $this->translate('High quality human translation','Landing') ?></i>
                <br><br>
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;
                    <?php echo $this->translate('20,000+ professional translators worldwide','Landing') ?></i>
                <br><br>
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;
                    <?php echo $this->translate('Support more than 70 languages','Landing') ?></i>
                <br><br>
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;
                    <?php echo $this->translate('New smart quotation system, without human intervention','Landing') ?></i>
                <br><br>
                <i class="fa fa-chevron-circle-right" style=" color: #fff; font-size: 24px;"> &nbsp;&nbsp;
                    <?php echo $this->translate('Guaranteed high quality and lowest price in the market','Landing') ?></i>
            </div>
            <div class="feature-item col-md-5 text-center">
                <img src="assets/home1.png" alt="PaperTask.com" class="preview-img">
            </div>
        </div>
        <br><br>
        <a href="javascript:void(0);" target="_blank" class="btn btn-download btn-lg">
            <?php echo $this->translate('Instant Quote / Order Translation','Landing') ?></a>
        <br><br><br>
    </div>
</div>
<div class="features">
    <h1 class="text-center">
        <?php echo $this->translate('Globalization people-powered translation cloud platform','Landing') ?></h1>
    <br>
    <div class="container">
        <div class="col-lg-12 text-center">
            <div class="detail-desc">
                <p style="font-size: 20px;">
                    <?php echo $this->translate('You can easily order files or text which need to be translated through our website. Our platform will instantly at your service. In the first task, experienced PaperTask project manager will assign it the job to the qualified translator(s) based on the field of your job, and add the translators to your resource group, so they will take over in a few minutes, and complete the translation. For your subsequent jobs, the platform will automatically assign it to the translators in your resource group.','Landing') ?></p>
            </div>
        </div>
    </div>
</div>
<div class="details">
    <ul class="list-details list-unstyled">
        <li>
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <h2 style="font-size: 35px; line-height: 40px;">
                            <?php echo $this->translate('Language Quality Assurance','Landing') ?></h2>
                        <p>
                        <h3 style="font-size: 20px;">
                            <?php echo $this->translate('While Ensuring the Translation Speed, Our Language Quality Assurance benefits you by','Landing') ?>:</h3>
                        <ul class="list-unstyled" style="margin:0px; padding:0px;font-size: 15px;">
                            <li><i class="fa fa-check color-green"></i> &nbsp;
                                <?php echo $this->translate('Delivering translation quality','Landing') ?></li>
                            <li><i class="fa fa-check color-green"></i> &nbsp;
                                <?php echo $this->translate('Facilitating formal feedback between your organization and the linguist','Landing') ?></li>
                            <li><i class="fa fa-check color-green"></i> &nbsp;
                                <?php echo $this->translate('Providing consistent linguistic quality management across multiple languages','Landing') ?></li>
                            <li><i class="fa fa-check color-green"></i> &nbsp;
                                <?php echo $this->translate('Offering measurable and independent linguistic quality assessments','Landing') ?></li>
                        </ul>
                        </p>
                    </div>
                    <div class="col-md-5 detail-img">
                        <br>
                        <img src="assets/quality-control.png" alt="Quality">
                    </div>
                </div>
            </div>
        </li>
        <li class="alt">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 detail-img" align="left">
                        <br>
                        <img src="assets/crowsourcing.png" alt="Reliable">
                    </div>
                    <div class="col-md-1">
                    </div>
                    <div class="col-md-7">
                        <h2 style="font-size: 35px; line-height: 40px;">
                            <?php echo $this->translate('Reliable, consistent Quality in large Volume translation','Landing') ?></h2>
                        <p>
                        <h3 style="font-size: 20px;">
                            <?php echo $this->translate('Quality Control for Large Scale Translation Project','Landing') ?></h3>
                        <ul class="list-unstyled" style="margin:0px; padding:0px;font-size: 15px;">
                            <li><i class="fa fa-check color-green"></i> &nbsp;
                                <?php echo $this->translate('Rigorous and meticulous review, both technical and editorial, confirms complete accuracy, appropriateness, and consistency of all translations.','Landing') ?></li>
                            <li><i class="fa fa-check color-green"></i> &nbsp;
                                <?php echo $this->translate('PaperTask maintains access to current and specific industry-related terminology and lexicons.','Landing') ?></li>
                            <li><i class="fa fa-check color-green"></i> &nbsp;
                                <?php echo $this->translate('Memory technology is utilized by PaperTask platform, allowing the company to use previously translated material.','Landing') ?></li>
                        </ul>
                        </p>
                    </div>
                </div>
            </div>
        </li>
        <li>
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <h2 style="font-size: 35px; line-height: 40px;">
                            <?php echo $this->translate('Feature-rich Localisation/Translation Management Platform','Landing') ?></h2>
                        <p>
                        <h3 style="font-size: 20px;">
                            <?php echo $this->translate('While Ensuring the Translation Speed, Our Language Quality Assurance benefits you by','Landing') ?>:</h3>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-check color-green"></i>
                                <?php echo $this->translate('Collaborative translation shortens the translation cycle, improving delivery times by 50% Or better!','Landing') ?></li>
                            <li><i class="fa fa-check color-green"></i>
                                <?php echo $this->translate('The delivery phase, as well as other factors like cost tracking and invoicing, are all largely automated in PaperTask.','Landing') ?></li>
                            <li><i class="fa fa-check color-green"></i>
                                <?php echo $this->translate('Continuous Dynamic Translation by PaperTask is one of the most advanced solution on the market today. Project setup, deadline calculations, translator assignments, document revisions, and job kick-offs are all automated.','Landing') ?></li>
                            <li><i class="fa fa-check color-green"></i>
                                <?php echo $this->translate('PaperTask helps clients manage their translators, keep track of their specialty domains, and keep records about performance.','Landing') ?></li>
                            <li><i class="fa fa-check color-green"></i>
                                <?php echo $this->translate('Client invoices are generated automatically. Customers can always view projects payment status, spending reports, download invoices directly.','Landing') ?></li>
                        </ul>
                        </p>
                    </div>
                    <div class="col-md-5 detail-img">
                        <br><br><br><br><br>
                        <img src="assets/platform.png" alt="PaperTask Platform">
                    </div>
                </div>

            </div>
        </li>
    </ul>
</div>
<div class="features">
    <div class="container">
        <div class="col-lg-12 text-center">
            <div class="detail-desc">
                <a href="javascript:void(0);" target="_blank" class="btn btn-primary btn-lg">
                    <?php echo $this->translate('Instant Quote / Order Translation','Landing') ?></a>
            </div>
        </div>
    </div>
</div>