<?php $this->headTitle($this->translate('Projects list')) ?>

<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/v2/js/plugins/footable/footable.core.css')
?>
<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/v2/js/admin/project/client-quotes.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/footable/footable.all.min.js')
?>

<?php
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>

    <script>
        $(document).ready(function() {

            $('.footable').footable();

        });

    </script>

<div class="row animate fadeInUp">

    <div class="ibox" ng-controller="ProjectIndexController">
        <div ng-controller="ItemListController">

            <div class="ibox-content m-b-sm ">
                <div class="row">
                    <form method="" class="form-horizontal">
                        <div class="row">
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('Quote No.','Employer'); ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" ng-model="filter.quote">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-5">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('Reference','Employer'); ?></label>
                                    <div class="col-sm-9">
                                        <input type="text" class="form-control" ng-model="filter.reference">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-2">
                                <button type="button" class="btn btn-sm btn-primary" ng-click="search()"> <?php echo $this->translate('Search','Employer'); ?></button>
                            </div>
                        </div>
                    </form>
                </div>

            </div>        
            <div class="ibox-content">

                <div class="project-list">

                    <table class="footable table table-hover toggle-arrow-tiny">
                        <thead>
                        <tr>

                            <th data-hide="phone,tablet"><?php echo $this->translate('Status','Employer'); ?></th>
                            <th><?php echo $this->translate('Project ID','Employer'); ?></th>
                            <th data-hide="phone,tablet"><?php echo $this->translate('Project Info','Employer'); ?></th>
                            <th class="text-right"><?php echo $this->translate('Price','Employer'); ?></th>
                        </tr>
                        </thead>                                
                        <tbody>
                            <tr ng-repeat="project in items">
                                <td class="project-status">
                                    <span class="label label-{{ ProjectStatus.get(project.status).decorator }}" style="font-size: 12px;">{{ ProjectStatus.get(project.status).name }}</span>
                                </td>
                                <td class="project-title text-navy">
                                    <span ng-if="project.number">{{ project.quote_no }}</span>
                                    <br/>
                                    <small style="font-size: 12px;">{{ DateFormatter.short(project.startDate) }}</small>
                                </td>
                                <td class="project-title">
                                    
                                    <span class="simple_tag" style="font-size: 8px;">English</span>
                                    <i class="fa fa-arrow-right"></i>
                                    <span class="simple_tag" style="font-size: 8px;">Chinese</span>
                                    <span class="simple_tag" style="font-size: 8px;">Jananese</span>
                                    
                                    <br/>
                                    <span>
                                    here put project deccription                                        
                                    </span>
                                </td>
                                <td class="project-actions text-right">
                                    <span class="text-warning" style="font-size: 15px;"><strong>{{ project.currency }}  {{ project.total_tmp | number:2 }}</strong></span>&nbsp;
                                    <a href="#" class="btn btn-info btn-sm" ng-click="quoteAccepted(project)"><i class="fa fa-check"></i> <?php echo $this->translate('Accept','Employer'); ?> </a>
                                    <a href="#" class="btn btn-white btn-sm" ng-click="goToQuote(project)"><i class="fa fa-folder"></i> <?php echo $this->translate('View','Employer'); ?> </a>
                                </td>
                            </tr>
                            </tr>
                        </tbody>
                    </table>

                    <div class="btn-group text-right">
                        <pagination total-items="pages.totalItemCount" ng-model="page" max-size="maxSize"
                                    class="pagination-sm" boundary-links="true" ng-change="pageChanged()"></pagination>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
