<?php $this->headTitle($this->translate('Projects list')) ?>

<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/v2/js/plugins/footable/footable.core.css')
?>
<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/v2/js/admin/project/project-index.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/CurrentUser.js')
    ->prependScript("angularApp = angular.module('project', ['ui.bootstrap']);")
    ->prependFile($this->basePath() . '/v2/js/plugins/angular-bootstrap/ui-bootstrap-0.11.2.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/footable/footable.all.min.js');
?>

    <script>
        $(document).ready(function() {

            $('.footable').footable();

        });

    </script>

<?php
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>


<div class="row animate fadeInUp">

    <div class="ibox" ng-controller="ProjectIndexController">
        <div ng-controller="ItemListController">

            <div class="ibox-content m-b-sm ">
                <div class="row">

                    <form method="" class="form-horizontal">
                        <div class="col-lg-12">
                            <div class="col-lg-2">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('ID','Employer'); ?></label>
                                    <div class="col-sm-9"><input type="text" name="q" ng-model="filter.project_id" class="form-control"></div>
                                </div>
                            </div>
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate('Reference','Employer'); ?></label>
                                    <div class="col-sm-8"><input
                                            type="text" class="form-control" name="reference" ng-model="filter.reference"></div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate('Source','Employer'); ?></label>
                                    <div class="col-sm-8">
                                        <select class="form-control" name="source" ng-model="filter.source"
                                                ng-options="language.name for language in languages">
                                            <option value=""></option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                <div class="form-group">
                                    <label class="col-sm-4 control-label"><?php echo $this->translate('Target','Employer'); ?></label>
                                    <div class="col-sm-8">
                                        <select class="form-control" name="source" ng-model="filter.target"
                                                ng-options="language.name for language in languages">
                                            <option value=""></option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        <div class="text-right tooltip-demo">
                            <a href="#" class="btn btn-sm btn-primary" ng-click="search()"><i class="fa fa-search"></i> <?php echo $this->translate('Search','Employer'); ?></a>
                            <a href="#" class="btn btn-white btn-sm" type="reset" ng-click="search={}"><i class="fa fa-times"></i> <?php echo $this->translate('Reset','Employer'); ?></a>
                        </div>
                        </div>
                    </form>

                </div>

            </div>        
            <div class="ibox-content">
                <div id="projectsList">
                    <div class="project-list">

                        <table class="footable table table-hover toggle-arrow-tiny">
                            <thead>
                            <tr>

                                <th data-hide="phone,tablet"><?php echo $this->translate('Status','Employer'); ?></th>
                                <th><?php echo $this->translate('Project ID','Employer'); ?></th>
                                <th data-hide="phone,tablet"><?php echo $this->translate('Project Info','Employer'); ?></th>
                                <th class="text-right"><?php echo $this->translate('Price','Employer'); ?></th>
                            </tr>
                            </thead>                                
                            <tbody>
                                <tr ng-repeat="project in items">
                                    <td class="project-status">
                                        <span class="label label-{{ ProjectStatus.get(project.status).decorator }}" style="font-size: 12px;">{{ ProjectStatus.get(project.status).name }}</span>
                                    </td>
                                    <td class="project-title">
                                        <strong style="font-size: 16px;">{{ project.project_no }}</strong>
                                    </td>
                                    <td class="project-title tooltip-demo">
                                        <strong style="font-size: 14px;">{{ project.reference }}</strong>
                                        <br />
                                        <span><code style="font-size: 10px;">English <i class="fa fa-arrow-right"></i> Chinese, 日文</code></span>
                                    </td>
                                    <td class="project-actions text-right">
                                        <span class="text-navy" style="font-size: 15px;"><strong>USD 50.25</strong></span>&nbsp;
                                        <a href="#" class="btn btn-white btn-sm" ng-click="goToDetail(project)"><i class="fa fa-folder"> <?php echo $this->translate('View','Employer'); ?> </i> </a>
                                    </td>
                                </tr>
                                </tr>
                            </tbody>
                        </table>

                        <div class="btn-group text-right">
                            <pagination total-items="pages.totalItemCount" ng-model="page" max-size="maxSize"
                                        class="pagination-sm" boundary-links="true" ng-change="pageChanged()"></pagination>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
