
<div class="panel-heading">
    <div class="panel-options">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#files" data-toggle="tab"><?php echo $this->translate("Project Files for Preview"); ?></a></li>
            <li class="" ng-show="project.status.id == 2"><a href="#tasks" data-toggle="tab"><span class="label label-warning">{{ project.tasksNum }}</span> <?php echo $this->translate("Schedule"); ?></a></li>
            <li class="" ><a href="#message" data-toggle="tab"><span class="label label-warning">{{ project.activitiesNum }}</span> Messages & Activities</a></li>
            <li class="" ng-show="project.status.id == 2"><a href="#feedback" data-toggle="tab"> Feedbacks</a></li>
            <li class=""><a href="#quote" data-toggle="tab"> Quote</a></li>
            <!-- if the project status is quote, then show quote, other wise hide quote -->
            <li class="" ng-show="project.status.id == 2"><a href="#invoice" data-toggle="tab"> Invoice</a></li>
            <!-- if the status is not quote, then show invoice -->
        </ul>
    </div>
</div>

<div class="panel-body">

    <div class="tab-content">
        <?php include "detail/tasks-client.phtml"; ?>
        <?php include "detail/activities.phtml"; ?>
        <?php include "detail/files.phtml"; ?>

        <div class="tab-pane" id="feedback">

            <div class="panel-body">
                <div class="panel-group" id="accordion_feedback">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="padding-bottom: 10px;">
                            <h5 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion_feedback" href="#feedback_lang1"> English <i class="fa fa-arrow-right"></i> Simplify Chinese </a>
                            </h5>
                        </div>
                        <div id="feedback_lang1" class="panel-collapse collapse in">
                            <div class="panel">
                                <div class="panel-body">
                                    <hr />
                                    <p>Leaving feedback here will help you get a better translation next time. On your next order, you'll be able to specify whether to use only your preferred translators. This translator is on your list of preferred translators.</p>

                                    <div class="panel panel-default tooltip-demo">
                                        <div class="panel-body">
                                          <div class="form-group">
                                            <label class="control-label">Quality</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Very poor. There were multiple mistakes and/or the style was very poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="bad">
                                                      <span class="custom-radio"></span>
                                                      Bad
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Poor. There were mistakes and/or the style was poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="poor">
                                                      <span class="custom-radio"></span>
                                                      Poor
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory. If mistakes occurred, they were corrected." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Good. The overall style was appropriate and there were few, if any, mistakes." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="good">
                                                      <span class="custom-radio"></span>
                                                      Good
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Perfect" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="perfect">
                                                      <span class="custom-radio"></span>
                                                      Perfect
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Turn Around Time</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_slow">
                                                      <span class="custom-radio"></span>
                                                      Much Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="slow">
                                                      <span class="custom-radio"></span>
                                                      Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="faster">
                                                      <span class="custom-radio"></span>
                                                      Faster
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_faster">
                                                      <span class="custom-radio"></span>
                                                      Much Faster
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Feed back to Translator and Project Manager</label>
                                            <textarea class="form-control" value="previous commons..." id="tarea{$h}" rows="3"></textarea>
                                          </div><!-- /form-group -->

                                            <div class="text-right m-t-md">
                                                <a href="#" class="btn btn-primary"> Update</a>
                                            </div>

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" style="padding-bottom: 10px;">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion_feedback" href="#feedback_lang2">English <i class="fa fa-arrow-right"></i> Traditional Chinese</a>
                            </h4>
                        </div>
                        <div id="feedback_lang2" class="panel-collapse collapse">

                            <div class="panel">
                                <div class="panel-body">
                                    <hr />
                                    <p>Leaving feedback here will help you get a better translation next time. On your next order, you'll be able to specify whether to use only your preferred translators. This translator is on your list of preferred translators.</p>

                                    <div class="panel panel-default tooltip-demo">
                                        <div class="panel-body">
                                          <div class="form-group">
                                            <label class="control-label">Quality</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Very poor. There were multiple mistakes and/or the style was very poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="bad">
                                                      <span class="custom-radio"></span>
                                                      Bad
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Poor. There were mistakes and/or the style was poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="poor">
                                                      <span class="custom-radio"></span>
                                                      Poor
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory. If mistakes occurred, they were corrected." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Good. The overall style was appropriate and there were few, if any, mistakes." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="good">
                                                      <span class="custom-radio"></span>
                                                      Good
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Perfect" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="perfect">
                                                      <span class="custom-radio"></span>
                                                      Perfect
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Turn Around Time</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_slow">
                                                      <span class="custom-radio"></span>
                                                      Much Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="slow">
                                                      <span class="custom-radio"></span>
                                                      Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="faster">
                                                      <span class="custom-radio"></span>
                                                      Faster
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_faster">
                                                      <span class="custom-radio"></span>
                                                      Much Faster
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Feed back to Translator and Project Manager</label>
                                            <textarea class="form-control" value="previous commons..." id="tarea{$h}" rows="3"></textarea>
                                          </div><!-- /form-group -->

                                            <div class="text-right m-t-md">
                                                <a href="#" class="btn btn-primary"> Update</a>
                                            </div>

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" style="padding-bottom: 10px;">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion_feedback" href="#feedback_lang3">English <i class="fa fa-arrow-right"></i> German </a>
                            </h4>
                        </div>
                        <div id="feedback_lang3" class="panel-collapse collapse">
                            <div class="panel">
                                <div class="panel-body">
                                    <hr />
                                    <p>Leaving feedback here will help you get a better translation next time. On your next order, you'll be able to specify whether to use only your preferred translators. This translator is on your list of preferred translators.</p>

                                    <div class="panel panel-default tooltip-demo">
                                        <div class="panel-body">
                                          <div class="form-group">
                                            <label class="control-label">Quality</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Very poor. There were multiple mistakes and/or the style was very poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="bad">
                                                      <span class="custom-radio"></span>
                                                      Bad
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Poor. There were mistakes and/or the style was poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="poor">
                                                      <span class="custom-radio"></span>
                                                      Poor
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory. If mistakes occurred, they were corrected." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Good. The overall style was appropriate and there were few, if any, mistakes." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="good">
                                                      <span class="custom-radio"></span>
                                                      Good
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Perfect" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="perfect">
                                                      <span class="custom-radio"></span>
                                                      Perfect
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Turn Around Time</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_slow">
                                                      <span class="custom-radio"></span>
                                                      Much Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="slow">
                                                      <span class="custom-radio"></span>
                                                      Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="faster">
                                                      <span class="custom-radio"></span>
                                                      Faster
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_faster">
                                                      <span class="custom-radio"></span>
                                                      Much Faster
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Feed back to Translator and Project Manager</label>
                                            <textarea class="form-control" value="previous commons..." id="tarea{$h}" rows="3"></textarea>
                                          </div><!-- /form-group -->

                                            <div class="text-right m-t-md">
                                                <a href="#" class="btn btn-primary"> Update</a>
                                            </div>

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- if the project status is quoted or quoting, then hide other tabs only show quote tab -->
        <div class="tab-pane" id="quote">
            <?php include "detail/quote.phtml"; ?>
        </div>

        <div class="tab-pane" id="invoice" ng-show="project.status.id==2">
            <?php include "detail/invoice.phtml"; ?>
        </div>

    </div>

</div>
