<?php $this->headTitle($this->translate('Project Details','Employer')) ?>
<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/datetimepicker/DateTimePicker.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/summernote/summernote-bs3.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/multiselect/bootstrap-multiselect.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/steps/jquery.steps.css')
?>
<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/v2/js/plugins/datetimepicker/DateTimePicker.js')
    ->prependFile($this->basePath() . '/v2/js/admin/project/project-detail.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/v2/js/admin/bootstrap-modal.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/angular-bootstrap/ui-bootstrap-tpls-0.11.2.min.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload','ui.bootstrap']);")
    ->prependScript("PROJECT_ID = {$this->id};")
    ->prependFile($this->basePath() . '/v2/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/summernote/summernote.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/slimscroll/jquery.slimscroll.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/metisMenu/jquery.metisMenu.js"') 
    ->prependFile($this->basePath() . '/v2/js/plugins/bootbox/bootbox.min.js');
?>

<?php
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>
<style>
.note-editor {
    height: 150px;
}

    .label_check label{
        margin-right: 0.3em;
    }
    
.dl-horizontal dt {
  		width: 167px;
}
    input[readonly][data-field=datetime]{
        background-color: #fff;
    }
    input[readonly][data-field=datetime]:hover,
    i.fa.fa-calendar:hover{
        cursor: pointer;
    }

.top-navigation .nav > li.active {
    background: none;
    border: none;
}

</style>



<div ng-controller="ProjectDetailController" id="ProjectDetailController">
    <div class="wrapper wrapper-content animated fadeInRight">

        <div class="row">
            <div class="col-lg-12">

                <div class="ibox product-detail">
                    <div class="ibox-content">

                        <?php include "detail/info.phtml"; ?>
                        <?php if (!$this->isemployer) { include "detail/miniform.phtml"; } ?>

                    </div>
                </div>

            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">

                <?php
                    switch($this->userData()['role']){
                        case 'Admin':
                            //staff menus here
                            switch($this->userData()['type']){
                                case 'Admin':
                                case 'Financial Manager':
                                case 'Operation Manager':
                                case 'Project Manager':
                                case 'Sales Director':
                                case 'Sales': // Sales Manager
                                case 'General Manager': // Inhouse
                                default:
                                    include "detail-common.phtml";
                            }
                            break;
                        case 'Employer': // employer == client
                        case 'Client':
                            
                            $filesTabActive = true;
                            include "detail-client.phtml";
                            break;
                        case 'Freelancer':
                        default:
                            include "detail-common.phtml";
                            // TODO: default menu
                    };
                ?>

            </div>
        </div>

    </div>
</div>

<script>
    $(document).ready(function(){
        $('.dtbox').DateTimePicker();
$('.dtbox1').DateTimePicker();

        // trigger datetime picker when click to calendar icon
        // TODO: this is not working
        $('i.fa.fa-calendar').on('click', function(e){
            console.log('clicked');
            //e.preventDefault();
			//console.log($(this).parents('.input-group').find('input[readonly]'));
            //$(this).parents('.input-group').find('input[readonly]').click();
        });
    });
</script>