
<div class="panel-heading">
    <div class="panel-options">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#preview" data-toggle="tab"><?php echo $this->translate("Project Files for Preview"); ?></a></li>
            <li class="" ng-show="project.status.id == 2"><a href="#tasks" data-toggle="tab"><span class="label label-warning">{{ project.tasksNum }}</span> <?php echo $this->translate("Schedule"); ?></a></li>
            <li class="" ><a href="#message" data-toggle="tab"><span class="label label-warning">{{ project.activitiesNum }}</span> Messages & Activities</a></li>
            <li class="" ng-show="project.status.id == 2"><a href="#feedback" data-toggle="tab"> Feedbacks</a></li>
            <li class=""><a href="#quote" data-toggle="tab"> Quote</a></li>
            <!-- if the project status is quote, then show quote, other wise hide quote -->
            <li class="" ng-show="project.status.id == 2"><a href="#invoice" data-toggle="tab"> Invoice</a></li>
            <!-- if the status is not quote, then show invoice -->
        </ul>
    </div>
</div>

<div class="panel-body">

    <div class="tab-content">
        <?php include "detail/tasks-client.phtml"; ?>
        <?php include "detail/activities.phtml"; ?>

        <div class="tab-pane active" id="preview">
            <div class="panel-body">
                <h3>Source Files</h3>
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Source File Name</th>
                        <th>Size</th>
                        <th>Time Stamp</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>1</td>
                        <td><a href=""><i class="fa fa-file"></i> Project_document_SC.docx <i class="fa fa-cloud-download"></i></a> </td>
                        <td>46.88 KB</td>
                        <td>2014-Oct-09 16:30</td>
                    </tr>
                    </tbody>
                </table>
            </div>


            <div class="panel-body">
                <h3>Files For Review</h3>
                <div class="panel-group" id="accordion_preview">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="padding-bottom: 10px;">
                            <h5 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion_preview" href="#preview_lang1"><i class="fa fa-exclamation-triangle text-danger"></i> English <i class="fa fa-arrow-right"></i> Simplify Chinese </a> <i class="fa fa-paperclip"></i></a> <!-- with paperclip means file for this language has been uploaded -->
                            </h5>
                        </div>
                        <div id="preview_lang1" class="panel-collapse collapse in">

                            <div class="panel-body">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>File Name</th>
                                        <th>Size</th>
                                        <th>Time Stamp</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td><a href=""><i class="fa fa-file"></i> Project_document_JP.docx <i class="fa fa-cloud-download"></i></a> </td>
                                        <td>46.88 KB</td>
                                        <td>2014-Oct-09 16:30</td>
                                    </tr>
                                    </tbody>
                                </table>

                                <div class="col-md-6">
                                    <p>Happy with your translation? Formally approve it here.</p>
                                    <a data-toggle="collapse" data-parent="#preview_lang1" href="#approve_lang1" class="btn btn-primary"><i class="fa fa-check-square-o"></i> Approve</a> <!-- if user click the approve button(all languages), the approve button and request correct button should hide, and project status should change to completed -->
                                </div>
                                <div class="col-md-6">
                                    <p>If you need the translator to fix mistakes or make changes:</p>
                                    <a data-toggle="collapse" data-parent="#preview_lang1" href="#correct_lang1" class="btn btn-warning"><i class="fa fa-edit"></i> Request corrections</a> <!-- if any language need correct, the project status will change to Reject -->
                                </div>
                            </div>
                            <div class="panel">
                                <div id="approve_lang1" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <hr />
                                        <p>Leaving feedback here will help you get a better translation next time. On your next order, you'll be able to specify whether to use only your preferred translators. This translator is on your list of preferred translators.</p>

                                        <div class="panel panel-default tooltip-demo">
                                            <div class="panel-body">
                                              <div class="form-group">
                                                <label class="control-label">Quality</label>
                                                <table class="table table-bordered table-hover table-striped">
                                                  <tbody>
                                                    <tr>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Very poor. There were multiple mistakes and/or the style was very poor." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="bad">
                                                          <span class="custom-radio"></span>
                                                          Bad
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Poor. There were mistakes and/or the style was poor." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="poor">
                                                          <span class="custom-radio"></span>
                                                          Poor
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory. If mistakes occurred, they were corrected." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="satisfactory">
                                                          <span class="custom-radio"></span>
                                                          Satisfactory
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Good. The overall style was appropriate and there were few, if any, mistakes." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="good">
                                                          <span class="custom-radio"></span>
                                                          Good
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Perfect" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="perfect">
                                                          <span class="custom-radio"></span>
                                                          Perfect
                                                        </label>
                                                      </td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div><!-- /form-group -->
                                              <div class="form-group">
                                                <label class="control-label">Turn Around Time</label>
                                                <table class="table table-bordered table-hover table-striped">
                                                  <tbody>
                                                    <tr>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much slower than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="m_slow">
                                                          <span class="custom-radio"></span>
                                                          Much Slower
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Slower than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="slow">
                                                          <span class="custom-radio"></span>
                                                          Slower
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="satisfactory">
                                                          <span class="custom-radio"></span>
                                                          Satisfactory
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Faster than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="faster">
                                                          <span class="custom-radio"></span>
                                                          Faster
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much faster than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="m_faster">
                                                          <span class="custom-radio"></span>
                                                          Much Faster
                                                        </label>
                                                      </td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div><!-- /form-group -->
                                              <div class="form-group">
                                                <label class="control-label">Feed back to Translator and Project Manager</label>
                                                <textarea class="form-control parsley-validated" placeholder="Your message here..." id="tarea{$h}" rows="3" data-required="true"></textarea>
                                              </div><!-- /form-group -->
                                                <div class="text-right m-t-md">
                                                    <a href="#" class="btn btn-primary"> Submit</a>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="panel">
                                <div id="correct_lang1" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <div class="panel panel-default">
                                          <form class="no-margin">
                                            <div class="panel-body">
                                                <div class="form-group">
                                                    <label class="control-label">What's wrong with the translation?</label>
                                                    <div class="checkbox"><label> <input type="checkbox" value=""> It is incomplete </label></div>
                                                    <div class="checkbox"><label> <input type="checkbox" value=""> It contains spelling or grammatical errors </label></div>
                                                    <div class="checkbox"><label> <input type="checkbox" value=""> It misses key meaning or details from the original </label></div>
                                                </div>
                                                <div class="form-group">
                                                <label class="control-label">Comments</label>
                                                <textarea class="form-control" placeholder="Your message here..." rows="3" id="commt{$h}" data-required="true"></textarea>
                                                <span class="help-block">(Please use English or Chinese (Simplified))</span>
                                                </div><!-- /form-group -->
                                                <div class="text-right m-t-md">
                                                    <a href="#" class="btn btn-warning"> Request corrections from translator or project manager</a>
                                                </div>
                                            </div>
                                          </form>
                                        </div><!-- /panel -->

                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" style="padding-bottom: 10px;">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion_preview" href="#preview_lang2">English <i class="fa fa-arrow-right"></i> Traditional Chinese</a>
                            </h4>
                        </div>
                        <div id="preview_lang2" class="panel-collapse collapse">

                            <div class="panel-body">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>File Name</th>
                                        <th>Size</th>
                                        <th>Time Stamp</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                    </tbody>
                                </table>

                                <div class="col-md-6">
                                    <p>Happy with your translation? Formally approve it here.</p>
                                    <a data-toggle="collapse" data-parent="#preview_lang2" href="#approve_lang2" class="btn btn-primary"><i class="fa fa-check-square-o"></i> Approve</a> <!-- if user click the approve button(all languages), the approve button and request correct button should hide, and project status should change to completed -->
                                </div>
                                <div class="col-md-6">
                                    <p>If you need the translator to fix mistakes or make changes:</p>
                                    <a data-toggle="collapse" data-parent="#preview_lang2" href="#correct_lang2" class="btn btn-warning"><i class="fa fa-edit"></i> Request corrections</a> <!-- if any language need correct, the project status will change to Reject -->
                                </div>
                            </div>
                            <div class="panel">
                                <div id="approve_lang2" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <hr />
                                        <p>Leaving feedback here will help you get a better translation next time. On your next order, you'll be able to specify whether to use only your preferred translators. This translator is on your list of preferred translators.</p>

                                        <div class="panel panel-default tooltip-demo">
                                            <div class="panel-body">
                                              <div class="form-group">
                                                <label class="control-label">Quality</label>
                                                <table class="table table-bordered table-hover table-striped">
                                                  <tbody>
                                                    <tr>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Very poor. There were multiple mistakes and/or the style was very poor." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="bad">
                                                          <span class="custom-radio"></span>
                                                          Bad
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Poor. There were mistakes and/or the style was poor." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="poor">
                                                          <span class="custom-radio"></span>
                                                          Poor
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory. If mistakes occurred, they were corrected." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="satisfactory">
                                                          <span class="custom-radio"></span>
                                                          Satisfactory
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Good. The overall style was appropriate and there were few, if any, mistakes." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="good">
                                                          <span class="custom-radio"></span>
                                                          Good
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Perfect" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="perfect">
                                                          <span class="custom-radio"></span>
                                                          Perfect
                                                        </label>
                                                      </td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div><!-- /form-group -->
                                              <div class="form-group">
                                                <label class="control-label">Turn Around Time</label>
                                                <table class="table table-bordered table-hover table-striped">
                                                  <tbody>
                                                    <tr>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much slower than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="m_slow">
                                                          <span class="custom-radio"></span>
                                                          Much Slower
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Slower than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="slow">
                                                          <span class="custom-radio"></span>
                                                          Slower
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="satisfactory">
                                                          <span class="custom-radio"></span>
                                                          Satisfactory
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Faster than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="faster">
                                                          <span class="custom-radio"></span>
                                                          Faster
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much faster than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="m_faster">
                                                          <span class="custom-radio"></span>
                                                          Much Faster
                                                        </label>
                                                      </td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div><!-- /form-group -->
                                              <div class="form-group">
                                                <label class="control-label">Feed back to Translator and Project Manager</label>
                                                <textarea class="form-control parsley-validated" placeholder="Your message here..." id="tarea{$h}" rows="3" data-required="true"></textarea>
                                              </div><!-- /form-group -->
                                                <div class="text-right m-t-md">
                                                    <a href="#" class="btn btn-primary"> Submit</a>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="panel">
                                <div id="correct_lang2" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <div class="panel panel-default">
                                          <form class="no-margin">
                                            <div class="panel-body">
                                                <div class="form-group">
                                                    <label class="control-label">What's wrong with the translation?</label>
                                                    <div class="checkbox"><label> <input type="checkbox" value=""> It is incomplete </label></div>
                                                    <div class="checkbox"><label> <input type="checkbox" value=""> It contains spelling or grammatical errors </label></div>
                                                    <div class="checkbox"><label> <input type="checkbox" value=""> It misses key meaning or details from the original </label></div>
                                                </div>
                                                <div class="form-group">
                                                <label class="control-label">Comments</label>
                                                <textarea class="form-control" placeholder="Your message here..." rows="3" id="commt{$h}" data-required="true"></textarea>
                                                <span class="help-block">(Please use English or Chinese (Simplified))</span>
                                                </div><!-- /form-group -->
                                                <div class="text-right m-t-md">
                                                    <a href="#" class="btn btn-warning"> Request corrections from translator or project manager</a>
                                                </div>
                                            </div>

                                          </form>
                                        </div><!-- /panel -->

                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" style="padding-bottom: 10px;">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion_preview" href="#preview_lang3">English <i class="fa fa-arrow-right"></i> German </a> <i class="fa fa-paperclip"></i></a> <!-- with paperclip means file for this language has been uploaded -->
                            </h4>
                        </div>
                        <div id="preview_lang3" class="panel-collapse collapse">

                            <div class="panel-body">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>File Name</th>
                                        <th>Size</th>
                                        <th>Time Stamp</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td><a href=""><i class="fa fa-file"></i> Project_document_JP.docx <i class="fa fa-cloud-download"></i></a> </td>
                                        <td>46.88 KB</td>
                                        <td>2014-Oct-09 16:30</td>
                                    </tr>
                                    </tbody>
                                </table>

                                <div class="col-md-6">
                                    <p>Happy with your translation? Formally approve it here.</p>
                                    <a data-toggle="collapse" data-parent="#preview_lang3" href="#approve_lang3" class="btn btn-primary"><i class="fa fa-check-square-o"></i> Approve</a> <!-- if user click the approve button(all languages), the approve button and request correct button should hide, and project status should change to completed -->
                                </div>
                                <div class="col-md-6">
                                    <p>If you need the translator to fix mistakes or make changes:</p>
                                    <a data-toggle="collapse" data-parent="#preview_lang3" href="#correct_lang3" class="btn btn-warning"><i class="fa fa-edit"></i> Request corrections</a> <!-- if any language need correct, the project status will change to Reject -->
                                </div>
                            </div>
                            <div class="panel">
                                <div id="approve_lang3" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <hr />
                                        <p>Leaving feedback here will help you get a better translation next time. On your next order, you'll be able to specify whether to use only your preferred translators. This translator is on your list of preferred translators.</p>

                                        <div class="panel panel-default tooltip-demo">
                                            <div class="panel-body">
                                              <div class="form-group">
                                                <label class="control-label">Quality</label>
                                                <table class="table table-bordered table-hover table-striped">
                                                  <tbody>
                                                    <tr>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Very poor. There were multiple mistakes and/or the style was very poor." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="bad">
                                                          <span class="custom-radio"></span>
                                                          Bad
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Poor. There were mistakes and/or the style was poor." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="poor">
                                                          <span class="custom-radio"></span>
                                                          Poor
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory. If mistakes occurred, they were corrected." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="satisfactory">
                                                          <span class="custom-radio"></span>
                                                          Satisfactory
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Good. The overall style was appropriate and there were few, if any, mistakes." width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="good">
                                                          <span class="custom-radio"></span>
                                                          Good
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Perfect" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="quality{$h}" value="perfect">
                                                          <span class="custom-radio"></span>
                                                          Perfect
                                                        </label>
                                                      </td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div><!-- /form-group -->
                                              <div class="form-group">
                                                <label class="control-label">Turn Around Time</label>
                                                <table class="table table-bordered table-hover table-striped">
                                                  <tbody>
                                                    <tr>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much slower than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="m_slow">
                                                          <span class="custom-radio"></span>
                                                          Much Slower
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Slower than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="slow">
                                                          <span class="custom-radio"></span>
                                                          Slower
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="satisfactory">
                                                          <span class="custom-radio"></span>
                                                          Satisfactory
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Faster than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="faster">
                                                          <span class="custom-radio"></span>
                                                          Faster
                                                        </label>
                                                      </td>
                                                      <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much faster than I expected" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" name="time{$h}" value="m_faster">
                                                          <span class="custom-radio"></span>
                                                          Much Faster
                                                        </label>
                                                      </td>
                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div><!-- /form-group -->
                                              <div class="form-group">
                                                <label class="control-label">Feed back to Translator and Project Manager</label>
                                                <textarea class="form-control parsley-validated" placeholder="Your message here..." id="tarea{$h}" rows="3" data-required="true"></textarea>
                                              </div><!-- /form-group -->
                                                <div class="text-right m-t-md">
                                                    <a href="#" class="btn btn-primary"> Submit</a>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="panel">
                                <div id="correct_lang3" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <div class="panel panel-default">
                                          <form class="no-margin">
                                            <div class="panel-body">
                                                <div class="form-group">
                                                    <label class="control-label">What's wrong with the translation?</label>
                                                    <div class="checkbox"><label> <input type="checkbox" value=""> It is incomplete </label></div>
                                                    <div class="checkbox"><label> <input type="checkbox" value=""> It contains spelling or grammatical errors </label></div>
                                                    <div class="checkbox"><label> <input type="checkbox" value=""> It misses key meaning or details from the original </label></div>
                                                </div>
                                                <div class="form-group">
                                                <label class="control-label">Comments</label>
                                                <textarea class="form-control" placeholder="Your message here..." rows="3" id="commt{$h}" data-required="true"></textarea>
                                                <span class="help-block">(Please use English or Chinese (Simplified))</span>
                                                </div><!-- /form-group -->
                                                <div class="text-right m-t-md">
                                                    <a href="#" class="btn btn-warning"> Request corrections from translator or project manager</a>
                                                </div>
                                            </div>
                                          </form>
                                        </div><!-- /panel -->

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="tab-pane" id="feedback">

            <div class="panel-body">
                <div class="panel-group" id="accordion_feedback">
                    <div class="panel panel-default">
                        <div class="panel-heading" style="padding-bottom: 10px;">
                            <h5 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion_feedback" href="#feedback_lang1"> English <i class="fa fa-arrow-right"></i> Simplify Chinese </a>
                            </h5>
                        </div>
                        <div id="feedback_lang1" class="panel-collapse collapse in">
                            <div class="panel">
                                <div class="panel-body">
                                    <hr />
                                    <p>Leaving feedback here will help you get a better translation next time. On your next order, you'll be able to specify whether to use only your preferred translators. This translator is on your list of preferred translators.</p>

                                    <div class="panel panel-default tooltip-demo">
                                        <div class="panel-body">
                                          <div class="form-group">
                                            <label class="control-label">Quality</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Very poor. There were multiple mistakes and/or the style was very poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="bad">
                                                      <span class="custom-radio"></span>
                                                      Bad
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Poor. There were mistakes and/or the style was poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="poor">
                                                      <span class="custom-radio"></span>
                                                      Poor
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory. If mistakes occurred, they were corrected." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Good. The overall style was appropriate and there were few, if any, mistakes." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="good">
                                                      <span class="custom-radio"></span>
                                                      Good
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Perfect" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="perfect">
                                                      <span class="custom-radio"></span>
                                                      Perfect
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Turn Around Time</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_slow">
                                                      <span class="custom-radio"></span>
                                                      Much Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="slow">
                                                      <span class="custom-radio"></span>
                                                      Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="faster">
                                                      <span class="custom-radio"></span>
                                                      Faster
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_faster">
                                                      <span class="custom-radio"></span>
                                                      Much Faster
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Feed back to Translator and Project Manager</label>
                                            <textarea class="form-control" value="previous commons..." id="tarea{$h}" rows="3"></textarea>
                                          </div><!-- /form-group -->

                                            <div class="text-right m-t-md">
                                                <a href="#" class="btn btn-primary"> Update</a>
                                            </div>

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" style="padding-bottom: 10px;">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion_feedback" href="#feedback_lang2">English <i class="fa fa-arrow-right"></i> Traditional Chinese</a>
                            </h4>
                        </div>
                        <div id="feedback_lang2" class="panel-collapse collapse">

                            <div class="panel">
                                <div class="panel-body">
                                    <hr />
                                    <p>Leaving feedback here will help you get a better translation next time. On your next order, you'll be able to specify whether to use only your preferred translators. This translator is on your list of preferred translators.</p>

                                    <div class="panel panel-default tooltip-demo">
                                        <div class="panel-body">
                                          <div class="form-group">
                                            <label class="control-label">Quality</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Very poor. There were multiple mistakes and/or the style was very poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="bad">
                                                      <span class="custom-radio"></span>
                                                      Bad
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Poor. There were mistakes and/or the style was poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="poor">
                                                      <span class="custom-radio"></span>
                                                      Poor
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory. If mistakes occurred, they were corrected." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Good. The overall style was appropriate and there were few, if any, mistakes." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="good">
                                                      <span class="custom-radio"></span>
                                                      Good
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Perfect" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="perfect">
                                                      <span class="custom-radio"></span>
                                                      Perfect
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Turn Around Time</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_slow">
                                                      <span class="custom-radio"></span>
                                                      Much Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="slow">
                                                      <span class="custom-radio"></span>
                                                      Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="faster">
                                                      <span class="custom-radio"></span>
                                                      Faster
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_faster">
                                                      <span class="custom-radio"></span>
                                                      Much Faster
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Feed back to Translator and Project Manager</label>
                                            <textarea class="form-control" value="previous commons..." id="tarea{$h}" rows="3"></textarea>
                                          </div><!-- /form-group -->

                                            <div class="text-right m-t-md">
                                                <a href="#" class="btn btn-primary"> Update</a>
                                            </div>

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" style="padding-bottom: 10px;">
                            <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion_feedback" href="#feedback_lang3">English <i class="fa fa-arrow-right"></i> German </a>
                            </h4>
                        </div>
                        <div id="feedback_lang3" class="panel-collapse collapse">
                            <div class="panel">
                                <div class="panel-body">
                                    <hr />
                                    <p>Leaving feedback here will help you get a better translation next time. On your next order, you'll be able to specify whether to use only your preferred translators. This translator is on your list of preferred translators.</p>

                                    <div class="panel panel-default tooltip-demo">
                                        <div class="panel-body">
                                          <div class="form-group">
                                            <label class="control-label">Quality</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Very poor. There were multiple mistakes and/or the style was very poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="bad">
                                                      <span class="custom-radio"></span>
                                                      Bad
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Poor. There were mistakes and/or the style was poor." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="poor">
                                                      <span class="custom-radio"></span>
                                                      Poor
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory. If mistakes occurred, they were corrected." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Good. The overall style was appropriate and there were few, if any, mistakes." width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="good">
                                                      <span class="custom-radio"></span>
                                                      Good
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Perfect" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="quality{$h}" value="perfect">
                                                      <span class="custom-radio"></span>
                                                      Perfect
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Turn Around Time</label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_slow">
                                                      <span class="custom-radio"></span>
                                                      Much Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Slower than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="slow">
                                                      <span class="custom-radio"></span>
                                                      Slower
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Satisfactory" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="satisfactory">
                                                      <span class="custom-radio"></span>
                                                      Satisfactory
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="faster">
                                                      <span class="custom-radio"></span>
                                                      Faster
                                                    </label>
                                                  </td>
                                                  <td class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="Much faster than I expected" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" name="time{$h}" value="m_faster">
                                                      <span class="custom-radio"></span>
                                                      Much Faster
                                                    </label>
                                                  </td>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label">Feed back to Translator and Project Manager</label>
                                            <textarea class="form-control" value="previous commons..." id="tarea{$h}" rows="3"></textarea>
                                          </div><!-- /form-group -->

                                            <div class="text-right m-t-md">
                                                <a href="#" class="btn btn-primary"> Update</a>
                                            </div>

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- if the project status is quoted or quoting, then hide other tabs only show quote tab -->
        <div class="tab-pane" id="quote">
            <?php include "detail/quote.phtml"; ?>
        </div>

        <div class="tab-pane" id="invoice" ng-show="project.status.id==2">
            <?php include "detail/invoice.phtml"; ?>
        </div>

    </div>

</div>
