                <div class="tabs-container">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#tasks" data-toggle="tab"><span class="label label-warning">{{ project.tasksNum }}</span> <?php echo $this->translate('Tasks','Admin') ?></a></li>
                        <li ng-class="{1:'active',2:''}[project.status.id]"><a href="#message" data-toggle="tab"><span class="label label-warning">{{ project.activitiesNum }}</span> <?php echo $this->translate('Messages','Admin') ?></a></li>
                        <li class=""><a href="#files" data-toggle="tab"><span class="label label-danger">{{ $root.filesLength }}</span> <?php echo $this->translate('Project Files','Admin') ?></a></li>

                        <li class="" ng-hide="project.status.id == 0 || project.status.id == 1"><a href="#feedback" data-toggle="tab"><span class="label label-warning">{{ project.feedbacksNum }}</span> <?php echo $this->translate('Quote','Admin') ?></a></li>
                        <!-- if the project status is quote, then show quote, other wise hide quote -->
                        <li class="" ng-hide="project.status.id == 0 || project.status.id == 1"><a href="#invoice" data-toggle="tab"> <?php echo $this->translate('Invoice','Admin') ?></a></li>
                        <!-- if the status is not quote, then show invoice -->
                    </ul>
                    <div class="tab-content">

                        <?php include "detail/tasks.phtml"; ?>
                        
                        <?php include "detail/activities.phtml"; ?>

                        <?php include "detail/files.phtml"; ?>

                        <?php include "detail/feedbacks.phtml"; ?>

                        <!-- if the project status is quoted or quoting, then hide other tabs only show quote tab -->
                        <?php include "detail/quote.phtml"; ?>

                        <?php include "detail/invoice.phtml"; ?>


                    </div>
                </div>


