<!DOCTYPE html>
<html lang="en">
	<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>PaperTask | Invoice Print</title>
    <!-- Le styles -->
	 
</head>
<body class="white-bg" style="background-color: #ffffff;">
    <div class="wrapper wrapper-content p-xl" style="padding: 20px 10px 40px; padding: 40px;">
		<div class="ibox-content p-xl" style="">
			<table style="width: 100%;max-width: 100%;margin-bottom: 20px;">
				<tbody>
				<tr>
					<td width="50%" style="text-align: left; "><span style="font-size: 10px;"><?php echo $this->translate('Invoice No: ','Employer'); ?><?php echo $this->invoices['invoice_no']; ?></span></td>
					<td width="50%" style="text-align: right;"><span style="font-size: 10px;">Invoice Date: <?php echo $this->invoiceDate;?></span></td>
				</tr>
				<tr>
					<td width="50%" style="text-align: left;"><span style="font-size: 10px;">PO No: <?php echo $this->project['po']; ?></span></td>
					<td width="50%" style="text-align: right;"><span style="font-size: 10px;">Due Date: <?php echo $this->dueDate;?></span></td>
				</tr>
				<div class="hr-line-dashed" style="clear:both;border-top: 1px dashed #676a6c; color: #ffffff; background-color: #ffffff;height: 1px;margin: 5px 0;"></div>
				<tr>
					<td width="50%" style="text-align: left;"><h3>From:</h3></td>
					<td width="50%" style="text-align: right;"><h3>To:</h3></td>
				</tr>
				<tr>
					<td width="50%" style="text-align: left;"><span style="font-size: 10px;"><?php echo $this->project['pm']['name']; ?></span></td>
					<td width="50%" style="text-align: right;"><span style="font-size: 10px;"><?php echo $this->project['client']['name']; ?></span></td>
				</tr>
				<tr>
					<td width="50%" style="text-align: left;">
					<address>
						<span style="font-size: 10px;"><?php echo $this->companyinfo['name']; ?></span><br>
						<span style="font-size: 8px;"><?php echo $this->companyinfo['address']; ?></span><br>
						<span style="font-size: 8px;"><?php echo $this->companyinfo['city']; ?>, <?php echo $this->companyinfo['country']; ?></span><br>
						<!--
						<abbr title="Phone">P:</abbr> <?php echo $this->companyinfo['telephone']; ?>
						-->
					</address></td>
					<td width="50%" style="text-align: right;">
						<address>
							<span style="font-size: 10px;"><?php echo $this->project['client']['company']['name']; ?></span><br>
							<span style="font-size: 8px;"><?php echo $this->project['client']['company']['address']; ?></span><br>
							<span style="font-size: 8px;"><?php echo $this->project['client']['company']['city']; ?>, <?php echo $this->project['client']['company']['country']; ?></span><br>
							<!--
							<abbr title="Phone">P:</abbr> <?php echo $this->project['client']['company']['telephone']; ?>
							-->
						</address>
					</td>
				</tr>
				</tbody>
			</table>
									
			<div class="table-responsive m-t" style="margin-left:2px;">
			<div class="hr-line-dashed" style="clear:both;border-top: 1px dashed #676a6c; color: #ffffff; background-color: #ffffff;height: 1px;margin: 5px 0;"></div>
			<?php foreach($this->project['targetLanguages'] as $targetLanguage) { ?>
			<table class="table table-bordered" style="border: 1px solid #e7e7e7; width: 100%; max-width: 100%; margin-bottom: 20px; border-spacing: 0px; padding: 2px;">
				<thead>
				<tr style="border-left: 1px solid #e7e7e7;">
					<th width="50%" style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857; font-weight: bold;"><span style="font-size: 10px;"><?php echo $this->project['sourceLanguage']['name']; ?> to <?php echo $targetLanguage['name'] ?></span></th>
					<th width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857; font-weight: bold;"><span style="font-size: 10px;">Unit</span></th>
					<th width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857; font-weight: bold;"><span style="font-size: 10px;">Unit Price</span></th>
					<th width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857; font-weight: bold;"><span style="font-size: 10px;">Quantity</span></th>
					<th width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857; font-weight: bold;"><span style="font-size: 10px;">Price</span></th>
				</tr>
				</thead>
				<tbody>
				<!-- this is only for translation use TM -->
				<?php if($iterm_translationtms[$targetLanguage['id']]) { ?>
				<tr style="border-left: 1px solid #e7e7e7;">
					<td width="50%" style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['name'];?> - Use TM</span></td>
					<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">Source Word</span></td>
					<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_translationtms[$targetLanguage['id']]['rate'];?></span></td>
					<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo 	$iterm_translationtms[$targetLanguage['id']]['sourcerepetitions'] + 
									$iterm_translationtms[$targetLanguage['id']]['sourceyibai'] +
									$iterm_translationtms[$targetLanguage['id']]['sourcejiuwu'] +
									$iterm_translationtms[$targetLanguage['id']]['sourcebawu'] +
									$iterm_translationtms[$targetLanguage['id']]['sourceqiwu'] +
									$iterm_translationtms[$targetLanguage['id']]['sourcewushi'];?></span></td>
					<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_translationtms[$targetLanguage['id']]['total'];?></span></td>
				</tr>
				<tr style="border-left: 1px solid #e7e7e7;"> <!-- this is only for translation use TM -->
					<td colspan="5" style="border: 1px solid #e7e7e7;">
						<div id="use_tm1" class="panel-collapse">
							<div>
								<table class="table table-bordered" style="border: 1px solid #ddd;width: 100%;max-width: 100%;margin-bottom: 20px;border-spacing: 0px; padding: 2px;">
									<thead>
									<tr>
										<th style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">TM Template</span></th>
										<th style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">Rate (%)</span></th>
										<th style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">Unit Price</span></th>
										<th style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">Quantity (Word)</span></th>
										<th style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">Price</span></th>
									</tr>
									</thead>
									<tbody>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">Repetitions</span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['raterepetitions'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['raterepetitions']/100 ;?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourcerepetitions'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['raterepetitions']/100)*$iterm_translationtms[$targetLanguage['id']]['sourcerepetitions'];?></span></td>
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">100%</span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rateyibai'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['rateyibai']/100 ;?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourceyibai'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['rateyibai']/100)*$iterm_translationtms[$targetLanguage['id']]['sourceyibai'];?></span></td>
										
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">95%-99%</span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['ratejiuwu'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratejiuwu']/100 ;?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourcejiuwu'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratejiuwu']/100)*$iterm_translationtms[$targetLanguage['id']]['sourcejiuwu'];?></span></td>
										
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">85%-94%</span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['ratebawu'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratebawu']/100 ;?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourcebawu'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratebawu']/100)*$iterm_translationtms[$targetLanguage['id']]['sourcebawu'];?></span></td>
										
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">75%-84%</span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rateqiwu'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['rateqiwu']/100 ;?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourceqiwu'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['rateqiwu']/100)*$iterm_translationtms[$targetLanguage['id']]['sourceqiwu'];?></span></td>
										
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">50%-74%</span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['ratewushi'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratewushi']/100 ;?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourcewushi'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratewushi']/100)*$iterm_translationtms[$targetLanguage['id']]['sourcewushi'];?></span></td>
										
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">No Match</span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['ratenomatch'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratenomatch']/100 ;?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourcenomatch'];?></span></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratenomatch']/100)*$iterm_translationtms[$targetLanguage['id']]['sourcenomatch'];?></span></td>
										
									</tr>
									<tr>
										<td colspan="4" style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 10px;">Total</span></td>
										<td class="text-info" style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 10px;"><?php echo $this->project['currency']; ?>  <?php echo $iterm_translationtms[$targetLanguage['id']]['total'];?></span></td>
									</tr>
									</tbody>
								</table>
							</div>
						</div>
					</td>
				</tr>
				<?php } ?>
				
				<?php if($this->hasTypeTranslationNoTM > 0) { ?>
					<?php foreach($this->iterm_translations as $iterm_translations) { 
					
					if($iterm_translations['language']['id'] == $targetLanguage['id']) {?>
						<tr>
							<td width="50%" style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translations['name'];?> - Translation (No TM)</span></td>
							<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;">Source Word</span></td>
							<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_translations['rate'];?></span></td>
							<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_translations['quantity'];?></span></td>
							<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_translations['total'];?></span></td>
						</tr>
					<?php } ?>	
				<?php }} ?>
				
				
				<?php if($this->hasTypeDesktopPublishingMac > 0) { ?>
					<?php foreach($this->iterm_dtpmacs as $iterm_dtpmac) { 
					if($iterm_dtpmac['language']['id'] == $targetLanguage['id']) {?>
						<tr>
							<td width="50%" style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_dtpmac['name'];?> - DTP MAC</span></td>
							<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_dtpmac['unit'];?></span></td>
							<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_dtpmac['rate'];?></span></td>
							<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_dtpmac['quantity'];?></span></td>
							<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_dtpmac['total'];?></span></td>
						</tr>
					<?php } ?>	
				<?php }} ?>
				
				<?php if($this->hasTypeDesktopPublishingWin > 0) { ?>
					<?php foreach($this->iterm_dtppcs as $iterm_dtppc) { 
					if($iterm_dtppc['language']['id'] == $targetLanguage['id']) {?>
						<tr>
							<td width="50%" style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_dtppc['name'];?> - DTP WIN</span></td>
							<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_dtppc['unit'];?></span></td>
							<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_dtppc['rate'];?></span></td>
							<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_dtppc['quantity'];?></span></td>
							<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_dtppc['total'];?></span></td>
						</tr>
					<?php } ?>	
				<?php }} ?>
				
				<?php if($this->hasTypeDesktopPublishingEngineer > 0) { ?>
					<?php foreach($this->iterm_engineerings as $iterm_engineering) { 
					if($iterm_engineering['language']['id'] == $targetLanguage['id']) {?>
						<tr>
							<td style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_engineering['name'];?> - Engineering </span></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_engineering['unit'];?></span></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_engineering['rate'];?></span></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_engineering['quantity'];?></span></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_engineering['total'];?></span></td>
						</tr>
					<?php } ?>	
				<?php }} ?>
				
				<?php if($this->hasTypeDesktopPublishingInterpreting > 0) { ?>
					<?php foreach($this->iterm_interpretings as $iterm_interpreting) { 
					if($iterm_interpreting['language']['id'] == $targetLanguage['id']) {?>
						<tr>
							<td style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_interpreting['name'];?> - iterm_interpreting</span></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_interpreting['unit'];?></span></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_interpreting['rate'];?></span></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $iterm_interpreting['quantity'];?></span></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 9px;"><?php echo $this->project['currency']; ?> <?php echo $iterm_interpreting['total'];?></span></td>
						</tr>
					<?php } ?>	
				<?php }} ?>
				
				
				</tbody>
			</table>
			<?php } ?>
		</div><!-- /table-responsive -->
		<table class="table invoice-total" style="width: 100%;max-width: 100%;margin-bottom: 20px;">
			<tbody>
			<tr>
				<td width="85%" style="text-align: right; padding: 8px;line-height: 1.42857;"><span style="font-size: 10px;">Sub Total :</span></td>
				<td width="15%" style="text-align: right;  border-bottom: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 10px;"><?php echo $this->project['currency']; ?> <?php echo $this->subtotal; ?></span></td>
			</tr>
			<tr>
				<td width="85%" style="text-align: right; padding: 8px;line-height: 1.42857;"><span style="font-size: 10px;">(-) Discount :</span></td>
				<td  width="15%" style="text-align: right;  border-bottom: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 10px;">- <?php echo $this->project['currency']; ?> <?php echo $this->project['discount']; ?></span></td>
			</tr>
			<tr>
				<td width="85%" style="text-align: right; padding: 8px;line-height: 1.42857;"><span style="font-size: 10px;">TAX ( <?php echo $this->project['tax']; ?>% ) :</span></td>
				<td  width="15%" style="text-align: right;  border-bottom: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 10px;"><?php echo $this->project['currency']; ?> <?php echo ($this->subtotal  - $this->project['discount'])* $this->project['tax']/100; ?></span></td>
			</tr>
			<tr>
				<td width="85%" style="text-align: right; padding: 8px;line-height: 1.42857;"><span style="font-size: 10px;">TOTAL :</span></td>
				<td  width="15%" style="text-align: right;  border-bottom: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span style="font-size: 10px;"><?php echo $this->project['currency']; ?> <?php echo $this->subtotal  - $this->project['discount'] + ($this->subtotal  - $this->project['discount'])* $this->project['tax']/100; ?></span></td>
			</tr>
			</tbody>
		</table>
		<!-- if the client is uncontracted, then "make a payment" will show, if client type is "contracted", then dont show "make a payment" instead of "accept the quote" after accept, the project status changed from quoted to ordered -->
		<br />
		<div class="hr-line-dashed" style="clear:both;border-top: 1px dashed #676a6c; color: #ffffff; background-color: #ffffff;height: 1px;margin: 5px 0;"></div>
		<div class="m-t">
			<h2 style="text-align: center;color: #ed5565;">Due Date: <?php echo $this->dueDate;?></h2>
			</br>
			
		</div>
		<table style="width: 100%;max-width: 100%;margin-bottom: 20px;">
				<tbody>
					<tr style="margin-bottom: 10px;">
						<td width="50%" style="text-align: left;">
							<h3>Bank Details</h3>
						</td>
						<td width="50%" style="text-align: right;">
							<h3>Other Payment Methods</h3>
						</td>
					</tr>
					<tr>
						<td width="50%" style="text-align: left;">
							<span style="float: left;width: 120px; font-size: 10px;">Company Name: <?php echo $this->companyinfo['name']; ?></span>
						</td>	
						<td  width="50%" style="text-align: right;">
							<span style="font-size: 10px;">Paypal: payments@papertask.com</span>
						</td>
					</tr>
					<tr>
						<td width="50%" style="text-align: left;">
							<span style="float: left;width: 120px; font-size: 10px;">Bank Name: <?php echo $this->bankinfo['name']; ?></span>
						</td>
						<td   width="50%" style="text-align: right;">
							<span style="font-size: 10px;">Alipay: payments@papertask.com</span>
						</td>
					</tr>
					<tr>
						<td width="50%" style="text-align: left;">
							<span style="float: left;width: 120px; font-size: 10px;">Bank Address: <?php echo $this->bankinfo['address']; ?>, <?php echo $this->bankinfo['city']; ?>, <?php echo $this->bankinfo['country']['name']; ?></span>
						</td>
						<td   width="50%" style="text-align: right;">
							
						</td>
					</tr>			
					<tr>
						<td width="50%" style="text-align: left;">
							<span style="float: left;width: 120px; font-size: 10px;">Account Number: <?php echo $this->bankinfo['accountNo']; ?></span>
						</td>
						<td   width="50%" style="text-align: right;">
							
						</td>
					</tr>	
					<tr>
						<td width="50%" style="text-align: left;">
							<span style="float: left;width: 120px; font-size: 10px;">Swift Code: <?php echo $this->bankinfo['swift']; ?></span>
						</td>
						<td   width="50%" style="text-align: right;">
							
						</td>
					</tr>
				</tbody>
		</table>
	</div>
</body>
</html>



