<!DOCTYPE html>
<html lang="en">
	<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>INSPINIA | Invoice Print</title>
    <!-- Le styles -->
	 
</head>
<body class="white-bg" style="background-color: #ffffff;">
    <div class="wrapper wrapper-content p-xl" style="padding: 20px 10px 40px;padding: 40px;">
		<div class="ibox-content p-xl" style="">
			<table style="width: 100%;max-width: 100%;margin-bottom: 20px;">
				<tbody>
				<tr>
					<td width="50%" style="text-align: left;"><h4>Invoice No. : <span style="color: #1ab394;"><?php echo $this->invoices['invoice_no']; ?></span></h4></td>
					<td width="50%" style="text-align: right;"><strong>Invoice Date:</strong> <?php echo $this->invoiceDate;?></td>
				</tr>
				<tr>
					<td width="50%" style="text-align: left;"><h4>PO No. : <span style="color: #1ab394;"><?php echo $this->project['po']; ?></span></h4></td>
					<td width="50%" style="text-align: right;"><strong>Due Date:</strong> <?php echo $this->dueDate;?></td>
				</tr>
				<tr>
					<td width="50%" style="text-align: left;"><h5>From:</h5></td>
					<td width="50%" style="text-align: right;"><h5>To:</h5></td>
				</tr>
				<tr>
					<td width="50%" style="text-align: left;"><strong><?php echo $this->project['pm']['name']; ?></strong></td>
					<td width="50%" style="text-align: right;"><strong><?php echo $this->project['client']['name']; ?> </strong></td>
				</tr>
				<tr>
					<td width="50%" style="text-align: left;"><strong>Project Manager</strong></td>
					<td width="50%" style="text-align: right;"><strong><?php echo $this->project['client']['position']; ?></strong></td>
				</tr>
				<tr>
					<td width="50%" style="text-align: left;"><address>
						<strong><?php echo $this->companyinfo['name']; ?></strong><br>
						<?php echo $this->companyinfo['address']; ?><br>
						<?php echo $this->companyinfo['city']; ?>, <?php echo $this->companyinfo['country']; ?><br>
						<abbr title="Phone">P:</abbr> <?php echo $this->companyinfo['telephone']; ?>
					</address></td>
					<td width="50%" style="text-align: right;"><address>
						<strong><?php echo $this->project['client']['company']['name']; ?></strong><br>
						<?php echo $this->project['client']['company']['address']; ?><br>
						<?php echo $this->project['client']['company']['city']; ?>, <?php echo $this->project['client']['company']['country']; ?><br>
						<abbr title="Phone">P:</abbr> <?php echo $this->project['client']['company']['telephone']; ?>
					</address></td>
				</tr>
				</tbody>
			</table>
			
			<div class="hr-line-dashed" style="clear:both;border-top: 1px dashed #e7eaec; color: #ffffff; background-color: #ffffff;height: 1px;margin: 20px 0;"></div>
			
			<div class="table-responsive m-t" style="margin-left:2px;">
			<?php foreach($this->project['targetLanguages'] as $targetLanguage) { ?>
			<table class="table table-bordered invoice-table" style="border: 1px solid #ddd;width: 100%;max-width: 100%;margin-bottom: 20px;border-spacing: 0px;">
				<thead>
				<tr style="border-left: 1px solid #e7e7e7;">
					<th width="50%" style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['sourceLanguage']['name']; ?> to <?php echo $targetLanguage['name'] ?> - task</th>
					<th width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">Unit</th>
					<th width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">Unit Price</th>
					<th width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">Quantity</th>
					<th width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">Total Price</th>
				</tr>
				</thead>
				<tbody>
				<!-- this is only for translation use TM -->
				<?php if($this->hasTypeTranslationUseTM > 0) { ?>
				<tr style="border-left: 1px solid #e7e7e7;">
					<td style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><div><a data-toggle="collapse" href="#use_tm1"><i class="fa fa-eye"></i> <strong><?php echo $iterm_translationtms[$targetLanguage['id']]['name'];?></strong></a> - <span class="text-navy"> Translation (Use TM)</span></div></td>
					<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">Source Word</td>
					<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $iterm_translationtms[$targetLanguage['id']]['rate'];?></td>
					<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo 	$iterm_translationtms[$targetLanguage['id']]['sourcerepetitions'] + 
									$iterm_translationtms[$targetLanguage['id']]['sourceyibai'] +
									$iterm_translationtms[$targetLanguage['id']]['sourcejiuwu'] +
									$iterm_translationtms[$targetLanguage['id']]['sourcebawu'] +
									$iterm_translationtms[$targetLanguage['id']]['sourceqiwu'] +
									$iterm_translationtms[$targetLanguage['id']]['sourcewushi'];?></td>
					<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $iterm_translationtms[$targetLanguage['id']]['total'];?></td>
				</tr>
				<tr style="border-left: 1px solid #e7e7e7;"> <!-- this is only for translation use TM -->
					<td colspan="5" style="border: 1px solid #e7e7e7;">
						<div id="use_tm1" class="panel-collapse">
							<div>
								<table class="table table-bordered" style="border: 1px solid #ddd;width: 100%;max-width: 100%;margin-bottom: 20px;border-spacing: 0px;">
									<thead>
									<tr>
										<th style="text-align: left; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">TM Template</th>
										<th style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">Rate (%)</th>
										<th style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">Unit Price</th>
										<th style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">Quantity (Word)</th>
										<th style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">Quantity</th>
									</tr>
									</thead>
									<tbody>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">Repetitions</td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['raterepetitions'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['raterepetitions']/100 ;?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourcerepetitions'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['raterepetitions']/100)*$iterm_translationtms[$targetLanguage['id']]['sourcerepetitions'];?></td>
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">100%</td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rateyibai'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['rateyibai']/100 ;?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourceyibai'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['rateyibai']/100)*$iterm_translationtms[$targetLanguage['id']]['sourceyibai'];?></td>
										
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">95%-99%</td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['ratejiuwu'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratejiuwu']/100 ;?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourcejiuwu'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratejiuwu']/100)*$iterm_translationtms[$targetLanguage['id']]['sourcejiuwu'];?></td>
										
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">85%-94%</td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['ratebawu'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratebawu']/100 ;?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourcebawu'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratebawu']/100)*$iterm_translationtms[$targetLanguage['id']]['sourcebawu'];?></td>
										
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">75%-84%</td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rateqiwu'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['rateqiwu']/100 ;?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourceqiwu'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['rateqiwu']/100)*$iterm_translationtms[$targetLanguage['id']]['sourceqiwu'];?></td>
										
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">50%-74%</td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['ratewushi'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratewushi']/100 ;?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourcewushi'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratewushi']/100)*$iterm_translationtms[$targetLanguage['id']]['sourcewushi'];?></td>
										
									</tr>
									<tr>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">No Match</td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['ratenomatch'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratenomatch']/100 ;?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translationtms[$targetLanguage['id']]['sourcenomatch'];?></td>
										<td style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo ($iterm_translationtms[$targetLanguage['id']]['rate']*$iterm_translationtms[$targetLanguage['id']]['ratenomatch']/100)*$iterm_translationtms[$targetLanguage['id']]['sourcenomatch'];?></td>
										
									</tr>
									<tr>
										<td colspan="4" style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><strong>Total</strong></td>
										<td class="text-info" style="text-align: right; border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?>  <?php echo $iterm_translationtms[$targetLanguage['id']]['total'];?></td>
									</tr>
									</tbody>
								</table>
							</div>
						</div>
					</td>
				</tr>
				<?php } ?>
				
				<?php if($this->hasTypeTranslationUseTM > 0) { ?>
					<?php foreach($this->iterm_translations as $iterm_translations) { 
					if($iterm_translations['language']['id'] == $targetLanguage['id']) {?>
						<tr>
							<td style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><div><strong> <?php echo $iterm_translations['name'];?></strong> - <span class="text-navy"> Translation (No TM)</span></div></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;">Source Word</td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $iterm_translations['rate'];?></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_translations['quantity'];?></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $iterm_translations['total'];?></td>
						</tr>
					<?php } ?>	
				<?php }} ?>
				
				
				<?php if($this->hasTypeDesktopPublishingMac > 0) { ?>
					<?php foreach($this->iterm_dtpmacs as $iterm_dtpmac) { 
					if($iterm_dtpmac['language']['id'] == $targetLanguage['id']) {?>
						<tr>
							<td width="50%" style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><div><strong> <?php echo $iterm_dtpmac['name'];?></strong> - <span class="text-info">DTP <i class="fa fa-apple"></i></span></div></td>
							<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_dtpmac['unit'];?> </td>
							<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $iterm_dtpmac['rate'];?></td>
							<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_dtpmac['quantity'];?></td>
							<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $iterm_dtpmac['total'];?></td>
						</tr>
					<?php } ?>	
				<?php }} ?>
				
				<?php if($this->hasTypeDesktopPublishingWin > 0) { ?>
					<?php foreach($this->iterm_dtppcs as $iterm_dtppc) { 
					if($iterm_dtppc['language']['id'] == $targetLanguage['id']) {?>
						<tr>
							<td width="50%" style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><div><strong> <?php echo $iterm_dtppc['name'];?></strong> - <span class="text-info">DTP <i class="fa fa-windows"></i></span></div></td>
							<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_dtppc['unit'];?> </td>
							<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $iterm_dtppc['rate'];?></td>
							<td width="10%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_dtppc['quantity'];?></td>
							<td width="15%" style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $iterm_dtppc['total'];?></td>
						</tr>
					<?php } ?>	
				<?php }} ?>
				
				<?php if($this->hasTypeDesktopPublishingEngineer > 0) { ?>
					<?php foreach($this->iterm_engineerings as $iterm_engineering) { 
					if($iterm_engineering['language']['id'] == $targetLanguage['id']) {?>
						<tr>
							<td style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><div><strong> <?php echo $iterm_engineering['name'];?></strong> - <span class="text-info">Engineering </span></div></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_engineering['unit'];?> </td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $iterm_engineering['rate'];?></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_engineering['quantity'];?></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $iterm_engineering['total'];?></td>
						</tr>
					<?php } ?>	
				<?php }} ?>
				
				<?php if($this->hasTypeDesktopPublishingInterpreting > 0) { ?>
					<?php foreach($this->iterm_interpretings as $iterm_interpreting) { 
					if($iterm_interpreting['language']['id'] == $targetLanguage['id']) {?>
						<tr>
							<td style="text-align: left;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><div><strong> <?php echo $iterm_interpreting['name'];?></strong> - <span class="text-info">iterm_interpreting </span></div></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_interpreting['unit'];?> </td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $iterm_interpreting['rate'];?></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $iterm_interpreting['quantity'];?></td>
							<td style="text-align: right;  border: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?>  <?php echo $iterm_interpreting['total'];?></td>
						</tr>
					<?php } ?>	
				<?php }} ?>
				
				
				</tbody>
			</table>
			<?php } ?>
		</div><!-- /table-responsive -->
		<table class="table invoice-total" style="width: 100%;max-width: 100%;margin-bottom: 20px;">
			<tbody>
			<tr>
				<td width="85%" style="text-align: right; padding: 8px;line-height: 1.42857;"><strong>Sub Total :</strong></td>
				<td width="15%" style="text-align: right;  border-bottom: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?>  <?php echo $this->subtotal; ?></td>
			</tr>
			<tr>
				<td width="85%" style="text-align: right; padding: 8px;line-height: 1.42857;"><strong>(-) Discount :</strong></td>
				<td  width="15%" style="text-align: right;  border-bottom: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><span class="text-danger"><strong>-</strong></span><?php echo $this->project['currency']; ?> <?php echo $this->project['discount']; ?></td>
			</tr>
			<tr>
				<td width="85%" style="text-align: right; padding: 8px;line-height: 1.42857;"><strong>TAX ( <?php echo $this->project['tax']; ?> %):</strong></td>
				<td  width="15%" style="text-align: right;  border-bottom: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?>  <?php echo ($this->subtotal  - $this->project['discount'])* $this->project['tax']/100; ?> </td>
			</tr>
			<tr>
				<td width="85%" style="text-align: right; padding: 8px;line-height: 1.42857;"><strong>TOTAL :</strong></td>
				<td  width="15%" style="text-align: right;  border-bottom: 1px solid #e7e7e7; padding: 8px;line-height: 1.42857;"><?php echo $this->project['currency']; ?> <?php echo $this->subtotal  - $this->project['discount'] + ($this->subtotal  - $this->project['discount'])* $this->project['tax']/100; ?> </td>
			</tr>
			</tbody>
		</table>
		<!-- if the client is uncontracted, then "make a payment" will show, if client type is "contracted", then dont show "make a payment" instead of "accept the quote" after accept, the project status changed from quoted to ordered -->
		<div class="hr-line-dashed" style="border-top: 1px dashed #e7eaec;color: #ffffff;background-color: #ffffff;height: 1px;margin: 20px 0;"></div>
		<div class="m-t">
			<h2 style="text-align: center;color: #ed5565;">Due Date: <?php echo $this->dueDate;?></h2>
			</br>
			
		</div>
		<table style="width: 100%;max-width: 100%;margin-bottom: 20px;">
				<tbody>
					<tr style="margin-bottom: 10px;">
						<td width="50%" style="text-align: left;">
							<h4>Bank Details</h4>
						</td>
						<td width="50%" style="text-align: right;">
							<h4>Other Payment Methods</h4>
						</td>
					</tr>
					<tr>
						<td width="50%" style="text-align: left;">
							<strong><span style="float: left;width: 120px;">Company Name</span></strong>:<?php echo $this->companyinfo['name']; ?>
						</td>	
						<td  width="50%" style="text-align: right;">
							<strong>Paypal:</strong>  payments@papertask.com
						</td>
					</tr>
					<tr>
						<td width="50%" style="text-align: left;">
							<strong><span style="float: left;width: 120px;">Bank Name</span></strong>:<?php echo $this->bankinfo['name']; ?>
						</td>
						<td   width="50%" style="text-align: right;">
							<strong>Alipay: </strong>payments@papertask.com
						</td>
					</tr>
					<tr>
						<td width="50%" style="text-align: left;">
							<strong><span style="float: left;width: 120px;">Bank Address</span></strong>:  <?php echo $this->bankinfo['address']; ?>, <?php echo $this->bankinfo['city']; ?>, <?php echo $this->bankinfo['country']; ?>
						</td>
						<td   width="50%" style="text-align: right;">
							
						</td>
					</tr>			
					<tr>
						<td width="50%" style="text-align: left;">
							<strong><span style="float: left;width: 120px;">Account Number</span></strong>: <?php echo $this->bankinfo['accountNo']; ?>
						</td>
						<td   width="50%" style="text-align: right;">
							
						</td>
					</tr>	
					<tr>
						<td width="50%" style="text-align: left;">
							<strong><span style="float: left;width: 120px;">Swift Code</span></strong>: <?php echo $this->bankinfo['swift']; ?>
						</td>
						<td   width="50%" style="text-align: right;">
							
						</td>
					</tr>
				</tbody>
		</table>
		</div>
	</div>
</body>
</html>



