<!DOCTYPE html>

<html lang="en" ng-app="project">

	<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<title>INSPINIA | Invoice Print</title>
    <!-- Le styles -->
	 
	 <link href="<?php echo $this->basePath() . '/css/bootstrap.min.css'?>" rel="stylesheet" media="all">
	 <link href="<?php echo $this->basePath() . '/css/style.css'?>" rel="stylesheet" media="all">
	 <link href="<?php echo $this->basePath() . '/css/bootstrap.min.css'?>" rel="stylesheet" media="all">
	 <link href="<?php echo $this->basePath() . '/font-awesome/css/font-awesome.csss'?>" rel="stylesheet" media="all">
	 
    <!-- Scripts -->
	<script src="<?php echo $this->basePath() . '/js/jquery-1.10.2.js'?>"></script>
	<script src="<?php echo $this->basePath() . '/js/bootstrap.min.js'?>"></script>
	<script src="<?php echo $this->basePath() . '/js/plugins/metisMenu/jquery.metisMenu.js'?>"></script>
	<script src="<?php echo $this->basePath() . '/js/inspinia.js'?>"></script>
	<script src="<?php echo $this->basePath() . '/js/angular.min.js'?>"></script>
	
	 <?php echo $this->headScript()
        
		->prependScript("PROJECT_ID = {$this->id};")
		->prependScript("angularApp = angular.module('project', []);")
		
    ; ?>
	<script src="<?php echo $this->basePath() . '/js/admin/project/quote-print.js'?>"></script>
	<script src="<?php echo $this->basePath() . '/js/admin/common/angular/ItemListController.js'?>"></script>
	<script src="<?php echo $this->basePath() . '/js/admin/common/angular/service/project.js'?>"></script>
	<script src="<?php echo $this->basePath() . '/js/admin/common/angular/CurrentUser.js'?>"></script>

   
<?php
echo $this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>

</head>
<body class="white-bg" ng-controller="QuotePrintController">
    <div class="wrapper wrapper-content p-xl">
		<div class="ibox-content p-xl">
			<div class="row">
				<div class="col-xs-6">
					<h4>Invoice No.</h4>
					<h4 class="text-navy">{{ invoice.invoice_no }}</h4>
					
					<h5>From:</h5>
					<strong>{{ project.pm.name }}</strong><br>
					<strong>Project Manager</strong><br>
					<address>
						<strong>{{companyinfo1.name}}</strong><br>
						{{companyinfo1.address}}<br>
						{{companyinfo1.city}}, {{companyinfo1.country}}<br>
						<abbr title="Phone">P:</abbr> {{companyinfo1.telephone}}
					</address>
				</div>

				<div class="col-xs-6 text-right">
					<p>
						<span><strong>Invoice Date:</strong>{{ DateFormatter.format1(invoice.invoiceDate) }}</span><br/>
						<span><strong>Due Date:</strong>{{  DateFormatter.format1(invoice.dueDate) }}</span>
					</p>
					<h5>To:</span></h5>
					<strong>{{ project.client.name }}</strong><br>
					<strong>{{ project.client.position }} </strong><br>
					<address>
						<strong>{{ project.client.company.name }}</strong><br>
						{{ project.client.company.address }}<br>
						{{ project.client.company.city }}, {{ project.client.company.country }}<br>
						<abbr title="Phone">P:</abbr> {{ project.client.company.telephone }}
					</address>

				</div>
			</div>
			
			<div class="hr-line-dashed"></div>
			<h4>Dear {{ project.client.name }},</h4><br>
			<h4>RE: {{ project.reference }} </h4><br>
			<p>Further to receipt of your enquiry, I now have pleasure in providing you with the cost for the above requirement.</p>
			<p><strong>Service Level: <span class="text-navy">  {{ project.serviceLevel.name }}</span></strong></p>
			<p><strong>Approximate duration: <span class="text-navy">{{ project.duration }} Working days</span></strong></p>
			<div class="hr-line-dashed"></div>
			
			<div class="table-responsive m-t"  ng-repeat="targetLanguage in project.targetLanguages">
			<table class="table table-bordered invoice-table">
				<thead>
				<tr>
					<th>{{ project.sourceLanguage.name }} to {{ targetLanguage.name }} - task</th>
					<th>Unit</th>
					<th>Unit Price</th>
					<th>Quantity</th>
					<th>Total Price</th>
				</tr>
				</thead>
				<tbody>
				<!-- this is only for translation use TM -->
				<tr  ng-show="hasTypeTranslationUseTM()" >
					<td><div><a data-toggle="collapse" href="#use_tm{{targetLanguage.id}}"><i class="fa fa-eye"></i> <strong>{{ itemtms[targetLanguage.id][0].name }}</strong></a> - <span class="text-navy"> Translation (Use TM)</span></div></td>
					<td>Source Word</td>
					<td>{{ itemtms[targetLanguage.id][0].rate }}</td>
					<td>{{ itemtms[targetLanguage.id][0].sourcerepetitions + itemtms[targetLanguage.id][0].sourceyibai + itemtms[targetLanguage.id][0].sourcejiuwu + itemtms[targetLanguage.id][0].sourcebawu + itemtms[targetLanguage.id][0].sourceqiwu + itemtms[targetLanguage.id][0].sourcewushi}}</td>
					<td>{{ itemtms[targetLanguage.id][0].total }}</td>
				</tr>
				<tr  ng-show="hasTypeTranslationUseTM()"> <!-- this is only for translation use TM -->
					<td colspan="5">
						<div id="use_tm{{targetLanguage.id}}" class="panel-collapse">
							<div class="table-responsive">
								<table class="table table-bordered">
									<thead>
									<tr>
										<th>TM Template</th>
										<th>Rate (%)</th>
										<th>Unit Price</th>
										<th>Quantity (Word)</th>
										<th>Quantity</th>
									</tr>
									</thead>
									<tbody>
									<tr>
										<td>Repetitions</td>
										<td>{{ itemtms[targetLanguage.id][0].raterepetitions }}</td>
										<td>{{ itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].raterepetitions / 100 | number:2 }}</td>
										<td>{{ itemtms[targetLanguage.id][0].sourcerepetitions }}</td>
										<td>{{ (itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].raterepetitions / 100) * itemtms[targetLanguage.id][0].sourcerepetitions | number:2 }}</td>
									</tr>
									<tr>
										<td>100%</td>
										<td>{{ itemtms[targetLanguage.id][0].rateyibai }}</td>
										<td>{{ itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].rateyibai / 100 | number:2 }}</td>
										<td>{{ itemtms[targetLanguage.id][0].sourceyibai }}</td>
										<td>{{ (itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].rateyibai / 100) * itemtms[targetLanguage.id][0].sourceyibai | number:2 }}</td>
									</tr>
									<tr>
										<td>95%-99%</td>
										<td>{{ itemtms[targetLanguage.id][0].ratejiuwu }}</td>
										<td>{{ itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].ratejiuwu / 100 | number:2 }}</td>
										<td>{{ itemtms[targetLanguage.id][0].sourcejiuwu }}</td>
										<td>{{ (itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].ratejiuwu / 100) * itemtms[targetLanguage.id][0].sourcejiuwu | number:2 }}</td>
									</tr>
									<tr>
										<td>85%-94%</td>
										<td>{{ itemtms[targetLanguage.id][0].ratebawu }}</td>
										<td>{{ itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].ratebawu / 100 | number:2 }}</td>
										<td>{{ itemtms[targetLanguage.id][0].sourcebawu }}</td>
										<td>{{ (itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].ratebawu / 100) * itemtms[targetLanguage.id][0].sourcebawu | number:2 }}</td>
									</tr>
									<tr>
										<td>75%-84%</td>
										<td>{{ itemtms[targetLanguage.id][0].rateqiwu }}</td>
										<td>{{ itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].rateqiwu / 100 | number:2 }}</td>
										<td>{{ itemtms[targetLanguage.id][0].sourceqiwu }}</td>
										<td>{{ (itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].rateqiwu / 100) * itemtms[targetLanguage.id][0].sourceqiwu | number:2 }}</td>
									</tr>
									<tr>
										<td>50%-74%</td>
										<td>{{ itemtms[targetLanguage.id][0].ratewushi }}</td>
										<td>{{ itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].ratewushi / 100 | number:2 }}</td>
										<td>{{ itemtms[targetLanguage.id][0].sourcewushi }}</td>
										<td>{{ (itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].ratewushi / 100) * itemtms[targetLanguage.id][0].sourcewushi | number:2 }}</td>
									</tr>
									<tr>
										<td>No Match</td>
										<td>{{ itemtms[targetLanguage.id][0].ratenomatch }}</td>
										<td>{{ itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].ratenomatch / 100 | number:2 }}</td>
										<td>{{ itemtms[targetLanguage.id][0].sourcenomatch }}</td>
										<td>{{ (itemtms[targetLanguage.id][0].rate_tmp * itemtms[targetLanguage.id][0].ratenomatch / 100) * itemtms[targetLanguage.id][0].sourcenomatch | number:2 }}</td>
									</tr>
									<tr>
										<td colspan="4" align="right"><strong>Total</strong></td>
										<td class="text-info">{{ itemtms[targetLanguage.id][0].total }}</td>
									</tr>
									</tbody>
								</table>
							</div>
						</div>
					</td>
				</tr>
				<tr ng-show="hasTypeTranslationNoTM()" ng-repeat = "itermnotmsnew in itermnotmsnews[targetLanguage.id]">
					
					<td><div><strong> {{ itermnotmsnew.name }} </strong> - <span class="text-navy"> Translation (No TM)</span></div></td>
					<td>{{ itermnotmsnew.unit }}</td>
					<td>{{ itermnotmsnew.rate }}</td>
					<td>{{ itermnotmsnew.quantity }}</td>
					<td>{{ itermnotmsnew.total }}</td>
				</tr>
				<tr ng-show="hasTypeDesktopPublishingMac()" ng-repeat = "itermdtpmac in itermdtpmacs[targetLanguage.id]">
					<td><div><strong> {{ itermdtpmac.name }}</strong> - <span class="text-info">DTP <i class="fa fa-apple"></i></span></div></td>
					<td>{{ itermdtpmac.unit }}</td>
					<td>{{ itermdtpmac.rate }}</td>
					<td>{{ itermdtpmac.quantity }}</td>
					<td>{{ itermdtpmac.total }}</td>
				</tr>
				<tr ng-show="hasTypeDesktopPublishingWin()" ng-repeat = "itermdtppc in itermdtppcs[targetLanguage.id]">
					<td><div><strong> {{ itermdtppc.name }}</strong> - <span class="text-info">DTP <i class="fa fa-windows"></i></span></div></td>
					<td>{{ itermdtppc.unit }}</td>
					<td>{{ itermdtppc.rate }}</td>
					<td>{{ itermdtppc.quantity }}</td>
					<td>{{ itermdtppc.total }}</td>
				</tr>
				<tr ng-show="hasTypeDesktopPublishingEngineer()" ng-repeat = "itermengineering in itermengineerings[targetLanguage.id]">
					<td><div><strong> {{ itermengineering.name }}</strong> - <span class="text-info">Engineering </span></div></td>
					<td>{{ itermengineering.unit }}</td>
					<td>{{ itermengineering.rate }}</td>
					<td>{{ itermengineering.quantity }}</td>
					<td>{{ itermengineering.total }}</td>
				</tr>
				<tr ng-show="interpreting.id > 0" ng-repeat = "iterminterpreting in iterminterpretings[targetLanguage.id]">
					<td><div><strong> {{ iterminterpreting.name }}</strong> - <span class="text-info"> Interpreting </span></div></td>
					<td>{{ iterminterpreting.unit }}</td>
					<td>{{ iterminterpreting.rate }}</td>
					<td>{{ iterminterpreting.quantity }}</td>
					<td>{{ iterminterpreting.total }}</td>
				</tr>
				
				</tbody>
			</table>
		</div><!-- /table-responsive -->
		<table class="table invoice-total">
			<tbody>
			<tr>
				<td><strong>Sub Total :</strong></td>
				<td>{{ subtotal }}</td>
			</tr>
			<tr>
				<td><strong>(-) Discount :</strong></td>
				<td><span class="text-danger"><strong>-</strong></span> {{currency}} {{ project.discount }}</td>
			</tr>
			<tr>
				<td><strong>TAX ({{ project.tax }} %):</strong></td>
				<td>{{ tax }}</td>
			</tr>
			<tr>
				<td><strong>TOTAL :</strong></td>
				<td>{{ total }}</td>
			</tr>
			</tbody>
		</table>
		<!-- if the client is uncontracted, then "make a payment" will show, if client type is "contracted", then dont show "make a payment" instead of "accept the quote" after accept, the project status changed from quoted to ordered -->
		<div class="hr-line-dashed"></div>
		<div class="m-t">
            <h2 class="text-center text-danger">Due Date: {{  DateFormatter.format(invoice.dueDate) }}</h2>
            <br>
			
                                                    <div class="row">
                                                        <div class="col-xs-6">
                                                            <dl class="dl-horizontal">
                                                                <dt><h4>Bank Details</h4></dt><dd></dd>
                                                                <dt>Company Name:</dt> <dd>{{ companyinfo1.name }}</dd>
                                                                <dt>Bank Name:</dt> <dd>{{ bankinfo1.name }}</dd>
                                                                <dt>Bank Address:</dt> <dd>{{ bankinfo1.address }}, {{ bankinfo1.city }}, {{ bankinfo1.country }}</dd>
                                                                <dt>Account Number:</dt> <dd>{{ bankinfo1.accountNo }}</dd>
                                                                <dt>Swift Code:</dt> <dd>{{ bankinfo1.swift }}</dd>
                                                            </dl>
                                                        </div>
                                                        <div class="col-xs-6">
                                                            <dl class="dl-horizontal">
                                                                <dt><h4>Other Payment Methods</h4></dt><dd></dd>
                                                                <dt>Paypal:</dt> <dd>payments@papertask.com</dd>
                                                                <dt>Alipay:</dt> <dd>payments@papertask.com</dd>
                                                            </dl>
                                                        </div>
                                                    </div>
                                                    <br><br>
                                                    <h2 class="text-center"><em>Thank you for your business!</em></h2>
                                                </div>

		</div>
	</div>
	<script>if(typeof(angular) != 'undefined' && typeof(angularApp) == 'undefined'){
        var angularApp = angularApp || angular.module('project', []);
    }</script>

</body>
</html>



