<?php $this->headTitle($this->translate('Request a Quote','Admin')) ?>


<!-- Le styles -->
<?php $this->headLink()
	->prependStylesheet($this->basePath() . '/v2/css/plugins/select2/select2.min.css')
	->prependStylesheet($this->basePath() . '/v2/css/plugins/footable/footable.core.css')
	->prependStylesheet($this->basePath() . '/v2/css/plugins/jquery-fileupload/jquery.fileupload.css');
?>

<!-- Scripts -->
<?php  $this->headScript()
    ->prependFile($this->basePath() . '/v2/js/admin/project/order-translation.js')
   ->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/v2/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload']);")
    ->prependFile($this->basePath() . '/v2/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/summernote/summernote.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/select2/select2.full.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/validate/jquery.validate.min.js')
	->prependFile($this->basePath() . '/v2/js/plugins/jquery-fileupload/jquery.ui.widget.js')
	->prependFile($this->basePath() . '/v2/js/plugins/jquery-fileupload/jquery.iframe-transport.js')
	->prependFile($this->basePath() . '/v2/js/plugins/jquery-fileupload/jquery.fileupload.js')
	->prependFile($this->basePath() . '/v2/js/plugins/jquery-fileupload/jquery.fileupload-validate.js')
	->prependFile($this->basePath() . '/v2/js/plugins/footable/footable.all.min.js');

?>


<?php
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>

<style type="text/css">
        .wizard > .content {
            min-height: 1000px;
        }
        .note-editor {
            height: 150px;
        }

        .nav-pills>li.active>a, .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus {
            color: #fff;
            background-color: #19aa8d;
        }

        .nav-pills>li.active>a, .nav-pills>li.active>a:hover, .nav-pills>li.active>a:focus {
            background-color: #19aa8d;
        }
        .top-navigation .nav > li.active > a {
        	color: #fff;
        }
        .nav > li.active {
            border-left: 4px solid #19aa8d;
            background: #19aa8d;
        }
		.tabs-container .nav-tabs > li.active > a, .tabs-container .nav-tabs > li.active > a:hover, .tabs-container .nav-tabs > li.active > a:focus {
			    color: #555555;
		}
		.top-navigation .nav > li.active {
		    background: none;
		    border: none;
		}

		.select2-container .select2-selection--single {
		    height: 38px;
		        font-size: 16px;
		}
		.select2-container--default .select2-selection--single .select2-selection__rendered {
		    line-height: 32px;
		}
    </style>


    <div class="animate fadeInUp">
        <div class="row">
            <div class="col-lg-12">
              <form id="form" action="#" class="wizard-big" ng-controller="OrderTranslationController" novalidate >

                  <div class=" form-group">
                    <div class="col-md-12">
                        <ul class="nav nav-pills nav-justified thumbnail setup-panel">
                            <li class="active"><a href="#step-1">
                                <h1 class="list-group-item-heading"><?php echo $this->translate('Step 1','Admin'); ?></h1>
                                <p class="list-group-item-text" style="font-size: 18px;"><?php echo $this->translate('Upload file(s)','Admin'); ?></p>
                            </a></li>
                            <li class="disabled"><a href="#step-2">
                                <h1 class="list-group-item-heading"><?php echo $this->translate('Step 2','Admin'); ?></h1>
                                <p class="list-group-item-text" style="font-size: 18px;"><?php echo $this->translate('Languages and Quality','Admin'); ?></p>
                            </a></li>
                        </ul>
                    </div>
                  </div>                                  
                     <?php include "needquote/step1.phtml" ?>                                                                 
                     <?php include "needquote/step2.phtml" ?>                                        

              </form>
            </div>

        </div>
    </div>


   <script>
      $(document).ready(function() {
          
          var navListItems = $('ul.setup-panel li a'),
              allWells = $('.setup-content');

          allWells.hide();

          navListItems.click(function(e)
          {
              e.preventDefault();
              var $target = $($(this).attr('href')),
                  $item = $(this).closest('li');
              
              if (!$item.hasClass('disabled')) {
                  navListItems.closest('li').removeClass('active');
                  $item.addClass('active');
                  allWells.hide();
                  $target.show();
              }
          });

          $(".sLanguage").select2();
          $(".tLanguage").select2();
          $('.footable').footable();
                    
          $('ul.setup-panel li.active a').trigger('click');
          
          // DEMO ONLY //
          $('#activate-step-2').on('click', function(e) {
              $('ul.setup-panel li:eq(1)').removeClass('disabled');
              $('ul.setup-panel li a[href="#step-2"]').trigger('click');
          });    

          /*
          $('#activate-step-3').on('click', function(e) {
              $('ul.setup-panel li a[href="#step-3"]').trigger('click');
              $(this).remove();
          }); 
			
			*/
			
          $('#activate-step-4').on('click', function(e) {
              $('ul.setup-panel li a[href="#step-4"]').trigger('click');
          }); 
          
          $('#activate-step-1').on('click', function(e) {
              $('ul.setup-panel li a[href="#step-1"]').trigger('click');             
          }); 
      });

      function StrDate(dateIn) {
    	   var yyyy = dateIn.getFullYear();
    	   var mm = dateIn.getMonth()+1; // getMonth() is zero-based
    	   var dd  = dateIn.getDate();
    	   var hh = dateIn.getHours();
    	   var mi = dateIn.getMinutes();
    	   var ss = dateIn.getSeconds();
    	   return String(yyyy +'-'+ mm +'-'+ dd + ' '+ hh +':'+ mi + ':' + ss); // Leading zeros for mm and dd
    	}

        jQuery.validator.setDefaults({
		  debug: false,
		  success: "valid"
		});
		$( "#form" ).validate();

 </script>


 

    