<?php $this->headTitle($this->translate('Add New Project')) ?>
<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/datetimepicker/DateTimePicker.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/summernote/summernote-bs3.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/summernote/summernote.css')
   // ->prependStylesheet($this->basePath() . '/v2/css/plugins/multiselect/bootstrap-multiselect.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/steps/jquery.steps.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/chosen/chosen.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/datapicker/datepicker3.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/select2/select2.min.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/footable/footable.core.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/v2/js/plugins/datetimepicker/DateTimePicker.js')
    ->prependFile($this->basePath() . '/v2/js/admin/project/create-project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/v2/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/v2/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload']);")
    ->prependFile($this->basePath() . '/v2/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/summernote/summernote.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/datapicker/bootstrap-datepicker.js')
//    ->prependFile($this->basePath() . '/v2/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/chosen/chosen.jquery.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/select2/select2.full.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/footable/footable.all.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/steps/jquery.steps.min.js');
?>
<?php
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>

<style>
    .form-group label.btn-outline {
        margin-right: 0.3em;
    }
    input[readonly][data-field=datetime]{
        background-color: #fff;
    }
    input[readonly][data-field=datetime]:hover,
    i.fa.fa-calendar:hover{
        cursor: pointer;
    }
</style>

<script>
    $(document).ready(function() {

        $('.footable').footable();
        $('.summernote').summernote();
        //$(".sLanguage").select2();
		//$(".tLanguages").select2();
		$(".sLanguage").select2({
		  placeholder: "Select language"
		});
		$(".tLanguages").select2({
		  placeholder: "Select language"
		});
        
        $('#ordered_date .input-group.date').datepicker({
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            autoclose: true
        });
        $('#due_date .input-group.date').datepicker({
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            autoclose: true
        });
    });

</script>


<div class="row">
    <div class="col-lg-12">
        <div class="ibox">
            <div class="ibox-title">
                <h5><i class="fa fa-archive"></i> Create Project</h5>
            </div>
            <div class="ibox-content">
                <form id="form" action="#" class="wizard-big" ng-controller="CreateProjectController">
                    <h1>Project Information</h1>
                    <fieldset>
                        <?php include "new/type_and_status.phtml" ?>
                        <?php include "new/files.phtml" ?>
                        <?php include "new/languages.phtml" ?>
                        <?php include "new/info.phtml" ?>
                    </fieldset>
                    <h1>Order Information</h1>
                    <fieldset>
                        <?php include "new/service_and_duration.phtml" ?>
                        <?php include "new/order_information.phtml" ?>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
<div ng-controller="ModalController" id="modalContainer">
    <?php include "new/modal/interpreting_modal.phtml" ?>
    <?php include "new/modal/engineering_modal.phtml" ?>
    <?php include "new/modal/desktop_publishing_modal.phtml" ?>
    <?php include "new/modal/translation_modal.phtml" ?>
</div>

<script>
    $(document).ready(function(){
        $('.dtbox').DateTimePicker();

        // trigger datetime picker when click to calendar icon
        // TODO: this is not working
        $('i.fa.fa-calendar').on('click', function(e){
            console.log('clicked');
            //e.preventDefault();
			//console.log($(this).parents('.input-group').find('input[readonly]'));

            //$(this).parents('.input-group').find('input[readonly]').click();
        });
    });
</script>
