<?php $this->headTitle($this->translate('Order  Translation')) ?>


<!-- Le styles -->
<?php $this->headLink()
//   ->prependStylesheet($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.css')
//  ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css')
//   ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
//  ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
//  ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
->prependStylesheet($this->basePath() . '/css/plugins/jquery-fileupload/jquery.fileupload.css');
?>

<!-- Scripts -->
<?php  $this->headScript()
//  ->prependFile($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.js')
->prependFile($this->basePath() . '/js/admin/project/order-translation-non-contract.js')
->prependFile($this->basePath() . '/js/admin/common/angular/service/project.js')
->prependFile($this->basePath() . '/js/admin/common/angular/CurrentUser.js')
//->prependFile($this->basePath() . '/js/admin/angular-steps.js')
->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload']);")
->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
//  ->prependFile($this->basePath() . '/js/plugins/datapicker/bootstrap-datepicker.js')
//  ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
//  ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
//  ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
//  ->prependFile($this->basePath() . '/js/inspinia.js');
 

->prependFile($this->basePath() . '/js/inspinia.js')
->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
->prependFile($this->basePath() . '/js/plugins/jquery-fileupload/jquery.ui.widget.js')
->prependFile($this->basePath() . '/js/plugins/jquery-fileupload/jquery.iframe-transport.js')
->prependFile($this->basePath() . '/js/plugins/jquery-fileupload/jquery.fileupload.js')
->prependFile($this->basePath() . '/js/plugins/jquery-fileupload/jquery.fileupload-validate.js');

?>

<?php
$this->inlineScript()
->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
		");
?>

<style type="text/css">
.wizard>.content {
	min-height: 1000px;
}

.note-editor {
	height: 150px;
}

.nav-pills>li.active>a,.nav-pills>li.active>a:hover,.nav-pills>li.active>a:focus
	{
	background-color: #19aa8d;
}

.nav>li.active {
	border-left: 4px solid #19aa8d;
	background: #19aa8d;
}
</style>


<div class="row">
	<div class="col-lg-12">
		<div class="wrapper wrapper-content animated">
			<div class="row">
				<div class="col-lg-8">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<h5>
								<i class="fa fa-files-o"></i> Order A Translation
							</h5>
						</div>
						<div class="ibox-content">
							<div class="row">
								<div class="col-lg-12">
									<form class="form-horizontal" action="#" role="form" class="wizard-big" ng-controller="OrderTranslationController">

										<div class=" form-group">
											<div class="col-md-12">
												<ul
													class="nav nav-pills nav-justified thumbnail setup-panel">
													<li class="active"><a href="#step-1">
															<h4 class="list-group-item-heading">Step 1</h4>
															<p class="list-group-item-text">Upload the file(s)</p>
													</a></li>
													<li class="disabled"><a href="#step-2">
															<h4 class="list-group-item-heading">Step 2</h4>
															<p class="list-group-item-text">Select Languages and
																Quality</p>
													</a></li>
													<li class="disabled"><a href="#step-3">
															<h4 class="list-group-item-heading">Step 3</h4>
															<p class="list-group-item-text">Confirm Your Information</p>
													</a></li>
												</ul>
											</div>
										</div>

										<?php include "ordertranslationnoncontract/step1.phtml"?>
										<?php include "ordertranslationnoncontract/step2.phtml"?>
										<?php include "ordertranslationnoncontract/step3.phtml"?>
										
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
				<?php include "ordertranslationnoncontract/orderinfo.phtml"?>
				
			</div>

		</div>
	</div>
</div>

<script>
      $(document).ready(function() {
          
          var navListItems = $('ul.setup-panel li a'),
              allWells = $('.setup-content');

          allWells.hide();

          navListItems.click(function(e)
          {
              e.preventDefault();
              var $target = $($(this).attr('href')),
                  $item = $(this).closest('li');
              
              if (!$item.hasClass('disabled')) {
                  navListItems.closest('li').removeClass('active');
                  $item.addClass('active');
                  allWells.hide();
                  $target.show();
              }
          });
          
          $('ul.setup-panel li.active a').trigger('click');
          
          // DEMO ONLY //
          $('#activate-step-2').on('click', function(e) {
              $('ul.setup-panel li:eq(1)').removeClass('disabled');
              $('ul.setup-panel li a[href="#step-2"]').trigger('click');
              $(this).remove();
          })    
          $('#activate-step-3').on('click', function(e) {
              $('ul.setup-panel li:eq(2)').removeClass('disabled');
              $('ul.setup-panel li a[href="#step-3"]').trigger('click');
              $(this).remove();
          })    
      });
    </script>




