<?php $this->headTitle($this->translate('Projects list')) ?>
<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.js')
    ->prependFile($this->basePath() . '/js/admin/project/quotes.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload', 'ui.bootstrap']);")
    ->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-tpls-0.11.2.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-0.11.2.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js')
?>

<?php
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>
<div class="row">
<div class="col-lg-12">
<div class="wrapper wrapper-content animate fadeInUp">

<div class="ibox">
<div class="ibox-title">
    <h5> Projects List</h5>
    <div class="ibox-tools">
        <a href="<?php echo $this->url('admin', ['controller' => 'project', 'action' => 'new']) ?>" class="btn btn-primary btn-xs">Create new project</a>
    </div>
</div>
<div class="ibox-content" ng-controller="ProjectIndexController">
    <div ng-controller="ItemListController">
        <div class="row m-b-sm m-t-sm">
            <div class="col-md-1">
                <button type="button" id="loading-example-btn" class="btn btn-white btn-sm"
                        ng-click="refresh()"><i class="fa fa-refresh"></i> Refresh</button>
            </div>
            <div class="col-md-9">
                <div class="input-group">
                    <input type="text" placeholder="Search" class="input-sm form-control" ng-model="search.q">
                    <span class="input-group-btn">
                    <button type="button" class="btn btn-sm btn-primary" ng-click="search()"> Search</button>
                      </span>
                </div>
            </div>
            <div class="col-md-2">
                <a data-toggle="collapse" href="#adv_search" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Advance Search</a>
            </div>
        </div>
        <div>
            <div class="row">
                <div class="col-lg-12">
                    <div id="adv_search" class="panel-collapse collapse faq-answer">
                        <?php include "client/search-quote.phtml" ?>
                    </div>
                </div>
            </div>
            <div class="hr-line-dashed"></div>
            <div id="projectsList">
                <div class="project-list">
                    <table class="table table-hover">
                        <tbody>
                        <tr ng-repeat="project in items">
                            <td class="project-status">
                                <span class="label label-warning" ng-if="project.number">{{ project.number }}</span>
                                <span class="label label-{{ ProjectStatus.get(project.status).decorator }}"
                                    >{{ ProjectStatus.get(project.status).name }}</span>
                            </td>
                            <td class="project-status">
                                <span class="btn btn-outline btn-{{ ProjectServiceLevel.get(project.serviceLevel).decorator }}
                                btn-sm">{{ ProjectServiceLevel.get(project.serviceLevel).name }}</span>
                            </td>
                            <td class="project-title">
                                <strong><?php echo $this->translate('Contract with') ?> {{ project.client.company.name }}</strong>
                                <br/>
                                <div class="tooltip-demo">
                                    <span ng-repeat="type in project.types">
                                        <code {{ TypeList.getTypeAttrs(type) }}>{{ type.name_short }}</code>
                                    </span>
                                </div>
                            </td>
                            <td class="project-title">
                                <span class="">{{ project.quote_no }}</span>
                                <br/>
                                <small>Quote Date: {{ DateFormatter.short(project.startDate) }}</small>
                            </td>
                            <td class="project-status">
                                <strong class="text-danger">{{ project.currency }}  {{ project.total_tmp | number:2 }}</strong>
                            </td>
                            <td class="project-actions">
								<a href="#" class="btn btn-primary btn-sm"
									ng-click="quoteAccepted(project)"><i class="fa fa-check-square-o"></i> Accept </a>

                                <a href="#" class="btn btn-white btn-sm"
                                   ng-click="goToQuote(project)"><i class="fa fa-folder"></i> View </a>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>

                <div class="btn-group text-right">
                    <pagination total-items="pages.totalItemCount" ng-model="page" max-size="maxSize"
                                class="pagination-sm" boundary-links="true" ng-change="pageChanged()"></pagination>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
</div>