<h1>Basic Information</h1>
<fieldset>
    <div class="panel panel-primary">
        <div class="panel-body">
			<div class="row">
				<div class="col-lg-6">
					<div class="form-group">
						<label>Email *</label>
						<input name="email" ng-model="freelancer.email" ng-disabled="freelancer.id"
						type="email" class="form-control required" required />
					</div>
					<div class="hr-line-dashed"></div>
					<div class="form-group">
						<label>First name *</label>
						<input id="name" name="name" type="text" ng-model="freelancer.firstName"
							   class="form-control required" />
					</div>
					<div class="hr-line-dashed"></div>
					<div class="form-group">
						<label>Gender *</label>
						<div data-toggle="buttons">
							<label class="btn btn-outline btn-primary btn-sm
														{{freelancer.gender ? 'active' : ''}}"
								   ng-click="freelancer.gender=true">
								<input type="radio" name="gender" value="1" /> Male
							</label>
							&nbsp;
							<label class="btn btn-outline btn-primary btn-sm
														{{!freelancer.gender ? 'active' : ''}}"
								   ng-click="freelancer.gender=false">
								<input type="radio" name="gender" value="0" /> Female
							</label>
						</div>
					</div>
					<div class="hr-line-dashed"></div>
					<div class="form-group">
						<label>City *</label>
						<input id="city" name="city" ng-model="freelancer.city" type="text"
							   class="form-control required" />
					</div>
				</div>
				<div class="col-lg-6">
					<div class="form-group">
						<label>User name *</label>
						<input id="username" name="username" type="text"
							   class="form-control" />
					</div>
					<div class="hr-line-dashed"></div>
					<div class="form-group">
						<label>Last name *</label>
						<input id="surname" name="surname" type="text" ng-model="freelancer.lastName"
							   class="form-control required" />
					</div>
					<div class="hr-line-dashed"></div>
					<div class="form-group">
						<label>Phone *</label>
						<input id="phone" name="phone" type="phone" ng-model="freelancer.phone"
							   class="form-control required" />
					</div>
					<div class="hr-line-dashed"></div>
					<div class="form-group">
						<label>Country *</label>
						<select class="form-control required" id="country" name="country" required
								ng-model="freelancer.country" ng-options="country.name for country in countries">
								
						</select>
					</div>
				</div>
			</div>
			
        </div>
    </div>
</fieldset>