<h1>Languages/Skills/Prices</h1>
<fieldset>

    <div class="panel panel-info">
        <div class="panel-body">
            <h2><i class="fa fa-desktop"></i>&nbsp; Currency</h2>
            <br />
            <?php include __DIR__ . "/../../user/currency-setup.phtml"; ?>
        </div>
    </div>
    <div class="panel panel-primary" ng-show="translation == 1">
        <div class="panel-body">
            <h2><i class="fa fa-coffee"></i>&nbsp; Translation</h2>
            <div class="hr-line-dashed"></div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>Specialisms * &nbsp; </label>
                        <select ng-class="{ required : translation == 1}" class="form-control multiselect" multiple="multiple"
                                ng-model="freelancer.TranslationSpecialisms"
                                ng-options="t.name for t in specialisms"
                                name="userTranslationSpecialisms" id="userTranslationSpecialisms">
                        </select>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>CAT Tools * &nbsp; </label>
                        <select ng-class="{ required : translation == 1}" class="form-control multiselect" multiple="multiple"
                                ng-model="freelancer.TranslationCatTools"
                                ng-options="t.name for t in catTools"
                                name="userTranslationCatTools" id="userTranslationCatTools">
                        </select>
                    </div>
                </div>
            </div>
            
			
			<div class="table-responsive">
				<table class="table table-striped table-bordered">
					<thead>
					<tr>
						<th>#</th>
						<th>Source Language </th>
						<th>Target Language </th>
						<th>Translation Price</th>
						<th>Action</th>
					</tr>
					</thead>
					<tbody>
					<tr ng-repeat="translationPrice in translationPrices">
						<td>{{$index + 1}}</td>
						<td>{{translationPrice.sourceLanguage.name}}</td>
						<td>{{translationPrice.targetLanguage.name}}</td>
						<td>{{translationPrice.price | number:2 }}</td>
						<td>							
							<a href="#" ng-click="editTranslationPrice($index, tp.id)" onclick="return false;">
			                	<i class="fa fa-edit"></i>
			                </a>
			            	<a href="#" ng-click="deleteTranslationPrice($index, tp.id)" onclick="return false;">
			                	<i class="fa fa-trash-o text-danger"></i>
			                </a>
							
							
						</td>
					</tr>
					</tbody>
				</table>
			</div>
			<div class="text-center">
				<a data-toggle="modal" class="btn btn-outline btn-primary" href="#modal-translation">Add Language pairs and prices</a>
			</div>
			<div class="hr-line-dashed"></div>

			
        </div>
    </div>

    <div class="panel panel-info" ng-show="desktop_publish == 1">
        <div class="panel-body">
            <h2><i class="fa fa-desktop"></i>&nbsp; Desktop Publishing</h2>
            <div class="hr-line-dashed"></div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>Operating System * &nbsp; </label>
                        <select ng-class="{ required : desktop_publish == 1}" class="form-control multiselect" multiple="multiple"
                                ng-model="freelancer.DesktopOperatingSystems"
                                ng-options="t.name for t in operatingSystems"
                                name="userDesktopOperatingSystems" id="userDesktopOperatingSystems">
                        </select>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label>CAT Tools * &nbsp; </label>
                        <select ng-class="{ required : desktop_publish == 1}" class="form-control multiselect" multiple="multiple"
                                ng-model="freelancer.DesktopCatTools"
                                ng-options="t.name for t in catTools"
                                name="userDesktopCatTools" id="userDesktopCatTools">
                        </select>
                    </div>
                </div>
            </div>
            
			<div class="table-responsive">
				<table class="table table-striped">
					<thead>
					<tr>
						<th>#</th>
						<th>Languages </th>
						<th>DTP software </th>
						<th>Price/Page <i class="fa fa-apple"></th>
						<th>Price/Page <i class="fa fa-windows"></i></th>
						<th>Price/Hour <i class="fa fa-apple"></th>
						<th>Price/Hour <i class="fa fa-windows"></i></th>
						<th>Action</th>
					</tr>
					</thead>
					<tbody>
					<tr ng-repeat="desktopPrice in desktopPrices">
						<td>{{$index + 1}}</td>
						<td>{{desktopPrice.language.name}}</td>
						<td>{{desktopPrice.software.name}}</td>
						<td>{{desktopPrice.priceMac | number:2 }}</td>
						<td>{{desktopPrice.pricePc | number:2 }}</td>
						<td>{{desktopPrice.priceHourMac | number:2 }}</td>
						<td>{{desktopPrice.priceHourPc | number:2 }}</td>
						<td>
						
						<a data-toggle="modal" href="#modal-dtp" ng-click="editDesktopPrice($index)" onclick="return false;"><i class="fa fa-edit"></i></a>
			            <a href="#" ng-click="deleteDesktopPrice($index, desktopPrice.id)" onClick="return false;"><i class="fa fa-trash-o text-danger"></i></a>
						</td>
					</tr>
					</tbody>
				</table>
			</div>
			<div class="text-center">
				<a data-toggle="modal" class="btn btn-outline btn-info" href="#modal-dtp">Add DTP prices</a>
			</div>
			<div class="hr-line-dashed"></div>
			
			
        </div>
    </div>

    <div class="panel panel-success" ng-show="interpreting == 1">
        <div class="panel-body">
            <h2><i class="fa fa-comments-o"></i>&nbsp; Interpreting</h2>
            <div class="hr-line-dashed"></div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="form-group">
                        <label>Specialisms * &nbsp; </label>
                        <select ng-class="{ required : interpreting == 1}" class="form-control multiselect" multiple="multiple"
                                ng-model="freelancer.InterpretingSpecialisms"
                                ng-options="t.name for t in specialisms"
                                name="userInterpretingSpecialisms" id="userInterpretingSpecialisms">
                        </select>
                    </div>
                </div>
            </div>
            
			<div class="table-responsive">
				<table class="table table-striped">
					<thead>
					<tr>
						<th>#</th>
						<th>Source Language </th>
						<th>Target Language </th>
						<th>Interpreting Service</th>
						<th>Price/Day</th>
						<th>Price/half-Day</th>
						<th>Action</th>
					</tr>
					</thead>
					<tbody>
					<tr ng-repeat="interpretingPrice in interpretingPrices">
						<td>{{$index + 1}}</td>
						<td>{{interpretingPrice.sourceLanguage.name}}</td>
						<td>{{interpretingPrice.targetLanguage.name}}</td>
						<td>{{interpretingPrice.service.name}}</td>
						<td>{{interpretingPrice.priceDay | number:2}}</td>
						<td>{{interpretingPrice.priceHalfDay | number:2}}</td>
						<td>
			            	<a data-toggle="modal" href="#" ng-click="editInterpretingPrice($index);" onclick="return false;">
								<i class="fa fa-edit"></i>
							</a>
			            	<a href="#" ng-click="deleteInterpretingPrice($index, interpretingPrice.id)" onClick="return false;"><i class="fa fa-trash-o text-danger"></i></a>

						</td>
					</tr>
					</tbody>
				</table>
			</div>
			<div class="text-center">
				<a data-toggle="modal" class="btn btn-outline btn-success" href="#modal-interpreting">Add Interpreting prices</a>
			</div>
			<div class="hr-line-dashed"></div>
			
			
			
        </div>
    </div>
</fieldset>