<!-- Scripts -->
<?php
$this->headScript ()->prependFile ( $this->basePath () . '/v2/js/admin/employer/details.js' )
					->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
					->prependFile ( $this->basePath () . '/v2/js/admin/bootstrap-modal.js' )
					->prependScript ( "angularApp = angular.module('project', []);" )
					->prependFile ( $this->basePath () . '/v2/js/plugins/summernote/summernote.min.js' )
					->prependFile ( $this->basePath () . '/v2/js/plugins/validate/jquery.validate.min.js' )
					->prependFile ( $this->basePath () . '/v2/js/plugins/steps/jquery.steps.min.js' );
?>
<?php
$this->inlineScript()
    ->prependScript("
        var USER_ID = '" . $user['id'] . "';
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
		var LANG_CODE = '" . $this->lang_code . "';
		
    ");
?>

<style>
	.top-navigation .nav > li.active {
	    background: none;
	    border: none;
	}
</style>

<div class="row animated fadeInRight" ng-controller="PapertaskEmployerDetailController" ng-init="init()">
	<div class="col-md-4">
		<div class="ibox">
			<div class="ibox-title">
				<h5>{{employer.username}}</h5>
				<div class="ibox-tools">				
					<span ng-show="userInfo.isActive == '1'" class="label label-primary"><?php echo $this->translate('Active') ?></span>
					<span ng-show="userInfo.isActive == '0'" class="label label-default"><?php echo $this->translate('Unactive') ?></span>
				</div>
			</div>

			<div class="ibox-content profile-content">
				<p><i class="fa fa-user"></i> &nbsp; 
                {{userInfo.lastName}}, {{userInfo.firstName}} &nbsp; 
                <i ng-show="userInfo.gender == '0'" class="fa fa-male"></i>
                <i ng-show="userInfo.gender == '1'" class="fa fa-female"></i>
                </p>
				<p><i class="fa fa-envelope"></i> &nbsp; {{userInfo.email}}</p>
                <p><i class="fa fa-tag"></i> &nbsp; {{userInfo.alias}}</p>
				<p><i class="fa fa-phone"></i> &nbsp; {{userInfo.phone}}</p>
				<p><i class="fa fa-briefcase"></i> &nbsp; {{employer.position}}</p>
				<p><i class="fa fa-building"></i> &nbsp; {{employer.company.name}}</p>
				<p><i class="fa fa-map-marker"></i> &nbsp; {{userInfo.city}}, {{userInfo.country.name}}</p>
				<p><i class="fa fa-link"></i> &nbsp; {{employer.company.website}}</p>
				<form role="form" class="form-inline">
                    <div class="form-group">
                        <input ng-model="password" type="password"
                               placeholder="<?php echo $this->translate('Reset password') ?>"
                               class="form-control required" required>
                    </div>
                    <button ng-click="resetPassword()" class="btn btn-danger" type="submit">
                        <?php echo $this->translate('Reset') ?></button>
                    <p ng-show="passwordChanged==1" class="text-success">
                        <?php echo $this->translate('Password changed.') ?></p>
                </form>
				<div class="hr-line-dashed"></div>
				<p><span class="label label-info">PM</span> {{employer.pm.name}} &nbsp;<span class="label label-info">Sales</span> {{employer.sales.name}}</p>
				<div class="hr-line-dashed"></div>
				<h4><?php echo $this->translate('Client Type') ?> </h4>
				<div class="row file-manager">
					<ul class="tag-list" style="padding: 0">
						<li>
                            <a ng-show="employer.contracted == '1'"><?php echo $this->translate('Contracted') ?></a>
                            <a ng-show="employer.contracted == '0'"><?php echo $this->translate('UnContracted') ?></a>
                        </li>
					</ul>
				</div>
				<div class="hr-line-dashed"></div>
				<h4><?php echo $this->translate('Default Service Level') ?> </h4>
				<div class="row file-manager">
					<ul class="tag-list" style="padding: 0">
						<li ng-show="employer.defaultServiceLevel == '1'"><a>Professional</a></li>
                        <li ng-show="employer.defaultServiceLevel == '2'"><a>Business</a></li>
                        <li ng-show="employer.defaultServiceLevel == '3'"><a>Premium</a></li>
					</ul>
				</div>
				<div class="hr-line-dashed"></div>
				<h4><?php echo $this->translate('Comments of PaperTask') ?></h4>
				<div id="objNote"></div>
				<a href="<?php echo $this->url('admin', ['controller'=>'employer', 'action'=>'edit']) ?>?userId=<?php echo $user['id'];?>"
               class="btn btn-primary btn-block"><i class="fa fa-paste"></i> <?php echo $this->translate('Edit') ?></a>
			   
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="panel blank-panel">
			<div class="panel-heading">
				<div class="panel-options">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#tab-1"><?php echo $this->translate('Service Prices') ?></a></li>
						<li class=""><a data-toggle="tab" href="#tab-2"><?php echo $this->translate('Resource Pool') ?></a></li>
						<li class=""><a data-toggle="tab" href="#tab-3"><?php echo $this->translate('Projects') ?></a></li>
					</ul>
				</div>
			</div>

			<div class="panel-body">
				<div class="tab-content">
					<div id="tab-1" class="tab-pane active">
						<div class="ibox float-e-margins">
							<div class="ibox-title">
								<h3><i class="fa fa-coffee"></i> <?php echo $this->translate('Translation') ?></h3>
							</div>
							<div class="ibox-content">
								<h4><?php echo $this->translate('Languages and Price') ?> </h4>
								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
										  <tr>
											<th><?php echo $this->translate('TM Template') ?></th>
											<th><?php echo $this->translate('Repetitions') ?></th>
											<th>100%</th>
											<th>95% - 99%</th>
											<th>85% - 94%</th>
											<th>75% - 84%</th>
											<th>50% - 74%</th>
											<th><?php echo $this->translate('No Match') ?></th>
										  </tr>
										</thead>
										<tbody>
										  <tr>
											<td>TM Rate</td>
											<td>{{tmRatios.repetitions}}%</td>
											<td>{{tmRatios.yibai}}%</td>
											<td>{{tmRatios.jiuwu}}%</td>
											<td>{{tmRatios.bawu}}%</td>
											<td>{{tmRatios.qiwu}}%</td>
											<td>{{tmRatios.wushi}}%</td>
											<td>{{tmRatios.nomatch}}%</td>
										  </tr>
										</tbody>
									  </table>
								  </div>

								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Source Language') ?> </th>
												<th><?php echo $this->translate('Target Language') ?> </th>
												<th><?php echo $this->translate('Translation Price') ?></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="translationPrice in translationPrices">
													<td>{{$index + 1}}</td>
													<td>{{translationPrice.sourceLanguage.name}}</td>
													<td>{{translationPrice.targetLanguage.name}}</td>
													<td class="text-info">
                                                        <strong > {{priceType}} {{translationPrice.price}} </strong>
                                                    </td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="ibox float-e-margins">
							<div class="ibox-title">
								<h3><i class="fa fa-desktop"></i> <?php echo $this->translate('Desktop Publishing') ?></h3>
							</div>
							<div class="ibox-content">
								<h4><?php echo $this->translate('Softwares and Price') ?> </h4>
								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Languages') ?> </th>
												<th><?php echo $this->translate('Software') ?> </th>
												<th><?php echo $this->translate('Page') ?> <i class="fa fa-apple"></th>
												<th><?php echo $this->translate('Page') ?> <i class="fa fa-windows"></i></th>
												<th><?php echo $this->translate('Hour') ?> <i class="fa fa-apple"></th>
												<th><?php echo $this->translate('Hour') ?> <i class="fa fa-windows"></i></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="dptPrice in dptPrices">
													<td>{{$index+1}}</td>
													<td>{{dptPrice.language.name}}</td>
													<td>{{dptPrice.software.name}}</td>
													<td class="text-info">
                                                        <strong><strong > {{priceType}} {{dptPrice.priceMac}} </strong>
                                                    </td>
													<td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.pricePc}} </strong>
                                                    </td>
                                                    <td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.priceHourMac}} </strong>
                                                    </td>
                                                    <td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.priceHourPc}} </strong>
                                                    </td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="ibox float-e-margins">
							<div class="ibox-title">
								<h3><i class="fa fa-gears"></i> <?php echo $this->translate('Engineering') ?></h3>
							</div>
							<div class="ibox-content">
								<h4><?php echo $this->translate('Categories and Price') ?> </h4>
								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th>Category </th>
												<th>Unit </th>
												<th>Price </th>
											</tr>
											</thead>
											<tbody>
											<tr ng-repeat="engineeringPrice in engineeringPices">
												<td>{{$index + 1}}</td>
												<td>{{engineeringPrice.engineeringcategory.category}}</td>
												<td>{{engineeringPrice.unit.name}}</td>
												<td class="text-info">
                                                    <strong>{{priceType}} {{engineeringPrice.price}}</strong>
                                                </td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="ibox float-e-margins">
							<div class="ibox-title">
								<h3><i class="fa fa-comments-o"></i> <?php echo $this->translate('Interpreting') ?></h3>
							</div>
							<div class="ibox-content">
								<h4>Languages and Price </h4>

								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Source Language') ?> </th>
												<th><?php echo $this->translate('Target Language') ?> </th>
												<th><?php echo $this->translate('Interpreting Service') ?></th>
												<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Day') ?></th>
												<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('half-Day') ?></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="interpretingPrice in interpretingPrices">
													<td>{{$index + 1}}</td>
													<td>{{interpretingPrice.sourceLanguage.name}}</td>
													<td>{{interpretingPrice.targetLanguage.name}}</td>
													<td>{{interpretingPrice.service.name}}</td>
													<td class="text-info"><strong>{{priceType}} {{interpretingPrice.priceDay}}</strong></td>
													<td class="text-info"><strong>{{priceType}} {{interpretingPrice.priceHalfDay}}</strong></td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div id="tab-2" class="tab-pane">
						<div class="ibox">
							<div class="ibox-title">
								<h5><?php echo $this->translate('Translators Pool') ?></h5>
							</div>
							<div class="ibox-content">
								<table class="table">
									<thead>
									<tr>
										<th>#</th>
										<th><?php echo $this->translate('Name') ?></th>
										<th><?php echo $this->translate('Type') ?></th>
										<th><?php echo $this->translate('Task Done') ?></th>
										<th></th>
									</tr>
									</thead>
									<tbody>
									<tr ng-repeat="translator in userInfo.translator_pool">
										<td>{{$index +1}}</td>
										<td><a href="">{{translator.firstName}}, {{translator.lastName}}</a></td>
										<td><i class="fa {{ResourceGroup.get(ResourceType.get(translator.freelancer.Resources[0]).resourceGroup).icon}}"> {{ResourceGroup.get(ResourceType.get(translator.freelancer.Resources[0]).resourceGroup).name}}</i></td>
										<td>{{translator.taskdone}}</td>
										<td><a href="" ng-click="removeResource(translator)"><i class="fa fa-trash-o text-danger"></i></a></td>
									</tr>
									
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<div id="tab-3" class="tab-pane">
						<div class="ibox">
							<div class="ibox-content">
								<div class="project-list">
									<table class="table table-hover">
										<tbody>
											<tr ng-repeat = "project in projects">
												<td class="project-status" width="1%">
													<span class="label label-{{ ProjectStatus.get(project.status).decorator }}"
															>{{ ProjectStatus.get(project.status).name }}</span>
												</td>
												<td class="project-title">
													<a href="#">{{project.id}}</a>
												</td>

												</td>
												<td class="project-title">
													<strong>{{project.reference}}</strong>
													<br />
													<small>{{ DateFormatter.short(project.startDate) }} - {{ DateFormatter.short(project.dueDate) }}</small>
												</td>
												<td class="project-title text-info">
													<strong>{{project.currency | uppercase}} {{project.total_tmp}}</strong>
												</td>
											</tr>
											
										</tbody>
									</table>
								</div>
								<div class="btn-group text-right">
									<button type="button" class="btn btn-white" ng-class="pages.previous?'':'disabled'" ng-click="onBtnPreviousClicked()"><i class="fa fa-chevron-left"></i></button>
									<button ng-repeat="page in pages.pagesInRange" class="btn btn-white" ng-class="page==pages.current?'active':''" ng-click="onBtnGoto(page-1)">{{page}}</button>
									<button type="button" class="btn btn-white"	ng-class="pages.next?'':'disabled'" ng-click="onBtnNextClicked()"><i class="fa fa-chevron-right"></i></button>						
			
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>

	</div>
</div>
 
<?php include "profile/modal.phtml" ?>