
<!-- Le styles -->
<?php
$this->headLink ()->prependStylesheet ( $this->basePath () . '/css/plugins/summernote/summernote-bs3.css' )
				  ->prependStylesheet ( $this->basePath () . '/css/plugins/summernote/summernote.css' )
?>

<!-- Scripts -->
<?php

$this->headScript ()->prependFile ( $this->basePath () . '/js/admin/employer/profile.js' )
					->prependFile ( $this->basePath () . '/js/admin/bootstrap-modal.js' )
					->prependScript ( "angularApp = angular.module('project', []);" )
					->prependFile ( $this->basePath () . '/js/plugins/summernote/summernote.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/validate/jquery.validate.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/pace/pace.min.js' )
					->prependFile ( $this->basePath () . '/js/inspinia.js' );
?>
<?php
$this->inlineScript()
    ->prependScript("
        var USER_ID = '" . $user['id'] . "';
        var EMPLOYER_ID = '';
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
    ");
?>
<style type="text/css">
.wizard-big.wizard>.content {
	min-height: 1200px;
}

.label {
	font-size: 15px;
}

h3 {
	font-size: 18px;
}

.float-e-margins .btn {
	margin-bottom: 0px;
}

.note-editor {
	height: 150px;
}
</style>

<div class="row" ng-controller="PapertaskEmployerProfileController" ng-init="init()" id="EmployerController">
	<div class="col-lg-12">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h3>
					<i class="fa fa-edit"></i> <?php echo $this->translate('Edit Client Profile') ?>
				</h3>
			</div>
			<div class="ibox-content">
				<form id="form" action="">
					<!-- Basic Information -->
					<div class="panel panel-primary">
						<div class="panel-heading">
							<i class="fa fa-info-circle"> <strong><?php echo $this->translate('Basic Information') ?></strong></i>
						</div>
						<div class="panel-body">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label><?php echo $this->translate('Email') ?> *</label>
										<input type="text" class="form-control " ng-model="userInfo.email" disabled>
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label><?php echo $this->translate('First name') ?> *</label> 
										<input id="firstname" name="firstname" type="text" ng-model="userInfo.firstName" class="form-control required">
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label><?php echo $this->translate('Gender') ?> *</label>
										<div data-toggle="buttons">
											<label class="btn btn-outline btn-primary btn-sm" ng-class="userInfo.gender == '0'?'active':''"  ng-click="setGender('0')" >
												<input type="radio" name="gender" > <?php echo $this->translate('Male') ?>
											</label> &nbsp; <label
												class="btn btn-outline btn-primary btn-sm"  ng-class="userInfo.gender == '1'?'active':''"   ng-click="setGender('1')">
												<input type="radio" name="gender"> <?php echo $this->translate('Female') ?>
											</label>
										</div>
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label><?php echo $this->translate('City') ?> *</label> 
										<input id="city" name="city" type="text" class="form-control required" ng-model="userInfo.city">
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label><?php echo $this->translate('Username') ?> *</label> 
										<input id="username" name="userName" type="text" class="form-control " ng-model="employer.name" disabled>
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label><?php echo $this->translate('Last name') ?> *</label> 
										<input id="lastname" name="surname" type="text" class="form-control required" ng-model="userInfo.lastName">
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label><?php echo $this->translate('Phone') ?> *</label> 
										<input id="phone" name="phone" type="phone" class="form-control required" ng-model="userInfo.phone">
									</div>
									<div class="hr-line-dashed"></div>
									<div class="form-group">
										<label><?php echo $this->translate('Country') ?> *</label> 
										<select class="form-control required" id="country" name="country" ng-model="userInfo.country" ng-options="country.name for country in countries">
										</select>
									</div>
								</div>
							</div>
						</div>
					</div>
					<!-- Company Information -->
					<div class="panel panel-primary">
						<div class="panel-heading">
							<i class="fa fa-building"> <strong><?php echo $this->translate('Company Information') ?></strong></i>
						</div>
						<div class="panel-body">
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										<label><?php echo $this->translate('Position') ?> </label> 
										<input id="position" name="position" type="text" class="form-control" ng-model="employer.position">
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										<label>Company </label>
										<select class="form-control required" id="company" name="company" ng-model="employer.company" ng-options="company.name for company in companies">
										</select> <span class="help-block m-b-none"> &nbsp;Not in the
											list? Please <a data-toggle="modal" class="text-info"
											href="#modal-company"><?php echo $this->translate('create a new company') ?></a>.
										</span>
									</div>
								</div>
								<input type="hidden" id="defaultServiceLevel" ng-model="employer.defaultServiceLevel">
							</div>
						</div>
					</div>

					<div class="row">
						<div class="col-sm-4 col-sm-offset-4">
							<button class="btn btn-primary btn-block" type="submit" ng-click="submit()" ><?php echo $this->translate('Save') ?></button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<?php include "profile/modal.phtml" ?>