<?php $this->headTitle($this->translate('Forgot password?')) ?>
<div class="middle-box text-center loginscreen  animated fadeInDown">
    <h3><?php echo $this->translate('Forgot password?') ?></h3>

    <form class="m-t" method="post" role="form" action="">
        <?php
        foreach ($this->form->getElements() as $element): ?>
            <?php
            $messages = $element->getMessages()
            ?>
            <div class="form-group<?php if ($messages) echo " has-error" ?>">
                <?php if ($messages): ?>
                    <?php foreach ($messages as $message): ?>
                        <div class="alert-danger"><?php echo $message; ?></div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php echo $this->formInput($element); ?>
            </div>
        <?php endforeach; ?>
        <button type="submit" class="btn btn-primary block full-width m-b"><?php echo $this->translate('Confirm') ?></button>

                <hr />
                <p class="text-muted text-center"><small><?php echo $this->translate('Do not have an account?') ?></small></p>
                <a class="btn btn-sm btn-white btn-block" href="<?php echo $this->url('user',array("lang"=>$this->translate('lang', 'Application'))) ?>/register/"><?php echo $this->translate('Create an account') ?></a>
                <hr />
                <p class="text-muted text-center"><small><?php echo $this->translate('Already have an account?') ?></small></p>
                <a class="btn btn-sm btn-white btn-block" href="<?php echo $this->url('user',array("lang"=>$this->translate('lang', 'Application'))) ?>/login/"><?php echo $this->translate('Login', 'Application'); ?></a>
    </form>
</div>