<div class="panel panel-default" ng-show="hasTypeTranslationShow()">
    <div class="panel-heading" style="padding-bottom: 10px;">
        Translation - <span class="text-info"><strong>Business</strong></span>
    </div>
    <div class="panel-body">
        <div ng-show="hasTypeTranslationNoTM()"
             ng-controller="TableItemController">
            {{ setModalId('#modal-translation-noTM') }}
            {{ setIdentifier(["translationNoTM", language]) }}
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Iterms - <span class="text-info">Translation (No TM)</span></th>
						<th>File</span></th>
                        <th>Unit </th>
                        <th>Unit Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tbody>
                    <tr ng-repeat="item in items">
                        <td class="col-md-1">{{ $index + 1 }}</td>
						<td class="col-md-2">{{ item.name }}</td>
                        <td class="col-md-3" style="word-wrap: break-word;">{{ item.file.name |  breakword:true:70:' ...'}}</td>
                        <td class="col-md-2"><?php echo $this->translate("Source word") ?></td>
                        <td class="col-md-1">{{ CurrentUser.price(item.rate, currency) }}</td>
                        <td class="col-md-1">{{ item.quantity }}</td>
                        <td class="col-md-1">{{ CurrentUser.price(item.total, currency) }}</td>
                        <td class="col-md-1">
                        <span ng-click="showModal(item)">
                            <i class="fa fa-edit"></i>
                        </span> &nbsp;&nbsp;
                            <span ng-click="remove($index)"><i class="fa fa-trash-o text-danger"></i></span>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="text-center">
                <a class="btn btn-outline btn-primary"
                   ng-click="showModal(false)">Add Iterm</a>
            </div>
            <div class="hr-line-dashed"></div>
        </div>
        <div ng-show="hasTypeTranslationUseTM()"
             ng-controller="TableItemController">
            {{ setModalId('#modal-translation-TM') }}
            {{ setIdentifier(["translationTM", language]) }}
			{{setRateTm()}}
			
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Iterms - <span class="text-info">Translation (Use TM)</span></th>
                        <th>Unit </th>
                        <th>Unit Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>1</td>
                        <td>{{ itemtm.name }}</td>
                        <td>Source Word</td>
                        <td>{{ CurrentUser.price(itemtm.rate, currency) }}</td>
                        <td>{{ itemtm.sourcerepetitions + itemtm.sourceyibai + itemtm.sourcejiuwu + itemtm.sourcebawu + itemtm.sourceqiwu + itemtm.sourcewushi}}</td>
                        <td>{{ CurrentUser.price( (itemtm.rate * raterepetitions / 100) * itemtm.sourcerepetitions 
																					+(itemtm.rate * rateyibai / 100) * itemtm.sourceyibai
																					+(itemtm.rate * ratejiuwu / 100) * itemtm.sourcejiuwu
																					+(itemtm.rate * ratebawu / 100) * itemtm.sourcebawu
																					+(itemtm.rate * ratewushi / 100) * itemtm.sourcewushi
																					+(itemtm.rate * ratenomatch / 100) * itemtm.sourcenomatch
											, currency)  }}</td>
                        <td>
							
                            <a data-toggle="modal" ng-click="showModalTM(false)"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;

                            <a data-toggle="collapse" href="#use_tm_{{language.id}}"><i class="fa fa-eye"></i></a>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="7">
                            <div id="use_tm_{{language.id}}" class="panel-collapse collapse">
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <thead>
                                        <tr>
                                            <th>TM Template</th>
                                            <th>Rate (%)</th>
                                            <th>Unit Price</th>
                                            <th>Quantity (Word)</th>
                                            <th>Quantity</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>Repetitions</td>
                                            <td>{{ raterepetitions }}</td>
                                            <td>{{ CurrentUser.price(itemtm.rate * raterepetitions / 100, currency) }}</td>
                                            <td>{{ itemtm.sourcerepetitions }}</td>
                                            <td>{{ CurrentUser.price((itemtm.rate * raterepetitions / 100) * itemtm.sourcerepetitions, currency) }}</td>
                                        </tr>
                                        <tr>
                                            <td>100%</td>
                                            <td>{{ rateyibai }}</td>
                                            <td>{{ CurrentUser.price(itemtm.rate * rateyibai / 100, currency) }}</td>
                                            <td>{{ itemtm.sourceyibai }}</td>
                                            <td>{{ CurrentUser.price((itemtm.rate * rateyibai / 100) * itemtm.sourceyibai, currency) }}</td>

                                        </tr>
                                        <tr>
                                            <td>95%-99%</td>
                                            <td>{{ ratejiuwu }}</td>
                                            <td>{{ CurrentUser.price(itemtm.rate * ratejiuwu / 100, currency) }}</td>
                                            <td>{{ itemtm.sourcejiuwu }}</td>
                                            <td>{{ CurrentUser.price((itemtm.rate * ratejiuwu / 100) * itemtm.sourcejiuwu, currency) }}</td>
                                        </tr>
                                        <tr>
                                            <td>85%-94%</td>
                                            <td>{{ ratebawu }}</td>
                                            <td>{{ CurrentUser.price(itemtm.rate * ratebawu / 100, currency) }}</td>
                                            <td>{{ itemtm.sourcebawu }}</td>
                                            <td>{{ CurrentUser.price((itemtm.rate * ratebawu / 100) * itemtm.sourcebawu, currency) }}</td>

                                        </tr>
                                        <tr>
                                            <td>75%-84%</td>
                                            <td>{{ rateqiwu }}</td>
                                            <td>{{ CurrentUser.price(itemtm.rate * rateqiwu / 100, currency) }}</td>
                                            <td>{{ itemtm.sourceqiwu }}</td>
                                            <td>{{ CurrentUser.price((itemtm.rate * rateqiwu / 100) * itemtm.sourceqiwu, currency) }}</td>
                                        </tr>
                                        <tr>
                                            <td>50%-74%</td>
                                            <td>{{ ratewushi }}</td>
                                            <td>{{ CurrentUser.price(itemtm.rate * ratewushi / 100, currency) }}</td>
                                            <td>{{ itemtm.sourcewushi }}</td>
                                            <td>{{ CurrentUser.price((itemtm.rate * ratewushi / 100) * itemtm.sourcewushi, currency) }}</td>

                                        </tr>
                                        <tr>
                                            <td>No Match</td>
                                            <td>{{ ratenomatch }}</td>
                                            <td>{{ CurrentUser.price(itemtm.rate * ratenomatch / 100, currency) }}</td>
                                            <td>{{ itemtm.sourcenomatch }}</td>
                                            <td>{{ CurrentUser.price((itemtm.rate * ratenomatch / 100) * itemtm.sourcenomatch, currency) }}</td>

                                        </tr>
                                        <tr>
                                            <td colspan="4" align="right"><strong>Total</strong></td>
                                            <td class="text-info">{{ CurrentUser.price( itemtm.total , currency)  }}</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>