<div class="tab-pane" id="feedback" ng-controller="ItemListController">
    <div ng-controller="ProjectFeedbackController">
        <div class="panel-body">
            <div class="panel-group" id="accordion_feedback">
                <div class="panel panel-default" ng-repeat="feedback in items">

                        <div class="panel-heading" style="padding-bottom: 10px;">
                            <h5 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion_feedback" href="#feedback_lang{$index}"> {{ project.sourceLanguage.name }} <i class="fa fa-arrow-right"></i> {{ feedback.language_data.name }} </a>
                            </h5>
                        </div>
                        <div id="feedback_lang{$index}" class="panel-collapse collapse in">
                            <div class="panel">
                                <div class="panel-body">
                                  
                                    <p><?php echo $this->translate('Leaving feedback here will help you get a better translation next time.','Employer'); ?></p>

                                    <div class="panel panel-default tooltip-demo">
                                        <div class="panel-body">
                                          <div class="form-group">
                                            <label class="control-label"><?php echo $this->translate('Quality','Employer'); ?></label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td ng-repeat="val in q_values" class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{val.title}}" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" ng-model="feedback.quality" value="{{val.id}}" ng-checked="feedback.quality == val.id">
                                                      <span class="custom-radio"></span>
                                                      {{val.name}}
                                                    </label>
                                                  </td>

                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label"><?php echo $this->translate('Turn Around Time','Employer'); ?></label>
                                            <table class="table table-bordered table-hover table-striped">
                                              <tbody>
                                                <tr>
                                                  <td ng-repeat="val in t_values" class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{val.title}}" width="20%">
                                                    <label class="label-radio inline">
                                                      <input type="radio" ng-model="feedback.turnAroundTime" value="{{val.id}}" ng-checked="feedback.turnAroundTime == val.id">
                                                      <span class="custom-radio"></span>
                                                      {{val.name}}
                                                    </label>
                                                  </td>

                                                </tr>
                                              </tbody>
                                            </table>
                                          </div><!-- /form-group -->
                                          <div class="form-group">
                                            <label class="control-label"><?php echo $this->translate('Feed back to Translator and Project Manager','Employer'); ?></label>
                                            <textarea class="form-control" ng-model='feedback.message' id="tarea{$h}" rows="3">{{feedback.message}}</textarea>
                                          </div><!-- /form-group -->

                                            <div class="text-right m-t-md">
                                                <a href="#" class="btn btn-primary" ng-click="sendFeedback(feedback)">{{feedback.buttonTitle}}</a>
                                            </div>

                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>

                </div>
            </div>
        </div>
    </div>
</div>
