<div ng-controller="ItemListController">
    <div ng-controller="ProjectCorrectionController">
    </div>
</div>
<div class="tab-pane<?php echo ($filesTabActive == true ? ' active': '');?>" id="files" ng-controller="ProjectFilesController">
    <div class="panel-body">
        <h3>Source Files</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Source File Name</th>
                    <th>Size</th>
                    <th>Time Stamp</th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="file in files">
                    <td>{{$index + 1}}</td>
                    <td><a href="#" ng-click="downloadFile(file.token)"><i class="fa fa-file"></i> {{file.name}} <i class="fa fa-cloud-download"></i></a> </td>
                    <td>{{file.size | filesize}}</td>
                    <td>{{ DateFormatter.format(file.time) }}</td>
                </tr>
            </tbody>
        </table>
        <div class="text-right m-t-md">
            <a href="#" class="btn btn-xs btn-primary"><i class="fa fa-cloud-upload"></i> Upload Source files</a>
        </div>
    </div>



    <div class="panel-body">
        <h3>Files For Review</h3>
        <div class="panel-group" id="accordion_preview">
            <div class="panel panel-default" ng-repeat="lang in project.targetLanguages">
                    <div class="panel-heading" style="padding-bottom: 10px;">
                        <h5 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion_preview" href="#preview_lang1"><i class="fa fa-exclamation-triangle text-danger" ng-hide="task.status.id == 1"></i> {{ project.sourceLanguage.name }} <i class="fa fa-arrow-right"></i> {{ lang.name }} </a> <i class="fa fa-paperclip" ng-show="lang.files.length"></i></a> <!-- with paperclip means file for this language has been uploaded -->
                        </h5>
                    </div>
                    <div id="preview_lang{{$index}}" class="panel-collapse collapse in">

                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>File Name</th>
                                    <th>Size</th>
                                    <th>Time Stamp</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="file in lang.files">
                                        <td>{{$index + 1}}</td>
                                        <td><a href="#" ng-click="downloadFile(file.token)"><i class="fa fa-file"></i> {{file.name}} <i class="fa fa-cloud-download"></i></a> </td>
                                        <td>{{file.size | filesize}}</td>
                                        <td>{{ DateFormatter.format(file.time) }}</td>
                                    </tr>
                                </tbody>
                            </table>

                            <div>
                                <div class="col-md-6">
                                    <p>Happy with your translation? Formally approve it here.</p>
                                    <a data-toggle="collapse" data-parent="#preview_lang{{$index}}" href="#approve_lang{{$index}}" class="btn btn-primary"><i class="fa fa-check-square-o"></i> Approve</a> <!-- if user click the approve button(all languages), the approve button and request correct button should hide, and project status should change to completed -->
                                </div>
                                <div class="col-md-6">
                                    <p>If you need the translator to fix mistakes or make changes:</p>
                                    <a data-toggle="collapse" data-parent="#preview_lang{{$index}}" href="#correct_lang{{$index}}" class="btn btn-warning"><i class="fa fa-edit"></i> Request corrections</a> <!-- if any language need correct, the project status will change to Reject -->
                                </div>
                            </div>
                        </div>
                        <div class="panel">
                            <div id="approve_lang{{$index}}" class="panel-collapse collapse">
                                <div class="panel">
                                    <div class="panel-body">
                                        <hr />
                                        <p>Leaving feedback here will help you get a better translation next time. On your next order, you'll be able to specify whether to use only your preferred translators. This translator is on your list of preferred translators.</p>

                                        <div class="panel panel-default tooltip-demo">
                                            <div class="panel-body">
                                              <div class="form-group">
                                                <label class="control-label">Quality</label>
                                                <table class="table table-bordered table-hover table-striped">
                                                  <tbody>
                                                    <tr>
                                                      <td ng-repeat="val in q_values" class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{val.title}}" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" ng-model="lang.feedback.quality" value="{{val.id}}" ng-checked="lang.feedback.quality == val.id">
                                                          <span class="custom-radio"></span>
                                                          {{val.name}}
                                                        </label>
                                                      </td>

                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div><!-- /form-group -->
                                              <div class="form-group">
                                                <label class="control-label">Turn Around Time</label>
                                                <table class="table table-bordered table-hover table-striped">
                                                  <tbody>
                                                    <tr>
                                                      <td ng-repeat="val in t_values" class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{val.title}}" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" ng-model="lang.feedback.turnAroundTime" value="{{val.id}}" ng-checked="lang.feedback.turnAroundTime == val.id">
                                                          <span class="custom-radio"></span>
                                                          {{val.name}}
                                                        </label>
                                                      </td>

                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div><!-- /form-group -->
                                              <div class="form-group">
                                                <label class="control-label">Feed back to Translator and Project Manager</label>
                                                <textarea class="form-control" ng-model='lang.feedback.message' id="tarea{$h}" rows="3">{{lang.feedback.message}}</textarea>
                                              </div><!-- /form-group -->

                                                <div class="text-right m-t-md">
                                                    <a href="#" class="btn btn-primary" ng-click="sendFeedback(lang)">{{lang.feedback.buttonTitle}}</a>
                                                </div>

                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="panel">
                            <div id="correct_lang{{$index}}" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <div class="panel panel-default">
                                      <form class="no-margin">
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <label class="control-label">What's wrong with the translation?</label>
                                                <div class="checkbox"><label> <input type="checkbox" ng-model="task.correction.options.incomplete"> It is incomplete </label></div>
                                                <div class="checkbox"><label> <input type="checkbox" ng-model="task.correction.options.spelling"> It contains spelling or grammatical errors </label></div>
                                                <div class="checkbox"><label> <input type="checkbox" ng-model="task.correction.options.meaning"> It misses key meaning or details from the original </label></div>
                                            </div>
                                            <div class="form-group">
                                            <label class="control-label">Comments</label>
                                            <textarea class="form-control" ng-model="task.correction.message" rows="3" id="commt{$h}" data-required="true">{{task.correction.message}}</textarea>
                                            <span class="help-block">(Please use English or Chinese (Simplified))</span>
                                            </div><!-- /form-group -->
                                            <div class="text-right m-t-md">
                                                <a href="#" class="btn btn-warning" ng-click="requestCorrection(task)"> Request corrections from translator or project manager</a>
                                            </div>
                                        </div>
                                      </form>
                                    </div><!-- /panel -->

                                </div>
                            </div>
                        </div>

                    </div>

            </div>

        </div>
    </div>
</div>
