<div ng-controller="ItemListController">
    <div ng-controller="ProjectCorrectionController">
    </div>
</div>

<div class="tab-pane<?php echo ($filesTabActive == true ? ' active': '');?>" id="files" ng-controller="ProjectFilesController">
    <div class="panel-body">
        <h3><?php echo $this->translate('Source Files','Employer'); ?></h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th><?php echo $this->translate('#','Employer'); ?></th>
                    <th><?php echo $this->translate('Source File Name','Employer'); ?></th>
                    <th><?php echo $this->translate('Size','Employer'); ?></th>
                    <th><?php echo $this->translate('Time Stamp','Employer'); ?></th>
                </tr>
            </thead>
            <tbody>
                <tr ng-repeat="file in files">
                    <td>{{$index + 1}}</td>
                    <td><a href="#" ng-click="downloadFile(file.token)"><i class="fa fa-file"></i> {{file.name}} <i class="fa fa-cloud-download"></i></a> </td>
                    <td>{{file.size | filesize}}</td>
                    <td>{{ formatDate(file.time.date) | date:'dd MMMM yyyy - h:mm a' }}</td>
                </tr>
            </tbody>
        </table>
        <div class="hr-line-dashed"></div>
        <h3><?php echo $this->translate('Files For Review','Employer'); ?></h3>
        <div class="panel-group" id="accordion_preview">
            <div class="panel panel-default" ng-repeat="lang in project.targetLanguages">
                    <div class="panel-heading" style="padding-bottom: 10px;">
                        <h5 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion_preview" href="#preview_lang{{$index}}"><i class="fa fa-exclamation-triangle text-danger" ng-show="lang.correction"></i> {{ project.sourceLanguage.name }} <i class="fa fa-arrow-right"></i> {{ lang.name }} </a> <i class="fa fa-paperclip" ng-show="lang.files.length"></i></a> <!-- with paperclip means file for this language has been uploaded -->
                        </h5>
                    </div>
                    <div id="preview_lang{{$index}}" class="panel-collapse collapse in" ng-if="lang.files.length">

                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th><?php echo $this->translate('#','Employer'); ?></th>
                                    <th><?php echo $this->translate('File Name','Employer'); ?></th>
                                    <th><?php echo $this->translate('Size','Employer'); ?></th>
                                    <th><?php echo $this->translate('Time Stamp','Employer'); ?></th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="file in lang.files">
                                        <td>{{$index + 1}}</td>
                                        <td><a href="#" ng-click="downloadFile(file.token)"><i class="fa fa-file"></i> {{file.name}} <i class="fa fa-cloud-download"></i></a> </td>
                                        <td>{{file.size | filesize}}</td>
                                        <td>{{ formatDate(file.time.date) | date:'dd MMMM yyyy - h:mm a' }}</td>
                                    </tr>
                                </tbody>
                            </table>

                            <!-- <div ng-show="lang.feedback.needToCreate && !!lang.files.length">  -->
                            <div ng-show=" !!lang.files.length && project.status.id != 5">
                                <div class="col-md-6">
                                    <p><?php echo $this->translate('Happy with your translation? Formally approve it here.','Employer'); ?></p>
                                    <a data-toggle="collapse" data-parent="#preview_lang{{$index}}" href="#approve_lang{{$index}}" class="btn btn-primary"><i class="fa fa-check-square-o"></i> <?php echo $this->translate('Approve','Employer'); ?></a> <!-- if user click the approve button(all languages), the approve button and request correct button should hide, and project status should change to completed -->
                                </div>
                                <div class="col-md-6">
                                    <p><?php echo $this->translate('If you need the translator to fix mistakes or make changes?','Employer'); ?></p>
                                    <a data-toggle="collapse" data-parent="#preview_lang{{$index}}" href="#correct_lang{{$index}}" class="btn btn-warning"><i class="fa fa-edit"></i> <?php echo $this->translate('Request corrections','Employer'); ?></a> <!-- if any language need correct, the project status will change to Reject -->
                                </div>
                            </div>
                        </div>
                        <div class="panel">
                            <div id="approve_lang{{$index}}" class="panel-collapse collapse">
                                <div class="panel">
                                    <div class="panel-body">
                                        <hr />
                                        <p><?php echo $this->translate('Leaving feedback here will help you get a better translation next time.','Employer'); ?></p>

                                        <div class="panel panel-default tooltip-demo">
                                            <div class="panel-body">
                                              <div class="form-group">
                                                <label class="control-label"><?php echo $this->translate('Quality','Employer'); ?></label>
                                                <table class="table table-bordered table-hover table-striped">
                                                  <tbody>
                                                    <tr>
                                                      <td ng-repeat="val in q_values" class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{val.title}}" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" ng-model="lang.feedback.quality" value="{{val.id}}" ng-checked="lang.feedback.quality == val.id">
                                                          <span class="custom-radio"></span>
                                                          {{val.name}}
                                                        </label>
                                                      </td>

                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div><!-- /form-group -->
                                              <div class="form-group">
                                                <label class="control-label"><?php echo $this->translate('Turn Around Time','Employer'); ?></label>
                                                <table class="table table-bordered table-hover table-striped">
                                                  <tbody>
                                                    <tr>
                                                      <td ng-repeat="val in t_values" class="tooltip-test" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{val.title}}" width="20%">
                                                        <label class="label-radio inline">
                                                          <input type="radio" ng-model="lang.feedback.turnAroundTime" value="{{val.id}}" ng-checked="lang.feedback.turnAroundTime == val.id">
                                                          <span class="custom-radio"></span>
                                                          {{val.name}}
                                                        </label>
                                                      </td>

                                                    </tr>
                                                  </tbody>
                                                </table>
                                              </div><!-- /form-group -->
                                              <div class="form-group">
                                                <label class="control-label"><?php echo $this->translate('Feed back to Translator and Project Manager','Employer'); ?></label>
                                                <textarea class="form-control" ng-model='lang.feedback.message' id="tarea{$h}" rows="3"></textarea>
                                              </div><!-- /form-group -->

                                                <div class="text-right m-t-md">
                                                    <a href="#" class="btn btn-primary" ng-click="sendFeedback(lang)">{{lang.feedback.buttonTitle}}</a>
                                                </div>

                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="panel">
                            <div id="correct_lang{{$index}}" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <div class="panel panel-default">
                                      <form class="no-margin">
                                        <div class="panel-body">
                                            <div class="form-group">
                                                <label class="control-label"><?php echo $this->translate('What\'s wrong with the translation?','Employer'); ?></label>
                                                <div class="checkbox"><label> <input type="checkbox" ng-model="lang.correction.options.incomplete"> <?php echo $this->translate('It is incomplete','Employer'); ?> </label></div>
                                                <div class="checkbox"><label> <input type="checkbox" ng-model="lang.correction.options.spelling"> <?php echo $this->translate('It contains spelling or grammatical errors','Employer'); ?> </label></div>
                                                <div class="checkbox"><label> <input type="checkbox" ng-model="lang.correction.options.meaning"> <?php echo $this->translate('It misses key meaning or details from the original','Employer'); ?> </label></div>
                                            </div>
                                            <div class="form-group">
                                            <label class="control-label"><?php echo $this->translate('Comments','Employer'); ?></label>
                                            <textarea class="form-control" ng-model="lang.correction.message" rows="3" id="commt{$h}" data-required="true">{{lang.correction.message}}</textarea>
                                            <span class="help-block"><?php echo $this->translate('(Please use English or Chinese (Simplified))','Employer'); ?></span>
                                            </div><!-- /form-group -->
                                            <div class="text-right m-t-md">
                                                <a href="#" class="btn btn-warning" ng-click="requestCorrection(lang)"> <?php echo $this->translate('Request corrections from translator or project manager','Employer'); ?></a>
                                            </div>
                                        </div>
                                      </form>
                                    </div><!-- /panel -->

                                </div>
                            </div>
                        </div>

                    </div>

            </div>

        </div>
    </div>
</div>
