<div class="tab-pane<?php echo ($filesTabActive == true ? ' active': '');?>" id="files" ng-controller="ProjectFilesController">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Source File Name</th>
                <th>Size</th>
                <th>Time Stamp</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="file in files">
                <td>{{$index + 1}}</td>
                <td><a href="#" ng-click="downloadFile(file.token)"><i class="fa fa-file"></i> {{file.name}} <i class="fa fa-cloud-download"></i></a> </td>
                <td>{{file.size | filesize}}</td>
                <td>{{ DateFormatter.format(file.time) }}</td>
                <td><i class="fa fa-trash"></i></td>
            </tr>
        </tbody>
    </table>
    <div class="text-right m-t-md">
        <a href="#" class="btn btn-xs btn-primary"><i class="fa fa-cloud-upload"></i> Upload Source files</a>
    </div>
    <div class="hr-line-dashed"></div>
    <h4>Files For Client Review</h4>
    <div class="panel-body">
        <div class="panel-group" id="accordion_files">
            <div class="panel panel-default" ng-repeat="lang in project.targetLanguages">
                    <div class="panel-heading" style="padding-bottom: 10px;">
                        <h5 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion_preview" href="#preview_lang{{$index}}"><i class="fa fa-exclamation-triangle text-danger" ng-hide="task.status.id == 1"></i> {{ project.sourceLanguage.name }} <i class="fa fa-arrow-right"></i> {{ lang.name }} </a> <i class="fa fa-paperclip" ng-show="lang.files.length"></i></a> <!-- with paperclip means file for this language has been uploaded -->
                        </h5>
                    </div>
                    <div id="preview_lang{{$index}}" class="panel-collapse collapse in">

                        <div class="panel-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Languages</th>
                                        <th>File Name</th>
                                        <th>Size</th>
                                        <th>Time Stamp</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr ng-repeat="file in lang.files">
                                        <td>{{$index + 1}}</td>
                                        <td>{{ project.sourceLanguage.name }} <i class="fa fa-arrow-right"></i> {{ lang.name }}</td>
                                        <td><a href="#" ng-click="downloadFile(file.token)"><i class="fa fa-file"></i> {{file.name}} <i class="fa fa-cloud-download"></i></a> </td>
                                        <td>{{file.size | filesize}}</td>
                                        <td>{{ DateFormatter.format(file.time) }}</td>
                                        <td><i class="fa fa-trash" ng-click="deleteFile(file.token)"></i></td>
                                    </tr>
                                    <tr ng-repeat="item in lang.uploader.queue" ng-show="item.isUploading">
                                        <td>{{$index + lang.files.length + 1 }}</td>
                                        <td>{{ project.sourceLanguage.name }} <i class="fa fa-arrow-right"></i> {{ lang.name }}</td>
                                        <td><a href="#" ng-click="downloadFile(item.token)" ng-hide="item.isUploading">{{ item.file.name }}</a>
                                            <div class="progress" style="margin-bottom: 0" ng-show="item.isUploading">
                                                <div class="progress-bar" role="progressbar"
                                                     ng-style="{ 'width': lang.uploader.progress + '%' }" style="width: 0%;">{{ item.file.name }}</div>
                                            </div>
                                        </td>
                                        <td class="text-right">{{ item.file.size | filesize }}</td>
                                        <td>{{ DateFormatter.format(item._file.lastModified) }}</td>
                                        <td class="text-center child-is-link">
                                            <i ng-click="removeItem(item)" class="fa fa-trash-o text-danger"></i>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <div class="text-center m-t-md">
                                <!-- <a href="#" class=""><i class="fa fa-cloud-upload"></i> Upload files</a> -->
                                <input type="file" nv-file-select="" uploader="lang.uploader" multiple="multiple" class="filestyle" data-input="false" data-buttonName="btn-primary" data-iconName="glyphicon-cloud-upload" data-buttonText=" Upload files" options = "{ input: false, buttonText: ' Upload files', icon: 'glyphicon-cloud-upload', buttonText: 'Upload files', buttonName: 'btn btn-sm btn-primary', badge: false}"/>
                                <!-- <file-uploader></file-uploader> -->

                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="panel-body">
                                <div class="form-group">
                                    <label class="control-label">What's wrong with the translation?</label>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" disabled ng-model="lang.correction.options.incomplete"> It is incomplete </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" disabled ng-model="lang.correction.options.spelling"> It contains spelling or grammatical errors </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" disabled ng-model="lang.correction.options.meaning"> It misses key meaning or details from the original </label>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label">Comments</label>
                                    <p>{{lang.correction.message}}</p>
                                </div>
                                <!-- /form-group -->
                            </div>
                        </div>
                    </div>

            </div>

        </div>
    </div>
</div>
