                        <div class="row">

                            <div class="col-md-12">
                                <?php if (!$this->isemployer) {?>
                                <button class="btn btn-danger pull-right" ng-click="showEdit()">
                                    <i class="fa fa-edit"></i><?php echo $this->translate('Edit Project') ?>
                                </button>
                                <?php } ?>
                                <h2 class="m-b-xs"><span class="font-bold text-navy">{{ project.project_no }}</span>&nbsp;&nbsp; <span>{{ project.reference }}</span></h2>
                                <hr>
                                <div>
                                    <button class="btn btn-{{ task.status.decorator }} pull-right">{{ project.status.name }}</button>
                                    <h1 class="product-main-price">{{ project.currency}} {{ project.total_tmp}} </h1>
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-6 b-r">
                                        <table class="table table-striped table-bordered">
                                            <tbody>
                                            <tr>
                                                <th><?php echo $this->translate('Due Date','Employer'); ?></th>
                                                <td> {{ formatDate(project.dueDate.date) | date:'dd MMMM yyyy - h:mm a' }} </td>
                                            </tr>
                                            <tr>
                                                <th><?php echo $this->translate('Source Language','Employer'); ?></th>
                                                <td> <code style="font-size: 14px;">{{ project.sourceLanguage.name }}</code> </td>
                                            </tr>
                                            <tr>
                                                <th><?php echo $this->translate('Project Type','Employer'); ?></th>
                                                <td>
                                                  <div class="tooltip-demo">
                                                    <span ng-repeat="type in project.types"><code style="font-size: 14px;" {{ type.inline_attrs }}>{{ type.name_short }}</code>&nbsp;</span>
                                                  </div>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="col-sm-6">
                                        <table class="table table-striped table-bordered">
                                            <tbody>
                                            <tr>
                                                <th><?php echo $this->translate('PO No','Employer'); ?></th>
                                                <td> {{ project.po }} </td>
                                            </tr>
                                            <tr>
                                                <th><?php echo $this->translate('Languages','Employer'); ?></th>
                                                <td> <span ng-repeat="language in project.targetLanguages"><code style="font-size: 14px;">{{ language.name }}</code>&nbsp;</span> </td>
                                            </tr>
                                            <tr>
                                                <th><?php echo $this->translate('Project Manager','Employer'); ?></th>
                                                <td> {{ project.pm.name }} </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <?php if (!$this->isemployer) {?>
                                <div class="row">
                                    <div class="col-sm-6 b-r">
                                        <table class="table table-striped table-bordered">
                                            <tbody>
                                            <tr>
                                                <th><?php echo $this->translate('Field'); ?></th>
                                                <td> {{ project.field.name }} </td>
                                            </tr>
                                            <tr>
                                                <th><?php echo $this->translate('Client Contact'); ?></th>
                                                <td>{{ project.client.name }}</td>
                                            </tr>
                                            <tr>
                                                <th><?php echo $this->translate('Sales'); ?></th>
                                                <td class="text-navy"> {{ project.sale.name }} </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="col-sm-6">
                                        <table class="table table-striped table-bordered">
                                            <tbody>
                                            <tr>
                                                <th><?php echo $this->translate('Client Company'); ?></th>
                                                <td>{{ project.client.company.name }}</td>
                                            </tr>
                                            <tr>
                                                <th><?php echo $this->translate('Project Manager'); ?></th>
                                                <td> {{ project.pm.name }} </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <?php } ?>
                            </div>
                        </div>

