                        <div class="row">

                            <div class="col-md-12">
                                <?php if (!$this->isemployer) {?>
                                <button class="btn btn-primary pull-right"><i class="fa fa-edit"> <?php echo $this->translate('Edit Project') ?></button>
                                <?php } ?>
                                <h2 class="m-b-xs"><span class="font-bold text-navy">{{ project.project_no }}</span>&nbsp;&nbsp; <span>{{ project.reference }}</span></h2>
                                <hr>
                                <div>
                                    <button class="btn btn-{{ task.status.decorator }} pull-right">{{ project.status.name }}</button>
                                    <h1 class="product-main-price">$406,602 <small class="text-muted" style="font-size: 16px;">1800 words</small> </h1>
                                </div>
                                <hr>
                                <div class="row">
                                      <div class="col-sm-6 b-r">
                                        <table class="table table-striped table-bordered">
                                            <tbody>
                                            <tr>
                                                <th><?php echo $this->translate('Due Date'); ?></th>
                                                <td> {{ formatDate(project.dueDate.date) | date:'dd MMMM yyyy - h:mm a' }} </td>
                                            </tr>
                                            <tr>
                                                <th><?php echo $this->translate('Source Language'); ?></th>
                                                <td> <code style="font-size: 14px;">{{ project.sourceLanguage.name }}</code> </td>
                                            </tr>
                                            <tr>
                                                <th><?php echo $this->translate('Project Type'); ?></th>
                                                <td>
                                                  <div class="tooltip-demo">
                                                    <span ng-repeat="type in project.types"><code style="font-size: 14px;" {{ type.inline_attrs }}>{{ type.name_short }}</code>&nbsp;</span>
                                                  </div>
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                      </div>
                                      <div class="col-sm-6">
                                        <table class="table table-striped table-bordered">
                                            <tbody>
                                            <tr>
                                                <th><?php echo $this->translate('PO No'); ?></th>
                                                <td> {{ project.po }} </td>
                                            </tr>
                                            <tr>
                                                <th><?php echo $this->translate('Languages'); ?></th>
                                                <td> <span ng-repeat="language in project.targetLanguages"><code style="font-size: 14px;">{{ language.name }}</code>&nbsp;</span> </td>
                                            </tr>
                                            <tr>
                                                <th><?php echo $this->translate('Project Manager'); ?></th>
                                                <td> {{ project.pm.name }} </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>

