
<div class="row">
    <div class="col-lg-12">
        <div class="m-b-md">
			<?php if (!$this->isemployer) {?>
            <button class="btn btn-danger btn-xs pull-right" ng-click="showEdit()">
                <i class="fa fa-edit"></i><?php echo $this->translate('Edit Project') ?>
            </button>
			<?php } ?>
            <h2><span class="text-info">{{ project.project_no }}</span> -
                {{ project.reference }}</h2>
        </div>

    </div>
</div>
<div class="row">
  <div class="ibox-content">
      <div class="row">
          <div class="col-sm-6 b-r">
            <table class="table table-striped table-bordered">
                <tbody>
                <tr>
                    <th width="25%"><?php echo $this->translate('Project ID'); ?></th>
                    <td class="text-navy"> {{ project.project_no }} </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Status'); ?>:</th>
                    <td> <span class="label label-{{ task.status.decorator }}">{{ project.status.name }} </span> </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Due Date'); ?></th>
                    <td> {{ formatDate(project.dueDate.date) | date:'dd MMMM yyyy - h:mm a' }} </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Project Type'); ?></th>
                    <td>
                      <div class="tooltip-demo">
                        <span ng-repeat="type in project.types"><code {{ type.inline_attrs }}>{{ type.name_short }}</code>&nbsp;</span>
                      </div>
                    </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Source Language'); ?></th>
                    <td> <code>{{ project.sourceLanguage.name }}</code> </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Client Contact'); ?></th>
                    <td>{{ project.client.name }}</td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Sales'); ?></th>
                    <td class="text-navy"> {{ project.sale.name }} </td>
                </tr>
                </tbody>
            </table>
          </div>
          <div class="col-sm-6">
            <table class="table table-striped table-bordered">
                <tbody>
                <tr>
                    <th width="25%"><?php echo $this->translate('Project Reference'); ?></th>
                    <td class="text-navy"> {{ project.reference }} </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Priority'); ?></th>
                    <td> <span class="label label-{{ project.priority.decorator }}">{{ project.priority.name }}</span> </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Field'); ?></th>
                    <td> {{ project.field.name }} </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('PO No'); ?></th>
                    <td> {{ project.po }} </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Languages'); ?></th>
                    <td> <span ng-repeat="language in project.targetLanguages"><code>{{ language.name }}</code>&nbsp;</span> </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Client Company'); ?></th>
                    <td>{{ project.client.company.name }}</td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Project Manager'); ?></th>
                    <td> {{ project.pm.name }} </td>
                </tr>
                </tbody>
            </table>
    </div>
                </div>
    </div>

</div>
