
<div class="row">
 <div class="row">
                                                    <div class="col-lg-6">
                                                        <form class="form-horizontal">
                                                            <div class="form-group" id="inv_data">
                                                                <label class="col-sm-3 control-label">Invoice Date *</label>

                                                                <div class="col-sm-6 input-group date">
                                                                    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
																	<input data-field="datetime" readonly type="text" name="invoiceDate" ng-model="invoice.invoiceDate"
																	class="form-control required valid" data-errorplace="element.parent().before(error)"/>
                                                                    <span class="input-group-btn"  ng-click="setinvoiceDate()">
                                                                        <button type="button" class="btn btn-primary">Set</button> 
                                                                    </span>
                                                                </div>
																<div class="dtbox"></div>

                                                            </div>
                                                    </div>
                                                    <div class="col-lg-6" align="right">
                                                        <a href="#" class="btn btn-white"><i class="fa fa-file-pdf-o "></i> Download </a>
                                                        <a href="#" target="_blank" class="btn btn-primary"  ng-click="printInvoice()"><i class="fa fa-print"></i> Print Invoice </a>
                                                    </div>
                                                </div>
                                                <div class="hr-line-dashed"></div>
												
<div id="divToPrint">												
<div class="row">
    <div class="col-sm-6">
        <h4>Invoice No.</h4>
        <h4 class="text-navy">{{ invoice.invoice_no }}</h4>
		
        <h5>From:</h5>
        <strong>{{ project.pm.name }}</strong><br>
        <strong>Project Manager</strong><br>
        <address>
            <strong>{{companyinfo1.name}}</strong><br>
            {{companyinfo1.address}}<br>
            {{companyinfo1.city}}, {{companyinfo1.country}}<br>
            <abbr title="Phone">P:</abbr> {{companyinfo1.telephone}}
        </address>
    </div>

    <div class="col-sm-6 text-right">
        <p>
            <span><strong>Invoice Date:</strong>{{ DateFormatter.format(invoice.invoiceDate) }}</span><br/>
            <span><strong>Due Date:</strong>{{  DateFormatter.format(invoice.dueDate) }}</span>
        </p>
        <h5>To:</span></h5>
        <strong>{{ project.client.name }}</strong><br>
        <strong>{{ project.client.position }} </strong><br>
        <address>
            <strong>{{ project.client.company.name }}</strong><br>
            {{ project.client.company.address }}<br>
            {{ project.client.company.city }}, {{ project.client.company.country }}<br>
            <abbr title="Phone">P:</abbr> {{ project.client.company.telephone }}
        </address>

    </div>
</div>

<div class="table-responsive m-t"  ng-repeat="targetLanguage in project.targetLanguages">
    <table class="table table-bordered invoice-table">
        <thead>
        <tr>
            <th>{{ project.sourceLanguage.name }} to {{ targetLanguage.name }} - task</th>
            <th>Unit</th>
            <th>Unit Price</th>
            <th>Quantity</th>
            <th>Total Price</th>
        </tr>
        </thead>
        <tbody>
		<!-- this is only for translation use TM -->
        <tr  ng-show="hasTypeTranslationUseTM()">
            <td><div><a data-toggle="collapse" href="#use_tm1"><i class="fa fa-eye"></i> <strong>{{ itemtm.name }}</strong></a> - <span class="text-navy"> Translation (Use TM)</span></div></td>
            <td>Source Word</td>
            <td>{{ itemtm.rate }}</td>
            <td>{{ itemtm.sourcerepetitions + itemtm.sourceyibai + itemtm.sourcejiuwu + itemtm.sourcebawu + itemtm.sourceqiwu + itemtm.sourcewushi}}</td>
            <td>{{ itemtm.total }}</td>
        </tr>
        <tr  ng-show="hasTypeTranslationUseTM()"> <!-- this is only for translation use TM -->
            <td colspan="5">
                <div id="use_tm1" class="panel-collapse collapse">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>TM Template</th>
                                <th>Rate (%)</th>
                                <th>Unit Price</th>
                                <th>Quantity (Word)</th>
                                <th>Quantity</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Repetitions</td>
                                <td>{{ itemtm.raterepetitions }}</td>
                                <td>{{ itemtm.rate * itemtm.raterepetitions / 100 }}</td>
                                <td>{{ itemtm.sourcerepetitions }}</td>
                                <td>{{ (itemtm.rate * itemtm.raterepetitions / 100) * itemtm.sourcerepetitions }}</td>
                            </tr>
                            <tr>
                                <td>100%</td>
                                <td>{{ itemtm.rateyibai }}</td>
                                <td>{{ itemtm.rate * itemtm.rateyibai / 100 }}</td>
                                <td>{{ itemtm.sourceyibai }}</td>
                                <td>{{ (itemtm.rate * itemtm.rateyibai / 100) * itemtm.sourceyibai }}</td>
                            </tr>
                            <tr>
                                <td>95%-99%</td>
                                <td>{{ itemtm.ratejiuwu }}</td>
                                <td>{{ itemtm.rate * itemtm.ratejiuwu / 100 }}</td>
                                <td>{{ itemtm.sourcejiuwu }}</td>
                                <td>{{ (itemtm.rate * itemtm.ratejiuwu / 100) * itemtm.sourcejiuwu }}</td>
                            </tr>
                            <tr>
                                <td>85%-94%</td>
                                <td>{{ itemtm.ratebawu }}</td>
                                <td>{{ itemtm.rate * itemtm.ratebawu / 100 }}</td>
                                <td>{{ itemtm.sourcebawu }}</td>
                                <td>{{ (itemtm.rate * itemtm.ratebawu / 100) * itemtm.sourcebawu }}</td>
                            </tr>
                            <tr>
                                <td>75%-84%</td>
                                <td>{{ itemtm.rateqiwu }}</td>
                                <td>{{ itemtm.rate * itemtm.rateqiwu / 100 }}</td>
                                <td>{{ itemtm.sourceqiwu }}</td>
                                <td>{{ (itemtm.rate * itemtm.rateqiwu / 100) * itemtm.sourceqiwu }}</td>
                            </tr>
                            <tr>
                                <td>50%-74%</td>
                                <td>{{ itemtm.ratewushi }}</td>
                                <td>{{ itemtm.rate * itemtm.ratewushi / 100 }}</td>
                                <td>{{ itemtm.sourcewushi }}</td>
                                <td>{{ (itemtm.rate * itemtm.ratewushi / 100) * itemtm.sourcewushi }}</td>
                            </tr>
                            <tr>
                                <td>No Match</td>
                                <td>{{ itemtm.ratenomatch }}</td>
                                <td>{{ itemtm.rate * itemtm.ratenomatch / 100 }}</td>
                                <td>{{ itemtm.sourcenomatch }}</td>
                                <td>{{ (itemtm.rate * itemtm.ratenomatch / 100) * itemtm.sourcenomatch }}</td>
                            </tr>
                            <tr>
                                <td colspan="4" align="right"><strong>Total</strong></td>
                                <td class="text-info">{{ itemtm.total }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </td>
        </tr>
        <tr ng-show="hasTypeTranslationNoTM()" ng-repeat = "itermnotmsnew in itermnotmsnews[targetLanguage.id]">
			
            <td><div><strong> {{ itermnotmsnew.name }} </strong> - <span class="text-navy"> Translation (No TM)</span></div></td>
            <td>{{ itermnotmsnew.unit }}</td>
            <td>{{ itermnotmsnew.rate }}</td>
            <td>{{ itermnotmsnew.quantity }}</td>
            <td>{{ itermnotmsnew.total }}</td>
        </tr>
        <tr ng-show="hasTypeDesktopPublishingMac()" ng-repeat = "itermdtpmac in itermdtpmacs[targetLanguage.id]">
            <td><div><strong> {{ itermdtpmac.name }}</strong> - <span class="text-info">DTP <i class="fa fa-apple"></i></span></div></td>
            <td>{{ itermdtpmac.unit }}</td>
            <td>{{ itermdtpmac.rate }}</td>
            <td>{{ itermdtpmac.quantity }}</td>
            <td>{{ itermdtpmac.total }}</td>
        </tr>
		<tr ng-show="hasTypeDesktopPublishingWin()" ng-repeat = "itermdtppc in itermdtppcs[targetLanguage.id]">
            <td><div><strong> {{ itermdtppc.name }}</strong> - <span class="text-info">DTP <i class="fa fa-windows"></i></span></div></td>
            <td>{{ itermdtppc.unit }}</td>
            <td>{{ itermdtppc.rate }}</td>
            <td>{{ itermdtppc.quantity }}</td>
            <td>{{ itermdtppc.total }}</td>
        </tr>
		<tr ng-show="hasTypeDesktopPublishingEngineer()" ng-repeat = "itermengineering in itermengineerings[targetLanguage.id]">
            <td><div><strong> {{ itermengineering.name }}</strong> - <span class="text-info">Engineering </span></div></td>
            <td>{{ itermengineering.unit }}</td>
            <td>{{ itermengineering.rate }}</td>
            <td>{{ itermengineering.quantity }}</td>
            <td>{{ itermengineering.total }}</td>
        </tr>
		<tr ng-show="interpreting.id > 0" ng-repeat = "iterminterpreting in iterminterpretings[targetLanguage.id]">
            <td><div><strong> {{ iterminterpreting.name }}</strong> - <span class="text-info"> Interpreting </span></div></td>
            <td>{{ iterminterpreting.unit }}</td>
            <td>{{ iterminterpreting.rate }}</td>
            <td>{{ iterminterpreting.quantity }}</td>
            <td>{{ iterminterpreting.total }}</td>
        </tr>
		
        </tbody>
    </table>
</div><!-- /table-responsive -->
<table class="table invoice-total">
    <tbody>
    <tr>
        <td><strong>Sub Total :</strong></td>
        <td>{{ subtotal }}</td>
    </tr>
    <tr>
        <td><strong>(-) Discount :</strong></td>
        <td><span class="text-danger"><strong>-</strong></span> {{ project.discount }}</td>
    </tr>
    <tr>
        <td><strong>TAX ({{ project.tax }} %):</strong></td>
        <td>{{ (subtotal - project.discount)* project.tax/100 }}</td>
    </tr>
    <tr>
        <td><strong>TOTAL :</strong></td>
        <td>{{ subtotal - project.discount + (subtotal - project.discount)* project.tax/100 }}</td>
    </tr>
    </tbody>
</table>
<div class="hr-line-dashed"></div>
<div class="m-t">
                                                    <h2 class="text-center text-danger">Due Date: {{  DateFormatter.format(invoice.dueDate) }}</h2>
                                                    <br>
                                                    <div class="row">
                                                        <div class="col-lg-6">
                                                            <dl class="dl-horizontal">
                                                                <dt><h4>Bank Details</h4></dt><dd></dd>
                                                                <dt>Company Name:</dt> <dd>{{ companyinfo1.name }}</dd>
                                                                <dt>Bank Name:</dt> <dd>{{ bankinfo1.name }}</dd>
                                                                <dt>Bank Address:</dt> <dd>{{ bankinfo1.address }}, {{ bankinfo1.city }}, {{ bankinfo1.country }}</dd>
                                                                <dt>Account Number:</dt> <dd>{{ bankinfo1.accountNo }}</dd>
                                                                <dt>Swift Code:</dt> <dd>{{ bankinfo1.swift }}</dd>
                                                            </dl>
                                                        </div>
                                                        <div class="col-lg-6">
                                                            <dl class="dl-horizontal">
                                                                <dt><h4>Other Payment Methods</h4></dt><dd></dd>
                                                                <dt>Paypal:</dt> <dd>payments@papertask.com</dd>
                                                                <dt>Alipay:</dt> <dd>payments@papertask.com</dd>
                                                            </dl>
                                                        </div>
                                                    </div>
                                                    <br><br>
                                                    <h2 class="text-center"><em>Thank you for your business!</em></h2>
                                                </div>
</div>
</div>

