
<div class="row">
    <div class="col-lg-12">
        <div id="edit_project" class="panel-collapse collapse faq-answer">
            <form method="" class="form-horizontal">
                <div class="row form-horizontal">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('Reference','Employer') ?> *</label>
                            <div class="col-sm-9">
                                <input name="reference" ng-model="tempProject.reference" type="text"
                                       class="form-control required">
                            </div>
                        </div>
                        <div class="form-group" id="ordered_date">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('Start Date','Employer') ?> *</label>
                            <div class="col-sm-9">
                                <div class="input-group date" >
									<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
									<input data-field="datetime" readonly type="text" name="startDate" ng-model="project.startDate.date"
										   class="form-control required valid" data-errorplace="element.parent().before(error)"/>
                                </div>
								<div class="dtbox1"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('Field','Employer') ?> *</label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" name="field" aria-required="true"
                                        ng-model="tempProject.field"
                                        ng-options="field.name for field in fields">
                                    <option value=""></option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('Sales','Employer') ?> </label>
                            <div class="col-sm-9">
                                <select class="form-control  valid" name="sale" aria-required="true"
                                        ng-model="tempProject.sale"
                                        ng-options="sale.name for sale in sales">
                                    <option value=""></option>
                                </select>
                            </div>
                        </div>
						<?php if (!$this->isemployer) {?>
						<div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('PO No','Employer') ?></label>
                            <div class="col-sm-9">
                                <input name="po" ng-model="tempProject.po" type="text"
                                       class="form-control ">
                            </div>
                        </div>
						<?php } ?>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('Priority','Employer') ?> *</label>
                            <div class="col-sm-9">
                                <div data-toggle="buttons" class="label_check">
                                    <label class="btn btn-outline btn-{{ priority.decorator }} btn-sm
                                                      {{ tempProject.priority == priority ? 'active' : '' }}"
                                           ng-repeat="priority in ProjectPriority.all()"
                                           ng-click="tempProject.priority = priority">
                                        <input type="radio" name="priority" value="{{ priority.id }}"> {{ priority.name }}
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group" id="due_date">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('Due Date','Employer') ?> *</label>
                            <div class="col-sm-9">
                                <div class="input-group date" >
									<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
									<input data-field="datetime" readonly type="text" name="startDate" ng-model="project.dueDate.date" 
										   class="form-control required valid" data-errorplace="element.parent().before(error)"/>
                                </div>
								<div class="dtbox1"></div>
                            </div>
                        </div>
						<?php if (!$this->isemployer) {?>	
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('Client','Employer') ?> *</label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" name="client" aria-required="true"
                                        ng-model="tempProject.client"
                                        ng-options="client.name for client in clients">
                                    <option value=""></option>
                                </select>
                            </div>
                        </div>
						<?php } ?>
						<?php if ($this->isemployer) {?>
							
						<div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('PO No','Employer') ?></label>
                            <div class="col-sm-9">
                                <input name="po" ng-model="tempProject.po" type="text"
                                       class="form-control required">
                            </div>
                        </div>
						<?php } ?>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('PM','Employer') ?> *</label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" name="pms" aria-required="true"
                                        ng-model="tempProject.pm"
                                        ng-options="pm.name for pm in pms">
                                    <option value=""></option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('Project Status','Employer') ?> *</label>
                            <div class="col-sm-9">
                                <select class="form-control required valid" name="pms" aria-required="true"
                                        ng-model="tempProject.pm"
                                        ng-options="pm.name for pm in pms">
                                    <option value=""></option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="text-right tooltip-demo">
                    <button ng-click="update()" class="btn btn-sm btn-primary"><i class="fa fa-save"></i> <?php echo $this->translate('Update','Employer') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>