<?php include "tasks/form.phtml" ?>
<div class="project-list">
    <table class="table table-hover">
        <tbody>
        <tr ng-repeat="task in project.tasks">
            <td class="project-status">
                <span class="label label-{{ task.status.decorator }}">{{ task.status.name }}</span> <!--<i class="fa fa-usd"></i>-->
            </td>
            <td class="project-title">
                <strong><?php echo $this->translate("project") ?> {{ project.reference }} </strong>
                <br>
                <strong class="text-info">{{ project.id }}-{{ $index + 1 }}</strong>
                |
                <code>{{ project.sourceLanguage.name }}</code>
                <i class="fa fa-arrow-right"></i>
                <code>{{ task.language.name }}</code>
                <i class="fa fa-paperclip" ng-show="task.uploaded"></i> <!-- paperclip means freelancer uploaded the translated file -->
            </td>

            </td>
            <td class="project-title">
                    <span ng-clock="showProfile(task.assignee)"
                          ng-show="task.assignee"><strong>{{ task.assignee.name }}</strong></span>
                    <span class="text-danger"
                          ng-show="!task.assignee"><strong><?php echo $this->translate("Un-Assigned") ?></strong></span>
                <div class="tooltip-demo">
                    <code {{ task.type.inline_attrs }}>{{ task.type.name }}</code>
                    |
                    {{ DateFormatter.short(project.startDate) }} - {{ DateFormatter.short(project.dueDate) }}
                </div>
            </td>
            <td class="project-actions">
                <div class="tooltip-demo">
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Send to Specialism Pool" class="btn btn-success btn-xs"><i class="fa fa-users"></i> S</a>
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Send to Client's Resource Pool" class="btn btn-info btn-xs"><i class="fa fa-users"></i> C</a>
                    <a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="View Task Details" class="btn btn-white btn-xs"><i class="fa fa-folder"></i> </a>
                    <a href="#" class="btn btn-white btn-xs"><i class="fa fa-trash-o"></i> </a>
                </div>
            </td>
        </tr>
        </tbody>
    </table>
</div>