<div class="tab-pane" id="tasks" ng-controller="ItemListController">
    <div ng-controller="ProjectTasksController">
        <?php include "tasks/form.phtml" ?>
        <div class="project-list">
            <table class="table table-hover">
                <tbody>
                <tr ng-repeat="task in items">
                    <td class="project-status">
                        <span class="label label-{{ task.status.decorator }}">{{ task.status.name }}</span> <!--<i class="fa fa-usd"></i>-->
                    </td>
                    <td class="project-title">
                        <strong><?php echo $this->translate("project") ?> {{ project.reference }} </strong>
                        <br>
                        <strong class="text-info">{{task.task_number }}</strong>
                        |
                        <code>{{ project.sourceLanguage.name }}</code>
                        <i class="fa fa-arrow-right"></i>
                        <code>{{ task.language.name }}</code>
                        <i class="fa fa-paperclip" ng-show="task.uploaded"></i> <!-- paperclip means freelancer uploaded the translated file -->
                    </td>

                    </td>
                    <td class="project-title">
                            <span ng-clock="showProfile(task.assignee)"
                                  ng-show="task.assignee"><strong>{{ task.assignee.name }}</strong></span>
                            <span class="text-warning"
                                  ng-show="task.is_specialism_pool"><strong><?php echo $this->translate('Assigned to Specialism Pool') ?></strong></span>
                            <span class="text-warning"
                                  ng-show="task.is_client_pool"><strong><?php echo $this->translate('Assigned to Client\'s Resource Pool') ?></strong></span>
                            <span ng-show="!task.assignee && !task.is_specialism_pool && !task.is_client_pool"
                                  class="text-danger"><strong><?php echo $this->translate("Un-Assigned") ?></strong></span>
                        <div class="tooltip-demo">
                            <code  data-toggle="tooltip"  tooltip-placement="top"  tooltip="{{task.type.tootip}}"  ng-bind-html="task.type.name_task" compile-template> </code>
                            |
                            {{formatDate(task.startDate.date) | date:'yyyy.MMM.dd'}} - {{ formatDate(task.dueDate.date) | date:'yyyy.MMM.dd' }}
                        </div>
                    </td>
                    <td class="project-actions">
                        <div class="tooltip-demo">
                            <button ng-hide="task.assignee" data-toggle="tooltip" data-placement="top" title=""
                                    tooltip="Send to Specialism Pool"
                                    class="btn btn-success btn-xs"
                                    ng-click="sendToSpecialismPool(task)"><i class="fa fa-users"></i> S</button>
                            <button ng-hide="task.assignee" data-toggle="tooltip" data-placement="top" title=""
                                    tooltip="Send to Client's Resource Pool"
                                    class="btn btn-info btn-xs"
                                    ng-click="sendToClientPool(task)"><i class="fa fa-users"></i> C</button>
                            <button href="#" data-toggle="tooltip" data-placement="top" title=""
                                    tooltip="View Task Details"
                                    class="btn btn-white btn-xs"
									ng-click="viewtaskdetail(task)"><i class="fa fa-folder"></i> </button>
                            <button ng-hide="task.is_completed" class="btn btn-white btn-xs"
                                    ng-click="remove($index)"><i class="fa fa-trash-o"></i></button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>