        <div ng-show="task.type.id==4">    
			<div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th><?php echo $this->translate('Item','Admin'); ?> - <span class="text-info">DTP <i class="fa fa-apple"></i></span></th>
						<th><?php echo $this->translate('File','Admin'); ?></th>
                        <th><?php echo $this->translate('DTP Software','Admin'); ?></th>
                        <th><?php echo $this->translate('Unit','Admin'); ?></th>
                        <th><?php echo $this->translate('Unit Price','Admin'); ?></th>
                        <th><?php echo $this->translate('Quantity','Admin'); ?></th>
                        <th><?php echo $this->translate('Total','Admin'); ?></th>
						<?php if (!($user['role'] == 'Freelancer')) { ?>
                        <th></th>
						<?php } ?>
                    </tr>
                    </thead>
                    <tbody>
						<tr ng-repeat="item in itermdtpmacs[language.id]">
							<td>{{ $index + 1 }}</td>
							<td>{{ item.name }}</td>
							<td>{{ item.file.name }}</td>
							<td>{{ item.software.name }}</td>
							<td>{{ item.unit.name }}</td>
							<td>{{ item.rate }}</td>
							<td>{{ item.quantity }}</td>
							<td>{{ item.total }}</td>
							<td>
							<?php if (!($user['role'] == 'Freelancer')) { ?>
												<span ng-click="editDesktopMac($index, item.id, language.id)">
													<i class="fa fa-edit"></i>
												</span>  &nbsp;&nbsp;
								<span ng-click="deleteDesktopMac($index, item.id, language.id)"><i class="fa fa-trash-o text-danger"></i></span>
								<?php } ?>
							</td>
						</tr>                    
					</tbody>
                </table>
            </div>
			<?php if (!($user['role'] == 'Freelancer')) { ?>
            <div class="text-center">
				 <a class="btn btn-outline btn-primary"
                   ng-click="addDesktopMac(language.id)"><?php echo $this->translate('Add Item','Admin'); ?></a>
				   
                
            </div>
			<?php } ?>
            
        </div>
        <div ng-show="task.type.id==5">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
						<th><?php echo $this->translate('Item','Admin'); ?> - <span class="text-info">DTP <i class="fa fa-windows"></i></span></th>
                        <th><?php echo $this->translate('File','Admin'); ?></th>
                        <th><?php echo $this->translate('DTP Software','Admin'); ?></th>
                        <th><?php echo $this->translate('Unit','Admin'); ?></th>
                        <th><?php echo $this->translate('Unit Price','Admin'); ?></th>
                        <th><?php echo $this->translate('Quantity','Admin'); ?></th>
                        <th><?php echo $this->translate('Total','Admin'); ?></th>
						<?php if (!($user['role'] == 'Freelancer')) { ?>
                        <th></th>
						<?php } ?>
                    </tr>
                    </thead>
                    <tbody>
						<tr ng-repeat="item in itermdtppcs[language.id]">
							<td>{{ $index + 1 }}</td>
							<td>{{ item.name }}</td>
							<td>{{ item.file.name }}</td>
							<td>{{ item.software.name }}</td>
							<td>{{ item.unit.name }}</td>
							<td>{{ item.rate }}</td>
							<td>{{ item.quantity }}</td>
							<td>{{ item.total }}</td>
							<?php if (!($user['role'] == 'Freelancer')) { ?>
							<td>
												<span ng-click="editDesktopPc($index, item.id, language.id)">
													<i class="fa fa-edit"></i>
												</span> &nbsp;&nbsp;
								<span ng-click="deleteDesktopPc($index, item.id, language.id)"><i class="fa fa-trash-o text-danger"></i></span>
								
							</td>
							<?php } ?>
						</tr>                    
					</tbody>
                </table>
            </div>
			<?php if (!($user['role'] == 'Freelancer')) { ?>
            <div class="text-center">
                <a class="btn btn-outline btn-primary"
                   ng-click="addDesktopPc(language.id)"><?php echo $this->translate('Add Item','Admin'); ?></a>
            </div>
			<?php } ?>
		</div>	
