	<div ng-show="task.type.id==6">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms</th>
					<th>File</th>
                    <th>ENG Category </th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <?php if (!($user['role'] == 'Freelancer')) { ?>
					<th>Action</th>
					<?php  } ?>	
                </tr>
                </thead>
                <tbody>
					<tr ng-repeat="item in itermengineerings[language.id]">
						<td>{{ $index + 1 }}</td>
						<td>{{ item.name }}</td>
						<td>{{ item.file.name }}</td>
						<td>{{ item.engineeringcategory.category }}</td>
						<td>{{ item.unit.name }}</td>
						<td>{{ item.rate }}</td>
						<td>{{ item.quantity }}</td>
						<td>{{ item.total }}</td>
						<?php if (!($user['role'] == 'Freelancer')) { ?>
						<td>
						
											<span ng-click="editEng($index, item.id, language.id)">
												<i class="fa fa-edit"></i>
											</span> &nbsp;&nbsp;
							<span ng-click="deleteEngineering($index, item.id, language.id)"><i class="fa fa-trash-o text-danger"></i></span>
						
						</td>
						<?php  } ?>	
					</tr>                
				</tbody>
            </table>
        </div>
        <?php if (!($user['role'] == 'Freelancer')) { ?>
        <div class="text-center">
            <a class="btn btn-outline btn-primary"
                   ng-click="addEngineering(language.id)">Add Iterm</a>
        </div>
		<?php  } ?>	
	</div>	
