<!-- if the task status is pooling, then show accept button, if the task is accpeted, then hide the accept button, and show upload files section -->
<form class="form-horizontal" ng-show="task.status.id == 3 || task.status.id == 4 || task.status.id == 6">
	<div class="form-group">
		<div class="col-sm-12">
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-6">
					<a href="" class="btn btn-block btn-warning" type="submit" ng-click="Accept(task.id)">Accept</a>
				</div>
				<div class="col-md-3"></div>
			</div>
		</div>
	</div>
</form>
<div class="hr-line-dashed"></div>
<!-- end of accept button section -->
<!-- if the task is accepted, then show final fileupload section and Reviewing button, and hide the accept button -->
<div ng-show="task.status.id == 2 || task.status.id == 8" class="row" ng-controller="AppController" nv-file-drop="" uploader="uploader">

					
	<table class="table table-bordered">
			<thead>
			<tr>
					<th>#</th>
					<th>Final Task Files</th>
					<th>Size</th>
					<th>Time Stamp</th>
					<th>Action</th>
			</tr>
			</thead>
			<tbody>
			<tr ng-repeat="file in taskfiles">
					<td>{{$index + 1}}</td>
					<td><a href="{{file.path}}"><i class="fa fa-file"></i> {{ file.name }} </a> </td>
					<td>{{ file.size/1024/1024|number:2 }} MB</td>
					<td>{{ file.date }}</td>
					<td><a href="#" ng-click="calTo('#modal-taskfile','#TaskDetailController', 'removetaskItem', file)"> <i class="fa fa-trash"></i></a> </td>
			</tr>
			</tbody>
	</table>
	<div class="text-center m-t-md" id="taskfiles">
		<input type="file" nv-file-select="" uploader="uploadertask" multiple="multiple" />
	</div>
	<!--<div class="text-center m-t-md">
		<a href="#" class="btn btn-sm btn-primary"><i class="fa fa-cloud-upload"></i> Upload final task files</a>
	</div>-->
</div>
<div class="hr-line-dashed"></div>
<div ng-show="task.status.id == 2"></div>

<form class="form-horizontal" ng-show="task.status.id == 2 || task.status.id == 8">
	<div class="form-group">
		<div class="col-sm-12">
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-6">

					<a href="#" class="btn btn-block btn-success" type="submit" ng-click="SubmitReview(task.id)">Submit
						for Reviewing</a><!-- if there is no file (at least one file) in the final file upload section, then disable the Reviewing button -->
				</div>
				<!-- if there is no file (at least one file) in the final file upload section, then disable the Reviewing button -->
				<div class="col-md-3"></div>
			</div>
		</div>
	</div>
</form>
