<!-- if the task status is pooling, then show accept button, if the task is accpeted, then hide the accept button, and show upload files section -->
<form class="form-horizontal" ng-show="task.status.id == 3 || task.status.id == 4 || task.status.id == 6">
	<div class="form-group">
		<div class="col-sm-12">
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-6">
					<a href="" class="btn btn-block btn-warning" type="submit" ng-click="Accept(task.id)">Accept</a>
				</div>
				<div class="col-md-3"></div>
			</div>
		</div>
	</div>
</form>
<div class="hr-line-dashed"></div>
<!-- end of accept button section -->
<!-- if the task is accepted, then show final fileupload section and Reviewing button, and hide the accept button -->
<div ng-show="task.status.id == 2" class="row" ng-controller="AppController" nv-file-drop="" uploader="uploader">
	<div class="col-lg-5">
		<dl class="dl-horizontal">
			<dt>Project Files:</dt>
			<dd>
				 <ul class="list-unstyled project-files tooltip-demo" >
				<li ng-repeat="file in files">
					<a href="{{file.path}}" data-toggle="tooltip" data-placement="left" title="" data-original-title="{{ file.size/1024/1024|number:2 }} MB | {{ file.date }}"><i class="fa fa-file"></i> {{ file.name }}</a>
					
					
				</li>
            </ul>
			</dd>
		</dl>
	</div>
	<div class="col-lg-7">
		<div class="col-lg-7" id="modal-taskfile">
        <dl class="dl-horizontal">
            <dt>Final Files:</dt> 
                <dd>
					<ul class="list-unstyled project-files tooltip-demo">
						<li ng-repeat="file in taskfiles">
							<a href="{{file.path}}" data-toggle="tooltip" data-placement="left" title="" data-original-title="{{ file.size/1024/1024|number:2 }} MB | {{ file.date }}"><i class="fa fa-file"></i> {{ file.name }}</a>
							<a href="#" ng-click="calTo('#modal-taskfile','#TaskDetailController',
	                                           'removetaskItem', file)"><i class="fa fa-trash"></i></a>
						</li>					</ul>
					<div class="text-center m-t-md" id="taskfiles">
						<input type="file" nv-file-select="" uploader="uploadertask" multiple="multiple" />
					</div>
                </dd>
            </dl>
    	</div>
	</div>
</div>
<div class="hr-line-dashed" ng-show="task.status.id == 2"></div>

<form class="form-horizontal" ng-show="task.status.id == 2">
	<div class="form-group">
		<div class="col-sm-12">
			<div class="row">
				<div class="col-md-3"></div>
				<div class="col-md-6">
					
					<a href="#" class="btn btn-block btn-success" type="submit" ng-click="SubmitReview(task.id)">Submit
						for Reviewing</a><!-- if there is no file (at least one file) in the final file upload section, then disable the Reviewing button -->
				</div>
				<!-- if there is no file (at least one file) in the final file upload section, then disable the Reviewing button -->
				<div class="col-md-3"></div>
			</div>
		</div>
	</div>
</form>
