	<div ng-show="task.type.id>=7">
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Iterms</th>
                    <th>Unit </th>
                    <th>Unit Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
					<tr ng-repeat="item in iterminterpretings[language.id]">
						<td>{{ $index + 1 }}</td>
						<td>{{ item.name }}</td>
						<td>{{ item.unit.name }}</td>
						<td>{{ item.rate }}</td>
						<td>{{ item.quantity }}</td>
						<td>{{ item.total }}</td>
						<td>
						<?php if (!($user['role'] == 'Freelancer')) { ?>
											<span ng-click="editInt($index, item.id, language.id)">
												<i class="fa fa-edit"></i>
											</span>
						<?php } ?>					
											 &nbsp;&nbsp;
							<span ng-click="deleteInt($index, item.id, language.id)"><i class="fa fa-trash-o text-danger"></i></span>
						</td>
					</tr>                
				</tbody>
            </table>
        </div>
        <div class="text-center">
            <a class="btn btn-outline btn-primary"
                   ng-click="addInt(language.id)">Add Iterm</a>
        </div>
	</div>	
