		<div ng-show="task.type.id==1">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th><?php echo $this->translate('Task','Admin'); ?> - <span class="text-info">Translation (No TM)</span></th>
						<th><?php echo $this->translate('File','Admin'); ?></span></th>
                        <th><?php echo $this->translate('Unit','Admin'); ?> </th>
                        <th><?php echo $this->translate('Unit Price','Admin'); ?></th>
                        <th><?php echo $this->translate('Quantity','Admin'); ?></th>
                        <th><?php echo $this->translate('Total','Admin'); ?></th>
						<?php if (!($user['role'] == 'Freelancer')) { ?>
                        <th></th>
						<?php } ?>
                    </tr>
                    </thead>
                    <tbody>
                    <tbody>
                    <tr ng-repeat="item in itermnotmsnews[language.id]">
                        <td>{{ $index + 1 }}</td>
						<td>{{ item.name }}</td>
                        <td>{{ item.file.name }}</td>
                        <td><?php echo $this->translate("Source word") ?></td>
                        <td>{{ item.rate }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.total }}</td>
                        <?php if (!($user['role'] == 'Freelancer')) { ?>
						<td>



							  <span ng-click="editTranslationNoTMPrice($index, item.id, language.id)"><i class="fa fa-edit"></i></span>



                            &nbsp;&nbsp;
                            <span ng-click="deleteTranslationNoTMPrice($index, item.id, language.id)"><i class="fa fa-trash-o text-danger"></i></span>

                        </td>
						<?php } ?>
                    </tr>
                    </tbody>
                </table>
            </div>
			<?php if (!($user['role'] == 'Freelancer')) { ?>
            <div class="text-center">
                <a class="btn btn-outline btn-primary"
                   ng-click="addTranslationNoTMPrice(language.id)">Add Iterm</a>
            </div>
			<?php } ?>

        </div>
            <div  ng-show="task.type.id==2" class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th><?php echo $this->translate('Task','Admin'); ?> - <span class="text-info">Translation (Use TM)</span></th>
                        <th><?php echo $this->translate('Unit','Admin'); ?></th>
                        <th><?php echo $this->translate('Unit Price','Admin'); ?></th>
                        <th><?php echo $this->translate('Quantity','Admin'); ?></th>
                        <th><?php echo $this->translate('Total','Admin'); ?></th>
						<th></th>

                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>1</td>
                        <td>{{ itemtms[language.id][0].name }}</td>
                        <td>Source Word</td>
                        <td>{{ itemtms[language.id][0].rate }}</td>
                        <td>{{ itemtms[language.id][0].sourcerepetitions + itemtms[language.id][0].sourceyibai 
						+ itemtms[language.id][0].sourcejiuwu + itemtms[language.id][0].sourcebawu 
						+ itemtms[language.id][0].sourceqiwu + itemtms[language.id][0].sourcewushi + itemtms[language.id][0].sourcenomatch}}</td>
                        <td>{{ itemtms[language.id][0].total }}</td>
                        <td>
							<?php if (!($user['role'] == 'Freelancer')) { ?>
                            <a data-toggle="modal" ng-click="editTranslationTM(1, item.id, language.id)"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
							<?php } ?>
                            <a data-toggle="collapse" href="#use_tm_{{language.id}}"><i class="fa fa-eye"></i></a>

                        </td>
                    </tr>
                    <tr>
                        <td colspan="7">
                            <div id="use_tm_{{language.id}}" class="panel-collapse collapse">
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <thead>
                                        <tr>
                                            <th><?php echo $this->translate('TM Template','Admin'); ?></th>
                                            <th><?php echo $this->translate('Rate','Admin'); ?> (%)</th>
                                            <th><?php echo $this->translate('Unit Price','Admin'); ?></th>
                                            <th><?php echo $this->translate('Quantity (Word)','Admin'); ?></th>
                                            <th><?php echo $this->translate('Quantity','Admin'); ?></th>
                                        </tr>
                                        </thead>
                                        <tbody>
										<tr>
											<td>Repetitions</td>
											<td>{{ itemtms[language.id][0].raterepetitions_fl }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].raterepetitions_fl / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourcerepetitions }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].raterepetitions_fl / 100) * itemtms[language.id][0].sourcerepetitions | number:2 }}</td>
										</tr>
										<tr>
											<td>100%</td>
											<td>{{ itemtms[language.id][0].rateyibai_fl }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].rateyibai_fl / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourceyibai }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].rateyibai_fl / 100) * itemtms[language.id][0].sourceyibai | number:2 }}</td>
										</tr>
										<tr>
											<td>95%-99%</td>
											<td>{{ itemtms[language.id][0].ratejiuwu_fl }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratejiuwu_fl / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourcejiuwu }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratejiuwu_fl / 100) * itemtms[language.id][0].sourcejiuwu | number:2 }}</td>
										</tr>
										<tr>
											<td>85%-94%</td>
											<td>{{ itemtms[language.id][0].ratebawu_fl }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratebawu_fl / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourcebawu }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratebawu_fl / 100) * itemtms[language.id][0].sourcebawu | number:2 }}</td>
										</tr>
										<tr>
											<td>75%-84%</td>
											<td>{{ itemtms[language.id][0].rateqiwu_fl }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].rateqiwu_fl / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourceqiwu }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].rateqiwu_fl / 100) * itemtms[language.id][0].sourceqiwu | number:2 }}</td>
										</tr>
										<tr>
											<td>50%-74%</td>
											<td>{{ itemtms[language.id][0].ratewushi_fl }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratewushi_fl / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourcewushi }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratewushi_fl / 100) * itemtms[language.id][0].sourcewushi | number:2 }}</td>
										</tr>
										<tr>
											<td>No Match</td>
											<td>{{ itemtms[language.id][0].ratenomatch_fl }}</td>
											<td>{{ itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratenomatch_fl / 100 | number:2 }}</td>
											<td>{{ itemtms[language.id][0].sourcenomatch }}</td>
											<td>{{ (itemtms[language.id][0].rate_tmp * itemtms[language.id][0].ratenomatch_fl / 100) * itemtms[language.id][0].sourcenomatch | number:2 }}</td>
										</tr>
										<tr>
											<td colspan="4" align="right"><strong><?php echo $this->translate('Total','Admin'); ?></strong></td>
											<td class="text-info">{{ itemtms[language.id][0].total }}</td>
										</tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
