<?php echo $this->doctype(); ?>
<html lang="en" ng-app="project">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle()->setSeparator(' | ')->prepend($this->translate('PaperTask'))->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->appendStylesheet($this->basePath() . '/v2/css/style.css')
        ->appendStylesheet($this->basePath() . '/v2/css/custom.css')
        ->prependStylesheet($this->basePath() . '/v2/css/animate.css')
        ->prependStylesheet($this->basePath() . '/v2/css/plugins/iCheck/custom.css')
        ->prependStylesheet($this->basePath() . '/v2/font-awesome/css/font-awesome.css')
        ->prependStylesheet($this->basePath() . '/v2/css/bootstrap.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/v2/js/common.js')
        ->prependFile($this->basePath() . '/v2/js/plugins/pace/pace.min.js')
        ->prependFile($this->basePath() . '/v2/js/inspinia.js')
        ->prependFile($this->basePath() . '/v2/js/plugins/slimscroll/jquery.slimscroll.min.js')
        ->prependFile($this->basePath() . '/v2/js/plugins/metisMenu/jquery.metisMenu.js')
        ->prependFile($this->basePath() . '/v2/js/plugins/angular-file-upload/angular-file-upload.js')
        ->prependFile($this->basePath() . '/v2/js/plugins/console-sham/console-sham.js')
        ->prependFile($this->basePath() . '/v2/js/angular.min.js')
        ->prependFile($this->basePath() . '/v2/js/es5-sham.min.js')
        ->prependFile($this->basePath() . '/v2/js/es5-shim.min.js')
//        ->prependFile("http://nervgh.github.io/js/es5-sham.min.js")
//        ->prependFile("http://nervgh.github.io/js/es5-shim.min.js")
        ->prependFile($this->basePath() . '/v2/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/v2/js/jquery-2.1.1.js')
        ->prependFile($this->basePath() . '/v2/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/v2/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>


</head>

<body class="top-navigation">
    <div id="wrapper">
        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom white-bg">

                <!-- top nav -->
                <?php
                    switch($this->userData()['role']){

                        case 'Admin':
                            //staff menus here
                            switch($this->userData()['type']){
                                case 'Admin':
                                    include "admin/left-sidebar-admin.phtml";
                                    break;
                                case 'Financial Manager':
                                    include "admin/left-sidebar-staff-fm.phtml";
                                    break;
                                case 'Operation Manager':
                                    include "admin/left-sidebar-staff-om.phtml";
                                    break;
                                case 'Project Manager':
                                    include "admin/left-sidebar-staff-pm.phtml";
                                    break;
                                case 'Sales Director':
                                    include "admin/left-sidebar-staff-sd.phtml";
                                    break;
                                case 'Sales': // Sales Manager
                                    include "admin/left-sidebar-staff-sm.phtml";
                                    break;
                                case 'General Manager': // Inhouse
                                    include "admin/left-sidebar-staff-gm.phtml";
                                    break;
                                default:
                                    include "admin/left-sidebar-admin.phtml";
                                    // include "admin/left-sidebar-staff-fm.phtml";
                                    // include "admin/left-sidebar-staff-om.phtml";
                                    // include "admin/left-sidebar-staff-pm.phtml";
                                    // include "admin/left-sidebar-staff-sd.phtml";
                                    // include "admin/left-sidebar-staff-sm.phtml";
                                    // include "admin/left-sidebar-staff-gm.phtml";

                            }
                            break;
                        case 'Employer': // employer == client
                        case 'Client':
                            include "admin/top-nav-client.phtml";
                            break;
                        case 'Freelancer':
                            $this->userData()['isSenior'] ? include "admin/left-sidebar-senior-freelancer.phtml" : include "admin/left-sidebar-freelancer.phtml";
                            break;
                        default:
                            include "admin/left-sidebar-client.phtml";
                            // TODO: default menu
                    };
                ?>
                <!-- top nav -->
            </div>

        <!-- Main Wrapper -->

            <div class="wrapper wrapper-content">
                <div class="row">
                    <div class="col-lg-12">
                        <!-- Flash Messenger -->
                        <?php
                        $flash = $this->flashMessenger();
                        $flash->setMessageOpenFormat('<div%s>
                                 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                     &times;
                                 </button>
                                 <ul><li>')
                            ->setMessageSeparatorString('</li><li>')
                            ->setMessageCloseString('</li></ul></div>');

                        echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
                        echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
                        echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                        echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                        ?><!-- End Flash Messenger -->
                    </div>
                </div>
                <?php echo $this->content ?>
            </div>

            <!-- Footer -->
            <div class="footer">
                <div class="text-center">
                  <small class="copyright">
                      2015 &copy; <a href="<?php echo $this->url('home',array('lang'=>$this->translate('lang', 'Application'))) ?>">PaperTask.com</a> <?php echo $this->translate('All rights reserved.', 'Application'); ?>&nbsp;&nbsp;&nbsp;&nbsp;
                      <a href="<?php echo $this->url('terms',array('lang'=>$this->translate('lang', 'Application'))) ?>"><?php echo $this->translate('Terms of Use', 'Application'); ?></a>
                      &nbsp;&nbsp;&nbsp;
                      <a href="<?php echo $this->url('privacy',array('lang'=>$this->translate('lang', 'Application'))) ?>"><?php echo $this->translate('Privacy Policy', 'Application'); ?></a>
                  </small>

                    <div class="btn-group dropup">
                        <button type="button" class="btn btn-sm btn-default"><?php
                        if ($this->translate('lang', 'Application')=="en-US"){
                            echo "ENGLISH";
                        }
                        if ($this->translate('lang', 'Application')=="zh-CN"){
                            echo "简体中文";
                        }
                        ?></button>
                        <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li ><a href="<?php echo $this->url($this->route,array("lang"=>"en-US")) ?>">ENGLISH</a></li>
                            <li selected="selected"><a href="<?php echo $this->url($this->route,array("lang"=>"zh-CN")) ?>">简体中文</a></li>
                        </ul>
                    </div>
                </div>
            </div><!-- End Footer -->
        
        </div>
    </div>

    <?php echo $this->inlineScript() ?>
    <script>
        if(typeof(angular) != 'undefined' && typeof(angularApp) == 'undefined'){
            var angularApp = angularApp || angular.module('project', []);}
    </script>
</body>
</html>
