<!DOCTYPE html>
<?php
?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?php

    echo $this->headTitle()->setSeparator(' | ')->prepend($this->translate('PaperTask'))->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <meta name="description" content="">
    <meta name="author" content="">


    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/v2/css/style.css')
        ->prependStylesheet($this->basePath() . '/v2/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/v2/css/animate.css')
        ->prependStylesheet($this->basePath() . '/v2/css/bootstrap.min.css')
    ?>

    <?php
    echo $this->headScript()
        ->prependFile($this->basePath() . '/v2/js/landing/languages.js')
        ->prependFile($this->basePath() . '/v2//js/plugins/validate/jquery.validate.min.js')
        ->prependScript("angularApp = angular.module('project', []);")
        ->prependFile($this->basePath() . '/v2/js/angular.min.js')
    ?>
    <?php
    echo $this->inlineScript()
        ->prependScript("
        
        
        if(typeof(angular) != 'undefined' && typeof(angularApp) == 'undefined'){
            var angularApp = angularApp || angular.module('languages', []);
          }
       
         
        ");
    echo $this->inlineScript()
        ->prependScript("
            var LANG_CODE = '" . $this->lang_code . "';
            var EXITS_CONFIRM_TEXT = '" . $this->translate('This option was existed, please choose other') . "';
            ");     

    ?>

</head>

<body id="page-top" class="landing-page">
<div class="navbar-wrapper">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home',array('lang'=>$this->translate('lang', 'Application'))) ?>">
                    PAPERTASK
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="page-scroll" href="#ovewview"><?php echo $this->translate('Ovewview', 'Application'); ?></a></li>
                    <li><a class="page-scroll" href="#pricing"><?php echo $this->translate('Languages and Pricing', 'Application'); ?></a></li>
                    <li><a class="page-scroll" href="#freelancer"><?php echo $this->translate('Freelancer', 'Application'); ?></a></li>
                    <li><a class="page-scroll" href="#client"><?php echo $this->translate('client', 'Application'); ?></a></li>
                    <li><a class="page-scroll" href="#contact"><?php echo $this->translate('Contact', 'Application'); ?></a></li>
                    <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                    <li>
                        <a class="page-scroll" href="<?php echo $this->url('user',array("lang"=>$this->translate('lang', 'Application'))) ?>/login/"><i class="fa fa-sign-in"> <?php echo $this->translate('SIGN IN', 'Application'); ?></i></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="<?php echo $this->url('user',array("lang"=>$this->translate('lang', 'Application'))) ?>/register/"><span class="text-navy"><i class="fa fa-user"> <?php echo $this->translate('SIGN UP', 'Application'); ?></i></span></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>

    <!-- ******CONTENT****** -->

    <!-- Flash Messenger -->
    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <div>')
        ->setMessageSeparatorString('</div><div>')
        ->setMessageCloseString('</div></div>');

    echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
    echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
    ?><!-- End Flash Messenger -->

    <?php echo $this->content ?>

    <!-- Mainly scripts -->
    <script type="text/javascript" src="<?php echo $this->basePath() .'/v2/js/jquery-2.1.1.js'?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath() .'/v2/js/bootstrap.min.js'?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath() .'/v2/js/plugins/metisMenu/jquery.metisMenu.js'?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath() .'/v2/js/plugins/slimscroll/jquery.slimscroll.min.js'?>"></script>

    <!-- Custom and plugin javascript -->
    <script type="text/javascript" src="<?php //echo $this->basePath() .'/v2/js/inspinia.js'?>"></script>
    <script type="text/javascript" src="<?php //echo $this->basePath() .'/v2/js/plugins/pace/pace.min.js'?>"></script>
    <script type="text/javascript" src="<?php //echo $this->basePath() .'/v2/js/plugins/wow/wow.min.js'?>"></script>
    <!--[if !IE]>-->

    <script>

        $(document).ready(function () {

            $('body').scrollspy({
                target: '.navbar-fixed-top',
                offset: 80
            });

            // Page scrolling feature
            $('a.page-scroll').bind('click', function(event) {
                var link = $(this);
                $('html, body').stop().animate({
                    scrollTop: $(link.attr('href')).offset().top - 50
                }, 500);
                event.preventDefault();
            });
        });

        var cbpAnimatedHeader = (function() {
            var docElem = document.documentElement,
                    header = document.querySelector( '.navbar-default' ),
                    didScroll = false,
                    changeHeaderOn = 200;
            function init() {
                window.addEventListener( 'scroll', function( event ) {
                    if( !didScroll ) {
                        didScroll = true;
                        setTimeout( scrollPage, 250 );
                    }
                }, false );
            }
            function scrollPage() {
                var sy = scrollY();
                if ( sy >= changeHeaderOn ) {
                    $(header).addClass('navbar-scroll')
                }
                else {
                    $(header).removeClass('navbar-scroll')
                }
                didScroll = false;
            }
            function scrollY() {
                return window.pageYOffset || docElem.scrollTop;
            }
            init();

        })();

        // Activate WOW.js plugin for animation on scrol
        new WOW().init();

    </script>

</head>


</body>
</html>
