<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle()->setSeparator(' | ')->prepend($this->translate('PaperTask'))->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/animate.css')
                        ->prependStylesheet($this->basePath() . '/css/plugins/iCheck/custom.css')
                        ->prependStylesheet($this->basePath() . '/font-awesome/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            
            ->prependFile($this->basePath() . '/js/jquery-1.10.2.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body class="gray-bg">

    <div class="text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <a class="logo-name" href="<?php echo $this->url('home') ?>" style="font-size: 80px;">
                    <img src="<?php echo $this->basePath() . '/img/logo.png' ?>" alt="" width="200">
                </a>

            </div>

            <div id="content" class="">
                <!-- Flash Messenger -->
                <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <div>')
                    ->setMessageSeparatorString('</div><div>')
                    ->setMessageCloseString('</div></div>');

                echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
                echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
                echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                ?><!-- End Flash Messenger -->

                <?php echo $this->content ?>
            </div>

            <br><br><br>

            <p class="m-t">
            2015 &copy; <a href="<?php echo $this->url('home',array('lang'=>$this->translate('lang', 'Application'))) ?>">PaperTask.com</a> <?php echo $this->translate('All rights reserved.', 'Application'); ?>
            <a href="<?php echo $this->url('privacy',array('lang'=>$this->translate('lang', 'Application'))) ?>"><?php echo $this->translate('Privacy Policy', 'Application'); ?></a> |
            <a href="<?php echo $this->url('terms',array('lang'=>$this->translate('lang', 'Application'))) ?>"><?php echo $this->translate('Terms of Use', 'Application'); ?></a>
            </p>
            <br><br>

        </div>
    </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
