<!DOCTYPE html>
<?php
//var_dump($this->route);exit; 
?>
<html lang="en">
<head>
    <meta charset="utf-8">

    <?php echo $this->headTitle()->setSeparator(' | ')->prepend($this->translate('PaperTask'))->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <meta name="description" content="">
    <meta name="author" content="">


    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/v2/css/style.css')
        ->prependStylesheet($this->basePath() . '/v2/font-awesome/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/v2/css/animate.css')
        ->prependStylesheet($this->basePath() . '/v2/css/bootstrap.min.css')
    ?>

</head>

<body class="gray-bg">

    <div class="text-center loginscreen   animated fadeInDown">
        <div>
            <div>

                <a class="logo-name" href="<?php echo $this->url('home') ?>" style="font-size: 80px;">
                    <img src="<?php echo $this->basePath() . '/v2/img/logo.png' ?>" alt="" width="200">
                </a>

            </div>

                <!-- Flash Messenger -->
                <?php
                $flash = $this->flashMessenger();
                $flash->setMessageOpenFormat('<div%s>
                     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                         &times;
                     </button>
                     <div>')
                    ->setMessageSeparatorString('</div><div>')
                    ->setMessageCloseString('</div></div>');

                echo $flash->render('error', array('alert', 'alert-dismissable', 'alert-danger'));
                echo $flash->render('info', array('alert', 'alert-dismissable', 'alert-info'));
                echo $flash->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                echo $flash->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                ?><!-- End Flash Messenger -->

                <?php echo $this->content ?>
        </div>
    </div>

    <br /><br /><br /><br />
    <div class="row m-b-lg text-center">
        <p><strong>&copy; 2015 <a href="<?php echo $this->url('home',array('lang'=>$this->translate('lang', 'Application'))) ?>">PaperTask.com</a> <?php echo $this->translate('All rights reserved.', 'Application'); ?></strong> &nbsp;&nbsp;&nbsp; <a href="<?php echo $this->url('terms',array('lang'=>$this->translate('lang', 'Application'))) ?>"><?php echo $this->translate('Terms of Use', 'Application'); ?></a>
                &nbsp;&nbsp;&nbsp;
                <a href="<?php echo $this->url('privacy',array('lang'=>$this->translate('lang', 'Application'))) ?>"><?php echo $this->translate('Privacy Policy', 'Application'); ?></a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <div class="btn-group dropup">
                <button type="button" class="btn btn-sm btn-default"><?php
                if ($this->translate('lang', 'Application')=="en-US"){
                    echo "ENGLISH";
                }
                if ($this->translate('lang', 'Application')=="zh-CN"){
                    echo "简体中文";
                }
                ?></button>
                <button type="button" class="btn btn-sm btn-default dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <ul class="dropdown-menu" role="menu">
					
                    <li ><a href="<?php echo $this->url($this->route,array("lang"=>"en-US")) ?>">ENGLISH</a></li>
                    <li selected="selected"><a href="<?php echo $this->url($this->route,array("lang"=>"zh-CN")) ?>">简体中文</a></li>
                </ul>
            </div>
        </p>
    </div>


    <!-- Mainly scripts -->
    <script type="text/javascript" src="<?php echo $this->basePath() .'/v2/js/jquery-2.1.1.js'?>"></script>
    <script type="text/javascript" src="<?php echo $this->basePath() .'/v2/js/bootstrap.min.js'?>"></script>

</head>

</div>
</body>
</html>
