<?php $this->headTitle($this->translate('Projects list')) ?>
<!-- Le styles -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<!-- Scripts -->
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.js')
    ->prependFile($this->basePath() . '/js/admin/dashboard/client-dashboard.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload', 'ui.bootstrap']);")
    ->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-tpls-0.11.2.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-0.11.2.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js')
?>

<?php
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>
<div class="row" ng-controller="DashboardProjectController">
	<div class="col-lg-12">
		<div class="wrapper wrapper-content animate fadeInUp">
					<div class="row">
                        <div class="col-lg-6">
                            <div class="widget style1 navy-bg">
                                <a href="<?php echo $this->url('admin', array('controller' => 'project',
                    'action' => 'order-translation',"lang"=>$this->translate('lang','Application'))) ?>" style="color: #fff;">
                                <div class="row">
                                    <div class="col-xs-4">
                                        <i class="fa fa-archive fa-5x"></i>
                                    </div>
                                    <div class="col-xs-8 text-left">
                                        <h2 class="font-bold">Order a Translation</h2>
                                        <span>Please provide translation information, the project will be process right away. </span>
                                    </div>
                                </div>
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="widget style1 lazur-bg">
                                <a href="<?php echo $this->url('admin', array('controller' => 'project',
                    'action' => 'client-quotes',"lang"=>$this->translate('lang','Application'))) ?>" style="color: #fff;">
                                <div class="row">
                                    <div class="col-xs-4">
                                        <i class="fa fa-files-o fa-5x"></i>
                                    </div>
                                    <div class="col-xs-8 text-left">
                                        <h2 class="font-bold">I Need a Quote</h2>
                                        <span>Please provide translation information, the quote will be provided in the shortest time.</span>
                                    </div>
                                </div>
                                </a>
                            </div>
                        </div>
                    </div>
				</br>
			<div class="ibox">
				<div class="ibox-title">
					<h5><i class="fa fa-files-o"></i> Quotation Waiting for You to Approve</h5>
				</div>
				<div class="ibox-content" >
						<div id="projectsList">
							<div class="project-list">
								<table class="table table-hover">
								<tbody>
								<tr ng-repeat="project in quoteprojects">
									<td class="project-status">
										<span class="label label-warning" ng-if="project.number">{{ project.number }}</span>
										<span class="label label-{{ ProjectStatus.get(project.status).decorator }}"
											>{{ ProjectStatus.get(project.status).name }}</span>
									</td>
									<td class="project-status">
										<span class="btn btn-outline btn-{{ ProjectServiceLevel.get(project.serviceLevel).decorator }}
										btn-sm">{{ ProjectServiceLevel.get(project.serviceLevel).name }}</span>
									</td>
									<td class="project-title">
										<strong><?php echo $this->translate('Contract with') ?> {{ project.client.company.name }}</strong>
										<br/>
										<div class="tooltip-demo">
											<span ng-repeat="type in project.client.types">
												<code data-original-title="{{ ProjectType.get(type).name }}"
												 title="" data-placement="top" data-toggle="tooltip">{{ ProjectType.get(type).name_short }}</code>
												<!-- <code {{ ProjectType.get(type) }}>{{ type.name_short }}</code> -->
											</span>
										</div>
									</td>
									<td class="project-title">
										<span class="">{{ project.reference }}</span>
										<br/>
										<small>{{ DateFormatter.short(project.startDate) }} - {{ DateFormatter.short(project.dueDate) }}</small>
									</td>
									<td class="project-title">
										{{ project.client.name }}
										<br/>
										{{ project.client.company.name }}
									</td>
									<td class="project-actions">
										<a href="" class="btn btn-white btn-sm"
										   ng-click="goToQuote(project)"><i class="fa fa-folder"></i> View </a>
										<a href="" class="btn btn-primary btn-sm"
										   ng-click="quoteAccepted(project)"><i class="fa fa-check-square-o"></i> Accept  </a>
									</td>
								</tr>
								</tbody>
								</table>
							</div>
					</div>
					<div class="text-right">
                        <button type="button" class="btn btn-xs btn-info" ng-click="gotoQuotingProject($index)"><i class="fa fa-chevron-right"></i> See All</button>
                    </div>
				</div>
			</div>
			
			<div class="ibox">
				<div class="ibox-title">
					<h5><i class="fa fa-archive"></i> Ongoing Projects</h5>
				</div>
				<div class="ibox-content">
						<div id="projectsList">
							<div class="project-list">
								<table class="table table-hover">
								<tbody>
								<tr ng-repeat="project in ongoingprojects">
									<td class="project-status">
										<span class="label label-warning" ng-if="project.number">{{ project.number }}</span>
										<span class="label label-{{ ProjectStatus.get(project.status).decorator }}"
											>{{ ProjectStatus.get(project.status).name }}</span>
									</td>
									<td class="project-status">
										<span class="btn btn-outline btn-{{ ProjectServiceLevel.get(project.serviceLevel).decorator }}
										btn-sm">{{ ProjectServiceLevel.get(project.serviceLevel).name }}</span>
									</td>
									<td class="project-title">
										<strong><?php echo $this->translate('Contract with') ?> {{ project.client.company.name }}</strong>
										<br/>
										<div class="tooltip-demo">
											<span ng-repeat="type in project.client.types">
												<code data-original-title="{{ ProjectType.get(type).name }}"
												 title="" data-placement="top" data-toggle="tooltip">{{ ProjectType.get(type).name_short }}</code>
											</span>
										</div>
									</td>
									<td class="project-title">
										<span class="">{{ project.reference }}</span>
										<br/>
										<small>{{ DateFormatter.short(project.startDate) }} - {{ DateFormatter.short(project.dueDate) }}</small>
									</td>
									<td class="project-title">
										{{ project.client.name }}
										<br/>
										{{ project.client.company.name }}
									</td>
									<td class="project-actions">
										<a href="#" class="btn btn-white btn-sm"
										   ng-click="goToDetail(project)"><i class="fa fa-folder"></i> View </a>
									</td>
								</tr>
								</tbody>
								</table>
							</div>
					</div>
					<div class="text-right">
                        <button type="button" class="btn btn-xs btn-info" ng-click="gotoOngoignProject()"><i class="fa fa-chevron-right"></i> See All</button>
                    </div>
				</div>
			</div>
			
			<div class="ibox">
				<div class="ibox-title">
					<h5><i class="fa fa-archive"></i> Projects For You To Review</h5>
				</div>
				<div class="ibox-content">
						<div id="projectsList">
							<div class="project-list">
								<table class="table table-hover">
								<tbody>
								<tr ng-repeat="project in reviewprojects">
									<td class="project-status">
										<span class="label label-warning" ng-if="project.number">{{ project.number }}</span>
										<span class="label label-{{ ProjectStatus.get(project.status).decorator }}"
											>{{ ProjectStatus.get(project.status).name }}</span>
									</td>
									<td class="project-status">
										<span class="btn btn-outline btn-{{ ProjectServiceLevel.get(project.serviceLevel).decorator }}
										btn-sm">{{ ProjectServiceLevel.get(project.serviceLevel).name }}</span>
									</td>
									<td class="project-title">
										<strong><?php echo $this->translate('Contract with') ?> {{ project.client.company.name }}</strong>
										<br/>
										<div class="tooltip-demo">
											<span ng-repeat="type in project.client.types">
												<code data-original-title="{{ ProjectType.get(type).name }}"
												 title="" data-placement="top" data-toggle="tooltip">{{ ProjectType.get(type).name_short }}</code>
											</span>
										</div>
									</td>
									<td class="project-title">
										<span class="">{{ project.reference }}</span>
										<br/>
										<small>{{ DateFormatter.short(project.startDate) }} - {{ DateFormatter.short(project.dueDate) }}</small>
									</td>
									<td class="project-title">
										{{ project.client.name }}
										<br/>
										{{ project.client.company.name }}
									</td>
									<td class="project-actions">
										<a href="#" class="btn btn-white btn-sm"
										   ng-click="goToDetail(project)"><i class="fa fa-folder"></i> View </a>
									</td>
								</tr>
								</tbody>
								</table>
							</div>
					</div>
					<div class="text-right">
                        <button type="button" class="btn btn-xs btn-info" ng-click="gotoReviewProject()"><i class="fa fa-chevron-right"></i> See All</button>
                    </div>
				</div>
			</div>
			
			<div class="ibox">
                        <div class="ibox-title">
					<h5><i class="fa fa-archive"></i>Rejected Projects</h5>
				</div>
				<div class="ibox-content">
						<div id="projectsList">
							<div class="project-list">
								<table class="table table-hover">
								<tbody>
								<tr ng-repeat="project in rejectedprojects">
									<td class="project-status">
										<span class="label label-warning" ng-if="project.number">{{ project.number }}</span>
										<span class="label label-{{ ProjectStatus.get(project.status).decorator }}"
											>{{ ProjectStatus.get(project.status).name }}</span>
									</td>
									<td class="project-status">
										<span class="btn btn-outline btn-{{ ProjectServiceLevel.get(project.serviceLevel).decorator }}
										btn-sm">{{ ProjectServiceLevel.get(project.serviceLevel).name }}</span>
									</td>
									<td class="project-title">
										<strong><?php echo $this->translate('Contract with') ?> {{ project.client.company.name }}</strong>
										<br/>
										<div class="tooltip-demo">
											<span ng-repeat="type in project.client.types">
												<code data-original-title="{{ ProjectType.get(type).name }}"
												 title="" data-placement="top" data-toggle="tooltip">{{ ProjectType.get(type).name_short }}</code>
											</span>
										</div>
									</td>
									<td class="project-title">
										<span class="">{{ project.reference }}</span>
										<br/>
										<small>{{ DateFormatter.short(project.startDate) }} - {{ DateFormatter.short(project.dueDate) }}</small>
									</td>
									<td class="project-title">
										{{ project.client.name }}
										<br/>
										{{ project.client.company.name }}
									</td>
									<td class="project-actions">
										<a href="#" class="btn btn-white btn-sm"
										   ng-click="goToDetail(project)"><i class="fa fa-folder"></i> View </a>
									</td>
								</tr>
								</tbody>
								</table>
							</div>
					</div>
					<div class="text-right">
                        <button type="button" class="btn btn-xs btn-info" ng-click="gotoRejectedProject()"><i class="fa fa-chevron-right"></i> See All</button>
                    </div>
				</div>
			</div>
			
			<div class="ibox">
                        <div class="ibox-title">
                            <h5><i class="fa fa-archive"></i> Unpaid Projects</h5>
                        </div>
                        <div class="ibox-content">

                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Project ID</th>
                                        <th>Project Reference</th>
                                        <th>Status</th>
                                        <th>Completed Date</th>
                                        <th>Amount</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr ng-repeat="project in unpayprojects">
                                        <td>{{ project.id }}</td>
                                        <td>{{ project.reference }}</td>
                                        <td>{{ ProjectStatus.get(project.status).name }}</td>
                                        <td>{{ DateFormatter.short(project.dueDate) }}</td>
                                        <td>{{ project.currency}} {{ project.total_tmp | number:2}}</td>
                                    </tr>
                                    
                                    </tbody>
                                </table>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="text-right">
                                    <button type="button" class="btn btn-xs btn-info"  ng-click="gotoUnpaidProject()"><i class="fa fa-chevron-right"></i> See All</button>
                            </div>
                        </div>
                    </div>
		</div>
	</div>
</div>