<?php $this->headTitle($this->translate('My Tasks')) ?>
<!-- Scripts -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.css')
	 //->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css')
    //->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    //->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
    //->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<?php
$this->headScript ()
	->prependFile($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.js')
    ->prependFile($this->basePath() . '/js/admin/dashboard/freelancer-dashboard.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-tpls-0.11.2.min.js')
    ->prependScript("angularApp = angular.module('project', []);")
    ->prependScript("FREELANCER_ID = {$this->freelancer_id};")
    ->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js');

$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
    ");
?>
					
<div class="row" ng-controller="DashboardFreelancerTaskControler" ng-init="init()">
	<div class="col-lg-12">
		<div class="wrapper wrapper-content animated fadeInUp">
			<div class="ibox">
				<div class="ibox-title">
					<h5><i class="fa fa-tasks"></i> Tasks Waiting For You To Accept</h5>
				</div>
				<div class="ibox-content">
					 <div class="project-list">
						<table class="table table-hover">
							<tbody>
								<tr ng-repeat="task in assigingtasks">
									<td class="project-status"><span
										class="label label-{{ TaskStatus.get(task.status).decorator }}">{{
											TaskStatus.get(task.status).name }}</span>
									</td>
									<td class="project-title"><strong>{{
											task.project.reference }} </strong> <br> <strong
										class="text-info">{{ task.project.id }}-{{ task.id }}</strong>
									</td>
									<td class="project-title">
										<div class="tooltip-demo">
											<code>{{ task.project.sourceLanguage.name }}</code>
											<i class="fa fa-arrow-right"></i>
											<code>{{ task.language.name }}</code>
											<br>
											<code  data-toggle="tooltip"  tooltip-placement="top"  tooltip="{{ProjectType.get(task.type).tootip}}"  ng-bind-html="ProjectType.get(task.type).name_task" compile-template> </code>
											| Due: {{ DateFormatter.short(task.dueDate) }} 
										</div>
									</td>
									<td class="project-title">{{ task.project.client.name }} <br /> <small>{{ task.project.client.company.name }}</small>
									</td>
									<td class="project-actions"><a href=""
										ng-click="Accept(task.id)"
										class="btn btn-info btn-sm"><i class="fa fa-check-square-o"></i>
											Accept</a> <a href="" class="btn btn-white btn-sm"
										ng-click="View(task.id)"><i class="fa fa-folder"></i> View</a>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="text-right">
                        <button type="button" class="btn btn-xs btn-info" ng-click="gotoWaitingTask()"><i class="fa fa-chevron-right"></i> See All</button>
                    </div>
				</div>
			</div>
			
			<div class="ibox">
				<div class="ibox-title">
					<h5><i class="fa fa-tasks"></i> Tasks Waiting For You To Review</h5>
				</div>
				<div class="ibox-content">
					 <div class="project-list">
						<table class="table table-hover">
							<tbody>
								<tr ng-repeat="task in reviewingtasks">
									<td class="project-status"><span
										class="label label-{{ TaskStatus.get(task.status).decorator }}">{{
											TaskStatus.get(task.status).name }}</span>
									</td>
									<td class="project-title"><strong>{{
											task.project.reference }} </strong> <br> <strong
										class="text-info">{{ task.project.id }}-{{ task.id }}</strong>
									</td>
									<td class="project-title">
										<div class="tooltip-demo">
											<code>{{ task.project.sourceLanguage.name }}</code>
											<i class="fa fa-arrow-right"></i>
											<code>{{ task.language.name }}</code>
											<br>
											<code  data-toggle="tooltip"  tooltip-placement="top"  tooltip="{{ProjectType.get(task.type).tootip}}"  ng-bind-html="ProjectType.get(task.type).name_task" compile-template> </code>
											| Due: {{ DateFormatter.short(task.dueDate) }} 
										</div>
									</td>
									<td class="project-title">{{ task.project.client.name }} <br /> <small>{{ task.project.client.company.name }}</small>
									</td>
									<td class="project-actions">
										<a href="" class="btn btn-white btn-sm"
										ng-click="View(task.id)"><i class="fa fa-folder"></i> View</a>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="text-right">
                        <button type="button" class="btn btn-xs btn-info" ng-click="gotoReviewTask()"><i class="fa fa-chevron-right"></i> See All</button>
                    </div>
				</div>
			</div>
			
			
			<div class="ibox">
				<div class="ibox-title">
					<h5><i class="fa fa-tasks"></i> Ongoing Tasks</h5>
				</div>
				<div class="ibox-content">
					 <div class="project-list">
						<table class="table table-hover">
							<tbody>
								<tr ng-repeat="task in ongoingtasks">
									<td class="project-status"><span
										class="label label-{{ TaskStatus.get(task.status).decorator }}">{{
											TaskStatus.get(task.status).name }}</span>
									</td>
									<td class="project-title"><strong>{{
											task.project.reference }} </strong> <br> <strong
										class="text-info">{{ task.project.id }}-{{ task.id }}</strong>
									</td>
									<td class="project-title">
										<div class="tooltip-demo">
											<code>{{ task.project.sourceLanguage.name }}</code>
											<i class="fa fa-arrow-right"></i>
											<code>{{ task.language.name }}</code>
											<br>
											<code  data-toggle="tooltip"  tooltip-placement="top"  tooltip="{{ProjectType.get(task.type).tootip}}"  ng-bind-html="ProjectType.get(task.type).name_task" compile-template> </code>
											| Due: {{ DateFormatter.short(task.dueDate) }} 
										</div>
									</td>
									<td class="project-title">{{ task.project.client.name }} <br /> <small>{{ task.project.client.company.name }}</small>
									</td>
									<td class="project-actions">
										<a href="" class="btn btn-white btn-sm"
										ng-click="View(task.id)"><i class="fa fa-folder"></i> View</a>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="text-right">
                        <button type="button" class="btn btn-xs btn-info" ng-click="gotoOngoingTask()"><i class="fa fa-chevron-right"></i> See All</button>
                    </div>
				</div>
			</div>
			
			<div class="ibox">
                        <div class="ibox-title">
                            <h5><i class="fa fa-tasks"></i> Unpaid Tasks</h5>
                        </div>
                        <div class="ibox-content">

                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>Task Reference</th>
                                        <th>Task Name</th>
                                        <th>Status</th>
                                        <th>Completed Date</th>
                                        <th>Amount</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr ng-repeat="task in unpaidtasks">
                                        <td>{{task.project.id}}-{{task.id}}</td>
                                        <td>{{ task.name }}</td>
                                        <td>{{ TaskStatus.get(task.status).name }}</td>
                                        <td> {{ DateFormatter.short(task.dueDate) }}</td>
                                        <td>{{ task.project.currency }} {{ task.total | number:2 }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="hr-line-dashed"></div>
                            <div class="text-right">
                                    <button type="button" class="btn btn-xs btn-info" ng-click="gotoUnpaidTask()"><i class="fa fa-chevron-right"></i> See All</button>
                            </div>
                        </div>
                    </div>
		</div>
	</div>
</div>
 <script>
 $(document).ready(function(){

     $('#loading-example-btn').click(function () {
         btn = $(this);
         simpleLoad(btn, true)

         // Ajax example
//         $.ajax().always(function () {
//             simpleLoad($(this), false)
//         });

         simpleLoad(btn, false)
     });
 });

 function simpleLoad(btn, state) {
     if (state) {
         btn.children().addClass('fa-spin');
         btn.contents().last().replaceWith(" Loading");
     } else {
         setTimeout(function () {
             btn.children().removeClass('fa-spin');
             btn.contents().last().replaceWith(" Refresh");
         }, 2000);
     }
 }
    $(document).ready(function(){
        $('.dtbox').DateTimePicker();

        // trigger datetime picker when click to calendar icon
        // TODO: this is not working
        $('i.fa.fa-calendar').on('click', function(e){
            console.log('clicked');
            e.preventDefault();

            $(this).parents('.input-group').find('input[readonly]').click();
        });
    });
</script>
