<?php $this->headTitle($this->translate('Dashboard')) ?>
<!-- Scripts -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/footable/footable.core.css')
?>

<?php
$this->headScript ()
    ->prependFile($this->basePath() . '/v2/js/admin/dashboard/freelancer-dashboard.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/angular-bootstrap/ui-bootstrap-tpls-0.11.2.min.js')
    ->prependScript("angularApp = angular.module('project', []);")
    ->prependScript("FREELANCER_ID = {$this->freelancer_id};")
	->prependScript("USER_FREELANCER_ID = {$this->user_id};")
    ->prependFile($this->basePath() . '/v2/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/footable/footable.all.min.js');
$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
    ");
?>

    <script>
        $(document).ready(function() {

            $('.footable').footable();

        });

    </script>
<div class="row" ng-controller="DashboardFreelancerTaskControler" ng-init="init()">
    
    <div class="animated fadeInRight" ng-repeat="task in rejectedtasks">
        <div class="row">
            <div class="col-lg-12">

                <div class="ibox" style="font-size: 16px;">
                    <div class="ibox-title">
                        <span class="label label-danger pull-right" style="font-size: 15px;">{{TaskStatus.get(task.status).name }}</span>
                        <h3><span class="text-navy">{{ task.task_number }}</span> &nbsp;{{ task.project.reference }}</h3>
                    </div>
                    <div class="ibox-content product-box">

                        <div class="product-desc">
                            <div><strong><?php echo $this->translate('Translation Languages:','Admin'); ?> </strong><strong><code>{{ task.project.sourceLanguage.name }} <i class="fa fa-arrow-right"></i> {{ task.language.name }}</code></strong></div>
                            <div><strong><?php echo $this->translate('Due Date:','Admin'); ?></strong> <strong><code>{{ DateFormatter.short(task.dueDate) }}</code></strong></div>
                            <div><strong><?php echo $this->translate('Task Type:','Admin'); ?></strong> <strong><code data-toggle="tooltip"  tooltip-placement="top"  tooltip="{{ProjectType.get(task.type).tootip}}"  ng-bind-html="ProjectType.get(task.type).name_task" compile-template> </code></strong></div>
                            <div class="m-t text-righ">
                                <a href="#" ng-click="View(task.id)" class="btn btn-outline btn-primary"><i class="fa fa-folder"></i> <?php echo $this->translate('View','Admin'); ?></a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="animated fadeInRight" ng-repeat="task in assigingtasks">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox product-box">
                    <div class="ibox-title">
                        <span class="label label-warning pull-right" style="font-size: 15px;">{{ TaskStatus.get(task.status).name }}</span>
                        <h3><span class="text-navy">{{ task.task_number }}</span> &nbsp;{{task.project.reference }}</h3>
                    </div>
                    <div class="ibox-content">
                    	<div class="btn-group pull-right">
                            <button ng-click="Accept(task.id)" class="btn btn-warning" type="button"><i class="fa fa-check-square-o"></i> <?php echo $this->translate('Accept','Admin'); ?></button>
                            <button class="btn btn-white" type="button" ng-click="View(task.id)"><i class="fa fa-folder"></i> <?php echo $this->translate('View','Admin'); ?></button>
                        </div>

                        <div>
                            <h1 class="product-main-price">{{ task.currency }} {{ task.total_freelancer }} 
							<small ng-show="1==0" class="text-muted" style="font-size: 18px;">1800 <?php echo $this->translate('words','Admin'); ?></small> 
							</h1>
                        </div>
                        <div class="hidden-sm">
		                    <table class="footable table small m-b-xs table-responsive" style="font-size: 16px;">
		                        <tbody>
		                        <tr>
		                            <td>
		                                <strong><?php echo $this->translate('Translation Languages:','Admin'); ?></strong>
		                            </td>
		                            <td>
		                                <strong><code>{{ task.project.sourceLanguage.name }} <i class="fa fa-arrow-right"></i> {{ task.language.name }}</code></strong>
		                            </td>

		                        </tr>
		                        <tr>
		                            <td>
		                                <strong><?php echo $this->translate('Due Date:','Admin'); ?></strong> <strong><code>{{ DateFormatter.short(task.dueDate) }}</code></strong>
		                            </td>
		                            <td>
		                                <strong><?php echo $this->translate('Task Type:','Admin'); ?></strong> <strong><code data-toggle="tooltip"  tooltip-placement="top"  tooltip="{{ProjectType.get(task.type).tootip}}"  ng-bind-html="ProjectType.get(task.type).name_task" compile-template> </code></strong>
		                            </td>
		                        </tr>
		                        </tbody>
		                    </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="animated fadeInRight" ng-repeat="task in ongoingtasks">
        <div class="row">
            <div class="col-lg-12">

                <div class="ibox" style="font-size: 16px;">
                    <div class="ibox-title">
                        <span class="label label-primary pull-right" style="font-size: 15px;">{{ TaskStatus.get(task.status).name }}</span>
                        <h3><span class="text-navy">{{ task.task_number }}</span> &nbsp;{{ task.project.reference }}</h3>
                    </div>
                    <div class="ibox-content product-box">

                        <div class="product-desc">
                            <div><strong><?php echo $this->translate('Translation Languages:','Admin'); ?> </strong><strong><code>{{ task.project.sourceLanguage.name }} <i class="fa fa-arrow-right"></i> {{ task.language.name }}</code></strong></div>
                            <div><strong><?php echo $this->translate('Due Date:','Admin'); ?></strong> <strong><code>{{ DateFormatter.short(task.dueDate) }}</code></strong></div>
                            <div><strong><?php echo $this->translate('Task Type:','Admin'); ?></strong> <strong><code data-toggle="tooltip"  tooltip-placement="top"  tooltip="{{ProjectType.get(task.type).tootip}}"  ng-bind-html="ProjectType.get(task.type).name_task" compile-template> </code></strong></div>
                            <div class="m-t text-right">
                                <a href="#" ng-click="View(task.id)" class="btn btn-outline btn-primary"><i class="fa fa-folder"></i> <?php echo $this->translate('View','Admin'); ?></a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>
						
 <script>
 $(document).ready(function(){

     $('#loading-example-btn').click(function () {
         btn = $(this);
         simpleLoad(btn, true)

         // Ajax example
//         $.ajax().always(function () {
//             simpleLoad($(this), false)
//         });

         simpleLoad(btn, false)
     });
 });

 function simpleLoad(btn, state) {
     if (state) {
         btn.children().addClass('fa-spin');
         btn.contents().last().replaceWith(" Loading");
     } else {
         setTimeout(function () {
             btn.children().removeClass('fa-spin');
             btn.contents().last().replaceWith(" Refresh");
         }, 2000);
     }
 }
    $(document).ready(function(){
        $('.dtbox').DateTimePicker();

        // trigger datetime picker when click to calendar icon
        // TODO: this is not working
        $('i.fa.fa-calendar').on('click', function(e){
            console.log('clicked');
            e.preventDefault();

            $(this).parents('.input-group').find('input[readonly]').click();
        });
    });
</script>
