<div class="row">
    <div class="col-lg-6">
        <div class="form-group">
            <label>Email *</label>
            <input name="email" ng-model="userInfo.email" type="email" class="form-control" required >
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Password *</label>
            <input id="password" name="password" type="password" ng-model="userInfo.password" class="form-control" required>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Confirm password *</label>
            <input id="confirmpwd" name="confirmpwd" type="password" class="form-control required" />
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Gender *</label>
            <div data-toggle="buttons">
                <label class="btn btn-outline btn-primary btn-sm {{userInfo.gender == '1' ? 'active' : ''}}" ng-click="userInfo.gender='1'">
                    <input type="radio" name="gender" value="1" > Male
                </label>
                &nbsp;
                <label class="btn btn-outline btn-primary btn-sm {{userInfo.gender == '0' ? 'active' : ''}}" ng-click="userInfo.gender='0'">
                    <input type="radio" name="gender" value="0" > Female
                </label>
            </div>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>City *</label>
            <input id="city" name="city" ng-model="userInfo.city" type="text" class="form-control required" >
        </div>
    </div>
    <div class="col-lg-6">
        <div class="form-group">
            <label>First name *</label>
            <input id="name" name="name" type="text" ng-model="userInfo.firstName" class="form-control required" >
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Last name *</label>
            <input id="surname" name="surname" type="text" ng-model="userInfo.lastName" class="form-control required" >
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Phone *</label>
            <input id="phone" name="phone" type="phone" ng-model="userInfo.phone" class="form-control required" >
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Cell Phone *</label>
            <input id="cellphone" name="cellphone" type="phone" ng-model="userInfo.cellphone" class="form-control required" >
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label>Country *</label>
            <select class="form-control required" id="country" name="country" required ng-model="userInfo.country" ng-options="country.name for country in countries track by country.id" required>
            </select>
        </div>
    </div>
</div>