<h4>
    <i class="fa fa-file-text"></i> 
    <?php echo $this->translate('Resume') ?>
</h4>
<div class="hr-line-dashed"></div>
<div class="row">
    <div class="col-lg-12">
        <div ng-controller="AppController" nv-file-drop uploader="uploader" class="form-group" ng-init="init()">
            <label><?php echo $this->translate('CV upload') ?> </label>
            <!-- TODO: file upload not working here -->
            <table class="table">
                <tbody>
                    <tr>
                        <td class="project-title" >
                            <div ng-repeat="cvfile in cvfiles track by $index" style="display: inline-block; margin:  5px;" ng-model="cvfiles" class="cvfiles">
                                <i class="fa fa-file-text"></i>&nbsp; <a href="<?php echo '../../../';?>{{cvfile.path}}">{{cvfile.name}}</a> &nbsp;&nbsp;
                                <span ng-click="deleteFile(cvfile.id);"><i class="fa fa-times-circle" style="cursor: pointer;"></i></span>
                            </div>
                        </td>
                        <td class="project-title" width="10%">
                            <button type="button" class="btn btn-w-m btn-white btn-xs" ng-click="openFileDialog()">
                                <i class="fa fa-cloud-upload">
                                    <?php echo $this->translate('Upload') ?>
                                </i>
                            </button>
                            <input type="file" id="objFile" nv-file-select="" uploader="uploader" style="display: none;"  />
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="hr-line-dashed">
        </div>
        <div class="form-group">
            <label><?php echo $this->translate('Working Experiences') ?></label>
            <summernote ng-model="resume.workingExperiences" class="summernote">
            </summernote>
        </div>
        <div class="hr-line-dashed"></div>
        <div class="form-group">
            <label><?php echo $this->translate('Education') ?> </label>
            <summernote ng-model="resume.education" class="summernote">
            </summernote>
        </div>
    </div>
</div>