<form class="form-horizontal" ng-submit="createTask()">
    <input type="hidden" name="project_id" value="{{ project.id }}" />
    <div class="form-group">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-md-4">
                    <select class="form-control required" name="type" ng-model="newTask.type"
                            ng-options="type.name_text for type in project.types">
                        <option value="">Select Task Type</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <select class="form-control required" name="language" ng-model="newTask.language"
                            ng-options="(project.sourceLanguage.name + ' to ' + language.name) for language in project.targetLanguages">
                        <option value="">Select Language Pair</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <button class="btn btn-primary" type="submit">
                        <?php echo $this->translate("Create New Task") ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="hr-line-dashed"></div>