<div
	class="tab-pane"
	id="correction" >
	<div class="panel">
		<div  class="panel-collapse">
			<div class="panel-body">
				<div class="panel panel-default">
					<form class="no-margin">
						<div class="panel-body">
							<div class="form-group">
								<label class="control-label"><?php echo $this->translate('What\'s wrong with the translation?') ?>
								</label>
								<div class="checkbox">
									<label> <input type="checkbox"
										ng-model="correction.options.incomplete"> <?php echo $this->translate('It is incomplete') ?>
									</label>
								</div>
								<div class="checkbox">
									<label> <input type="checkbox"
										ng-model="correction.options.spelling"> <?php echo $this->translate('It contains spelling or grammatical errors') ?>
									</label>
								</div>
								<div class="checkbox">
									<label> <input type="checkbox"
										ng-model="correction.options.meaning"> <?php echo $this->translate('It misses key meaning or details from the original') ?>
									</label>
								</div>
							</div>
							<div class="form-group">
								<label class="control-label"><?php echo $this->translate('Comments :') ?>
								</label>
								<div class="form-control"
									
									>{{correction.message}}</div>
								
							</div>
							<!-- /form-group -->
							
						</div>
					</form>
				</div>
				<!-- /panel -->

			</div>
		</div>
	</div>
</div>
