<div class="ibox" ng-controller="AppController" nv-file-drop="" uploader="uploader">
<div class="row">
    <div class="col-lg-6" id="modal-file">
        <dl class="dl-horizontal">
            <h3>Project Files:</h3> 
            
            <ul class="list-unstyled project-files tooltip-demo" >
				<li ng-repeat="file in files">
					<a href="<?php echo $this->url('admin',array('controller'=>'project','action'=>'downloadFile'),array('query'=>array('token'=>'')))?>{{file.token}}" data-toggle="tooltip" data-placement="left" title="" data-original-title="{{ file.size/1024/1024|number:2 }} MB | {{ file.date }}"><i class="fa fa-file"></i> {{ file.name }}</a>
					<a href="#" ng-click="calTo('#modal-file','#TaskDetailController',
	                                           'removeItem', file)"><i class="fa fa-trash"></i></a>
					
					
				</li>
            </ul>
			<div class="text-center m-t-md" id="projectfiles">
				<input type="file" nv-file-select="" uploader="uploader" multiple="multiple" />
			</div>
            
            
        </dl>
    </div>
    <div class="col-lg-6" id="modal-taskfile">
        <dl class="dl-horizontal">
            <h3>Final Files:</h3> 
                					<ul class="list-unstyled project-files tooltip-demo">
						<li ng-repeat="file in taskfiles">
							<a href="<?php echo $this->url('admin',array('controller'=>'project','action'=>'downloadFile'),array('query'=>array('token'=>'')))?>{{file.token}}" data-toggle="tooltip" data-placement="left" title="" data-original-title="{{ file.size/1024/1024|number:2 }} MB | {{ file.date }}"><i class="fa fa-file"></i> {{ file.name }}</a>
							<a href="#" ng-click="calTo('#modal-taskfile','#TaskDetailController',
	                                           'removetaskItem', file)"><i class="fa fa-trash"></i></a>
						</li>					</ul>
					<div class="text-center m-t-md" id="taskfiles">
						<input type="file" nv-file-select="" uploader="uploadertask" multiple="multiple" />
					</div>
                
            </dl>
    </div>
</div>	
<div>