<div class="ibox" ng-controller="AppController" nv-file-drop="" uploader="uploader">
					
  <div class="row">
  	<div class="col-lg-12" id="modal-file">
  		<table class="table table-bordered">
  				<thead>
  				<tr>
  						<th width="5%" class="text-center">#</th>
  						<th>Project Source Files</th>
  						<th width="10%">Size</th>
  						<th width="20%">Time Stamp</th>
              <th width="5%" class="text-center">Action</th>
  				</tr>
  				</thead>
  				<tbody>
  				<tr ng-repeat="file in files">
  						<td class="text-center">{{$index + 1}}</td>
						<td><a href="<?php echo $this->url('admin',array('controller'=>'project','action'=>'downloadFile'),array('query'=>array('token'=>'')))?>{{file.token}}" ng-hide="item.isUploading"><i class="fa fa-file"></i> {{ file.name }}</a>
							
						</td>
					
  						<!--<td><a href="<?php echo $this->url('admin',array('controller'=>'project','action'=>'downloadFile'),array('query'=>array('token'=>'')))?>{{file.token}}" ><i class="fa fa-file"></i> {{ file.name }}</a></td>-->
  						<td>{{ file.size/1024/1024|number:2 }} MB</td>
  						<td>{{ file.date }}</td>
						<td class="text-center"><a href="#" ng-click="calTo('#modal-taskfile','#TaskDetailController', 'removetaskItem', file)"><i class="fa fa-trash"></i></a></td>
  				</tr>
				<tr ng-repeat="item in uploader.queue">
						<td>{{$index + 1}}</td>
						<td><a href="#" ng-hide="item.isUploading">{{ item.file.name }}</a>
							<div class="progress" style="margin-bottom: 0" ng-show="item.isUploading">
								<div class="progress-bar" role="progressbar"
									 ng-style="{ 'width': uploader.progress + '%' }" style="width: 0%;">{{ item.file.name }}</div>
							</div>
						</td>
						<td class="text-right">{{ item.file.size/1024|number:2 }} Kb</td>
						<td>{{ DateFormatter.format(item.file.lastModified) }}</td>
						<td class="text-center child-is-link">
							<i ng-click="removeItem(item)" class="fa fa-trash-o text-danger"></i>
						</td>
                </tr>
  				</tbody>
  		</table>
			<div class="text-center m-t-md" id="projectfiles">
				<input type="file" nv-file-select="" uploader="uploader" multiple="multiple" />
			</div>
  	</div>
  </div>
            
  <div class="hr-line-dashed"></div>
            
  <div class="row">
  	<div class="col-lg-12" id="modal-tasksourcefile">
  		<table class="table table-bordered">
  				<thead>
  				<tr>
  						<th width="5%" class="text-center">#</th>
  						<th>Task Source Files</th>
  						<th width="10%">Size</th>
  						<th width="20%">Time Stamp</th>
              <th width="5%" class="text-center">Action</th>
  				</tr>
  				</thead>
  				<tbody>
  				<tr ng-repeat="file in tasksourcefiles">
  						<td class="text-center">{{$index + 1}}</td>
  						<td><a href="" ><i class="fa fa-file"></i> {{ file.name }}</a></td>
  						<td>{{ file.size/1024/1024|number:2 }} MB</td>
  						<td>{{ file.date }}</td>
              <td class="text-center"><a href="#" ng-click="calTo('#modal-taskfile','#TaskDetailController', 'removetaskItem', file)"><i class="fa fa-trash"></i></a></td>
  				</tr>
				<tr ng-repeat="item in uploadertasksource.queue">
						<td>{{$index + 1}}</td>
						<td><a href="#" ng-hide="item.isUploading">{{ item.file.name }}</a>
							<div class="progress" style="margin-bottom: 0" ng-show="item.isUploading">
								<div class="progress-bar" role="progressbar"
									 ng-style="{ 'width': uploadertasksource.progress + '%' }" style="width: 0%;">{{ item.file.name }}</div>
							</div>
						</td>
						<td class="text-right">{{ item.file.size/1024|number:2 }} Kb</td>
						<td>{{ DateFormatter.format(item.file.lastModified) }}</td>
						<td class="text-center child-is-link">
							<i ng-click="removeItem(item)" class="fa fa-trash-o text-danger"></i>
						</td>
                </tr>
  				</tbody>
  		</table>
      <div class="text-center m-t-md" id="tasksourcefiles">
        <input type="file" nv-file-select="" uploader="uploadertasksource" multiple="multiple" />
      </div>
  	</div>
    </div>

  <div class="hr-line-dashed"></div>

  <div class="row">
    <div class="col-lg-12" id="modal-taskfile">
      <table class="table table-bordered">
          <thead>
          <tr>
              <th width="5%" class="text-center">#</th>
              <th>Task Final Files</th>
              <th width="10%">Size</th>
              <th width="20%">Time Stamp</th>
              <th width="5%" class="text-center">Action</th>
          </tr>
          </thead>
          <tbody>
          <tr ng-repeat="file in taskfiles">
              <td class="text-center">{{$index + 1}}</td>
              <td><a href="<?php echo $this->url('admin',array('controller'=>'project','action'=>'downloadFile'),array('query'=>array('token'=>'')))?>{{file.token}}" ><i class="fa fa-file"></i> {{ file.name }}</a></td>
              <td>{{ file.size/1024/1024|number:2 }} MB</td>
              <td>{{ file.date }}</td>
              <td class="text-center"><a href="#" ng-click="calTo('#modal-taskfile','#TaskDetailController', 'removetaskItem', file)"><i class="fa fa-trash"></i></a></td>
          </tr>
		  <tr ng-repeat="item in uploadertask.queue">
						<td>{{$index + 1}}</td>
						<td><a href="#" ng-hide="item.isUploading">{{ item.file.name }}</a>
							<div class="progress" style="margin-bottom: 0" ng-show="item.isUploading">
								<div class="progress-bar" role="progressbar"
									 ng-style="{ 'width': uploadertask.progress + '%' }" style="width: 0%;">{{ item.file.name }}</div>
							</div>
						</td>
						<td class="text-right">{{ item.file.size/1024|number:2 }} Kb</td>
						<td>{{ DateFormatter.format(item.file.lastModified) }}</td>
						<td class="text-center child-is-link">
							<i ng-click="removeItem(item)" class="fa fa-trash-o text-danger"></i>
						</td>
                </tr>
          </tbody>
      </table>
					<div class="text-center m-t-md" id="taskfiles">
						<input type="file" nv-file-select="" uploader="uploadertask" multiple="multiple" />
					</div>
    </div>
</div>	

<div>