<div class="row">
	<div class="col-lg-12">
		<table class="table table-bordered">
				<thead>
				<tr>
						<th>#</th>
						<th>Task Source Files</th>
						<th>Size</th>
						<th>Time Stamp</th>
				</tr>
				</thead>
				<tbody>
				
				<tr ng-repeat="file in files_tm">
						<td>{{$index + 1}}</td>
						<td><a href="<?php echo $this->url('admin',array('controller'=>'project','action'=>'downloadFile'),array('query'=>array('token'=>'')))?>{{file.token}}"><i class="fa fa-file"></i> {{ file.name }}</a></td>
						<td>{{ file.size/1024/1024|number:2 }} MB</td>
						<td>{{ file.date }}</td>
				</tr>
				</tbody>
		</table>
    </div>
</div>
