
<div class="row">
    <div class="col-lg-12">
        <div class="m-b-md">
			<?php if ($this->isStaff==1) {?>
            <button class="btn btn-danger btn-xs pull-right" ng-click="showEdit()">
                <i class="fa fa-edit"></i><?php echo $this->translate('Edit Task') ?>
            </button>
			<?php } ?>
            <h2><span class="text-info">{{ project.project_no }}-{{ task.id }}</span><?php echo ' '; ?>
                {{ task.name }}</h2>
        </div>

    </div>
</div>
<div class="row">
  <div class="ibox-content">
      <div class="row">
          <div class="col-sm-6 b-r">
            <table class="table table-striped table-bordered">
                <tbody>
                <tr>
                    <th width="25%">Task ID</th>
                    <td class="text-navy"> {{ project.project_no }}-{{ task.id }} </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Status'); ?>:</th>
                    <td> <span class="label label-{{ task.status.decorator }}">{{ task.status.name }} </span> </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Due Date'); ?></th>
                    <td> {{ DateFormatter.format(task.dueDate) }} </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Task Type'); ?></th>
                    <td>
                      <div class="tooltip-demo">
                        <span><code {{ task.type.inline_attrs }}>{{ task.type.name_short }}</code>&nbsp;</span>
                      </div>
                    </td>
                </tr>
                <?php if (!$this->isStaff) {?>
                  <?php }else { ?>
                <tr>
                    <th><?php echo $this->translate('Client Contact'); ?></th>
                    <td>
              					{{ project.client.name }}
                    </td>
                </tr>
                <?php } ?>
                <tr>
                    <th><?php echo $this->translate('Sales'); ?></th>
                    <td class="text-navy"> {{ project.sale.name }} </td>
                </tr>
                </tbody>
            </table>
          </div>
          <div class="col-sm-6">
            <table class="table table-striped table-bordered">
                <tbody>
                <tr>
                    <th width="25%">Task Reference</th>
                    <td class="text-navy"> {{ task.name }} </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Priority'); ?></th>
                    <td> <span class="label label-{{ project.priority.decorator }}">{{ project.priority.name }}</span> </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Field'); ?></th>
                    <td> {{ project.field.name }} </td>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Languages'); ?></th>
                    <td> <code>{{ project.sourceLanguage.name }}</code> <i class="fa fa-arrow-right"></i> <code>{{ task.language.name }}</code></td>
                </tr>
                <?php if (!$this->isStaff) {?>
                  <?php }else { ?>
                <tr>
                    <th><?php echo $this->translate('Client Company'); ?></th>
                    <td>
              					{{ project.client.company.name }}
                    </td>
                </tr>
                <?php } ?>
                <tr>
                    <th><?php echo $this->translate('Project Manager'); ?></th>
                    <td> {{ project.pm.name }} </td>
                </tr>
                </tbody>
            </table>
          </div>
      </div>
  </div>

</div>
