
<div class="row">
    <div class="col-lg-12">
        <div class="m-b-md">
			<?php if ($this->isStaff==1) {?>
            <button class="btn btn-danger btn-xs pull-right" ng-click="showEdit()">
                <i class="fa fa-edit"></i><?php echo $this->translate('Edit Task') ?>
            </button>
			<?php } ?>
            <h2><span class="text-info">{{ project.project_no }}-{{ task.id }}</span><?php echo ' '; ?>
                {{ task.name }}</h2>
        </div>

    </div>
</div>
<div class="row">
    <div class="col-lg-5">
        <dl class="dl-horizontal">
            <dt><?php echo $this->translate('Status'); ?>:</dt>
            <dd><span class="label label-{{ task.status.decorator }}">{{ task.status.name }} </span>
            </dd>
            <br>
            <dt><?php echo $this->translate('Client Contact'); ?>:</dt> 
			<dd><a href="#" class="text-navy">
				<?php if (!$this->isStaff) {?>
					{{ project.user.alias }}
				<?php }else { ?>
					{{ project.client.name }}
				<?php } ?>
			</a></dd>
            <dt><?php echo $this->translate('Client Company'); ?>:</dt> <dd>{{ project.client.company.name }}</dd>
            <br>
            <dt><?php echo $this->translate('Start Date'); ?>:</dt> <dd>{{ DateFormatter.format(task.startDate) }}</dd>
            <dt><?php echo $this->translate('Due Date'); ?>:</dt> <dd>{{ DateFormatter.format(task.dueDate) }}</dd>
            
            <br>
            <dt><?php echo $this->translate('Source Language'); ?>:</dt> <dd><code>{{ project.sourceLanguage.name }}</code></dd>
            <br>
        </dl>
    </div>
    <div class="col-lg-7">
        <dl class="dl-horizontal" >
            <dt><?php echo $this->translate('Priority'); ?>:</dt> <dd><span class="label label-{{ project.priority.decorator }}">{{ project.priority.name }}</span> </dd>
            <br>
            <dt><?php echo $this->translate('Sales'); ?>:</dt> <dd>{{ project.sale.name }}</dd>
            <dt><?php echo $this->translate('Project Manager'); ?>:</dt> <dd>{{ project.pm.name }}</dd>
            <br>
            <dt><?php echo $this->translate('Field'); ?>:</dt> <dd>{{ project.field.name }}</dd>
            
            <dt><?php echo $this->translate('Type'); ?>:</dt>
            <dd>
                <div class="tooltip-demo">
                    <span><code {{ task.type.inline_attrs }}>{{ task.type.name_short }}</code>&nbsp;</span>
                </div>
            </dd>
            <br>
            <dt><?php echo $this->translate('Target Languages'); ?>:</dt> <dd>
                <span ng-repeat="language in project.targetLanguages"><code>{{ task.language.name }}</code>&nbsp;</span>
            </dd>
        </dl>
    </div>
</div>