<div class="row">
    <div class="col-lg-12">
        <div id="edit_task" class="panel-collapse collapse faq-answer">
            <form method="" class="form-horizontal">
                <div class="row form-horizontal">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Reference *</label>
                            <div class="col-sm-10">
                                <input name="reference" ng-model="tempTask.name" type="text"
                                       class="form-control required">
                            </div>
                        </div>
                        
                    </div>
					<div class="col-lg-6">
						
						<div class="form-group" id="ordered_date">
						<!-- 
                            <label class="col-sm-4 control-label">Start Date *</label>
                            <div class="col-sm-8">
                                <div class="input-append date form_datetime" >
                                    <input class="form-control" type="text"
                                           value="{{ DateFormatter.format(tempTask.startDate) }}">
                                    <span class="add-on"><i class="icon-remove"></i></span>
                                    <span class="add-on"><i class="icon-th"></i></span>
                                </div>
                            </div>
							-->
							<label class="col-sm-4 control-label">Start Date *</label>
							<div class="col-sm-8">
								<div class="input-group date">
									<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
									<input data-field="datetime" type="text" name="startDate" ng-model="tempTask.startDate"
										   class="form-control required valid" data-errorplace="element.parent().before(error)"/>
								</div>
								<div class="dtbox"></div>
							</div>
                        </div>
						
					</div>	
                    <div class="col-lg-6">
                        <!--<div class="form-group" id="due_date">
                            <label class="col-sm-4 control-label">Due Date *</label>
                            <div class="col-sm-8">
                                <div class="input-append date form_datetime" >
                                    <input class="form-control" type="text"
                                           value="{{ DateFormatter.format(tempTask.dueDate) }}">
                                    <span class="add-on"><i class="icon-remove"></i></span>
                                    <span class="add-on"><i class="icon-th"></i></span>
                                </div>
                            </div>
                        </div>-->
						<div class="form-group" id="due_date">
							<label class="col-sm-4 control-label">Due Date *</label>
							<div class="col-sm-8">
								<div class="input-group date">
									<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
									<input data-field="datetime" type="text" name="dueDate" ng-model="tempTask.dueDate"
										   class="form-control required valid" data-errorplace="element.parent().before(error)"/>
								</div>
								<div class="dtbox"></div>
							</div>
						</div>

                    </div>
                </div>
                <div class="text-right">
                    <button ng-click="update()" class="btn btn-sm btn-primary"><i class="fa fa-save"></i> Update</button>
                </div>
            </form>
        </div>
    </div>
</div>