<div class="tab-pane active" id="tasks">
    <?php include "order/translations.phtml" ?>
    <?php include "order/desktop_publishing.phtml" ?>
    <?php include "order/engineering.phtml" ?>
    <?php include "order/interpreting.phtml" ?>

	<div class="hr-line-dashed"></div>
	
    <form class="form-horizontal">
        <div class="form-group">
            <div class="col-sm-12">
                    <div class="row">
                        <div class="col-md-4">
								<select ng-model="task.freelancerassign" class="form-control"  name="account"
                                            ng-options="freelancer.lastName  + ' ' + freelancer.firstName for freelancer in freelancers track by freelancer.freelancerid">
                                        <option value=""><?php echo $this->translate("Select Freelancer Resource") ?></option>
                                </select>
						</div>
                    <div class="col-md-2"><button class="btn btn-primary" type="button" ng-click="assignFre()">Assign Task</button></div> <!-- this button never disabled -->
                    <div class="col-md-3" align="center"><a href="" class="btn btn-success" type="button" ng-click="sendToSpecialismPool()">Send to Specialism Pool</a></div> 
                    <div class="col-md-3" ><a href="" class="btn btn-info" type="button" ng-click="sendToClientPool()">Send to Client's Resource Pool</a></div>
                    <!-- if the task has been send to any pool, then the button need to be disabled then the task status should be pooling-->
                </div>
			</div>
        </div>
    </form>
</div>
                    
