<div class="tab-pane active" id="tasks">
    <?php include "order/translations.phtml" ?>
    <?php include "order/desktop_publishing.phtml" ?>
    <?php include "order/engineering.phtml" ?>
    <?php include "order/interpreting.phtml" ?>

	<div class="hr-line-dashed"></div>
	
    
    <?php if($user['role'] == 'Admin') 
            			include "order/admin_assign_task.phtml";
            	else if ($user['role'] == 'Freelancer') 
            			include "order/freelancer_accept_quote.phtml";
            
     ?> 
</div>
                    
