<div class="col-lg-4">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<h5>
								<i class="fa fa-files-o"></i> Order Information
							</h5>
						</div>
						<div class="ibox-content">
							<br>
							<table class="table">
								<thead>
									<tr>
										<th>3 iterms</th>
										<!-- before iterms, put the number of files uploaded -->
										<th class="text-right">888 words</th>
									</tr>
									<tr>
										<th>Languages</th>
										<th class="text-right">4</th>
										<!-- target languages number -->
									</tr>
									<tr>
										<th>Quality Level</th>
										<th class="text-right"><span class="label label-primary">Business</span>
											CNY 0.12/Word</th>
									</tr>
								</thead>
							</table>
							<br> <br>
							<table class="table">
								<thead>
									<tr>
										<th>Iterms Total</th>
										<th class="text-right">CNY 1200.88</th>
									</tr>
									<tr>
										<th>Tax</th>
										<th class="text-right">CNY 200.88</th>
									</tr>
									<tr style="font-size: 22px;">
										<th>Total</th>
										<th class="text-right">CNY 1200.88</th>
									</tr>
								</thead>
							</table>
							<br>
							<p>
								Estimated delivery <strong>34 hours.</strong>
							</p>
							<!-- this hour based on the word count of the files, algorithm is estimate time = total word count / 2000 = number of hours, if the result is 1.2, then show 2, if 1.7, show 2 also-->
						</div>
					</div>
				</div>