<div class="col-lg-4">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<h5>
								<i class="fa fa-files-o"></i> Order Information
							</h5>
						</div>
						<div class="ibox-content">
							<br>
							<table class="table">
								<thead>
									<tr>
										<th>{{totalitems}} iterms</th>
										<!-- before iterms, put the number of files uploaded -->
										<th class="text-right">{{totalwords}} words</th>
									</tr>
									<tr>
										<th>Languages</th>
										<th class="text-right">{{numberLangs}}</th>
										<!-- target languages number -->
									</tr>
									<tr>
										<th>Quality Level</th>
										<th class="text-right" ng-show="totalitems > 0"><span class="label label-primary">{{project.serviceLevel.name}}</span>
											{{CurrentCurrency}} {{price | currency : '' : 2}}/Word</th>
									</tr>
								</thead>
							</table>
							<br> <br>
							<table class="table">
								<thead>
									<tr>
										<th>Iterms Total</th>
										<th class="text-right" ng-show="totalitems > 0">{{CurrentCurrency}} {{ItermsTotal | currency : '' : 2}}</th>
									</tr>
									<tr ng-show="1==0">
										<th>Tax</th>
										<th class="text-right">{{CurrentCurrency}} {{tax | currency : '' : 2}}</th>
									</tr>
									<tr style="font-size: 22px;">
										<th>Total</th>
										<th class="text-right" ng-show="totalitems > 0">{{CurrentCurrency}} {{total | currency : '' : 2}}</th>
									</tr>
								</thead>
							</table>
							<br>
							<p>
								Estimated delivery <strong>{{hours | currency : '' : 0}} hours.</strong>
							</p>
							<!-- this hour based on the word count of the files, algorithm is estimate time = total word count / 2000 = number of hours, if the result is 1.2, then show 2, if 1.7, show 2 also-->
						</div>
					</div>
					
				</div>