<div class="setup-content" id="step-3">
											<div class="well">

												<form class="form-horizontal" role="form">
													<div class="row">
														<div class="col-sm-12">
															<div class="form-group">
																<label class="col-sm-3 control-label"> Need Fapiao *</label>
																<div class="col-sm-9">
																	<div data-toggle="buttons">
																		<!-- here IF YES, THEN SHOW TITLE, "NO" = HIDE TITLE, by default "NO"-->
																		<label class="btn btn-outline btn-primary"> <input
																			type="radio" name="" value="" /> YES
																		</label> <label class="btn btn-outline btn-primary"> <input
																			type="radio" name="" value="" /> NO
																		</label>
																	</div>
																</div>
															</div>
															<div class="form-group">
																<label class="col-sm-3 control-label"> Title *</label>
																<div class="col-sm-9">
																	<input type="text" class="form-control" value=""
																		placeholder="Your Chinese Company Title for Issue FAPIAO">
																</div>
															</div>
														</div>
														<div class="col-sm-12">
															<div class="form-group">
																<label class="col-sm-3 control-label"> Address *</label>
																<div class="col-sm-9">
																	<input type="text" class="form-control" value=""
																		placeholder="Your Mailing Address">
																</div>
															</div>
														</div>
													</div>

												</form>

												<div class="text-center">
													<!-- if second step choose NO to translate graphic, then show this button -->
													<button id="" class="btn btn-primary btn-lg">Pay and Start
														to Translate</button>
												</div>
												<div class="text-center">
													<!-- if second step choose yes to translate graphic, then show this button -->
													<button id="" class="btn btn-primary btn-lg">Request a
														Quote</button>
												</div>
											</div>

										</div>