<div class=" setup-content" id="step-2">
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-3">
				<h4>Currency</h4>
				<div data-toggle="buttons">
					<!-- here do a judgement, if page load in chinese, then defaule currency is CNY, otherwise USD -->
					<label class="btn btn-outline btn-primary"> <input type="radio"
						name="usd" value="" /> USD
					</label> <label class="btn btn-outline btn-primary"> <input
						type="radio" name="cny" checked value="" /> CNY
					</label>
				</div>
			</div>
			<div class="col-md-6">
				<h4>Select Quality Level</h4>
				<div data-toggle="buttons">
					<!-- here do a judgement, if page load in chinese, then defaule currency is CNY, otherwise USD -->
					<label class="btn btn-outline btn-primary"> <input type="radio"
						name="prof" value="" /> Professional <i
						class="fa fa-question-circle"></i>
					</label> <label class="btn btn-outline btn-primary"> <input
						type="radio" name="business" value="" /> Business <i
						class="fa fa-question-circle"></i>
					</label> <label class="btn btn-outline btn-primary"> <input
						type="radio" name="premium" value="" /> Premium <i
						class="fa fa-question-circle"></i>
					</label>
				</div>
			</div>
			<div class="col-md-3">
				<h4>Translate Graphics</h4>
				<div data-toggle="buttons">
					<!-- here put it in default NO -->
					<label class="btn btn-outline btn-primary"> <input type="radio"
						name="cny" value="" /> YES
					</label> <label class="btn btn-outline btn-primary"> <input
						type="radio" name="usd" checked value="" /> NO
					</label>
				</div>
			</div>
		</div>


		<hr>
		<div class="row">
			<div class="col-md-6">
				<h4>Translate From *</h4>
				<select class="form-control required valid" name="sourceLanguage"
					aria-required="true"
					ng-options="language.name for language in languages"
					ng-model="project.sourceLanguage"
					ng-change="change_client(project.client)">
					<option value="">Select Source Language</option>
				</select>
			</div>
			<div class="col-md-6">
				<h4>Translate To *</h4>
				<select class="form-control required valid" name="sourceLanguage"
					aria-required="true"
					ng-options="language.name for language in languages"
					ng-model="project.targetLanguage"
					ng-change="change_client(project.client); add_targetLanguage();">
					<option value="">Add Target Languages</option>
				</select>
			</div>
		</div>
		<br>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>#</th>
					<th>Target Languages</th>
					<th>Rate</th>
					<th>Word count</th>
					<th>Iterm Total</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="item in project.targetLanguages">
					<td>{{$index + 1}}</td>
					<td><span class="label label-primary">{{item.name}}</span></td>
					</td>
					<td>CNY 0.12 / word</td>
					<!-- here load papertask list price -->
					<td>1000</td>
					<td>CNY 1200</td>
					<td class="text-center child-is-link"><i
						ng-click="removeTargetLang(item)"
						class="fa fa-trash-o text-danger"></i>
					</td>
				</tr>
				
			</tbody>
		</table>
		<div class="text-center">
			<button id="" class="btn btn-primary btn-lg">Previous</button>
			<button id="activate-step-3" class="btn btn-primary btn-lg">Next</button>
		</div>
	</div>
</div>
