<div class="row setup-content" id="step-3">
	<form id="formStep3" class="form-horizontal" role="form" novalidate>
		<div class="col-lg-12">
			<div class="ibox-content">
				<div class="row">
					<div class="col-lg-12">
						<div class="form-group">
							<label class="col-sm-3 control-label"> <?php echo $this->translate('Literary Style','Admin'); ?> *</label>
							<div class="col-sm-6">
									<?php if($this->lang_code == 'en-US') {?>
									<select id="style" required class="form-control required valid" name="style"
										aria-required="true"
										ng-options="style_item.name for style_item in style track by style_item.id"
										ng-model="project.style"
										required
										>
										<option value="" ng-disabled="disable" ng-hide="true">Select Style</option>
									</select>
									<?php } else {?>
									<select id="style" required class="form-control required valid" name="style"
										aria-required="true"
										ng-options="style_item.name_cn for style_item in style track by style_item.id"
										ng-model="project.style"
										required
										>
										<option value="" ng-disabled="disable" ng-hide="true">选择风格</option>
									</select>
									<?php }?>
							</div>
						</div>	
						<!-- document field load the project field content -->
						<div class="form-group">
							<label class="col-sm-3 control-label"> <?php echo $this->translate('Document fields','Admin'); ?> *</label>
							<div class="col-sm-6">
				                <?php if($this->lang_code == 'en-US') {?>
									<select id="field" required class="form-control required valid" name="field"
										aria-required="true"
										ng-options="field_item.name for field_item in fields track by field_item.id"
										ng-model="project.field"
										required
										>
										<option value="" ng-disabled="disable" ng-hide="true">Select Style</option>
									</select>
									<?php } else {?>
									<select id="field" required class="form-control required valid" name="field"
										aria-required="true"
										ng-options="field_item.name_cn for field_item in fields track by field_item.id"
										ng-model="project.field"
										required
										>
										<option value="" ng-disabled="disable" ng-hide="true">选择字段</option>
									</select>
									<?php }?>
							</div>
						</div>
						<!-- save this information to Project Description -->
						<div class="form-group">
							<label class="col-sm-3 control-label"> <?php echo $this->translate('Remarks','Admin'); ?></label>
							<div class="col-sm-8">
				                <textarea class="form-control m-b" rows="6" ng-model="project.description"></textarea>
							</div>
						</div>
						<!--
						<div class="form-group">
							<label class="col-sm-3 control-label"> <?php echo $this->translate('Need Fapiao','Admin'); ?> *</label>
							<div class="col-sm-9">
								<div data-toggle="buttons" class="form-group">
									<label
										class="btn btn-outline btn-primary {{Fapiao == project.fapiao ? 'active': ''}}"
										ng-repeat="Fapiao in Fapiaos"
										ng-click="chooseFapiao(Fapiao);">
										<input type="radio" name="{{Fapiao.name}}"
										value="{{Fapiao.id}}" />
										{{Fapiao.name}}
									</label>
								</div>
							</div>
						</div>
						
						<div class="form-group" ng-show="isFapiao">
							<label class="col-sm-3 control-label"><?php echo $this->translate('Title','Admin'); ?> *</label>
							<div class="col-sm-9">
								<input id="tit" type="text" name="title" class="form-control required valid" value=""
									placeholder="Your Chinese Company Title for Issue FAPIAO" required ng-model="project.fapiaoTitle">
							</div>
						</div>	
						
						<div class="form-group" ng-show="isFapiao">
							<label class="col-sm-3 control-label"><?php echo $this->translate('Address','Admin'); ?> *</label>
							<div class="col-sm-9">

								<input type="mail"  name='mail' class="form-control required valid" value=""
									placeholder="Your Mailing Address" required ng-model="project.fapiaoAddress"> 
							</div>
						</div>
						-->
					</div>
				</div>
			</div>			


	        <br /><br />

			<div class="text-center" ng-show="!isGraph">
				<button id=""  type="button"  class="btn btn-primary btn-lg" onclick="PrevStep3()"><?php echo $this->translate('Previous','Admin'); ?></button>
				<!-- if second step choose NO to translate graphic, then show this button -->
				<button id='PayAndStartTrans'  type="button" class="btn btn-primary btn-lg" ng-click="PayAndStartTrans()"><?php echo $this->translate('Pay and Start to Translate','Admin'); ?></button>
			</div>
			<div class="text-center" ng-show="isGraph">
				<button id="" type="button"  class="btn btn-primary btn-lg" onclick="PrevStep3()"><?php echo $this->translate('Previous','Admin'); ?></button>
				<!-- if second step choose yes to translate graphic, then show this button -->
				<button id='RequestQuote'  type="button"  class="btn btn-primary btn-lg" ng-click="RequestQuote()"><?php echo $this->translate('Request a Quote','Admin'); ?></button>
			</div>
			<br /><br /><br />
		</div>
	</form>
</div>
