<div class="setup-content" id="step-2">
	<form id="formStep2" action="#" class="wizard-big" novalidate>
		<div class="col-md-12">
			<div class="ibox-content">
				<div class="row">
					<div class="col-md-5">	
						<h4 style="font-size: 16px;"><?php echo $this->translate('Translate From','Application'); ?> *</h4>	
						<?php if($this->lang_code == 'en-US') {?>		
						<select id="sourceLanguage" required class="form-control required valid" name="sourceLanguage"
							aria-required="true"
							ng-options="language.name for language in sourceLanguages track by language.id"
							ng-model="project.sourceLanguage"
							required
							ng-change="changePServicePrice();removeLangFSML();clearTargetLanguages();">
							<option value="" ng-disabled="disable" ng-hide="true"><?php echo $this->translate('Select Source Language','Application'); ?></option>
						</select>
						<?php } else {?>
						<select id="sourceLanguage" required class="form-control required valid" name="sourceLanguage"
							aria-required="true"
							ng-options="language.name_cn for language in sourceLanguages track by language.id"
							ng-model="project.sourceLanguage"
							required
							ng-change="changePServicePrice();removeLangFSML();clearTargetLanguages();">
							<option value="" ng-disabled="disable" ng-hide="true"><?php echo $this->translate('Select Source Language','Application'); ?></option>
						</select>
						<?php }?>
					</div>
					<div class="col-md-5">
						<h4 style="font-size: 16px;"><?php echo $this->translate('Translate To','Application'); ?> *</h4>
						<?php if($this->lang_code == 'en-US') {?>		
						<select class="form-control required valid" name="targetLanguage"
						aria-required="true"
						ng-options="language.name for language in modifiedTarLangs track by language.id"
						ng-model="project.targetLanguage"
						required
						ng-change="add_targetLanguage();changePServicePrice();">
						<option value="" ng-hide="hidetargetLang" ><?php echo $this->translate('Add Target Languages','Application'); ?></option>
						</select>
						<?php } else {?>
						<select class="form-control required valid" name="targetLanguage"
						aria-required="true"
						ng-options="language.name_cn for language in modifiedTarLangs track by language.id"
						ng-model="project.targetLanguage"
						required
						ng-change="add_targetLanguage();changePServicePrice();">
						<option value="" ng-hide="hidetargetLang" ><?php echo $this->translate('Add Target Languages','Application'); ?></option>
						</select>
						<?php }?>
					</div>
					<div class="col-md-2">
						<h4 style="font-size: 16px;"><?php echo $this->translate('Currency','Application'); ?> *</h4>
						<div data-toggle="buttons" class="form-group">
							<!-- here do a judgement, if page load in chinese, then defaule currency is CNY, otherwise USD -->
							<select class="form-control required valid" name="currency" id="currency"
								aria-required="true"
								ng-options="currency.name for currency in currencys track by currency.id"
								 ng-model="project.currency"
								required
								ng-change="chooseCurrency();refreshInfo();">
						   </select>  
						</div>
					</div>
				</div>
			</div>
			<br />

	        <div class="ibox-content">
                <div class="project-list">

                    <table class="footable table table-hover toggle-arrow-tiny">
                        <thead>
                        <tr style="font-size: 16px;">
                        	<th data-hide="phone,tablet"></th>
                            <th ><?php echo $this->translate('Target Languages','Admin'); ?></th>
                            <th data-hide="phone,tablet"><?php echo $this->translate('Quality Level','Admin'); ?></th>
                            <th data-hide="phone,tablet"><?php echo $this->translate('Unit Price','Admin'); ?></th>
                            <th data-hide="phone,tablet"><?php echo $this->translate('Translate Graphics?','Admin'); ?></th>
                            <th class="text-right"></th>
                        </tr>
                        </thead>                                
                        <tbody>
                            <tr ng-repeat="item in project.targetLanguages">
                                <td class="project-status">
                                    <span class="label label-warning pull-left">{{$index + 1}}</span>
                                </td>
                                <td class="project-status">
									<?php if($this->lang_code == 'en-US') {?>		
                                    <span style="font-size: 14px;" class="label label-info">{{item.name}}</span>
									<?php } else {?>
									<span style="font-size: 14px;" class="label label-info">{{item.name_cn}}</span>
									<?php }?>
                                </td>
								<td class="project-title tooltip-demo">
									<select required class="form-control valid" name="servicelevel"
										aria-required="false"
										ng-options="servicelevel.name for servicelevel in ProjectServiceLevels"
										ng-model="project.serviceLevel"	
										ng-change="chooseProjectServiceLevel();changePServicePrice();">
									</select>
								</td>
                                <td class="project-title">
                                    <strong class="text-danger" style="font-size: 16px;">{{CurrentCurrency}} {{item.price | currency : '' : 2}} / <?php echo $this->translate('Word','Application'); ?></strong>
                                </td>
                                <td class="project-title tooltip-demo">
									<select class="form-control required valid " name="transGraph"
										aria-required="true"
										ng-options="transGraph.name for transGraph in transGraphs"
										ng-model="project.transGraph"
										ng-change="choosetransGraph();">	
									</select>
                                </td>

                                <td class="project-actions text-right child-is-link">
                                	<button ng-click="removeTargetLang(item)" class="btn btn-white btn-xs"> <i class="fa fa-trash-o text-danger"></i></button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
	        </div>

	        <br /><br />
		<div class="text-center">
			<button id="" type="button"  class="btn btn-primary btn-lg" onclick="PrevStep2()"><?php echo $this->translate('Previous','Admin'); ?></button>
			<button id=""  type="button"  class="btn btn-primary btn-lg" ng-click="checkValidStep2()"><?php echo $this->translate('Next','Admin'); ?></button>
		</div>

			<br /><br /><br />
		</div>
	</form>
</div>
