<!-- Scripts -->
<?php
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css');

$this->headScript ()->prependFile ( $this->basePath () . '/js/admin/freelancer/details.js' )
					->prependFile ( $this->basePath () . '/js/admin/bootstrap-modal.js' )
					->prependFile($this->basePath() . '/js/angular-filter.js')
					->prependScript ( "angularApp = angular.module('project', ['summernote','angular.filter']);" )
					->prependFile ( $this->basePath () . '/js/plugins/summernote/summernote.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/validate/jquery.validate.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/steps/jquery.steps.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/pace/pace.min.js' )
					->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
					->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
					 ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js')
					->prependFile ( $this->basePath () . '/js/inspinia.js' );

?>
<?php
$this->inlineScript()
    ->prependScript("
        var USER_ID = '" . $user['id'] . "';
		var LANG_CODE = '" . $this->lang_code . "';
		var EXITS_CONFIRM_TEXT = '" . $this->translate('This client was existed') . "';
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
    ");
?>

<div class="row animated fadeInRight" ng-controller="FreelancerController" ng-init="init()">
	<div class="col-md-4">
		<div class="ibox">
			<div class="ibox-title">
				<h5>{{userInfo.username}}</h5>
				<div class="ibox-tools">
					<span ng-show="userInfo.isActive == '1'" class="label label-primary"><?php echo $this->translate('Active') ?></span>
					<span ng-show="userInfo.isActive == '0'" class="label label-default"><?php echo $this->translate('Unactive') ?></span>
				</div>
			</div>

			<div class="ibox-content profile-content">
				<p><i class="fa fa-user"></i> &nbsp;
                {{userInfo.lastName}}, {{userInfo.firstName}} &nbsp;
                <i ng-show="userInfo.gender == '0'" class="fa fa-male"></i>
                <i ng-show="userInfo.gender == '1'" class="fa fa-female"></i>
                </p>
				<p><i class="fa fa-envelope"></i> &nbsp; {{userInfo.email}}</p>
				<p><i class="fa fa-tag"></i> &nbsp; {{userInfo.alias}}</p>

				<p><i class="fa fa-phone"></i> &nbsp; {{userInfo.phone}}</p>
				<p><i class="fa fa-map-marker"></i> &nbsp; {{userInfo.city}}, {{userInfo.country.name}}</p>
				<p class="small font-bold">
					<?php if ($freelancer['isSenior']) {?>
						<span class="fa fa-circle "> &nbsp; <?php echo $this->translate('Senior Freelancer') ?></span>
					<?php } else {?>
						<span class="fa fa-circle"> &nbsp; <?php echo $this->translate('Freelancer') ?></span>
					<?php }?>

                </p>
				<p class="small font-bold">
                                <span><i class="fa fa-thumbs-up text-danger"></i> &nbsp;
                                    <span>
										<?php
										//var_dump($freelancer['Rating'][0]);
										for ($i = 0; $i < 6; $i++)  {
											if($i < $freelancer['Rating'][0]) {?>
											<i class="fa fa-star text-warning"></i>
											<?php } else { ?>
											<i class="fa fa-star-o text-warning"></i>
										<?php } }?>
                                    </span>
                                </span>
                </p>
				 <p>
                <?php
                    foreach ( $cvfiles as $k => $v ) {
                        ?>
                        <i class="fa fa-file-text"></i><a href="<?php echo '../../../'.$v['path'];?>" class="text-info"> &nbsp; <?php echo $v['name'];?></a>
                        <?php
                    }
                ?>
				</p>

				<form role="form" class="form-inline">
                    <div class="form-group">
                        <input ng-model="password" type="password"
                               placeholder="<?php echo $this->translate('Reset password') ?>"
                               class="form-control required" required>
                    </div>
                    <button ng-click="resetPassword()" class="btn btn-danger" type="submit">
                        <?php echo $this->translate('Reset') ?></button>
                    <p ng-show="passwordChanged==1" class="text-success">
                        <?php echo $this->translate('Password changed.') ?></p>
                </form>
				<div class="hr-line-dashed"></div>
				<h4><?php echo $this->translate('Freelancer Type') ?> </h4>
				<div class="row file-manager">
					<ul class="tag-list" style="padding: 0">
						<li ng-show="freelancer.ResourcesGroup['translation'] == 1">
							<a href=""><i class="fa fa-coffee"></i> <?php echo $this->translate('Translation') ?></a></li>
						<li ng-show="freelancer.ResourcesGroup['desktop'] == 1">
							<a href=""><i class="fa fa-desktop"></i> <?php echo $this->translate('Desktop Publishing') ?>
							</a></li>
						<li ng-show="freelancer.ResourcesGroup['interpreting'] == 1">
							<a href=""><i class="fa fa-comments-o"></i> <?php echo $this->translate('Interpreting') ?></a></li>
					</ul>

					<!--<ul class="tag-list" style="padding: 0">
                    <li ng-show="resourcesType[freelancerData.resources[0].group.name] == 1">
                        <a href=""><i class="fa fa-coffee"></i> <?php echo $this->translate('Translation') ?></a></li>
                    <li ng-show="resourcesType[freelancerData.resources[1].group.name] == 1">
                        <a href=""><i class="fa fa-desktop"></i> <?php echo $this->translate('Desktop Publishing') ?>
                        </a></li>
                    <li ng-show="resourcesType[freelancerData.resources[2].group.name] == 1">
                        <a href=""><i class="fa fa-comments-o"></i> <?php echo $this->translate('Interpreting') ?></a></li>
					</ul>-->

				</div>
				<div class="hr-line-dashed"></div>
				<h4><?php echo $this->translate('Comments of PaperTask') ?></h4>
				<div id="objComment"></div>


            <div class="hr-line-dashed"></div>
            <h4><?php echo $this->translate('Payment information') ?></h4>

            <p><strong><?php echo $this->translate('Paypal') ?></strong>: {{bankInfo.paypal}}</p>

            <p><strong><?php echo $this->translate('Alipay') ?></strong>: {{bankInfo.alipay}}</p>

            <p><strong><?php echo $this->translate('Bank Info') ?></strong>: </p>
            <address class="well">
                <strong><?php echo $this->translate('Bank Name') ?></strong>:  {{bankInfo.account}}<br>
                {{bankInfo.address}}<br>
                {{bankInfo.city}}, {{bankInfo.country}}<br>
                <strong><?php echo $this->translate('Beneficiary Name') ?></strong>: {{bankInfo.name}}<br>
                <strong><?php echo $this->translate('Account No./IBAN') ?></strong>: {{bankInfo.accountNo}}<br>
                <strong><?php echo $this->translate('Swift Code') ?></strong>: {{bankInfo.swift}}<br>
                <strong><?php echo $this->translate('ABA Routing Number') ?></strong>: {{bankInfo.routingNumber}}
            </address>

            <a href="<?php echo $this->url('admin', ['controller'=>'freelancer', 'action'=>'edit-profile']) ?>?id=<?php echo $user['id'];?>"
               class="btn btn-primary btn-block"><i class="fa fa-paste"></i> Edit</a>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="panel blank-panel">
			<div class="panel-heading">
				<div class="panel-options">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#tab-1"><?php echo $this->translate('Skills and Price (PaperTask)') ?></a></li>
						<li class=""><a data-toggle="tab" href="#tab-2"><?php echo $this->translate('Skills and Price (Personal)') ?></a></li>
						<li class=""><a data-toggle="tab" href="#tab-3"><?php echo $this->translate('Task') ?></a></li>
						<li class=""><a data-toggle="tab" href="#tab-4"><?php echo $this->translate('Test') ?></a></li>
						<li class=""><a data-toggle="tab" href="#tab-5"><?php echo $this->translate('Resume') ?></a></li>
					</ul>
				</div>
			</div>

			<div class="panel-body">
				<div class="tab-content">
					<div id="tab-1" class="tab-pane active">
						<div class="ibox float-e-margins" ng-show="freelancer.ResourcesGroup['translation'] == 1" >
							<div class="ibox-title">
								<h5><i class="fa fa-coffee"></i> <?php echo $this->translate('Translation') ?></h5>
                                <?php if($this->isAdmin): ?>
								<div class="ibox-tools">
                                    <a data-toggle="collapse" href="#translation_client" class="btn btn-primary btn-xs"><i class="fa fa-search"></i><?php echo $this->translate('Search Clients') ?></a>
                                </div>
                                <?php endif ?>
							</div>
							<div class="ibox-content">
                                <?php if($this->isAdmin): ?>
									<div class="row">
                                                <div class="col-lg-12">
                                                    <div id="translation_client" class="panel-collapse collapse faq-answer">
                                                        <form method="" class="form-horizontal">
                                                            <div class="row">
                                                                <div class="col-lg-4">
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Name') ?></label>
																		<div class="col-sm-8"><input type="text" class="form-control" ng-model="searchParamsTranslation.name" ></div>
                                                                    </div>
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Company') ?></label>
																		<div class="col-sm-8">
																			<select class="form-control" id="company" name="company" ng-model="searchParamsTranslation.company" >
																				<option value=""></option>
																				<option ng-repeat="company in companies" ng-value="company.id">{{company.name}}</option>
																			</select>
																		</div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-4">
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('ID') ?></label>
																		<div class="col-sm-8"><input ng-model="searchParamsTranslation.idEmployer" type="text" class="form-control" ></div>
                                                                    </div>
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Country') ?></label>
																		<div class="col-sm-8">
																			<select class="form-control" name="" ng-model="searchParamsTranslation.country" >
																				<option value=""></option>
																				<option ng-repeat="country in countries" ng-value="country.id">{{country.name}}</option>
																			</select>
																		</div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-4">
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Email') ?></label>
																		<div class="col-sm-8"><input type="text" class="form-control" ng-model="searchParamsTranslation.email"></div>
                                                                    </div>
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Currency') ?></label>
																		<div class="col-sm-8">
																			<select class="form-control" name="" ng-model="searchParamsTranslation.currency" >
																			  <option></option>
																			  <option value="cny">CNY</option>
																			  <option value="usd">USD</option>
																			</select>
																		</div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="text-right tooltip-demo">
																<a href="#" class="btn btn-sm btn-primary" ng-click="advancedSearchTranslation()"><i class="fa fa-search"></i> <?php echo $this->translate('Search') ?></a>
																<a href="#" class="btn btn-white btn-sm" type="reset" ng-click="resetTranslation()"><i class="fa fa-times"></i> <?php echo $this->translate('Reset') ?></a>
                                                            </div>
                                                        </form>
                                                        <div class="project-list">
                                                            <table class="table table-hover">
                                                                <tbody>
																	<tr ng-repeat="employer in translation_employers">
																		<td class="project-status" width="1%">
																			<span ng-if="employer.isActive=='1'" class="label label-primary"><?php echo $this->translate('Active') ?></span>
																			<span  ng-if="employer.isActive=='0'" class="label label-default"><?php echo $this->translate('Unactive') ?></span>
																		</td>
																		<td class="project-title">
																			<strong><i class="fa fa-user"></i> {{employer.lastName}}&nbsp;{{employer.firstName}}</strong>
																			<br/>
																			<small><?php echo $this->translate('Created') ?> {{employer.createdTime}}</small>
																		</td>
																		<td class="project-title">
																			<strong><i class="fa fa-envelope"></i> {{employer.email}}</strong>
																			<br/>
																			<small>{{employer.employer.position}}</small>
																		</td>
																		<td class="project-title">
																			<strong><i class="fa fa-building"></i> {{employer.employer.company.name}}</strong>
																			<br/>
																			<small>{{employer.country.name}}</small>
																		</td>
																		<td class="project-actions">
																			<a href="#" class="btn btn-white btn-sm" ng-click="addClientTrans(employer.employer,employer.id)" ><?php echo $this->translate('Add') ?></a>
																		</td>
																	</tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
														<div class="btn-group text-right">
															<button type="button" class="btn btn-white" ng-class="pagesTranslation.previous?'':'disabled'" ng-click="onBtnPreviousTranslationClicked()"><i class="fa fa-chevron-left"></i></button>
															<button ng-repeat="page in pagesTranslation.pagesInRange" class="btn btn-white" ng-class="page==pagesTranslation.current?'active':''" ng-click="onBtnGotoTranslation(page-1)">{{page}}</button>
															<button type="button" class="btn btn-white"	ng-class="pagesTranslation.next?'':'disabled'" ng-click="onBtnNextTranslationClicked()"><i class="fa fa-chevron-right"></i></button>
														</div>

                                                    </div>
                                                </div>
                                            </div>
								<?php endif ?>
                                <h4>Clients <small>- means freelancer can do tasks for these clients.</small></h4>
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Name</th>
                                                    <th>Company</th>
                                                    <th>Task Done</th>
                                                    <th></th>
                                                </tr>
                                                </thead>
                                                <tbody>
												<tr ng-repeat="employer in clientsTranslation">
													<td>{{$index + 1}}</td>
													<td><a href="">{{employer.client.name}}&nbsp</a></td>
													<td>{{employer.client.company.name}}</td>
													<td>88</td>
													<td><a href=""><i class="fa fa-trash-o text-danger" ng-click="deleteClientTrans(employer , employer.id)"></i></a></td>
												</tr>
                                                </tbody>
                                            </table>

                                            <div class="hr-line-dashed"></div>

								<h4>
									<?php echo $this->translate('Specialism  <small>- with <i class="fa fa-check"></i> means field tested and pass.</small>') ?>
								</h4>

                                <?php if($this->isAdmin): ?>
    								<div class="row file-manager">
    									 <label class="checkbox-inline" ng-repeat="specialism in TranslationSpecialisms">
    										<input type="checkbox" ng-click="setTestTranslationSpecialisms(specialism)" ng-checked="checkTranslationSpecialism[{{specialism.id - 1}}] == 1" value="{{specialism.id}} " id="inlineCheckbox1"> {{specialism.name}}</label>

    								</div>
                                <?php else: ?>
                                    <div class="row file-manager">
                                        <ul class="tag-list" style="padding: 0">
                                            <li ng-repeat="specialism in TranslationSpecialisms"><a href=""><i class="fa fa-check" ng-show="checkTranslationSpecialism[{{specialism.id - 1}}] == 1"></i> {{specialism.name}}</a></li>
                                        </ul>
                                    </div>
                                <?php endif ?>

								<div class="hr-line-dashed"></div>
								<h4>Cat tools </h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">
										<li ng-repeat="tool in TranslationCatTools">
											<a href="">{{tool.name}}</a>
										</li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4><?php echo $this->translate('Languages and Price') ?> </h4>
                                <?php if($this->isAdmin): ?>
								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
										  <tr>
											<th><?php echo $this->translate('TM Template') ?></th>
											<th><?php echo $this->translate('Repetitions') ?></th>
											<th>100%</th>
											<th>95% - 99%</th>
											<th>85% - 94%</th>
											<th>75% - 84%</th>
											<th>50% - 74%</th>
											<th><?php echo $this->translate('No Match') ?></th>
										  </tr>
										</thead>
										<tbody>
										  <tr>
											<td>TM Rate</td>
											<td>{{tmRatios.repetitions}}%</td>
											<td>{{tmRatios.yibai}}%</td>
											<td>{{tmRatios.jiuwu}}%</td>
											<td>{{tmRatios.bawu}}%</td>
											<td>{{tmRatios.qiwu}}%</td>
											<td>{{tmRatios.wushi}}%</td>
											<td>{{tmRatios.nomatch}}%</td>
										  </tr>
										</tbody>
									  </table>
								  </div>
                              <?php endif ?>
								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Source Language') ?> </th>
												<th><?php echo $this->translate('Target Language') ?> </th>
												<th><?php echo $this->translate('Translation Price') ?></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="translationPrice in translationPrices">
													<td>{{$index + 1}}</td>
													<td>{{translationPrice.sourceLanguage.name}}</td>
													<td>{{translationPrice.targetLanguage.name}}</td>
													<td class="text-info">
                                                        <strong > {{priceType}} {{translationPrice.price}} </strong>
                                                    </td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="ibox float-e-margins" ng-show="freelancer.ResourcesGroup['desktop'] == 1" >
							<div class="ibox-title">
								<h5><i class="fa fa-desktop"></i> <?php echo $this->translate('Desktop Publishing') ?></h5>
                                <?php if($this->isAdmin): ?>
								<div class="ibox-tools">
                                    <a data-toggle="collapse" href="#desktop_client" class="btn btn-primary btn-xs"><i class="fa fa-search"></i><?php echo $this->translate('Search Clients') ?></a>
                                </div>
                                <?php endif ?>
							</div>
							<div class="ibox-content">
                                <?php if($this->isAdmin): ?>
								<div class="row">
                                                <div class="col-lg-12">
                                                    <div id="desktop_client" class="panel-collapse collapse faq-answer">
                                                        <form method="" class="form-horizontal">
                                                            <div class="row">
                                                                <div class="col-lg-4">
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Name') ?></label>
																		<div class="col-sm-8"><input type="text" class="form-control" ng-model="searchParamsDesktop.name" ></div>
                                                                    </div>
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Company') ?></label>
																		<div class="col-sm-8">
																			<select class="form-control" id="company" name="company" ng-model="searchParamsDesktop.company" >
																				<option value=""></option>
																				<option ng-repeat="company in companies" ng-value="company.id">{{company.name}}</option>
																			</select>
																		</div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-4">
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('ID') ?></label>
																		<div class="col-sm-8"><input ng-model="searchParamsDesktop.idEmployer" type="text" class="form-control" ></div>
                                                                    </div>
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Country') ?></label>
																		<div class="col-sm-8">
																			<select class="form-control" name="" ng-model="searchParamsDesktop.country" >
																				<option value=""></option>
																				<option ng-repeat="country in countries" ng-value="country.id">{{country.name}}</option>
																			</select>
																		</div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-4">
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Email') ?></label>
																		<div class="col-sm-8"><input type="text" class="form-control" ng-model="searchParamsDesktop.email"></div>
                                                                    </div>
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Currency') ?></label>
																		<div class="col-sm-8">
																			<select class="form-control" name="" ng-model="searchParamsDesktop.currency" >
																			  <option></option>
																			  <option value="cny">CNY</option>
																			  <option value="usd">USD</option>
																			</select>
																		</div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="text-right tooltip-demo">
																<a href="#" class="btn btn-sm btn-primary" ng-click="advancedSearchDesktop()"><i class="fa fa-search"></i> <?php echo $this->translate('Search') ?></a>
																<a href="#" class="btn btn-white btn-sm" type="reset" ng-click="resetDesktop()"><i class="fa fa-times"></i> <?php echo $this->translate('Reset') ?></a>
                                                            </div>
                                                        </form>
                                                        <div class="project-list">
                                                            <table class="table table-hover">
                                                                <tbody>
																	<tr ng-repeat="employer in desktop_employers">
																		<td class="project-status" width="1%">
																			<span ng-if="employer.isActive=='1'" class="label label-primary"><?php echo $this->translate('Active') ?></span>
																			<span  ng-if="employer.isActive=='0'" class="label label-default"><?php echo $this->translate('Unactive') ?></span>
																		</td>
																		<td class="project-title">
																			<strong><i class="fa fa-user"></i> {{employer.lastName}}&nbsp;{{employer.firstName}}</strong>
																			<br/>
																			<small><?php echo $this->translate('Created') ?> {{employer.createdTime}}</small>
																		</td>
																		<td class="project-title">
																			<strong><i class="fa fa-envelope"></i> {{employer.email}}</strong>
																			<br/>
																			<small>{{employer.employer.position}}</small>
																		</td>
																		<td class="project-title">
																			<strong><i class="fa fa-building"></i> {{employer.employer.company.name}}</strong>
																			<br/>
																			<small>{{employer.country.name}}</small>
																		</td>
																		<td class="project-actions">
																			<a href="#" class="btn btn-white btn-sm" ng-click="addClientDesktop(employer.employer,employer.id)" ><?php echo $this->translate('Add') ?></a>
																		</td>
																	</tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
														<div class="btn-group text-right">
															<button type="button" class="btn btn-white" ng-class="pagesDesktop.previous?'':'disabled'" ng-click="onBtnPreviousDesktopClicked()"><i class="fa fa-chevron-left"></i></button>
															<button ng-repeat="page in pagesDesktop.pagesInRange" class="btn btn-white" ng-class="page==pagesDesktop.current?'active':''" ng-click="onBtnGotoTranslation(page-1)">{{page}}</button>
															<button type="button" class="btn btn-white"	ng-class="pagesDesktop.next?'':'disabled'" ng-click="onBtnNextDesktopClicked()"><i class="fa fa-chevron-right"></i></button>
														</div>

                                                    </div>
                                                </div>
                                            </div>
								<?php endif ?>
                                <h4>Clients <small>- means freelancer can do tasks for these clients.</small></h4>
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Name</th>
                                                    <th>Company</th>
                                                    <th>Task Done</th>
                                                    <th></th>
                                                </tr>
                                                </thead>
                                                <tbody>
												<tr ng-repeat="employer in clientsDesktop">
													<td>{{$index + 1}}</td>
													<td><a href="">{{employer.client.name}}&nbsp</a></td>
													<td>{{employer.client.company.name}}</td>
													<td>88</td>
													<td><a href=""><i class="fa fa-trash-o text-danger" ng-click="deleteClientDesktop(employer , employer.id)"></i></a></td>
												</tr>
                                                </tbody>
                                            </table>

                                            <div class="hr-line-dashed"></div>
								<h4>Operating System </h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">
										<li ng-repeat="system in operatingSystems">
											<a href=""><i class="fa {{(this.id==1) ? 'fa-apple' : 'fa-windows'}}"></i>
												{{system.name}}</a></li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4><?php echo $this->translate('Cat tools') ?></h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">
										<li ng-repeat="tool in DesktopCatTools"><a href="">{{tool.name}}</a></li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4><?php echo $this->translate('Softwares and Price') ?> </h4>
								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Languages') ?> </th>
												<th><?php echo $this->translate('Software') ?> </th>
												<th><?php echo $this->translate('Page') ?> <i class="fa fa-apple"></th>
												<th><?php echo $this->translate('Page') ?> <i class="fa fa-windows"></i></th>
												<th><?php echo $this->translate('Hour') ?> <i class="fa fa-apple"></th>
												<th><?php echo $this->translate('Hour') ?> <i class="fa fa-windows"></i></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="dptPrice in dptPrices">
													<td>{{$index+1}}</td>
													<td>{{dptPrice.language.name}}</td>
													<td>{{dptPrice.software.name}}</td>
													<td class="text-info">
                                                        <strong><strong > {{priceType}} {{dptPrice.priceMac}} </strong>
                                                    </td>
													<td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.pricePc}} </strong>
                                                    </td>
                                                    <td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.priceHourMac}} </strong>
                                                    </td>
                                                    <td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.priceHourPc}} </strong>
                                                    </td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<!--<div class="ibox float-e-margins">
							<div class="ibox-title">
								<h3><i class="fa fa-gears"></i> <?php echo $this->translate('Engineering') ?></h3>
							</div>
							<div class="ibox-content">
								<h4><?php echo $this->translate('Categories and Price') ?> </h4>
								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th>Category </th>
												<th>Unit </th>
												<th>Price </th>
											</tr>
											</thead>
											<tbody>
											<tr ng-repeat="engineeringPrice in engineeringPices">
												<td>{{$index + 1}}</td>
												<td>{{engineeringPrice.engineeringcategory.category}}</td>
												<td>{{engineeringPrice.unit.name}}</td>
												<td class="text-info">
                                                    <strong>{{priceType}} {{engineeringPrice.price}}</strong>
                                                </td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>-->
						<div class="ibox float-e-margins" ng-show="freelancer.ResourcesGroup['interpreting'] == 1" >
							<div class="ibox-title">
								<h5><i class="fa fa-comments-o"></i> <?php echo $this->translate('Interpreting') ?></h5>
                                <?php if($this->isAdmin): ?>
								<div class="ibox-tools">
                                    <a data-toggle="collapse" href="#interpreting_client" class="btn btn-primary btn-xs"><i class="fa fa-search"></i><?php echo $this->translate('Search Clients') ?></a>
                                </div>
                                <?php endif ?>
							</div>
							<div class="ibox-content">
							<div class="row">
                                                <div class="col-lg-12">
                                                    <div id="interpreting_client" class="panel-collapse collapse faq-answer">
                                                        <form method="" class="form-horizontal">
                                                            <div class="row">
                                                                <div class="col-lg-4">
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Name') ?></label>
																		<div class="col-sm-8"><input type="text" class="form-control" ng-model="searchParamsInterpreting.name" ></div>
                                                                    </div>
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Company') ?></label>
																		<div class="col-sm-8">
																			<select class="form-control" id="company" name="company" ng-model="searchParamsInterpreting.company" >
																				<option value=""></option>
																				<option ng-repeat="company in companies" ng-value="company.id">{{company.name}}</option>
																			</select>
																		</div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-4">
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('ID') ?></label>
																		<div class="col-sm-8"><input ng-model="searchParamsInterpreting.idEmployer" type="text" class="form-control" ></div>
                                                                    </div>
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Country') ?></label>
																		<div class="col-sm-8">
																			<select class="form-control" name="" ng-model="searchParamsInterpreting.country" >
																				<option value=""></option>
																				<option ng-repeat="country in countries" ng-value="country.id">{{country.name}}</option>
																			</select>
																		</div>
                                                                    </div>
                                                                </div>
                                                                <div class="col-lg-4">
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Email') ?></label>
																		<div class="col-sm-8"><input type="text" class="form-control" ng-model="searchParamsInterpreting.email"></div>
                                                                    </div>
                                                                    <div class="form-group">
																		<label class="col-sm-4 control-label"><?php echo $this->translate('Currency') ?></label>
																		<div class="col-sm-8">
																			<select class="form-control" name="" ng-model="searchParamsInterpreting.currency" >
																			  <option></option>
																			  <option value="cny">CNY</option>
																			  <option value="usd">USD</option>
																			</select>
																		</div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="text-right tooltip-demo">
																<a href="#" class="btn btn-sm btn-primary" ng-click="advancedSearchInterpreting()"><i class="fa fa-search"></i> <?php echo $this->translate('Search') ?></a>
																<a href="#" class="btn btn-white btn-sm" type="reset" ng-click="resetInterpreting()"><i class="fa fa-times"></i> <?php echo $this->translate('Reset') ?></a>
                                                            </div>
                                                        </form>
                                                        <div class="project-list">
                                                            <table class="table table-hover">
                                                                <tbody>
																	<tr ng-repeat="employer in interpreting_employers">
																		<td class="project-status" width="1%">
																			<span ng-if="employer.isActive=='1'" class="label label-primary"><?php echo $this->translate('Active') ?></span>
																			<span  ng-if="employer.isActive=='0'" class="label label-default"><?php echo $this->translate('Unactive') ?></span>
																		</td>
																		<td class="project-title">
																			<strong><i class="fa fa-user"></i> {{employer.lastName}}&nbsp;{{employer.firstName}}</strong>
																			<br/>
																			<small><?php echo $this->translate('Created') ?> {{employer.createdTime}}</small>
																		</td>
																		<td class="project-title">
																			<strong><i class="fa fa-envelope"></i> {{employer.email}}</strong>
																			<br/>
																			<small>{{employer.employer.position}}</small>
																		</td>
																		<td class="project-title">
																			<strong><i class="fa fa-building"></i> {{employer.employer.company.name}}</strong>
																			<br/>
																			<small>{{employer.country.name}}</small>
																		</td>
																		<td class="project-actions">
																			<a href="#" class="btn btn-white btn-sm" ng-click="addClientInterpreting(employer.employer , employer.id)" ><?php echo $this->translate('Add') ?></a>
																		</td>
																	</tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
														<div class="btn-group text-right">
															<button type="button" class="btn btn-white" ng-class="pagesInterpreting.previous?'':'disabled'" ng-click="onBtnPreviousInterpretingClicked()"><i class="fa fa-chevron-left"></i></button>
															<button ng-repeat="page in pagesInterpreting.pagesInRange" class="btn btn-white" ng-class="page==pagesInterpreting.current?'active':''" ng-click="onBtnGotoInterpreting(page-1)">{{page}}</button>
															<button type="button" class="btn btn-white"	ng-class="pagesInterpreting.next?'':'disabled'" ng-click="onBtnNextInterpretingClicked()"><i class="fa fa-chevron-right"></i></button>
														</div>

                                                    </div>
                                                </div>
                                            </div>
								<h4>Clients <small>- means freelancer can do tasks for these clients.</small></h4>
                                            <table class="table">
                                                <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Name</th>
                                                    <th>Company</th>
                                                    <th>Task Done</th>
                                                    <th></th>
                                                </tr>
                                                </thead>
                                                <tbody>
												<tr ng-repeat="employer in clientsInterpreting">
													<td>{{$index + 1}}</td>
													<td><a href="">{{employer.client.name}}&nbsp</a></td>
													<td>{{employer.client.company.name}}</td>
													<td>88</td>
													<td><a href=""><i class="fa fa-trash-o text-danger" ng-click="deleteClientInterpreting(employer , employer.id)"></i></a></td>
												</tr>
                                                </tbody>
                                            </table>

                                            <div class="hr-line-dashed"></div>
								<h4><?php echo $this->translate('Specialism') ?></h4>



                                <?php if($this->isAdmin): ?>
                                    <div class="row file-manager">
                                        <label class="checkbox-inline" ng-repeat="specialism in InterpretingSpecialisms">
                                            <input type="checkbox" ng-click="setTestInterpretingSpecialisms(specialism)" ng-checked="checkInterpretingSpecialism[{{specialism.id - 1}}] == 1" value="{{specialism.id}} " id="inlineCheckbox1"> {{specialism.name}} </label>
                                    </div>
                                <?php else: ?>
                                    <div class="row file-manager">
                                        <ul class="tag-list" style="padding: 0">
                                            <li ng-repeat="specialism in InterpretingSpecialisms"><a href=""><i class="fa fa-check" ng-show="checkInterpretingSpecialism[{{specialism.id - 1}}] == 1"></i> {{specialism.name}}</a></li>
                                        </ul>
                                    </div>
                                <?php endif; ?>

								<div class="hr-line-dashed"></div>
								<h4>Languages and Price </h4>

								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Source Language') ?> </th>
												<th><?php echo $this->translate('Target Language') ?> </th>
												<th><?php echo $this->translate('Interpreting Service') ?></th>
												<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Day') ?></th>
												<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('half-Day') ?></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="interpretingPrice in interpretingPrices">
													<td>{{$index + 1}}</td>
													<td>{{interpretingPrice.sourceLanguage.name}}</td>
													<td>{{interpretingPrice.targetLanguage.name}}</td>
													<td>{{interpretingPrice.service.name}}</td>
													<td class="text-info"><strong>{{priceType}} {{interpretingPrice.priceDay}}</strong></td>
													<td class="text-info"><strong>{{priceType}} {{interpretingPrice.priceHalfDay}}</strong></td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>

					<div id="tab-2" class="tab-pane">
 						<div class="ibox float-e-margins" ng-show="freelancer.ResourcesGroup['translation'] == 1">
							<div class="ibox-title">
								<h3><i class="fa fa-coffee"></i> <?php echo $this->translate('Translation') ?></h3>
							</div>
							<div class="ibox-content">
								<h4>
									<?php echo $this->translate('Specialism  <small>- with <i class="fa fa-check"></i> means field tested and pass.</small>') ?>
								</h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">
										<!-- TODO: check specialism is tested or not -->
										<li ng-repeat="specialism in TranslationSpecialisms">
											<a href=""><i ng-show="specialism.tested==1" class="fa fa-check"></i>
												{{specialism.name}}</a>
										</li>
									</ul>
								</div>


								<div class="hr-line-dashed"></div>
								<h4>Cat tools </h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">
										<li ng-repeat="tool in TranslationCatTools">
											<a href="">{{tool.name}}</a>
										</li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4><?php echo $this->translate('Languages and Price') ?> </h4>

								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Source Language') ?> </th>
												<th><?php echo $this->translate('Target Language') ?> </th>
												<th><?php echo $this->translate('Translation Price') ?></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="translationPrice in translationPricesP">
													<td>{{$index + 1}}</td>
													<td>{{translationPrice.sourceLanguage.name}}</td>
													<td>{{translationPrice.targetLanguage.name}}</td>
													<td class="text-info">
                                                        <strong > {{priceType}} {{translationPrice.price}} </strong>
                                                    </td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="ibox float-e-margins" ng-show="freelancer.ResourcesGroup['desktop'] == 1">
							<div class="ibox-title">
								<h3><i class="fa fa-desktop"></i> <?php echo $this->translate('Desktop Publishing') ?></h3>
							</div>
							<div class="ibox-content">
								<h4>Operating System </h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">
										<li ng-repeat="system in operatingSystems">
											<a href=""><i class="fa {{(this.id==1) ? 'fa-apple' : 'fa-windows'}}"></i>
												{{system.name}}</a></li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4><?php echo $this->translate('Cat tools') ?></h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">
										<li ng-repeat="tool in DesktopCatTools"><a href="">{{tool.name}}</a></li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4><?php echo $this->translate('Softwares and Price') ?> </h4>
								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Languages') ?> </th>
												<th><?php echo $this->translate('Software') ?> </th>
												<th><?php echo $this->translate('Page') ?> <i class="fa fa-apple"></th>
												<th><?php echo $this->translate('Page') ?> <i class="fa fa-windows"></i></th>
												<th><?php echo $this->translate('Hour') ?> <i class="fa fa-apple"></th>
												<th><?php echo $this->translate('Hour') ?> <i class="fa fa-windows"></i></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="dptPrice in dptPricesP">
													<td>{{$index+1}}</td>
													<td>{{dptPrice.language.name}}</td>
													<td>{{dptPrice.software.name}}</td>
													<td class="text-info">
                                                        <strong><strong > {{priceType}} {{dptPrice.priceMac}} </strong>
                                                    </td>
													<td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.pricePc}} </strong>
                                                    </td>
                                                    <td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.priceHourMac}} </strong>
                                                    </td>
                                                    <td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.priceHourPc}} </strong>
                                                    </td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="ibox float-e-margins" ng-show="freelancer.ResourcesGroup['interpreting'] == 1">
							<div class="ibox-title">
								<h3><i class="fa fa-comments-o"></i> <?php echo $this->translate('Interpreting') ?></h3>
							</div>
							<div class="ibox-content">
								<h4><?php echo $this->translate('Specialism') ?></h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">

										<!-- TODO: check specialism is tested or not -->
										<li ng-repeat="specialism in InterpretingSpecialisms">
											<a href=""><i ng-show="specialism.tested==1" class="fa fa-check"></i>
												{{specialism.name}}</a>
										</li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4>Languages and Price </h4>

								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Source Language') ?> </th>
												<th><?php echo $this->translate('Target Language') ?> </th>
												<th><?php echo $this->translate('Interpreting Service') ?></th>
												<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Day') ?></th>
												<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('half-Day') ?></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="interpretingPrice in interpretingPricesP">
													<td>{{$index + 1}}</td>
													<td>{{interpretingPrice.sourceLanguage.name}}</td>
													<td>{{interpretingPrice.targetLanguage.name}}</td>
													<td>{{interpretingPrice.service.name}}</td>
													<td class="text-info"><strong>{{priceType}} {{interpretingPrice.priceDay}}</strong></td>
													<td class="text-info"><strong>{{priceType}} {{interpretingPrice.priceHalfDay}}</strong></td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div id="tab-3" class="tab-pane">
						<div class="ibox">
							<div class="ibox-content">
								<div class="project-list">
									<table class="table table-hover">
										<tbody>
											<tr>
												<td class="project-status" width="1%">
													<span class="label label-default">Completed</span>
												</td>
												<td class="project-title">
													<a href="#">88888888</a>
												</td>

												</td>
												<td class="project-title">
													<strong>Project Name dfadsfja;kfja;dkfja;dfadsfja;kfja;dkfja;</strong>
													<br />
													<small>2014.Sep.08 -  2014.Oct.28</small>
												</td>
												<td class="project-title text-info">
													<strong>CNY 868.88</strong>
												</td>
											</tr>
											<tr>
												<td class="project-status" width="1%">
													<span class="label label-primary">Ongoing</span>
												</td>
												<td class="project-title">
													<a href="#">88887366</a>
												</td>
												<td class="project-title">
													<strong>Project Name</strong>
													<br />
													<small>2014.Sep.08 -  2014.Oct.28</small>
												</td>
												<td class="project-title text-info">
													<strong>CNY 1868.88</strong>
												</td>
											</tr>
										</tbody>
									</table>
								</div>
								<div class="btn-group text-right">
									<button type="button" class="btn btn-white"><i class="fa fa-chevron-left"></i></button>
									<button class="btn btn-white">1</button>
									<button class="btn btn-white  active">2</button>
									<button class="btn btn-white">3</button>
									<button class="btn btn-white">4</button>
									<button type="button" class="btn btn-white"><i class="fa fa-chevron-right"></i> </button>
								</div>
							</div>
						</div>
					</div>
					<div id="tab-5" class="tab-pane">

                                    <div class="ibox float-e-margins">
                                        <div class="ibox-title">
                                            <h3><i class="fa fa-cog"></i> Working Experiences</h3>
                                        </div>
                                        <div class="ibox-content">
                                            <p><?php echo $resume['workingExperiences'];?></p>
                                        </div>
                                    </div>

                                    <div class="ibox float-e-margins">
                                        <div class="ibox-title">
                                            <h3><i class="fa fa-graduation-cap"></i> Education</h3>
                                        </div>
                                        <div class="ibox-content">
                                            <p><?php echo $resume['education'];?></p>
                                        </div>
                                    </div>

                                    <div class="ibox float-e-margins">
                                        <div class="ibox-title">
                                            <h3><i class="fa fa-comment-o"></i> Recommended</h3>
                                        </div>
                                        <div class="ibox-content">
                                           <p><?php echo $resume['recommended'];?></p>
                                        </div>
                                    </div>
                    </div>
				</div>

                <?php if(!$this->isAdmin): ?>
                <a href="<?php echo $this->url('admin', ['controller'=>'freelancer', 'action'=>'edit-price']) ?>?id=<?php echo $user['id'];?>" class="btn btn-primary btn-block" type="button"><i class="fa fa-paste"></i> Edit Personal Skills &amp; Prices</a>
                <?php endif ?>
            </div>

		</div>

	</div>

</div>

 <?php //include "profile/modal.phtml" ?>
