<!-- Scripts -->
<?php
$this->headScript ()->prependFile ( $this->basePath () . '/js/admin/freelancer/details.js' )
					->prependFile ( $this->basePath () . '/js/admin/bootstrap-modal.js' )
					->prependScript ( "angularApp = angular.module('project', []);" )
					->prependFile ( $this->basePath () . '/js/plugins/summernote/summernote.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/validate/jquery.validate.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/steps/jquery.steps.min.js' )
					->prependFile ( $this->basePath () . '/js/plugins/pace/pace.min.js' )
					->prependFile ( $this->basePath () . '/js/inspinia.js' );
?>
<?php
$this->inlineScript()
    ->prependScript("
        var USER_ID = '" . $user['id'] . "';
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
    ");
?>
					
<div class="row animated fadeInRight" ng-controller="FreelancerController" ng-init="init()">
	<div class="col-md-4">
		<div class="ibox">
			<div class="ibox-title">
				<h5>{{userInfo.lastName}}, {{userInfo.firstName}}</h5>
				<div class="ibox-tools">				
					<span ng-show="userInfo.isActive == '1'" class="label label-primary"><?php echo $this->translate('Active') ?></span>
					<span ng-show="userInfo.isActive == '0'" class="label label-default"><?php echo $this->translate('Unactive') ?></span>
				</div>
			</div>

			<div class="ibox-content profile-content">
				<p><i class="fa fa-user"></i> &nbsp; 
                {{userInfo.lastName}}, {{userInfo.firstName}} &nbsp; 
                <i ng-show="userInfo.gender == '0'" class="fa fa-male"></i>
                <i ng-show="userInfo.gender == '1'" class="fa fa-female"></i>
                </p>
				<p><i class="fa fa-envelope"></i> &nbsp; {{userInfo.email}}</p>
				<p><i class="fa fa-tag"></i> &nbsp; {{userInfo.tag}}</p>
				
				<p><i class="fa fa-phone"></i> &nbsp; {{userInfo.phone}}</p>
				<p><i class="fa fa-map-marker"></i> &nbsp; {{userInfo.city}}, {{userInfo.country.name}}</p>
				<p class="small font-bold">
					<span ng-show="userInfo.isSenior == '1'" class="fa fa-circle text-danger"><?php echo $this->translate('Senior Freelancer') ?></span>
					<span ng-show="userInfo.isSenior == '0'" class="fa fa-circle text-danger"><?php echo $this->translate('Freelancer') ?></span>
                </p>
				<p class="small font-bold">
                                <span><i class="fa fa-thumbs-up text-danger"></i> &nbsp; 
                                    <span>
                                        <i class="fa fa-star text-warning"></i>
                                        <i class="fa fa-star text-warning"></i>
                                        <i class="fa fa-star text-warning"></i>
                                        <i class="fa fa-star text-warning"></i>
                                        <i class="fa fa-star-o text-warning"></i>
                                        <i class="fa fa-star-o text-warning"></i>
                                    </span>
                                </span>
                </p>
				<p><i class="fa fa-file-text"></i><a href="" class="text-info"> &nbsp; John.docx</a></p>
				
				<form role="form" class="form-inline">
                    <div class="form-group">
                        <input ng-model="password" type="password"
                               placeholder="<?php echo $this->translate('Reset password') ?>"
                               class="form-control required" required>
                    </div>
                    <button ng-click="resetPassword()" class="btn btn-danger" type="submit">
                        <?php echo $this->translate('Reset') ?></button>
                    <p ng-show="passwordChanged==1" class="text-success">
                        <?php echo $this->translate('Password changed.') ?></p>
                </form>
				<div class="hr-line-dashed"></div>
				<h4><?php echo $this->translate('Freelancer Type') ?> </h4>
				<div class="row file-manager">
					<ul class="tag-list" style="padding: 0">
						<li ng-show="freelancer.ResourcesGroup['translation'] == 1">
							<a href=""><i class="fa fa-coffee"></i> <?php echo $this->translate('Translation') ?></a></li>
						<li ng-show="freelancer.ResourcesGroup['desktop'] == 1">
							<a href=""><i class="fa fa-desktop"></i> <?php echo $this->translate('Desktop Publishing') ?>
							</a></li>
						<li ng-show="freelancer.ResourcesGroup['interpreting'] == 1">
							<a href=""><i class="fa fa-comments-o"></i> <?php echo $this->translate('Interpreting') ?></a></li>
					</ul>
					
					<!--<ul class="tag-list" style="padding: 0">
                    <li ng-show="resourcesType[freelancerData.resources[0].group.name] == 1">
                        <a href=""><i class="fa fa-coffee"></i> <?php echo $this->translate('Translation') ?></a></li>
                    <li ng-show="resourcesType[freelancerData.resources[1].group.name] == 1">
                        <a href=""><i class="fa fa-desktop"></i> <?php echo $this->translate('Desktop Publishing') ?>
                        </a></li>
                    <li ng-show="resourcesType[freelancerData.resources[2].group.name] == 1">
                        <a href=""><i class="fa fa-comments-o"></i> <?php echo $this->translate('Interpreting') ?></a></li>
					</ul>-->
				
				</div>
				<div class="hr-line-dashed"></div>
				  <h4><?php echo $this->translate('Comments of PaperTask') ?></h4>

            <p>
                {{resume.papertaskComments}}
            </p>

            <div class="hr-line-dashed"></div>
            <h4><?php echo $this->translate('Payment information') ?></h4>

            <p><strong><?php echo $this->translate('Paypal') ?></strong>: {{bankInfo.paypal}}</p>

            <p><strong><?php echo $this->translate('Alipay') ?></strong>: {{bankInfo.alipay}}</p>

            <p><strong><?php echo $this->translate('Bank Info') ?></strong>: </p>
            <address class="well">
                <strong><?php echo $this->translate('Bank Name') ?></strong><br>
                {{bankInfo.address}}<br>
                {{bankInfo.city}}, {{bankInfo.country}}<br>
                <strong><?php echo $this->translate('Beneficiary Name') ?></strong>: {{bankInfo.name}}<br>
                <strong><?php echo $this->translate('Account No./IBAN') ?></strong>: {{bankInfo.accountNo}}<br>
                <strong><?php echo $this->translate('Swift Code') ?></strong>: {{bankInfo.swift}}<br>
                <strong><?php echo $this->translate('ABA Routing Number') ?></strong>: {{bankInfo.routingNumber}}
            </address>

            <a href="<?php echo $this->url('admin', ['controller'=>'freelancer', 'action'=>'edit-payment-info']) ?>?id={{user.user.id}}"
               class="btn btn-primary btn-block"><i class="fa fa-paste"></i> Edit</a>
			</div>
		</div>
	</div>
	<div class="col-md-8">
		<div class="panel blank-panel">
			<div class="panel-heading">
				<div class="panel-options">
					<ul class="nav nav-tabs">
						<li class="active"><a data-toggle="tab" href="#tab-1"><?php echo $this->translate('Skills and Price (PaperTask)') ?></a></li>
						<li class=""><a data-toggle="tab" href="#tab-2"><?php echo $this->translate('Skills and Price (Personal)') ?></a></li>
						<li class=""><a data-toggle="tab" href="#tab-3"><?php echo $this->translate('Task') ?></a></li>
						<li class=""><a data-toggle="tab" href="#tab-4"><?php echo $this->translate('Test') ?></a></li>
						<li class=""><a data-toggle="tab" href="#tab-5"><?php echo $this->translate('Resume') ?></a></li>
					</ul>
				</div>
			</div>

			<div class="panel-body">
				<div class="tab-content">
					<div id="tab-1" class="tab-pane active">
						<div class="ibox float-e-margins" ng-show="freelancer.ResourcesGroup['translation'] == 1" >
							<div class="ibox-title">
								<h3><i class="fa fa-coffee"></i> <?php echo $this->translate('Translation') ?></h3>
							</div>
							<div class="ibox-content">
								<h4>
									<?php echo $this->translate('Specialism  <small>- with <i class="fa fa-check"></i> means field tested and pass.</small>') ?>
								</h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">
										<!-- TODO: check specialism is tested or not -->
										<li ng-repeat="specialism in TranslationSpecialisms">
											<a href=""><i ng-show="specialism.tested==1" class="fa fa-check"></i>
												{{specialism.name}}</a>
										</li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4>Cat tools </h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">
										<li ng-repeat="tool in TranslationCatTools">
											<a href="">{{tool.name}}</a>
										</li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4><?php echo $this->translate('Languages and Price') ?> </h4>
								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
										  <tr>
											<th><?php echo $this->translate('TM Template') ?></th>
											<th><?php echo $this->translate('Repetitions') ?></th>
											<th>100%</th>
											<th>95% - 99%</th>
											<th>85% - 94%</th>
											<th>75% - 84%</th>
											<th>50% - 74%</th>
											<th><?php echo $this->translate('No Match') ?></th>
										  </tr>
										</thead>
										<tbody>
										  <tr>
											<td>TM Rate</td>
											<td>{{tmRatios.repetitions}}%</td>
											<td>{{tmRatios.yibai}}%</td>
											<td>{{tmRatios.jiuwu}}%</td>
											<td>{{tmRatios.bawu}}%</td>
											<td>{{tmRatios.qiwu}}%</td>
											<td>{{tmRatios.wushi}}%</td>
											<td>{{tmRatios.nomatch}}%</td>
										  </tr>
										</tbody>
									  </table>
								  </div>

								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Source Language') ?> </th>
												<th><?php echo $this->translate('Target Language') ?> </th>
												<th><?php echo $this->translate('Translation Price') ?></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="translationPrice in translationPrices">
													<td>{{$index + 1}}</td>
													<td>{{translationPrice.sourceLanguage.name}}</td>
													<td>{{translationPrice.targetLanguage.name}}</td>
													<td class="text-info">
                                                        <strong > {{priceType}} {{translationPrice.price}} </strong>
                                                    </td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="ibox float-e-margins" ng-show="freelancer.ResourcesGroup['desktop'] == 1" >
							<div class="ibox-title">
								<h3><i class="fa fa-desktop"></i> <?php echo $this->translate('Desktop Publishing') ?></h3>
							</div>
							<div class="ibox-content">
								<h4>Operating System </h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">
										<li ng-repeat="system in operatingSystems">
											<a href=""><i class="fa {{(this.id==1) ? 'fa-apple' : 'fa-windows'}}"></i>
												{{system.name}}</a></li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4><?php echo $this->translate('Cat tools') ?></h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">
										<li ng-repeat="tool in DesktopCatTools"><a href="">{{tool.name}}</a></li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4><?php echo $this->translate('Softwares and Price') ?> </h4>
								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Languages') ?> </th>
												<th><?php echo $this->translate('Software') ?> </th>
												<th><?php echo $this->translate('Page') ?> <i class="fa fa-apple"></th>
												<th><?php echo $this->translate('Page') ?> <i class="fa fa-windows"></i></th>
												<th><?php echo $this->translate('Hour') ?> <i class="fa fa-apple"></th>
												<th><?php echo $this->translate('Hour') ?> <i class="fa fa-windows"></i></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="dptPrice in dptPrices">
													<td>{{$index+1}}</td>
													<td>{{dptPrice.language.name}}</td>
													<td>{{dptPrice.software.name}}</td>
													<td class="text-info">
                                                        <strong><strong > {{priceType}} {{dptPrice.priceMac}} </strong>
                                                    </td>
													<td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.pricePc}} </strong>
                                                    </td>
                                                    <td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.priceHourMac}} </strong>
                                                    </td>
                                                    <td class="text-info">
                                                        <strong><strong> {{priceType}} {{dptPrice.priceHourPc}} </strong>
                                                    </td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<!--<div class="ibox float-e-margins">
							<div class="ibox-title">
								<h3><i class="fa fa-gears"></i> <?php echo $this->translate('Engineering') ?></h3>
							</div>
							<div class="ibox-content">
								<h4><?php echo $this->translate('Categories and Price') ?> </h4>
								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th>Category </th>
												<th>Unit </th>
												<th>Price </th>
											</tr>
											</thead>
											<tbody>
											<tr ng-repeat="engineeringPrice in engineeringPices">
												<td>{{$index + 1}}</td>
												<td>{{engineeringPrice.engineeringcategory.category}}</td>
												<td>{{engineeringPrice.unit.name}}</td>
												<td class="text-info">
                                                    <strong>{{priceType}} {{engineeringPrice.price}}</strong>
                                                </td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>-->
						<div class="ibox float-e-margins" ng-show="freelancer.ResourcesGroup['interpreting'] == 1" >
							<div class="ibox-title">
								<h3><i class="fa fa-comments-o"></i> <?php echo $this->translate('Interpreting') ?></h3>
							</div>
							<div class="ibox-content">
								<h4><?php echo $this->translate('Specialism') ?></h4>

								<div class="row file-manager">
									<ul class="tag-list" style="padding: 0">

										<!-- TODO: check specialism is tested or not -->
										<li ng-repeat="specialism in InterpretingSpecialisms">
											<a href=""><i ng-show="specialism.tested==1" class="fa fa-check"></i>
												{{specialism.name}}</a>
										</li>
									</ul>
								</div>
								<div class="hr-line-dashed"></div>
								<h4>Languages and Price </h4>

								<div class="table-responsive">
									<table class="table table-striped">
										<thead>
											<tr>
												<th>#</th>
												<th><?php echo $this->translate('Source Language') ?> </th>
												<th><?php echo $this->translate('Target Language') ?> </th>
												<th><?php echo $this->translate('Interpreting Service') ?></th>
												<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('Day') ?></th>
												<th><?php echo $this->translate('Price') ?>/<?php echo $this->translate('half-Day') ?></th>
											</tr>
											</thead>
											<tbody>
												<tr ng-repeat="interpretingPrice in interpretingPrices">
													<td>{{$index + 1}}</td>
													<td>{{interpretingPrice.sourceLanguage.name}}</td>
													<td>{{interpretingPrice.targetLanguage.name}}</td>
													<td>{{interpretingPrice.service.name}}</td>
													<td class="text-info"><strong>{{priceType}} {{interpretingPrice.priceDay}}</strong></td>
													<td class="text-info"><strong>{{priceType}} {{interpretingPrice.priceHalfDay}}</strong></td>
												</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
					
					<div id="tab-2" class="tab-pane">
						<div class="ibox float-e-margins">
							<div class="ibox-title">
								<h3><i class="fa fa-coffee"></i> <?php echo $this->translate('Comming soon') ?></h3>
							</div>
							
						</div>
					</div>
					<div id="tab-3" class="tab-pane">
						<div class="ibox">
							<div class="ibox-content">
								<div class="project-list">
									<table class="table table-hover">
										<tbody>
											<tr>
												<td class="project-status" width="1%">
													<span class="label label-default">Completed</span>
												</td>
												<td class="project-title">
													<a href="#">88888888</a>
												</td>

												</td>
												<td class="project-title">
													<strong>Project Name dfadsfja;kfja;dkfja;dfadsfja;kfja;dkfja;</strong>
													<br />
													<small>2014.Sep.08 -  2014.Oct.28</small>
												</td>
												<td class="project-title text-info">
													<strong>CNY 868.88</strong>
												</td>
											</tr>
											<tr>
												<td class="project-status" width="1%">
													<span class="label label-primary">Ongoing</span>
												</td>
												<td class="project-title">
													<a href="#">88887366</a>
												</td>
												<td class="project-title">
													<strong>Project Name</strong>
													<br />
													<small>2014.Sep.08 -  2014.Oct.28</small>
												</td>
												<td class="project-title text-info">
													<strong>CNY 1868.88</strong>
												</td>
											</tr>
										</tbody>
									</table>
								</div>
								<div class="btn-group text-right">
									<button type="button" class="btn btn-white"><i class="fa fa-chevron-left"></i></button>
									<button class="btn btn-white">1</button>
									<button class="btn btn-white  active">2</button>
									<button class="btn btn-white">3</button>
									<button class="btn btn-white">4</button>
									<button type="button" class="btn btn-white"><i class="fa fa-chevron-right"></i> </button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>

	</div>
</div>
 
<?php //include "profile/modal.phtml" ?>