<?php $this->headTitle($this->translate('Edit Profile')) ?>
<?php
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css');
$this->headScript()
    ->prependFile($this->basePath() . '/js/admin/freelancer/edit-profile.js')
    ->prependFile($this->basePath() . '/js/common.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-file-upload/angular-file-upload.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload']);")
    ->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js');

$this->inlineScript()
    ->prependScript("
        var USER_ID = '" . $this->user['id'] . "';
        $(document).ready(function(){
            //$('.summernote').summernote();
        });
        var edit = function() {
            $('.click2edit').summernote({focus: true});
        };
        var save = function() {
            var aHTML = $('.click2edit').code(); //save HTML If you need(aHTML: array).
            $('.click2edit').destroy();
        };
		var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
        ");
?>


<div ng-controller="EditProfileFreelancerController" ng-init="init()" id="EditProfileFreelancerController" class="ibox float-e-margins">
    <div class="ibox-title">
        <h4><i class="fa fa-edit"></i> <?php echo $this->translate('Edit Profile') ?></h4>
    </div>

    <div class="ibox-content">
        <form name="editProfileForm" method="">
			<div class="row">
                                    <div class="col-lg-2">
                                        <h4><i class="fa fa-plug"></i>&nbsp; <?php echo $this->translate('Status') ?></h4>
                                    </div>
                                    <div class="col-lg-8">
                                        <div data-toggle="buttons">
											<label class="btn btn-outline btn-primary {{active_class(userInfo.isActive, '1')}}" ng-click="setActive('1')">
												<input type="radio" name="active" > <?php echo $this->translate('Active') ?>
											</label>
											&nbsp;
											<label class="btn btn-outline btn-primary {{active_class(userInfo.isActive, '0')}}" ng-click="setActive('0')">
												<input type="radio" name="deactive"  > <?php echo $this->translate('De-Active') ?>
											</label>
										</div>		
                                    </div>
            </div>			
			<div class="hr-line-dashed"></div> 
			<div class="panel panel-primary">
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-lg-8">
                                                <h4><i class="fa fa-file-text"></i> Comments from PaperTask </h4>  
                                            </div>
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <label class="col-sm-4 control-label"><i class="fa fa-star"></i> Rating</label>
                                                    <div class="col-sm-6">
                                                        <select name="">
                                                          <option></option>
                                                          <option value="">A+</option>
                                                          <option value="">A</option>
                                                          <option value="">A-</option>
                                                          <option value="">B+</option>
                                                          <option value="">B</option>
                                                          <option value="">B-</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
											
                                        </div>
                                        <div class="hr-line-dashed"></div>
                                        <div class="row">
                                            <div class="col-lg-12">
                                                <div class="summernote"></div>
                                            </div>
                                        </div>
                                    </div>
            </div>			
            <div class="panel panel-primary">
                <div class="panel-body">
                    <h4><i class="fa fa-info-circle"></i> <?php echo $this->translate('Basic Information') ?></h4>
                    <div class="hr-line-dashed"></div>
					
                    <?php include __DIR__ . "/edit-profile/basic-info.phtml" ?>
                </div>
            </div>
			<div class="panel panel-primary">
                <div class="panel-body">
                    <h4><i class="fa fa-puzzle-piece"></i> <?php echo $this->translate('Resource Type') ?></h4>
                    <div class="hr-line-dashed"></div>
					
                    <?php include __DIR__ . "/edit-profile/resource-type.phtml" ?>
                </div>
            </div>
			
			<div class="panel panel-primary">
                <div class="panel-body">
                    <h4><i class="fa fa-usd"></i> <?php echo $this->translate('Price for PaperTask') ?></h4>
                    <div class="hr-line-dashed"></div>
					
                    <?php include __DIR__ . "/edit-profile/language-skill-price.phtml" ?>
                </div>
            </div>
			
			<div class="panel panel-primary">
                <div class="panel-body">
                    <h4><i class="fa fa-bank"></i> <?php echo $this->translate('Payment Information') ?></h4>
                    <div class="hr-line-dashed"></div>
					
                    <?php include __DIR__ . "/edit-profile/bank-info.phtml" ?>
                </div>
            </div>
			
            <div class="panel panel-primary">
                <div class="panel-body">

                    <?php include __DIR__ . "/../user/resume.phtml" ?>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-4 col-sm-offset-4">
                    <button ng-click="editProfile()" class="btn btn-primary btn-block" type="submit">
                        <?php echo $this->translate('Save') ?></button>
                </div>
            </div>

        </form>
    </div>
</div>
<?php include "/edit-profile/modal.phtml" ?>