
<!-- Le styles -->
<?php $this->headLink()
        ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
        ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<!-- Scripts -->
<?php 
$this->headScript()
    ->prependFile($this->basePath() . '/js/admin/freelancer/finish-registration.js')
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', []);")
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js')
	->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js');

$this->inlineScript()
    ->prependScript("
        var USER_ID = '" . $this->user->getId() . "';
		var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
		var EXITS_CONFIRM_TEXT = '" . $this->translate('This client was existed') . "';
		var EXITS_CONFIRM_OPTION_TEXT = '" . $this->translate('This option was existed, please chose other') . "';
		var LANG_CODE = '" . $this->lang_code . "';
        ");	
	
?>
<!-- Add custom style -->
<style type="text/css">

    .label {
        font-size: 15px;
    }

    h3 {
        font-size: 18px;
    }

    .float-e-margins .btn {
        margin-bottom: 0px;
    }

    .resource-types .panel-body label{
        margin-right: 0.5em;
    }

    .multiselect-container{
        max-height: 250px;
        overflow-y: auto;
        overflow-x: hidden;
    }

</style>
<!-- End custom style -->
    <script>
        USER_ID = "<?php echo ($this->user) ? $this->user->getId() : '' ?>"
    </script>
    <div class="row" class="ibox-content" id="UpdateInfoController" ng-init="init()" ng-controller="UpdateInfoController">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div>
                    <h2 ng-show="!userInfo.profileUpdated">
                        Please finish your account information
                    </h2>
                    <h2 ng-show="userInfo.profileUpdated">
                        Update your account information
                    </h2>

                    <form id="form" action="#" class="wizard-big">
                        <?php include __DIR__ . "/finish-registration/basic-info.phtml" ?>
                        <?php include __DIR__ . "/finish-registration/resource-type.phtml" ?>
                        <?php include __DIR__ . "/finish-registration/language-skill-price.phtml" ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
<?php include __DIR__ . "/finish-registration/modal.phtml" ?>

    <script type="text/javascript">
        $(document).ready(function () {
            $('.multiselect').multiselect({
                numberDisplayed: 1
            });
        });
    </script>
