
<!-- Le styles -->
<?php $this->headLink()
        ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
        ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<!-- Scripts -->
<?php 

$this->headScript()
    ->prependFile($this->basePath() . '/js/admin/freelancer/freelancer.js')
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', []);")
	->prependFile ( $this->basePath () . '/js/plugins/summernote/summernote.min.js' )
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
	->prependFile ( $this->basePath () . '/js/plugins/bootbox/bootbox.min.js' )
    ->prependFile($this->basePath() . '/js/inspinia.js');
	
$this->inlineScript()
    ->prependScript("
        var LANG_CODE = '" . $this->lang_code . "';
		var EXITS_CONFIRM_TEXT = '" . $this->translate('This option was existed, please choose other') . "';
        ");	
		
?>
<!-- Add custom style -->
<style type="text/css">

    .label {
        font-size: 15px;
    }

    h3 {
        font-size: 18px;
    }

    .float-e-margins .btn {
        margin-bottom: 0px;
    }

    .resource-types .panel-body label{
        margin-right: 0.5em;
    }

    .multiselect-container{
        max-height: 250px;
        overflow-y: auto;
        overflow-x: hidden;
    }

</style>
<!-- End custom style -->

    <div class="row" id="FreelancerController" ng-init="init()" ng-controller="FreelancertController">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
				<div class="ibox-title">
					<h3>
						<i class="fa fa-user"></i> <?php echo $this->translate('Create Freelancer Account') ?>
					</h3>
				</div>
                <div class="ibox-content">
                    

                    <form id="form" action="#" class="wizard-big">
                        <?php include __DIR__ . "/new/basic-info.phtml" ?>
                        <?php include __DIR__ . "/new/resource-type.phtml" ?>
                        <?php include __DIR__ . "/new/language-skill-price.phtml" ?>
                    </form>
                </div>
            </div>
        </div>
    </div>
<?php include "new/modal.phtml" ?>
