<form method="" class="form-horizontal">
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                <label class="col-sm-3 control-label"> ID</label>
                <div class="col-sm-9"><input type="text" name="q" ng-model="filter.project_id" class="form-control"></div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Source</label>
                <div class="col-sm-9">
                    <select class="form-control" name="source" ng-model="filter.source"
                            ng-options="language.name for language in languages">
                        <option value=""></option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Order</label>
                <div class="col-sm-9">
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        <input data-field="datetime" type="text" class="form-control" name="startDate"
                               ng-model="filter.startDate">
                    </div>
                    <div class="dtbox"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label class="col-sm-3 control-label">Reference</label>
                <div class="col-sm-9"><input
                        type="text" class="form-control" name="reference" ng-model="filter.reference"></div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Target</label>
                <div class="col-sm-9">
                    <select class="form-control" name="source" ng-model="filter.target"
                            ng-options="language.name for language in languages">
                        <option value=""></option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Completed</label>
                <div class="col-sm-9">
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        <input type="text" data-field="datetime"
                               class="form-control" name="dueDate" ng-model="filter.dueDate">
                    </div>
                    <div class="dtbox"></div>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label class="col-sm-3 control-label">Field</label>
                <div class="col-sm-9">
                    <select class="form-control" name="field" ng-model="filter.field"
                            ng-options="field.name for field in ProjectField.all()">
                        <option value=""></option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="text-right tooltip-demo">
        <a href="#" class="btn btn-sm btn-primary" ng-click="search()"><i class="fa fa-search"></i> Search</a>
        <a href="#" class="btn btn-white btn-sm" type="reset" ng-click="search={}"><i class="fa fa-times"></i> Reset</a>
    </div>
</form>
<script>
    (function($){
        $(function(){
            $('.dtbox').DateTimePicker();
        });
    })(jQuery);
</script>