<style>
    .logo-name {
        font-size: 80px;
    }

    hr {
        border-top: 1px solid #2f4050;
    }
    .jumbotron h1, .jumbotron .h1 {
        font-size: 40px;
    }
</style>
<h3><?php echo $this->translate('Register to PaperTask','User'); ?></h3>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3">
            <div class="jumbotron">
            	<?php if($this->type == 'needConfirm') {            	
            	
            	?>
                <h1><?php echo $this->translate('Please login your email and confirm','User'); ?></h1>
                <p><?php echo $this->translate('We have sent an confirmation email to your email:','User'); ?>
                    <?php echo $this->email ?></p>
                <p><?php echo $this->translate(
                        'If you do not see the confirmation email in you INBOX, please check your JUNK mail.','User'); ?></p>
                 <?php } else { ?>
                 
                 <h1><?php echo $this->translate('Please contact your Administrator','User'); ?></h1>
               	 <p><?php echo $this->translate('Your account has been blocks','User'); ?> <br>
                    Email: <?php echo $this->email ?></p>
                 <p><?php echo $this->translate(
                        'If you have any problem, pls send email to suppor@papertask.com.','User'); ?></p>
                 
                 <?php } ?>
                
            </div>
        </div>

    </div>
</div>