<form method="" class="form-horizontal">
    <div class="row">
        <div class="col-lg-4">
            <div class="form-group">
                <label class="col-sm-3 control-label">Trans. ID</label>
                <div class="col-sm-9"><input type="text" name="q" ng-model="filter.trans_id" class="form-control"></div>
            </div>
            
            <div class="form-group">
                <label class="col-sm-3 control-label">Payer</label>
				<div class="col-sm-9"><input type="text" name="q" ng-model="filter.payer" class="form-control"></div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">FAPIAO No.</label>
                <div class="col-sm-9"><input type="text" name="q" ng-model="filter.fapiao_no" class="form-control"></div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label class="col-sm-3 control-label">Trans. Type</label>
                <div class="col-sm-9">
                    <select class="form-control" name="sale" ng-model="filter.typeStatus"
                            ng-options="status.name for status in PayStatus.all()">
                        <option value=""></option>
                    </select>
                </div>
            </div>
           
            <div class="form-group">
                <label class="col-sm-3 control-label">Payee</label>
                <div class="col-sm-9"><input type="text" name="client_id" ng-model="filter.payee" class="form-control"></div>
            </div>
			<div class="form-group">
                <label class="col-sm-3 control-label"> Client ID</label>
                <div class="col-sm-9"><input type="text" name="client_id" ng-model="filter.clientId" class="form-control"></div>
            </div>

            
        </div>
        <div class="col-lg-4">
            <div class="form-group">
                <label class="col-sm-3 control-label">Pay Date</label>
                <div class="col-sm-9">
                    <div class="input-group date">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        <input data-field="datetime" type="text" class="form-control" name="payDate"
                               ng-model="filter.payDate">
                    </div>
                    <div class="dtbox"></div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-3 control-label">Currency</label>
                <div class="col-sm-9">
                    <select class="form-control" name="status" ng-model="filter.currency"
                            ng-options="status.name for status in Currency.all()">
                        <option value=""></option>
                    </select>
                </div>
            </div>
           <div class="form-group">
                <label class="col-sm-3 control-label"> Company</label>
                <div class="col-sm-9"><input type="text" class="form-control" name="company" ng-model="filter.company"></div>
            </div>
        </div>
    </div>
    <div class="text-right tooltip-demo">
        <a href="#" class="btn btn-sm btn-primary" ng-click="advancedSearch()"><i class="fa fa-search"></i> Search</a>
        <a href="#" class="btn btn-white btn-sm" type="reset" ng-click="reset()"><i class="fa fa-times"></i> Reset</a>
    </div>
</form>
<script>
    (function($){
        $(function(){
            $('.dtbox').DateTimePicker();
        });
    })(jQuery);
</script>