<?php $this->headTitle($this->translate('Unpaid Project')) ?>
<!-- Scripts -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/footable/footable.core.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/datapicker/datepicker3.css');
?>

<?php
$this->headScript ()
	
	->prependFile ( $this->basePath () . '/v2/js/admin/finance/client-transaction.js' )
	->prependFile($this->basePath() . '/v2/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/CurrentUser.js')
    ->prependScript("angularApp = angular.module('project', ['ui.bootstrap']);")
    ->prependFile($this->basePath() . '/v2/js/plugins/angular-bootstrap/ui-bootstrap-0.11.2.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/datapicker/bootstrap-datepicker.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/footable/footable.all.min.js');

$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
    ");
?>

    <script>
        $(document).ready(function() {

            $('.footable').footable();

        });

    </script>


<div class="row animate fadeInUp">


                            <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="8">
                                <thead>
                                <tr>

                                    <th data-toggle="true">Project</th>
                                    <th>Name</th>
                                    <th>Phone</th>
                                    <th data-hide="all">Company</th>
                                    <th data-hide="all">Completed</th>
                                    <th data-hide="all">Task</th>
                                    <th data-hide="all">Date</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>Project - This is example of project</td>
                                    <td>Patrick Smith</td>
                                    <td>0800 051213</td>
                                    <td>Inceptos Hymenaeos Ltd</td>
                                    <td><span class="pie">0.52/1.561</span></td>
                                    <td>20%</td>
                                    <td>Jul 14, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Alpha project</td>
                                    <td>Alice Jackson</td>
                                    <td>0500 780909</td>
                                    <td>Nec Euismod In Company</td>
                                    <td><span class="pie">6,9</span></td>
                                    <td>40%</td>
                                    <td>Jul 16, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Betha project</td>
                                    <td>John Smith</td>
                                    <td>0800 1111</td>
                                    <td>Erat Volutpat</td>
                                    <td><span class="pie">3,1</span></td>
                                    <td>75%</td>
                                    <td>Jul 18, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Gamma project</td>
                                    <td>Anna Jordan</td>
                                    <td>(016977) 0648</td>
                                    <td>Tellus Ltd</td>
                                    <td><span class="pie">4,9</span></td>
                                    <td>18%</td>
                                    <td>Jul 22, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Alpha project</td>
                                    <td>Alice Jackson</td>
                                    <td>0500 780909</td>
                                    <td>Nec Euismod In Company</td>
                                    <td><span class="pie">6,9</span></td>
                                    <td>40%</td>
                                    <td>Jul 16, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Project
                                        <small>This is example of project</small>
                                    </td>
                                    <td>Patrick Smith</td>
                                    <td>0800 051213</td>
                                    <td>Inceptos Hymenaeos Ltd</td>
                                    <td><span class="pie">0.52/1.561</span></td>
                                    <td>20%</td>
                                    <td>Jul 14, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Gamma project</td>
                                    <td>Anna Jordan</td>
                                    <td>(016977) 0648</td>
                                    <td>Tellus Ltd</td>
                                    <td><span class="pie">4,9</span></td>
                                    <td>18%</td>
                                    <td>Jul 22, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Project
                                        <small>This is example of project</small>
                                    </td>
                                    <td>Patrick Smith</td>
                                    <td>0800 051213</td>
                                    <td>Inceptos Hymenaeos Ltd</td>
                                    <td><span class="pie">0.52/1.561</span></td>
                                    <td>20%</td>
                                    <td>Jul 14, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Alpha project</td>
                                    <td>Alice Jackson</td>
                                    <td>0500 780909</td>
                                    <td>Nec Euismod In Company</td>
                                    <td><span class="pie">6,9</span></td>
                                    <td>40%</td>
                                    <td>Jul 16, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Betha project</td>
                                    <td>John Smith</td>
                                    <td>0800 1111</td>
                                    <td>Erat Volutpat</td>
                                    <td><span class="pie">3,1</span></td>
                                    <td>75%</td>
                                    <td>Jul 18, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Gamma project</td>
                                    <td>Anna Jordan</td>
                                    <td>(016977) 0648</td>
                                    <td>Tellus Ltd</td>
                                    <td><span class="pie">4,9</span></td>
                                    <td>18%</td>
                                    <td>Jul 22, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Alpha project</td>
                                    <td>Alice Jackson</td>
                                    <td>0500 780909</td>
                                    <td>Nec Euismod In Company</td>
                                    <td><span class="pie">6,9</span></td>
                                    <td>40%</td>
                                    <td>Jul 16, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Project
                                        <small>This is example of project</small>
                                    </td>
                                    <td>Patrick Smith</td>
                                    <td>0800 051213</td>
                                    <td>Inceptos Hymenaeos Ltd</td>
                                    <td><span class="pie">0.52/1.561</span></td>
                                    <td>20%</td>
                                    <td>Jul 14, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                <tr>
                                    <td>Gamma project</td>
                                    <td>Anna Jordan</td>
                                    <td>(016977) 0648</td>
                                    <td>Tellus Ltd</td>
                                    <td><span class="pie">4,9</span></td>
                                    <td>18%</td>
                                    <td>Jul 22, 2013</td>
                                    <td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
                                </tr>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <td colspan="5">
                                        <ul class="pagination pull-right"></ul>
                                    </td>
                                </tr>
                                </tfoot>
                            </table>

    <div class="ibox" ng-controller="ClientUnpaidController" ng-init="init()">

        <div class="ibox-content m-b-sm ">
            <div class="row">
                <form method="" class="form-horizontal">
                    <div class="col-lg-12">
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="col-sm-4 control-label"><?php echo $this->translate('Transaction ID','Employer'); ?></label>
                                <div class="col-sm-8">
                                    <input type="text" name="q" ng-model="filter.trans_id" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group">
                                <label class="col-sm-4 control-label"><?php echo $this->translate('Pay Date','Employer'); ?></label>
                                <div class="col-sm-8">
                                    <div class="input-group date">
                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                        <input data-field="datetime" type="text" class="form-control" name="payDate"
                                               ng-model="filter.payDate">
                                    </div>
                                    <div class="dtbox"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <div class="form-group">
                                <label class="col-sm-4 control-label"><?php echo $this->translate('FAPIAO No.','Employer'); ?></label>
                                <div class="col-sm-8">
                                    <input type="text" name="q" ng-model="filter.fapiao_no" class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <a href="#" class="btn btn-sm btn-primary" ng-click="advancedSearch()"><i class="fa fa-search"></i> <?php echo $this->translate('Search','Employer'); ?></a>
                        </div>
                    </div>
                </form>
            </div>

        </div>        
        <div class="ibox-content">
            <div id="projectsList">
                <div class="project-list">

                    <table class="footable table table-hover toggle-arrow-tiny">
                        <thead>
                        <tr>
                            <th><?php echo $this->translate('Transaction ID','Employer'); ?></th>
                            <th><?php echo $this->translate('Pay Date','Employer'); ?></th>
                            <th class="text-right"><?php echo $this->translate('Amount','Employer'); ?></th>
                            <th width="20%" class="text-right"></th>
                        </tr>
                        </thead>                                
                        <tbody>
                            <tr ng-repeat="transaction in transactionlist">
                                <td class="project-status">
                                    <strong style="font-size: 16px;">{{transaction.intrans_no}}</strong>
                                </td>
                                <td class="project-title">
                                    <strong style="font-size: 16px;">{{DateFormatter.short(transaction.payDate)}}</strong>
                                </td>
                                <td class="project-title text-right">
                                    <span class="text-navy" style="font-size: 15px;"><strong>{{transaction.currency}} {{transaction.total}}</strong></span>
                                </td>
                                <td class="project-actions text-right">
                                    <a href="#" class="btn btn-white btn-sm" ng-click="gotodetail(transaction)"><i class="fa fa-folder"> <?php echo $this->translate('View','Employer'); ?> </i> 
                                    </a>
                                </td>
                            </tr>
                            </tr>
                        </tbody>
                    </table>

                    <div class="btn-group text-right">
                        <pagination total-items="pages.totalItemCount" ng-model="page" max-size="maxSize"
                                    class="pagination-sm" boundary-links="true" ng-change="pageChanged()"></pagination>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<div class="row" ng-controller="ClientUnpaidController" ng-init="init()">
	<div class="col-lg-12">
		<div class="wrapper wrapper-content animated fadeInUp">

			<div class="ibox">
				<div class="ibox-title">
					<h5>Financial Reports</h5>
				</div>

				<div class="ibox-content">

					<div class="row m-b-sm m-t-sm">
                                <div class="col-md-10">
                                    <div class="input-group">
                                    	<input type="text" placeholder="Search" class="input-sm form-control" ng-model="filter.key">
                                    	<span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary" ng-click="search()"> Search</button>
                                      </span>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                	<a data-toggle="collapse" href="#adv_search" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Advance Search</a>
                                </div>
                    </div>

					<div class="row">
						<div id="adv_search" class="panel-collapse collapse faq-answer">
							<?php include "transaction/search.phtml" ?>
						</div>
					</div>
					<div class="hr-line-dashed"></div>
					 <div class="table-responsive">
						<table class="table">
							<tbody>

									<tr ng-repeat="transaction in transactionlist">
										<td class="project-status">
                                            <span class="label label-primary"><i class="fa fa-sign-out"></i>Outgoing</span>
                                        </td>
										<td class="project-title">
                                                <strong class="">Transaction No. {{transaction.intrans_no}}</strong>
                                                <br/>
                                                <small>Pay Date: {{DateFormatter.short(transaction.payDate)}}</small>
                                        </td>
<!--
										<td class="project-title" ng-if="transaction.typeStatus == 1">
	                                            <strong>{{transaction.client.name}}</strong>
	                                            <br/>
	                                             {{transaction.client.company.name}}
	                                    </td>
-->
										<td class="project-title" ng-if="transaction.typeStatus == 2">
                                                <strong>{{transaction.freelancer.firstName}} {{transaction.freelancer.lastName}}</strong>

                                        </td>
										<td class="project-status">
                                                <strong class="text-success">{{transaction.currency}} {{transaction.total}}</strong>
                                                <br>
                                                <small>Record Date: {{DateFormatter.short(transaction.createDate)}}</small>
                                        </td>
										<td class="project-actions">
                                                <a href="#" class="btn btn-white btn-sm" ng-click="gotodetail(transaction)"><i class="fa fa-folder"></i> View </a>
                                        </td>
									</tr>

							</tbody>
						</table>
					 </div>
					<div class="btn-group text-right">
						<button type="button" class="btn btn-white" ng-class="pages.previous?'':'disabled'" ng-click="onBtnPreviousClicked()"><i class="fa fa-chevron-left"></i></button>
						<button ng-repeat="page in pages.pagesInRange" class="btn btn-white" ng-class="page==pages.current?'active':''" ng-click="onBtnGoto(page-1)">{{page}}</button>
						<button type="button" class="btn btn-white"	ng-class="pages.next?'':'disabled'" ng-click="onBtnNextClicked()"><i class="fa fa-chevron-right"></i></button>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
 <script>
    $(document).ready(function(){
        $('.dtbox').DateTimePicker();

        // trigger datetime picker when click to calendar icon
        // TODO: this is not working
        $('i.fa.fa-calendar').on('click', function(e){
            console.log('clicked');
            e.preventDefault();

            $(this).parents('.input-group').find('input[readonly]').click();
        });
    });
</script>
