<?php $this->headTitle($this->translate('Unpaid Tasks','Admin')) ?>
<!-- Scripts -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/datapicker/datepicker3.css')
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/footable/footable.core.css')
?>

<?php
$this->headScript ()
	->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
	->prependFile($this->basePath() . '/v2/js/admin/finance/freelancer-unpaid-task.js')
    ->prependScript("angularApp = angular.module('project', []);")
    ->prependScript("FREELANCER_ID = {$this->freelancer_id};")
    ->prependFile($this->basePath() . '/v2/js/plugins/datapicker/bootstrap-datepicker.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/footable/footable.all.min.js');

$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
    ");
?>
					
<div class="row" ng-controller="FreelancerUnpaidTask" ng-init="init()">
	<div class="col-lg-12">
		<div class="wrapper wrapper-content animated fadeInUp">
			<div class="ibox">
				<div class="ibox-title">
					<h5><?php echo $this->translate('Unpaid Tasks','Admin') ?></h5>
				</div>

				<div class="ibox-content">
				
					<div class="row m-b-sm m-t-sm">
                        <div class="col-md-10">
                            <div class="input-group">
                            	<input type="text" placeholder="<?php echo $this->translate('Search','Admin') ?>" class="input-sm form-control" ng-model="filter.bsearch">
                            	<span class="input-group-btn">
                                <button type="button" class="btn btn-sm btn-primary" ng-click='search()'> <?php echo $this->translate('Search','Admin') ?></button> 
                              </span>
                            </div>
                        </div>
                        <div class="col-md-2">
                        	<a data-toggle="collapse" href="#adv_search" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> <?php echo $this->translate('Advance Search','Admin') ?></a>
                        </div>
                    </div>
							
					<div class="row">
						<div class="col-lg-12">
							<div id="adv_search" class="panel-collapse collapse faq-answer">
                                <form method="" class="form-horizontal">
                                    <div class="row">
                                        <div class="col-lg-4">
                                            <div class="form-group">
                                                <label class="col-sm-3 control-label"> <?php echo $this->translate('Task ID','Admin') ?></label>
                                                <div class="col-sm-9"><input type="text" class="form-control" ng-model="filter.taskId"></div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group">
                                                <label class="col-sm-3 control-label"><?php echo $this->translate('Reference','Admin') ?></label>
                                                <div class="col-sm-9"><input type="text" class="form-control" ng-model="filter.reference"></div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="form-group" id="data_4">
                                                <label class="col-sm-3 control-label"><?php echo $this->translate('Month','Admin') ?></label>
                                                <div class="col-sm-9">
                                                    <div class="input-group date">
                                                        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                                                        <input type="text" class="form-control" value="" ng-model="filter.dueMonth">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="text-right tooltip-demo">
                                        <a class="btn btn-sm btn-primary" ng-click="advancedSearch()"><i class="fa fa-search"></i> <?php echo $this->translate('Search','Admin') ?></a>
                                        <a class="btn btn-white btn-sm" type="reset"  ng-click="reset()"><i class="fa fa-times"></i> <?php echo $this->translate('Reset','Admin') ?></a>
                                    </div>
                                </form>
                            </div>
						</div>
					</div>
					<div class="hr-line-dashed"></div>
					 <div class="table-responsive">
                        <table class="footable table table-hover">
                            <thead>
                            <tr>
                                <th><?php echo $this->translate('Task ID','Admin') ?></th>
                                <th><?php echo $this->translate('Task Reference','Admin') ?></th>
                                <th><?php echo $this->translate('Status','Admin') ?></th>
                                <th><?php echo $this->translate('Completed Date','Admin') ?></th>
                                <th><?php echo $this->translate('Amount','Admin') ?></th>
                            </tr>
                            </thead>
                            <tbody>
                                <tr ng-repeat="task in tasks">
                                    <td>{{ task.task_number }}</td>
                                    <td>{{ task.project.reference }}</td>
                                    <td>{{task.status.name }}</td>
                                    <td>{{formatDate(task.dueDate.date) | date:'yyyy.MMM.dd'}}</td>
                                    <td>{{task.currency | uppercase}} {{task.total_freelancer}}</td>
                                </tr>
                            
                            </tbody>
                        </table>
                    </div>
					<div class="btn-group text-right">
						<button type="button" class="btn btn-white" ng-class="pages.previous?'':'disabled'" ng-click="onBtnPreviousClicked()"><i class="fa fa-chevron-left"></i></button>
						<button ng-repeat="page in pages.pagesInRange" class="btn btn-white" ng-class="page==pages.current?'active':''" ng-click="onBtnGoto(page-1)">{{page}}</button>
						<button type="button" class="btn btn-white"	ng-class="pages.next?'':'disabled'" ng-click="onBtnNextClicked()"><i class="fa fa-chevron-right"></i></button>						

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
 <script>


 function simpleLoad(btn, state) {
     if (state) {
         btn.children().addClass('fa-spin');
         btn.contents().last().replaceWith(" Loading");
     } else {
         setTimeout(function () {
             btn.children().removeClass('fa-spin');
             btn.contents().last().replaceWith(" Refresh");
         }, 2000);
     }
 }
 $(document).ready(function(){
    $('.footable').footable();

     $('#data_1 .input-group.date').datepicker({
         todayBtn: "linked",
         keyboardNavigation: false,
         forceParse: false,
         calendarWeeks: true,
         autoclose: true
     });

     $('#data_2 .input-group.date').datepicker({
         startView: 1,
         todayBtn: "linked",
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true
     });

     $('#data_3 .input-group.date').datepicker({
         startView: 2,
         todayBtn: "linked",
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true
     });

     $('#data_4 .input-group.date').datepicker({
         minViewMode: 1,
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true,
         todayHighlight: true
     });

     $('#data_5 .input-daterange').datepicker({
         keyboardNavigation: false,
         forceParse: false,
         autoclose: true
     });

     $('#loading-example-btn').click(function () {
         btn = $(this);
         simpleLoad(btn, true)

         // Ajax example
//         $.ajax().always(function () {
//             simpleLoad($(this), false)
//         });

         simpleLoad(btn, false)
     });
 });
</script>
