<?php $this->headTitle($this->translate('Unpaid Project')) ?>
<!-- Scripts -->
<?php $this->headLink()
    ->prependStylesheet($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.css')
	 ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<?php
$this->headScript ()
	->prependFile($this->basePath() . '/js/plugins/datetimepicker/DateTimePicker.js')
	->prependFile ( $this->basePath () . '/js/admin/finance/freelancer-unpaid.js' )
	->prependFile($this->basePath() . '/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload', 'ui.bootstrap']);")
    ->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-tpls-0.11.2.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-0.11.2.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js');

$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
    ");
?>
					
<div class="row" ng-controller="FreelancerUnpaidController" ng-init="init()">
	<div class="col-lg-12">
		<div class="wrapper wrapper-content animated fadeInUp">
			<div class="ibox">
				<div class="ibox-title">
					<h5>Freelancers Unpaid Projects</h5>
				</div>

				<div class="ibox-content">
				
					<div class="row m-b-sm m-t-sm">
                                <div class="col-md-10">
                                    <div class="input-group">
                                    	<input type="text" placeholder="Search" class="input-sm form-control" ng-model="filter.email"> 
                                    	<span class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary" ng-click='search()'> Search</button> 
                                      </span>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                	<a data-toggle="collapse" href="#adv_search" class="btn btn-sm btn-primary"><i class="fa fa-search"></i> Advance Search</a>
                                </div>
                    </div>
							
					<div class="row">
						<div id="adv_search" class="panel-collapse collapse faq-answer">
							<?php include "freelancer-unpaid/search.phtml" ?>
						</div>
					</div>
					<div class="hr-line-dashed"></div>
					 <div class="table-responsive">
						<table class="table">
							<thead>
                                <tr>
                                    <th>Freelancer</th>
                                    <th>Task ID</th>
                                    <th>Task Reference</th>
                                    <th>Status</th>
                                    <th>Completed Date</th>
                                    <th>Amount</th>
                                </tr>
                            </thead>
							<tbody  ng-repeat="tu_array in tus">
								
									<tr ng-repeat="tu in tu_array.task"> 
										<td>
											<div class="tooltip-demo">
												<span data-toggle="tooltip" data-placement="top" title="" data-original-title="here put company name" ng-if="$index == 0">
												<a href="" ng-click="gotodetail(tu_array.freelancer.id)">{{tu_array.freelancer.email}}</a></span>
											</div>
										</td>
										<td>{{tu.task_number}}</td>
										<td>{{tu.reference}}</td>
										<td>{{ ProjectStatus.get(tu.status).name }}</td>
										<td>{{ DateFormatter.short(tu.dueDate) }}</td>
										<td>{{tu_array.freelancer.currency}} {{pu.total}}</td>
									</tr>
								
							</tbody>
						</table>
					 </div>
					<div class="btn-group text-right">
						<button type="button" class="btn btn-white" ng-class="pages.previous?'':'disabled'" ng-click="onBtnPreviousClicked()"><i class="fa fa-chevron-left"></i></button>
						<button ng-repeat="page in pages.pagesInRange" class="btn btn-white" ng-class="page==pages.current?'active':''" ng-click="onBtnGoto(page-1)">{{page}}</button>
						<button type="button" class="btn btn-white"	ng-class="pages.next?'':'disabled'" ng-click="onBtnNextClicked()"><i class="fa fa-chevron-right"></i></button>						

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
 <script>
    $(document).ready(function(){
        $('.dtbox').DateTimePicker();

        // trigger datetime picker when click to calendar icon
        // TODO: this is not working
        $('i.fa.fa-calendar').on('click', function(e){
            console.log('clicked');
            e.preventDefault();

            $(this).parents('.input-group').find('input[readonly]').click();
        });
    });
</script>
