<?php echo  $this->headTitle($this->translate('Transaction Details')) ?>
<!-- Scripts -->
<?php echo  $this->headLink()
    ->prependStylesheet($this->basePath() . '/v2/css/plugins/footable/footable.core.css');
?>

<?php
echo $this->headScript ()
	->prependFile($this->basePath() . '/v2/js/admin/finance/incomming-detail.js')
	->prependFile($this->basePath() . '/v2/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/v2/js/admin/common/angular/CurrentUser.js')
    ->prependScript("angularApp = angular.module('project', ['ui.bootstrap']);")
    ->prependFile($this->basePath() . '/v2/js/plugins/angular-bootstrap/ui-bootstrap-tpls-0.11.2.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/angular-bootstrap/ui-bootstrap-0.11.2.min.js')
    ->prependFile($this->basePath() . '/v2/js/plugins/validate/jquery.validate.min.js');

$this->inlineScript()
    ->prependScript("
        var LANG_CODE = '" . $this->lang_code . "';
    ");
?>

<div class="row animated fadeInUp" ng-controller="IncommingDetailController" id = "IncommingDetailController" ng-init="init()">
	<div class="col-lg-12">

		<div class="ibox">
			<div class="ibox-title">
				<h5><?php echo $this->translate('Transaction','Employer'); ?></h5>
			</div>
			<form id="form">
			<div class="ibox-content">

						<div class="row">

							<div class="col-sm-6">
                                <h4><?php echo $this->translate('Transaction ID','Employer'); ?></h4>
                                <h3 class="text-navy">{{transaction.intrans_no}}</h3>
                            </div>

							<div class="col-sm-6 text-right">
                                <p>
                                    <span><strong><?php echo $this->translate('FAPIAO No.','Employer'); ?>: </strong> {{transaction.fapiao_no}}</span><br/>
                                    <span><strong><?php echo $this->translate('Pay Date','Employer'); ?>: </strong>{{DateFormatter.format(transaction.payDate)}}</span><br/>
                                    <span><strong><?php echo $this->translate('Record Add Date','Employer'); ?>: </strong> {{DateFormatter.format(transaction.createDate)}}</span>
                                </p>
                                <h5><?php echo $this->translate('Bank Information','Employer'); ?>:</span></h5>
                                <strong>{{bankinfos[0].name}}</strong><br>
                                <address>
                                    <strong>{{companyinfo1.name}}</strong><br>
                                    {{companyinfo1.address}}<br>
                                    {{companyinfo1.city}}, {{companyinfo1.country.name}}<br>
                                </address>

                            </div>


                        </div>

						<div class="hr-line-dashed"></div>


				 <div class="table-responsive m-t">
					<table class="table table-bordered invoice-table">
						<thead>
                            <tr>
                               <th width="10%"><?php echo $this->translate('Project ID','Employer'); ?></th>
                               <th><?php echo $this->translate('Project Reference','Employer'); ?></th>
                                <th><?php echo $this->translate('Completed Date','Employer'); ?></th>
                                <th><?php echo $this->translate('Price','Employer'); ?></th>
                            </tr>
                        </thead>
						<tbody>
								<tr ng-repeat="project in projects">
									<td><span class="text-navy">{{ project.project_no }}</span></strong></td>
                <td>{{ project.reference }}</td>
                <td>{{ DateFormatter.short(project.dueDate) }}</td>
									<td>{{project.currency}} {{project.total_tmp}}</td>
								</tr>

						</tbody>
					</table>
				 </div>

						<table class="table invoice-total">
                            <tbody>
                            <tr>
                                <td><strong><?php echo $this->translate('Sub Total','Employer'); ?>:</strong></td>
                                <td>{{transaction.currency}} {{subtotal_show}}</td>
                            </tr>
                            <tr>
                                <td><strong>(-) <?php echo $this->translate('Transaction Fee','Employer'); ?>:</strong></td>
                                <td>{{transaction.currency}} {{fee_show}}</td>
                            </tr>
                            <tr>
                                <td><strong><?php echo $this->translate('TOTAL','Employer'); ?>: </strong></td>
                                <td>{{transaction.currency}} {{total_show}}</td>
                            </tr>
                            </tbody>
                        </table>


			</div>
			</form>
		</div>

	</div>
</div>

