<?php $this->headTitle($this->translate('Financial Reports')) ?>
<!-- Scripts -->
<?php $this->headLink()
    
    ->prependStylesheet($this->basePath() . '/js/plugins/datapicker/datepicker3.css')
	 ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote-bs3.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/summernote/summernote.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/multiselect/bootstrap-multiselect.css')
    ->prependStylesheet($this->basePath() . '/css/plugins/steps/jquery.steps.css')
?>

<?php
$this->headScript ()
	
	->prependFile($this->basePath() . '/js/plugins/datapicker/bootstrap-datepicker.js')
	->prependFile ( $this->basePath () . '/js/admin/finance/report.js' )
	->prependFile($this->basePath() . '/js/admin/common/angular/ItemListController.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/service/project.js')
    ->prependFile($this->basePath() . '/js/admin/common/angular/CurrentUser.js')
    ->prependFile($this->basePath() . '/js/admin/angular-steps.js')
    ->prependFile($this->basePath() . '/js/admin/bootstrap-modal.js')
    ->prependScript("angularApp = angular.module('project', ['summernote', 'angularFileUpload', 'ui.bootstrap']);")
    ->prependFile($this->basePath() . '/js/plugins/bootstrap-filestyle/bootstrap-filestyle.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-tpls-0.11.2.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-bootstrap/ui-bootstrap-0.11.2.min.js')
    ->prependFile($this->basePath() . '/js/plugins/angular-summernote/angular-summernote.js')
    ->prependFile($this->basePath() . '/js/plugins/summernote/summernote.min.js')
    ->prependFile($this->basePath() . '/js/plugins/multiselect/bootstrap-multiselect.js')
    ->prependFile($this->basePath() . '/js/plugins/validate/jquery.validate.min.js')
    ->prependFile($this->basePath() . '/js/plugins/steps/jquery.steps.min.js')
    ->prependFile($this->basePath() . '/js/plugins/bootbox/bootbox.min.js')
    ->prependFile($this->basePath() . '/js/plugins/pace/pace.min.js')
    ->prependFile($this->basePath() . '/js/inspinia.js');

$this->inlineScript()
    ->prependScript("
		var LANG_CODE = '" . $this->lang_code . "';
        var DELETE_CONFIRM_TEXT = '" . $this->translate('Are you sure to delete?') . "';
    ");
?>
<div class="row" ng-controller="ReportController" ng-init="init()">
	<div class="col-lg-12">
		<div class="wrapper wrapper-content animated fadeInUp">

			<div class="row">
				<div class="col-lg-4">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<h5>In Currency</h5>
						</div>
						<div class="ibox-content">
							<div data-toggle="buttons">
                                            <label class="btn btn-outline btn-lg btn-primary" ng-class="{ 'active' : currency == 'USD' }" ng-click="changeCurrency('USD')">
                                                <input type="radio" name="usd" value=""  /> <i class="fa fa-usd"></i> USD</i>
                                            </label>
                                            &nbsp;
                                            <label class="btn btn-outline btn-lg btn-primary" ng-class="{ 'active' : currency == 'CNY' }"  ng-click="changeCurrency('CNY')">
                                                <input type="radio" name="cny" value="" /> <i class="fa fa-cny"></i> CNY</i>
                                            </label>
                                        </div>

						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<h5>Unpaid Total</h5>
						</div>
						<div class="ibox-content">
							<h1 class="no-margins">{{currency}} {{balance_pu}}</h1>
                                    <div class="stat-percent font-bold text-danger"><i class="fa fa-tasks"></i> {{count_pu.num_pu}} Projects</div>
							<small>Total Unpaid Projects</small>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<h5>Paid Total</h5>
						</div>
						<div class="ibox-content">
							<h1 class="no-margins">{{currency}} {{balance_pp}}</h1>
                                    <div class="stat-percent font-bold text-navy"><i class="fa fa-tasks"></i> {{count_pp.num_pp}} Projects</div>
							<small>Total Paid Projects</small>
						</div>
					</div>
				</div>
			</div>

			<div class="ibox">
				<div class="ibox-title">
					<h5>Financial Reports</h5>
				</div>
				<div class="ibox-content">
					<div class="row m-b-sm m-t-sm">
						<div class="col-md-10">
							<div class="input-group">
								<input type="text" placeholder="Search"
									class="input-sm form-control" ng-model="filter.search"> <span class="input-group-btn" >
									<button type="button" class="btn btn-sm btn-primary" ng-click="search()">Search</button>
								</span>
							</div>
						</div>
						<div class="col-md-2">
							<a data-toggle="collapse" href="#adv_search"
								class="btn btn-sm btn-primary"><i class="fa fa-search"></i>
								Advance Search</a>
						</div>
					</div>

					<div class="row">
						<div class="col-lg-12">
							<div id="adv_search" class="panel-collapse collapse faq-answer">
								<form method="" class="form-horizontal">
									<div class="row">
										<div class="col-lg-4">
											<div class="form-group">
												<label class="col-sm-3 control-label"> ID</label>
												<div class="col-sm-9">
													<input type="text" class="form-control" ng-model="filter.project_id">
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-3 control-label">Source</label>
												<div class="col-sm-9">
													<select class="form-control" name="" ng-options="language.name for language in languages" ng-model="filter.source">
														<option></option>
													</select>
												</div>
											</div>
											<div class="form-group" id="data_1">
												<label class="col-sm-3 control-label">Order</label>
												<div class="col-sm-9">
													<div class="input-group date">
														<span class="input-group-addon"><i class="fa fa-calendar"></i>
														</span> <input type="text" class="form-control" value="" ng-model="filter.startDate">
													</div>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-3 control-label"> Client ID</label>
												<div class="col-sm-9">
													<input type="text" class="form-control" ng-model="filter.clientId">
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-3 control-label">PM</label>
												<div class="col-sm-9">
													<select class="form-control" name="" ng-options="pm.name for pm in pms" ng-model="filter.pm">
														<option></option>

													</select>
												</div>
											</div>
											<div class="form-group" id="data_1">
												<label class="col-sm-3 control-label">Report Start</label>
												<div class="col-sm-9">
													<div class="input-group date">
														<span class="input-group-addon"><i class="fa fa-calendar"></i>
														</span> <input type="text" class="form-control" value="" ng-model="filter.reportStart">
													</div>
												</div>
											</div>
										</div>
										<div class="col-lg-4">
											<div class="form-group">
												<label class="col-sm-3 control-label">Reference</label>
												<div class="col-sm-9">
													<input type="text" class="form-control" ng-model="filter.reference">
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-3 control-label">Target</label>
												<div class="col-sm-9">
													<select class="form-control" name="" ng-options="language.name for language in languages" ng-model="filter.target">
														<option></option>
													</select>
												</div>
											</div>
											<div class="form-group" id="data_1">
												<label class="col-sm-3 control-label">Completed</label>
												
												<div class="col-sm-9">
													<div class="input-group date">
														<span class="input-group-addon"><i class="fa fa-calendar"></i>
														</span> 
														<input type="text" class="form-control" value="" ng-model="filter.dueDate">
													</div>
												</div>
												 
											</div>
											<div class="form-group">
												<label class="col-sm-3 control-label"> Company</label>
												<div class="col-sm-9">
													<input type="text" class="form-control" ng-model="filter.company">
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-3 control-label">Sales</label>
												<div class="col-sm-9">
													<select class="form-control" name="" ng-options="sale.name for sale in sales" ng-model="filter.sale">
														<option></option>
												
													</select>
												</div>
											</div>
											<div class="form-group" id="data_1">
												<label class="col-sm-3 control-label">Report End</label>
												<div class="col-sm-9">
													<div class="input-group date">
														<span class="input-group-addon"><i class="fa fa-calendar"></i>
														</span> <input type="text" class="form-control" value="" ng-model="filter.reportEnd">
													</div>
												</div>
											</div>
										</div>
										<div class="col-lg-4">
											<div class="form-group">
												<label class="col-sm-3 control-label">Field</label>
												<div class="col-sm-9">
													<select class="form-control" name="" ng-options="field.name for field in Fields" ng-model="filter.field">
														<option></option>
														
													</select>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-3 control-label">Status</label>
												<div class="col-sm-9">
													<select class="form-control" name="" ng-options="status.name for status in ProjectStatus" ng-model="filter.status">
														<option></option>

													</select>
												</div>
											</div>
											<div class="form-group">
												<label class="col-sm-3 control-label">Pay Status</label>
												<div class="col-sm-9">
													<select class="form-control" name="" ng-options="payStatus.name for payStatus in PayStatus" ng-model="filter.payStatus">
														<option></option>
											
													</select>
												</div>
											</div>
											<div class="form-group" id="data_1">
												<label class="col-sm-3 control-label">Invoice Date</label>
												<div class="col-sm-9">
													<div class="input-group date">
														<span class="input-group-addon"><i class="fa fa-calendar"></i>
														</span> <input type="text" class="form-control" value="" ng-model="filter.invoiceDate">
													</div>
												</div>
											</div>

											<div class="form-group" id="data_4">
												<label class="col-sm-3 control-labe">Month select</label>
												<div class="col-sm-9">
													<div class="input-group date">
														<span class="input-group-addon"><i class="fa fa-calendar"></i>
														</span><input type="text" class="form-control"
															value="" ng-model="filter.monthSelect">
													</div>
												</div>
											</div>
										</div>
									</div>
									<div class="text-right tooltip-demo">
										<a href="#" class="btn btn-sm btn-primary" ng-click="advancedSearch()"><i
											class="fa fa-search"></i> Search</a> <a href="#"
											class="btn btn-white btn-sm" type="reset" ng-click="reset()"><i
											class="fa fa-times"></i> Reset</a>
									</div>
								</form>
							</div>
						</div>
					</div>
					<div class="hr-line-dashed"></div>

					<div class="project-list">

						<table class="table table-hover">
							<tbody>
								<tr ng-repeat="project in projects">
									<td class="project-status"><span class="label label-{{project.status.decorator}}">{{project.status.name}}</span>
										<i class="fa fa-usd" ng-if="project.payStatus == 2"></i><!--with dollor sign means paid -->
									</td>
									<td class="project-title"><strong><a href=""> Contract with
												{{project.client.company.name}} Company</a>
									</strong> <br />
										<div class="tooltip-demo">
											<code ng-repeat="type in project.types" data-toggle="tooltip" data-placement="top" title=""
												data-original-title="{{type.tootip}}">{{type.name_short}}</code>
												
										</div></td>
									<td class="project-title"><span class="">{{project.reference}}</span> <br />
										<small>{{formatDate(project.startDate.date) | date:'yyyy.MMM.dd'}} - {{formatDate(project.dueDate.date) | date:'yyyy.MMM.dd'}}</small></td>
									<td class="project-title">{{project.client.name}} <br /> {{project.client.company.name}}
									</td>
									<td class="project-title">
										<div class="tooltip-demo">
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Sales Manager">
												<i class="fa fa-user"></i>{{project.sale.name}}
											</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Project Manager">
												<i class="fa fa-user"></i>{{project.pm.name}}
											</code>
											<br> &nbsp;Pay:
										</div>
									</td>
									<td class="project-status"><strong class="text-danger" ng-if="project.payStatus != 2">{{project.currency | uppercase}}
											{{project.total_tmp}}</strong>
										 <strong class="text-navy" ng-if="project.payStatus == 2">{{project.currency | uppercase}} {{project.total_tmp}}</strong> 	
									</td>
								</tr>
								
								
								
								
								<!-- 
								<tr>
									<td class="project-status"><span class="label label-primary">Ongoing</span>
										<i class="fa fa-usd"></i></td>
									<td class="project-title"><strong>Contract with Zender Company</strong>
										<br />
										<div class="tooltip-demo">
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Translation with Translation Memory">TM</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Translation without Translation Memory">No-TM</code>
											<code>Proofreading</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Desktop Publishing">DTP</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Engineering">ENG</code>
										</div></td>
									<td class="project-title"><span class="">88888888</span> <br />
										<small>2014.Sep.09 - 2014.Oct.18</small></td>
									<td class="project-title">Client's name <br /> Client's Company
									</td>
									<td class="project-title">
										<div class="tooltip-demo">
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Sales Manager">
												<i class="fa fa-user"></i> kjiang
											</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Project Manager">
												<i class="fa fa-user"></i> myang
											</code>
											<br> &nbsp;Pay: 2014.Aug.28
										</div>
									</td>
									<td class="project-status"><strong class="text-navy">CNY 878.88</strong>
									</td>
								</tr>
								<tr>
									<td class="project-status"><span class="label label-success">Reviewing</span>
									</td>
									<td class="project-title"><strong>Contract with Zender Company</strong>
										<br />
										<div class="tooltip-demo">
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Translation with Translation Memory">TM</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Translation without Translation Memory">No-TM</code>
											<code>Proofreading</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Desktop Publishing">DTP</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Engineering">ENG</code>
										</div></td>
									<td class="project-title"><span class="">88888888</span> <br />
										<small>2014.Sep.09 - 2014.Oct.18</small></td>
									<td class="project-title">Client's name <br /> Client's Company
									</td>
									<td class="project-title">
										<div class="tooltip-demo">
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Sales Manager">
												<i class="fa fa-user"></i> kjiang
											</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Project Manager">
												<i class="fa fa-user"></i> myang
											</code>
											<br> &nbsp;Pay:
										</div>
									</td>
									<td class="project-status"><strong class="text-danger">CNY
											878.88</strong></td>
								</tr>
								<tr>
									<td class="project-status"><span class="label label-default">Completed</span>
										<i class="fa fa-usd"></i> --><!--with dollor sign means paid -->
										<!-- 
									</td>
									<td class="project-title"><strong>Contract with Zender Company</strong>
										<br />
										<div class="tooltip-demo">
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Translation with Translation Memory">TM</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Translation without Translation Memory">No-TM</code>
											<code>Proofreading</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Desktop Publishing">DTP</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Engineering">ENG</code>
										</div></td>
									<td class="project-title"><span class="">88888888</span> <br />
										<small>2014.Sep.09 - 2014.Oct.18</small></td>
									<td class="project-title">Client's name <br /> Client's Company
									</td>
									<td class="project-title">
										<div class="tooltip-demo">
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Sales Manager">
												<i class="fa fa-user"></i> kjiang
											</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Project Manager">
												<i class="fa fa-user"></i> myang
											</code>
											<br> &nbsp;Pay: 2014.Aug.28
										</div>
									</td>
									<td class="project-status"><strong class="text-navy">CNY 878.88</strong>
									</td>
								</tr>
								<tr>
									<td class="project-status"><span class="label label-white">Rejected</span>
									</td>
									<td class="project-title"><strong>Contract with Zender Company</strong>
										<br />
										<div class="tooltip-demo">
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Translation with Translation Memory">TM</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Translation without Translation Memory">No-TM</code>
											<code>Proofreading</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Desktop Publishing">DTP</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Engineering">ENG</code>
										</div></td>
									<td class="project-title"><span class="">88888888</span> <br />
										<small>2014.Sep.09 - 2014.Oct.18</small></td>
									<td class="project-title">Client's name <br /> Client's Company
									</td>
									<td class="project-title">
										<div class="tooltip-demo">
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Sales Manager">
												<i class="fa fa-user"></i> kjiang
											</code>
											<code data-toggle="tooltip" data-placement="top" title=""
												data-original-title="Project Manager">
												<i class="fa fa-user"></i> myang
											</code>
											<br> &nbsp;Pay:
										</div>
									</td>
									<td class="project-status"><strong class="text-danger">CNY
											878.88</strong></td>
								</tr>
								 -->
							</tbody>
						</table>
					</div>
					<div class="btn-group text-right">
						<button type="button" class="btn btn-white" ng-class="pages.previous?'':'disabled'" ng-click="onBtnPreviousClicked()"><i class="fa fa-chevron-left"></i></button>
						<button ng-repeat="page in pages.pagesInRange" class="btn btn-white" ng-class="page==pages.current?'active':''" ng-click="onBtnGoto(page-1)">{{page}}</button>
						<button type="button" class="btn btn-white"	ng-class="pages.next?'':'disabled'" ng-click="onBtnNextClicked()"><i class="fa fa-chevron-right"></i></button>						

					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-3">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<span class="label label-primary pull-right">88 Projects</span>
							<h5>Total</h5>
						</div>
						<div class="ibox-content">
							<h1 class="no-margins">CNY 886,200.87</h1>
						</div>
					</div>
				</div>
				<div class="col-lg-3">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<h5>Cost</h5>
						</div>
						<div class="ibox-content">
							<h1 class="no-margins">CNY 275,800.78</h1>
						</div>
					</div>
				</div>
				<div class="col-lg-3">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<h5>Margin</h5>
						</div>
						<div class="ibox-content">
							<h1 class="no-margins">CNY 106,120.68</h1>
						</div>
					</div>
				</div>
				<div class="col-lg-3">
					<div class="ibox float-e-margins">
						<div class="ibox-title">
							<h5>Margin (%)</h5>
						</div>
						<div class="ibox-content">
							<h1 class="no-margins">26%</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
		
<script>
$(document).ready(function(){

    $('#data_1 .input-group.date').datepicker({
        todayBtn: "linked",
        keyboardNavigation: false,
        forceParse: false,
        calendarWeeks: true,
        autoclose: true
    });

    $('#data_2 .input-group.date').datepicker({
        startView: 1,
        todayBtn: "linked",
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true
    });

    $('#data_3 .input-group.date').datepicker({
        startView: 2,
        todayBtn: "linked",
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true
    });

    $('#data_4 .input-group.date').datepicker({
        minViewMode: 1,
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true,
        todayHighlight: true
    });

    $('#data_5 .input-daterange').datepicker({
        keyboardNavigation: false,
        forceParse: false,
        autoclose: true
    });

    $('#loading-example-btn').click(function () {
        btn = $(this);
        simpleLoad(btn, true)

        // Ajax example
//        $.ajax().always(function () {
//            simpleLoad($(this), false)
//        });

        simpleLoad(btn, false)
    });

   
});

function simpleLoad(btn, state) {
    if (state) {
        btn.children().addClass('fa-spin');
        btn.contents().last().replaceWith(" Loading");
    } else {
        setTimeout(function () {
            btn.children().removeClass('fa-spin');
            btn.contents().last().replaceWith(" Refresh");
        }, 2000);
    }
}
</script>