<div class="col-lg-4 well">
              <h1 class="text-center"><?php echo $this->translate('Order Information', 'Application'); ?></h1>
              <br>
              <table class="table">
                <thead>
                <tr>
                    <th>{{totalitems}} <?php echo $this->translate('items', 'Application'); ?></th> <!-- before iterms, put the number of files uploaded -->
                    <th class="text-right"> {{totalwords}} <?php echo $this->translate('words', 'Application'); ?></th>
                </tr>
                <tr>
                    <th><?php echo $this->translate('Languages', 'Application'); ?></th>
                    <th class="text-right">{{numberLangs}}</th> <!-- target languages number -->
                </tr>
                <tr>
                    <th><?php echo $this->translate('Quality Level', 'Application'); ?></th>
                    <th class="text-right" ng-show="totalitems > 0"><span class="label label-primary"><?php echo $this->translate('{{project.serviceLevel.name}}', 'Application'); ?></span> {{CurrentCurrency}} {{price | currency : '' : 2}}/Word</th>
                </tr>
                </thead>
              </table>
              <br><br>
              <table class="table">
                <thead>
                <tr>
                    <th><?php echo $this->translate('Items Total', 'Application'); ?></th>
                    <th class="text-right" ng-show="totalitems > 0">{{CurrentCurrency}} {{ItermsTotal | currency : '' : 2}}</th>
                </tr>
                <tr ng-show="1==0">
                    <th>Tax</th>
                    <th class="text-right">{{CurrentCurrency}} {{tax | currency : '' : 2}}</th>
                </tr>
                <tr style="font-size: 22px;">
                    <th><?php echo $this->translate('Total', 'Application'); ?></th>
                    <th class="text-right" ng-show="totalitems > 0">{{CurrentCurrency}} {{total | currency : '' : 2}}</th>
                </tr>
                </thead>
              </table>
              <p>Estimated delivery <strong>{{hours | currency : '' : 0}} hours.</strong></p> <!-- this hour based on the word count of the files, algorithm is estimate time = total word count / 2000 = number of hours, if the result is 1.2, then show 2, if 1.7, show 2 also-->
            </div>