<div class="setup-content" id="step-3">
	<div class="well">

		<form id="formStep3" class="form-horizontal" role="form" novalidate>
			<div class="row">
				<!-- here need ajax verify to see if the email address is exist, if no show below infor to create a new account -->
				<div class="col-sm-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">Email *</label>
						<div class="col-sm-8">
							<input type="email" id='emailAddress' name="email" class="form-control  required valid" value=""
								placeholder="Email Address" required ng-model="project.newClient.Email">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label class="col-sm-5 control-label">Need Fapiao *</label>
						<div class="col-sm-7">
							<div data-toggle="buttons">
								<!-- here IF YES, THEN SHOW TITLE, "NO" = HIDE TITLE, by default "NO"-->
								<label
									class="btn btn-outline btn-primary btn-custom {{Fapiao == project.fapiao ? 'active': ''}}"
									ng-repeat="Fapiao in Fapiaos"
									ng-click="chooseFapiao(Fapiao);">
									<input type="radio" name="{{Fapiao.name}}"
									value="{{Fapiao.id}}" />
									{{Fapiao.name}}
								</label>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row" ng-show="isFapiao">
				<!-- here need ajax verify to see if the email address is exist, if no show below infor to create a new account -->
				<div class="col-sm-12">
					<div class="form-group">
						<label class="col-sm-2 control-label"> Title *</label>
						<div class="col-sm-10">
							<input id="tit" type="text" name="title" class="form-control required valid" value=""
								placeholder="Your Chinese Company Title for Issue FAPIAO" required ng-model="project.fapiaoTitle">
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="form-group">
						<label class="col-sm-2 control-label"> Address *</label>
						<div class="col-sm-10">
							<input id="add" type="text" class="form-control required valid" value=""
								placeholder="Your Mailing Address" required ng-model="project.fapiaoAddress">
						</div>
					</div>
				</div>
			</div>

			<div class="row" ng-hide="haveEmail">
				<div class="col-sm-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">Last Name *</label>
						<div class="col-sm-8">
							<input id="lastname" name='lastname' type="text" class="form-control required valid" value=""
								placeholder="Last Name" required ng-model="project.newClient.LastName">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label for="inputPassword" class="col-sm-4 control-label">First
							Name *</label>
						<div class="col-sm-8">
							<input id="firstname" name='firstname' type="text" class="form-control required valid" value=""
								placeholder="First Name" required ng-model="project.newClient.FirstName">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">Password *</label>
						<div class="col-sm-8">
							<input id="pass" type="password" name='password' class="form-control required valid" value=""
								placeholder="Type Your Password" required ng-model="project.newClient.Pass">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label class="col-sm-4 control-label">Cellphone *</label>
						<div class="col-sm-8">
							<input id="cellphone" name='cellphone' type="text" class="form-control required valid" value=""
								placeholder="Your Cellphone/Landline" required ng-model="project.newClient.CellPhone">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label for="inputPassword" class="col-sm-4 control-label">Company</label>
						<div class="col-sm-8">
							<input id="company" name='company' type="text" class="form-control  required valid" value=""
								placeholder="Your Company Full Name" required ng-model="project.newClient.CompanyName">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label for="inputPassword" class="col-sm-4 control-label">Country</label>
						<div class="col-sm-8">
							<select class="form-control required valid" name="country"
								aria-required="true"
								ng-options="country.name for country in countries"
								ng-model="project.newClient.Country"
								required
								ng-change="">
								<option value=""></option>
							</select>
						</div>
					</div>
				</div>
			</div>
		</form>
		<hr>
		<div class="text-center" ng-show="!isGraph">
			<button id="" type="button" class="btn btn-primary btn-lg"
				onclick="PrevStep3()">Previous</button>
			<!-- if second step choose NO to translate graphic, then show this button -->
			<button id='PayAndStartTrans' type="button"
				class="btn btn-primary btn-lg" ng-click="PayAndStartTrans()">Pay and
				Start to Translate</button>
		</div>
		<div class="text-center" ng-show="isGraph">
			<button id="" type="button" class="btn btn-primary btn-lg"
				onclick="PrevStep3()">Previous</button>
			<!-- if second step choose yes to translate graphic, then show this button -->
			<button id='RequestQuote' type="button"
				class="btn btn-primary btn-lg" ng-click="RequestQuote()">Request a
				Quote</button>
		</div>
	</div>

</div>

