<div class="setup-content" id="step-1">
	
	<div class="col-md-12">
		<div class="ibox-content" ng-controller="AppController" nv-file-drop="" uploader="uploader">
			<div class="row">
				<div class="col-md-9">
					<h2>
						<?php echo $this->translate('We accept the following files, under','Application'); ?> <span
							class="text-danger">50MB</span> <?php echo $this->translate('size:','Application'); ?></a>
					</h2>
					<p style="font-size: 15px;"><?php echo $this->translate('Allowed file types are "txt, zip, rar, gif, jpeg, jpg, png, doc, docx, ppt, pptx, pdf, chm, xls, xlsx, txt, zip, rar".','Application'); ?></p>
					<p>
						<!--
						<span class="text-danger"><?php echo $this->translate('If files are bigger then 50MB, pleasae put the download link into the "Project Information" at bottom.','Application'); ?></span>
						-->
					</p>
				</div>
				<br />
				<div class="col-md-3 text-center" id="files">
					<span class="btn btn-primary btn-lg fileinput-button" style="font-size: 18px;"> <i
						class="fa fa-cloud-upload"></i> <span><?php echo $this->translate('Select files','Application'); ?></span>
						<input id="fileupload" type="file" name="files[]"
						nv-file-select="" uploader="uploader" multiple>
					</span>
				</div>
				<br /><br /><br />
				<div class="col-md-12">
					<table class="table table-bordered">
						<!--
						<thead>
							<tr>
								<th width="10%">#</th>
								<th><?php echo $this->translate('File Name','Application'); ?></th>
								<th width="20%"><?php echo $this->translate('File Size','Application'); ?></th>
								
								<th><?php echo $this->translate('size:','Application'); ?>Time Stamp</th>
								
								<th width="5%"></th>
							</tr>
						</thead>
						-->

						<tbody>
							<tr ng-repeat="item in uploader.queue" style="font-size: 18px;">
								<td width="5%">{{$index + 1}}</td>
								<td><a href="#" ng-hide="item.isUploading">{{
										item.file.name }}</a>
									<div class="progress" style="margin-bottom: 0"
										ng-show="item.isUploading">
										<div class="progress-bar" role="progressbar"
											ng-style="{ 'width': uploader.progress + '%' }"
											style="width: 0%;">{{ item.file.name }}</div>
									</div></td>
								<td>{{ item.file.size/1024/1024|number:2 }} Mb</td>
								<!--
								<td>{{ getTime(item) }}</td>
								-->
								<td width="5%" class="text-center child-is-link"><a href=""><i
									ng-click="removeItem(item)"
									class="fa fa-trash-o text-danger"></i></a></td>
							</tr>
						</tbody>
					</table>
				</div>
				<br />
				<div class="text-center">
					<button ng-show="project.files.length > 0" id="activate-step-2" type="button"
						class="btn btn-primary btn-lg" ng-click="initStep2()" style="font-size: 18px;"><?php echo $this->translate('Next','Application'); ?></button>
					<!-- next button show after at least one file is uploaded -->
				</div>

			</div>
		</div>
	</div>
	
</div>








