<div class=" setup-content" id="step-1">
	<div class="panel-heading">
                          <div class="panel-options">
                              <ul class="nav nav-tabs">
                                  <li class="active"><a href="#tab-1" data-toggle="tab">Uoload Files</a></li>
                                  <li class=""><a href="#tab-2" data-toggle="tab">Paste Text</a></li>
                              </ul>
                          </div>
                      </div>
					  
	<div class="panel-body">
		<div class="tab-content">
			<div class="tab-pane active" id="tab-1">
			<div class="col-md-12 well" ng-controller="AppController"
													nv-file-drop="" uploader="uploader">
				<h4>We accept the following files, under <span class="text-danger">50MB</span> size: </h4>
											<p>Allowed file types are "txt, zip, rar, html, htm, xml, gif, jpeg, jpg, png, doc, docx, ppt, pptx, pdf, chm, xls, xlsx, txt, zip, rar, html, htm, xml".</p>
											<p><span class="text-danger">If files are bigger then 50MB, pleasae put the download link into the "Project Information" at bottom.</span></p>
											<br>
											
				<div class="col-md-4" id="files">
															<span class="btn btn-primary btn fileinput-button"> <i
																class="fa fa-cloud-upload"></i> <span>Select files</span>
																<input id="fileupload" type="file" name="files[]"
																nv-file-select="" uploader="uploader" multiple>
															</span>
														</div>
				<div class="col-md-8">
					<p></p>
					<div class="progress progress-bar-default" ng-show="uploader.isUploading" >
						<div style="width: {{uploader.progress}}%" aria-valuemax="100" aria-valuemin="0"
							aria-valuenow="{{uploader.progress}}" role="progressbar" class="progress-bar">
							<span class="sr-only">{{uploader.progress}}% Complete (success)</span>
						</div>
					</div>
				</div>
				<br>
				<br>
				<br>
				<div class="project-list">
					<table class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>#</th>
								<th>File Name</th>
								<th>Word Count</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<tr ng-repeat="item in project.files">
								<td>{{ $index + 1 }}</td>
								<td class="project-title">{{item.name }}</td>
								<td class="project-completion">{{item.count }} words</td>
								<td class="project-actions text-right"><a href="#"
									class="btn btn-danger btn-xs" ng-click="removeItem(item)"><i class="fa fa-trash-o"></i>
										Delete </a></td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="text-center">
					<button id="" type="button" class="btn btn-primary btn-lg"
						ng-click="initStep2()">Next</button>
					<!-- next button show after at least one file is uploaded -->
				</div>
			</div>
			</div>
			<div class="tab-pane" id="tab-2">
                <textarea class="form-control" rows="8"></textarea>
            </div>
		</div>
	</div>	
	
</div>



