<div class="setup-content" id="step-3">
	

		<form id="formStep3" class="form-horizontal" role="form" novalidate>
		<div class="col-md-12 well">
			<div class="row">
				<!-- here need ajax verify to see if the email address is exist, if no show below infor to create a new account -->
				<div class="col-sm-6">
					<div class="form-group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Email', 'Application'); ?> *</label>
						<div class="col-sm-8">
							<input type="email" id='emailAddress' name="email" class="form-control  required valid" value=""
								placeholder="<?php echo $this->translate('Email Address', 'Application'); ?>" required ng-model="project.newClient.Email">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label class="col-sm-5 control-label"><?php echo $this->translate('Need Fapiao', 'Application'); ?> *</label>
						<div class="col-sm-7">
							<div data-toggle="buttons">
								<!-- here IF YES, THEN SHOW TITLE, "NO" = HIDE TITLE, by default "NO"-->
								<label
									class="btn btn-outline btn-primary btn-custom {{Fapiao == project.fapiao ? 'active': ''}}"
									ng-repeat="Fapiao in Fapiaos"
									ng-click="chooseFapiao(Fapiao);">
									<input type="radio" name="{{Fapiao.name}}"
									value="{{Fapiao.id}}" />
									{{Fapiao.name}}
								</label>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row" ng-show="isFapiao">
				<!-- here need ajax verify to see if the email address is exist, if no show below infor to create a new account -->
				<div class="col-sm-12">
					<div class="form-group">
						<label class="col-sm-2 control-label"> <?php echo $this->translate('Title', 'Application'); ?> *</label>
						<div class="col-sm-10">
							<input id="tit" type="text" name="title" class="form-control required valid" value=""
								placeholder="<?php echo $this->translate('Your Chinese Company Title for Issue FAPIAO', 'Application'); ?>" required ng-model="project.fapiaoTitle">
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="form-group">
						<label class="col-sm-2 control-label"> <?php echo $this->translate('Address', 'Application'); ?> *</label>
						<div class="col-sm-10">
							<input id="add" type="text" class="form-control required valid" value=""
								placeholder="<?php echo $this->translate('Your Mailing Address', 'Application'); ?>" required ng-model="project.fapiaoAddress">
						</div>
					</div>
				</div>
			</div>

			<div class="row" ng-hide="haveEmail">
				<div class="col-sm-6">
					<div class="form-group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Last Name', 'Application'); ?> *</label>
						<div class="col-sm-8">
							<input id="lastname" name='lastname' type="text" class="form-control required valid" value=""
								placeholder="<?php echo $this->translate('Last Name', 'Application'); ?>" required ng-model="project.newClient.LastName">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label for="inputPassword" class="col-sm-4 control-label"><?php echo $this->translate('First Name', 'Application'); ?> *</label>
						<div class="col-sm-8">
							<input id="firstname" name='firstname' type="text" class="form-control required valid" value=""
								placeholder="<?php echo $this->translate('First Name', 'Application'); ?>" required ng-model="project.newClient.FirstName">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Password', 'Application'); ?> *</label>
						<div class="col-sm-8">
							<input id="pass" type="password" name='password' class="form-control required valid" value=""
								placeholder="<?php echo $this->translate('Type Your Password', 'Application'); ?>" required ng-model="project.newClient.Pass">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label class="col-sm-4 control-label"><?php echo $this->translate('Cellphone', 'Application'); ?> *</label>
						<div class="col-sm-8">
							<input id="cellphone" name='cellphone' type="text" class="form-control required valid" value=""
								placeholder="<?php echo $this->translate('Your Cellphone/Landline', 'Application'); ?>" required ng-model="project.newClient.CellPhone">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label for="inputPassword" class="col-sm-4 control-label"><?php echo $this->translate('Company', 'Application'); ?></label>
						<div class="col-sm-8">
							<input id="company" name='company' type="text" class="form-control  required valid" value=""
								placeholder="<?php echo $this->translate('Your Company Full Name', 'Application'); ?>" required ng-model="project.newClient.CompanyName">
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="form-group">
						<label for="inputPassword" class="col-sm-4 control-label"><?php echo $this->translate('Country', 'Application'); ?></label>
						<div class="col-sm-8">
							<select class="form-control required valid" name="country"
								aria-required="true"
								ng-options="country.name for country in countries"
								ng-model="project.newClient.Country"
								required
								ng-change="">
								<option value=""></option>
							</select>
						</div>
					</div>
				</div>
			</div>
			</div>
		</form>
		<hr>
		<div class="text-center" ng-show="!isGraph">
			<button id="" type="button" class="btn btn-primary btn-lg"
				onclick="PrevStep3()"><?php echo $this->translate('Previous', 'Application'); ?></button>
			<!-- if second step choose NO to translate graphic, then show this button -->
			<button id='PayAndStartTrans' type="button"
				class="btn btn-primary btn-lg" ng-click="PayAndStartTrans()"><?php echo $this->translate('Pay and Start to Translate', 'Application'); ?></button>
			<!--<button id="" type="button" class="btn btn-primary btn-lg"
				ng-click="showpay()">Oder</button>	-->
		</div>
		<div class="text-center" ng-show="isGraph">
			<button id="" type="button" class="btn btn-primary btn-lg"
				onclick="PrevStep3()"><?php echo $this->translate('Previous', 'Application'); ?></button>
			<!-- if second step choose yes to translate graphic, then show this button -->
			<button id='RequestQuote' type="button"
				class="btn btn-primary btn-lg" ng-click="RequestQuote()"><?php echo $this->translate('Request a Quote', 'Application'); ?></button>
			
		</div>
	

</div>

<!-- Payment methord -->
    <div id="modal-order-pay" class="modal fade" aria-hidden="true" style="display:none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="myModalLabel">Payment Methord</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="row">

                          <div class="col-lg-12">

                              <div class="ibox">

                                  <div class="ibox-content">

                                      <div class="panel-group payments-method" id="accordion">
                                          <div class="panel panel-default" ng-show="CurrentCurrency == 'USD'">
                                              <div class="panel-heading">
                                                  <div class="pull-right">
                                                      <i class="fa fa-cc-paypal text-success"></i>
                                                  </div>
                                                  <h5 class="panel-title">
                                                      <a data-toggle="collapse" data-parent="#accordion" href="#paypal">PayPal</a>
                                                  </h5>
                                              </div>
                                              <div id="paypal" class="panel-collapse collapse in">
                                                  <div class="panel-body">

                                                      <div class="row">
                                                        <div class="col-md-12 text-center">
                                                            <table class="table">
                                                              <thead>
                                                              <tr>
                                                                  <th>Total</th>
                                                                  <th class="text-right">{{CurrentCurrency}} {{total | currency : '' : 2}}</th>
                                                              </tr>
                                                              </thead>
                                                            </table>
                                                            <p class="m-t">
                                                                You will be redirected to PayPal's payment page and then sent back once you complete your purchase.
                                                            </p>
                                                            <a class="btn btn-primary" ng-click="paypaypal()"> 
                                                                <i class="fa fa-cc-stripe">
                                                                    Purchase via PayPal
                                                                </i>
                                                            </a>
                                                        </div>

                                                      </div>


                                                       </div>
                                              </div>
                                          </div>
                                          <div class="panel panel-default" ng-show="CurrentCurrency == 'CNY'">
                                              <div class="panel-heading">
                                                  <div class="pull-right">
                                                      <i class="fa fa-cc-alipay text-success"></i>
                                                  </div>
                                                  <h5 class="panel-title">
                                                      <a data-toggle="collapse" data-parent="#accordion" href="#alipay">Alipay</a>
                                                  </h5>
                                              </div>
                                              <div id="alipay" class="panel-collapse collapse in">
                                                  <div class="panel-body">

                                                      <div class="row">
                                                        <div class="col-md-12 text-center">
                                                            <table class="table">
                                                              <thead>
                                                              <tr>
                                                                  <th>Total</th>
                                                                  <th class="text-right">{{CurrentCurrency}} {{total | currency : '' : 2}}</th>
                                                              </tr>
                                                              </thead>
                                                            </table>
                                                            <p class="m-t">
                                                                You will be redirected to Alipay's payment page and then sent back once you complete your purchase.
                                                            </p>
                                                            <a class="btn btn-primary" ng-click="payalipay()">
                                                                <i class="fa fa-cc-alipay">
                                                                    Purchase via Alipay
                                                                </i>
                                                            </a>
                                                        </div>
                                                      </div>






                                                  </div>
                                              </div>
                                          </div>

                                          <div class="panel panel-default" ng-show="1 == 0">
                                              <div class="panel-heading">
                                                  <div class="pull-right">
                                                      <i class="fa fa-cc-stripe text-success"></i>
                                                  </div>
                                                  <h5 class="panel-title">
                                                      <a data-toggle="collapse" data-parent="#accordion" href="#stripe">Stripe</a>
                                                  </h5>
                                              </div>
                                              <div id="stripe" class="panel-collapse collapse">
                                                  <div class="panel-body">

                                                      <div class="row">
                                                        <div class="col-md-12 text-center">
                                                            <table class="table">
                                                              <thead>
                                                              <tr>
                                                                  <th>Total</th>
                                                                  <th class="text-right">{{CurrentCurrency}} {{total | currency : '' : 2}}</th>
                                                              </tr>
                                                              </thead>
                                                            </table>
                                                            <p class="m-t">
                                                                You will be redirected to Stripe's payment page and then sent back once you complete your purchase.
                                                            </p>
                                                            <a class="btn btn-primary">
                                                                <i class="fa fa-cc-stripe">
                                                                    Purchase via Stripe
                                                                </i>
                                                            </a>
                                                        </div>
                                                      </div>






                                                  </div>
                                              </div>
                                          </div>

                                      </div>

                                  </div>

                              </div>

                          </div>


                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


